### ISSUE TITLE
Escape layer name

### ISSUE THREAD

**Issue by aaronlidman** [mapbox/tippecanoe#1]
It's currently possible to create layer names that are inaccessible in Mapbox studio.

For example: `-l "All the trees"` creates an "All the trees" layer, but that's an invalid selector.

**Comment by aaronlidman** [comment]
![screen shot 2017-04-12 at 11 09 41 am](https://cloud.githubusercontent.com/assets/58878/24972526/8e67dbf6-1f70-11e7-88c1-1babf0179a6b.png)

This got fixed!

**Comment by ericfischer** [comment]
Fixed on the Studio side instead of the Tippecanoe side, I guess!
