### ISSUE TITLE
Multhreaded GeoJSON reading

### ISSUE THREAD

**Issue by ericfischer** [mapbox/tippecanoe#102]
About 70% of the time in the input stage is parsing GeoJSON; the other 30% is projection and serialization. The latter could be moved off to its own thread at the cost of more complexity.

**Comment by ericfischer** [comment]
I've been working on this in https://github.com/mapbox/tippecanoe/tree/multithread-input

Unfortunately, while it works, it does not seem to be helpful so far: the overhead of handling an event queue of geometries to serialize is apparently slower than just parsing and serializing them in the same thread.

It may still be a useful prerequisite to having multiple threads work on parsing different parts of the same input file at the same time.

**Comment by ericfischer** [comment]
This is totally not helping. I moved the JSON parsing into multiple threads, but that made it even slower than it already was.

I think improvements in input stage performance will have to come from a different file format, and that additional improvement from multithreading will be in better pipelining of the tiling stage (https://github.com/mapbox/tippecanoe/issues/103).

**Comment by aaronlidman** [comment]
@ericfischer - Even for line-delimited geojson like we talked about? That would be easier to break up right?

**Comment by ericfischer** [comment]
@aaronlidman Yes, this was on line-delimited GeoJSON. After mapping the input file into memory, finding parseable segments is pretty quick. But parsing several segments in parallel was slower than just doing them sequentially.

The one other thing I could try here is to build up a queue of Features within each input thread and only pass them off to the projection/serialization thread after several have accumulated, to avoid the per-Feature thread management overhead. I guess I should try that before declaring this a failure.

**Comment by aaronlidman** [comment]
![screen shot 2015-12-18 at 2 00 08 pm](https://cloud.githubusercontent.com/assets/58878/11905049/05cc92d6-a592-11e5-8eec-b5e32a6989e7.png)
*Parsing from about 4 to 10 - blue is CPU, orange is RAM*

Noting from chat just now. GeoJSON parsing is taking the vast majority of time for a few of my use cases with larger datasets. Memory and CPU usage is very low during this period and there are likely wins to be had by parallelizing and using more resources.

**Comment by ericfischer** [comment]
New thought is: let each input parser thread stream its output into completely independent geometry, metadata, and string pool files so there is no locking overhead between the threads. After they are all finished, concatenate the separate temporary files into unified ones for tiling. Requires changing references from the geometry into the metadata, and from the metadata into the string pool, from absolute offsets to segment+offset pairs. (Alternately, could rewrite the sub-files instead of just copying them, fixing up all the references in the process.)

**Comment by ericfischer** [comment]
Working on this in https://github.com/mapbox/tippecanoe/tree/multithread-input2

**Comment by ericfischer** [comment]
It still doesn't actually use multiple threads, but it *does* read the input in several pieces into separate temporary files, merge them back together, and make tiles out of them, so it's getting close.

**Comment by ericfischer** [comment]
@aaronlidman, I think https://github.com/mapbox/tippecanoe/pull/136 is ready to test. It seems to work and seems to save considerable running time (parsing LA County parcels in 0:30 instead of 1:52 with 8 CPUs), but I am not going to merge it because it's a bad idea to make a giant change an hour before I go away for a week.

If you want to try it, please do and let me know if it works for you. You have to use the `-P` option to turn on parallel processing of input because it doesn't work for all GeoJSON files, only ones where each Feature is on its own line. Also note that for parallelism, the input must be a named file that can be mapped into memory, not a pipe that must be read as a stream.

**Comment by aaronlidman** [comment]
Awesome thank you @ericfischer. I'll throw the planet at this and let you know what happens.

**Comment by aaronlidman** [comment]
Initial results look good:

run | wall clock | system time | user time | cpu %
--- | --- | --- | --- | ---
california | 13:30.33 | 52.26 | 1879.99 | 238%
california - parallel | 10:44.71 | 55.76 | 1990.72 | 317%
*c3.2xlarge - 15.0 GB RAM - 8 cores*

Planet is still going.

**Comment by aaronlidman** [comment]
<img width="1640" alt="screen shot 2015-12-25 at 11 26 42 am" src="https://cloud.githubusercontent.com/assets/58878/12003765/9cba51d4-aafa-11e5-8b60-d2c595ee0d78.png">
<img width="266" alt="screen shot 2015-12-25 at 11 50 24 am" src="https://cloud.githubusercontent.com/assets/58878/12003830/b006a852-aafd-11e5-8ab3-0a2529e6c326.png">

run | wall clock | system time (sec) | user time (sec) | cpu %
--- | --- | --- | --- | ---
planet |  7h 8m | 7746 | 57485 | 253%
planet - parallel | 2h 14m | 7775 | 71575 | 982%
*r3.8xlarge - 244 GB RAM - 32 cores*

- parsing took 16 minutes
- this feels amazing

I have other observations from watching these planets closely, but will bring them up elsewhere.

@ericfischer - This is fantastic. :clap:

**Comment by aaronlidman** [comment]
The only other improvement I can think of would be support for streaming ldjson. Is it possible to chunk the stream for a fixed number of lines/features and parse those chunks in parallel?

**Comment by ericfischer** [comment]
Glad it's helping @aaronlidman! Doing some chunking on streamed input should definitely be possible. I need to figure out some strategy for figuring out how much to buffer before handing it off to the parser threads, but even pulling a number out of the air should be better than nothing.

Still a distressing amount of time spent on the low zooms in your graph above! I hope something in https://github.com/mapbox/tippecanoe/issues/137 will be able to help with that.

**Comment by ericfischer** [comment]
The sorting phase should be multithreaded with 2b378ceb9ff.

**Comment by aaronlidman** [comment]
Closed with https://github.com/mapbox/tippecanoe/pull/136

:+1: :+1:
