### ISSUE TITLE
Feature filtering

### ISSUE THREAD

**Issue by ericfischer** [mapbox/tippecanoe#106]
So that you can, for instance, have a complete OSM GeoJSON but only include the highway=\* features.

Maybe a regular expression style syntax:

```
tippecanoe -e highway=^
tippecanoe -e 'highway=^trunk$'
tippecanoe -V building=^
```

If you specify multiple filters, should they filter each other or be cumulative?

cc @mourner

**Comment by mourner** [comment]
That looks pretty good. I think cumulative filters would be used more often, but eventually we may wan to support both. Although it can grow into an unwieldy filter DSL, yeah...

**Comment by aaronlidman** [comment]
Why not leave this to the user to grep for themself?

**Comment by mourner** [comment]
@aaronlidman you can only grep this easily if the source is LD GeoJSON with line-delimited individual features, but not if it's a FeatureCollection for example.

**Comment by ericfischer** [comment]
Fixed in https://github.com/mapbox/tippecanoe/pull/462
