### ISSUE TITLE
Merge files into one layer

### ISSUE THREAD

**Issue by mourner** [mapbox/tippecanoe#107]
> -l name: Layer name (default "file" if source is file.json or output is file.mbtiles). **Only works if there is only one layer.**

What's the reason for this limitation? E.g. I want to convert several GeoJSON extracts (US West, US South, etc.) into MBTiles with a single `osm` layer (as opposed to layer for each file). I would expect this to work by just passing `-l osm` but apparently this wouldn't work currently. cc @ericfischer

**Comment by ericfischer** [comment]
@mourner That seems like a good idea. Originally, separately-named files were all merged into a single layer, but @amyleew asked for multilayer support so I added it. This seems like a reasonable way to say that you really did just want one layer and here's what to call it.

**Comment by amyleew** [comment]
@ericfischer can there be an option to join or have separate files?

**Comment by ericfischer** [comment]
@amyleew That's what I'm thinking now: if you specify a layer name with `-l`, the layers will be merged, otherwise they will be kept separate.

**Comment by amyleew** [comment]
:+1:

**Comment by ericfischer** [comment]
Working on this in https://github.com/mapbox/tippecanoe/pull/108

**Comment by ericfischer** [comment]
Should be fixed now! Thanks for the feature requests.

**Comment by amyleew** [comment]
Awesome @ericfischer
