### ISSUE TITLE
Update existing mbtiles

### ISSUE THREAD

**Issue by anandthakker** [mapbox/tippecanoe#109]
@ericfischer How feasible would it be to have an `-a` (append) option that would add tiles to an existing `mbtiles` instead of giving an error?   The use case I have in mind is using tippecanoe to build a single source using different settings (and maybe even different data) below a certain zoom level.

**Comment by ericfischer** [comment]
This would be pretty hard to do in tippecanoe proper as currently structured. What is probably more practical is to make `tile-join` able to combine them, since it already can read from one mbtiles and write to another, if that's good enough.

**Comment by ericfischer** [comment]
Working on this in https://github.com/mapbox/tippecanoe/tree/tile-join-multi. Now you can at least do:

    $ ./tippecanoe -Z0 -z9 -o low.mbtiles tl_2014_06001_roads.json
    using layer 0 name tl_2014_06001_roads
    Sorting 27804 features
    27804 features, 1779662 bytes of geometry, 377722 bytes of metadata, 592621 bytes of string pool
      96.2%  9/82/198

    $ ./tippecanoe -Z10 -z14 -o high.mbtiles tl_2014_06001_roads.json
    using layer 0 name tl_2014_06001_roads
    Sorting 27804 features
    27804 features, 1940614 bytes of geometry, 377722 bytes of metadata, 592621 bytes of string pool
      100.1%  14/2658/6338

    $ ./tile-join -o both.mbtiles low.mbtiles high.mbtiles

to make mbtiles at two separate zoom ranges and then combine them. But the metadata still isn't right, and it will fail if the same tile is defined in both input files. I'll have to fix that in the next few days.

**Comment by anandthakker** [comment]
Oh cool!  Yeah, joining two separate ones is just as good; this will work
great for my use case.

**Comment by ericfischer** [comment]
I think the metadata should be correctly merged after my last change 71e00fc. I still need to figure out how to handle the case where multiple tilesets define the exact same tile.
