### ISSUE TITLE
Several runs on the same source

### ISSUE THREAD

**Issue by mourner** [mapbox/tippecanoe#111]
We have a use case of generating two separate MBTiles (for z12 and for z15 with different extents) from the same GeoJSON data.

How can we avoid duplicating z12 work when doing z15 run? Could we generate some temporary files that we can reuse on the second run?

cc @ericfischer @MateoV

**Comment by ericfischer** [comment]
I could make the input stage and the tiling stage independent, so you could save the results of one input and use them for multiple tilings.

The main awkwardness is that the geometries in the serialized form are scaled to the maxzoom resolution, so the prebaked form would have to skip that optimization, but that shouldn't be too bad.

**Comment by ericfischer** [comment]
If this happens I think it will be part of https://github.com/mapbox/tippecanoe/issues/525
