### ISSUE TITLE
Handling multiple inputs and layers

### ISSUE THREAD

**Issue by amyleew** [mapbox/tippecanoe#113]
> -l name: Layer name (default "file" if source is file.json or output is file.mbtiles). If there are multiple input files specified, the files are all merged into the single named layer.

@ericfischer - Can you add support multiple input files added to separate layers? Ideally where each can be named individually.

**Comment by amyleew** [comment]
Am I [reading this response](https://github.com/mapbox/tippecanoe/issues/107#issuecomment-152674286) correctly? If you **do not specify `-l name`** each layer will be on separate layers? Testing now...

**Comment by amyleew** [comment]
What's the proper syntax for adding multiple .json files here? Tried a few below with no luck @ericfischer. Getting the same error `tippecanoe: Only accepts one input file`

```
tippecanoe -o minor_islands2.mbtiles [Users/amyleewalton/Downloads/minor_islands.json Users/amyleewalton/Downloads/minor_islands_coastline.json Users/amyleewalton/Downloads/minor_islands_label_points.json]
```

```
tippecanoe -o minor_islands4.mbtiles [Users/amyleewalton/Downloads/minor_islands.json, Users/amyleewalton/Downloads/minor_islands_coastline.json, Users/amyleewalton/Downloads/minor_islands_label_points.json]
```

```
tippecanoe -o minor_islands2.mbtiles Users/amyleewalton/Downloads/minor_islands.json Users/amyleewalton/Downloads/minor_islands_coastline.json Users/amyleewalton/Downloads/minor_islands_label_points.json
```

```
tippecanoe -o minor_islands5.mbtiles Users/amyleewalton/Downloads/minor_islands.json, Users/amyleewalton/Downloads/minor_islands_coastline.json, Users/amyleewalton/Downloads/minor_islands_label_points.json
```

**Comment by ericfischer** [comment]
@amyleew What version of tippecanoe do you have? (Use `tippecanoe -v` to find out.) It sounds like it must be 1.1.0 or earlier.

If you're doing this on a Mac and aren't building it yourself from source, `brew update` and then `brew upgrade tippecanoe` should get you 1.3, which is pretty close to current.

The syntax should be

    tippecanoe -o out.mbtiles in1.json in2.json in3.json

with no extra punctuation.

**Comment by ericfischer** [comment]
Closing since I think this is resolved. Please let me know if this still isn't working for you with a recent version of tippecanoe.
