### ISSUE TITLE
Better clipping at the edge of the world

### ISSUE THREAD

**Issue by ericfischer** [mapbox/tippecanoe#117]
Any latitudes in the input over 85.0511° are capped at 0 or 2^31-1, which is 85.051129°.

Any longitudes in the input over 180° are capped to 0 or 2^31-1.

This will produce messed up geometries for anything that crosses over the line and doesn't include a point right on the line. Even if there is a point on the line, it will still smash anything beyond the edge onto the edge instead of letting it wrap around.

**Comment by mourner** [comment]
Here's how it's done in GeoJSON-VT if it's of any help: https://github.com/mapbox/geojson-vt/blob/master/src/wrap.js

Basically, I clip the data into -1, 0 and 1 z0 tiles, then shift coordinates in -1 and 1 and append all features to 0, resulting in one tile with properly date-wrapped geometries.

**Comment by ericfischer** [comment]
That sounds great @mourner. Do you run into any problems with the Y coordinates blowing up toward the poles?

**Comment by mourner** [comment]
@ericfischer just clamping to spherical mercator square. Although I just realized there's probably a bug there (should be 0..1 and not -1..1 https://github.com/mapbox/geojson-vt/blob/master/src/convert.js#L100)

**Comment by ericfischer** [comment]
Should be fixed in https://github.com/mapbox/tippecanoe/commit/bbcf9e1b3c01b321a32410c0b78ee94ed074289e
