### ISSUE TITLE
Inner rings not inside outer rings

### ISSUE THREAD

**Issue by ericfischer** [mapbox/tippecanoe#123]
Further testing on Natural Earth `ne_10m_admin_0_countries` turns up lots of cases where a polygon's inner ring has points that are not inside the polygon's outer ring according to `pnpoly`.

I'm not sure yet whether they are (harmlessly?) on the line or genuinely sticking out.

**Comment by ericfischer** [comment]
Some of these are at a considerable distance from the outer ring. For example, right at the start of Canada at z0:

    [ -61.831055, 47.249407 ], [ -62.006836, 47.249407 ], [ -62.006836, 47.309034 ], [ -61.831055, 47.249407 ]

as a child of

    [ -59.633789, 45.920587 ], [ -59.809570, 45.920587 ], [ -59.809570, 46.042736 ], [ -59.633789, 46.042736 ], [ -59.633789, 45.920587 ]

**Comment by ericfischer** [comment]
https://github.com/mapbox/tippecanoe/pull/187 ought to fix this in the course of fixing self-intersecting polygons, but it looks like it still doesn't.

**Comment by ericfischer** [comment]
It's even flaky depending on what maxzoom you use:

    ./tippecanoe --check-polygons -f -z5 -o foo.mbtiles ne_10m_admin_0_countries.json

finds `3853,1336 at 533 not in outer ring (116 to 524)` in Russia at z0 and `Internal error: self-intersecting polygon. 3382,3476 to 3385,3477 intersects 3388,3474 to 3380,3477` in Gambia at z2, but

    ./tippecanoe --check-polygons -f -z2 -o foo.mbtiles ne_10m_admin_0_countries.json

has more problems (Russia and Denmark at z0, Turkey at z1, France at z2, but Gambia is OK) because the coordinates during the initial encoding get quantized more severely.

**Comment by springmeyer** [comment]
> #187 ought to fix this in the course of fixing self-intersecting polygons, but it looks like it still doesn't.

@ericfischer - still the case that this is not fixed? Or working now? /cc @flippmoke

**Comment by ericfischer** [comment]
@springmeyer I am still getting complaints about self-intersections and am trying to figure out whether the error is in the polygons or in my debugging code.

**Comment by ericfischer** [comment]
@springmeyer I am pretty sure there are still problems, even though some of the diagnostics are bogus. For example,

```
./tippecanoe --check-polygons -f -z2 -o foo.mbtiles ne_10m_admin_0_countries.json
```

complains, among other things, of:

```
Internal error: self-intersecting polygon. 1465,978 to 1471,983 intersects 1470,982 to 1469,984
```

which when plotted is a slight overlap:

![screen shot 2016-04-26 at 4 06 55 pm](https://cloud.githubusercontent.com/assets/1951835/14836939/ffa762e4-0bc8-11e6-865a-3c230d5011d0.png)

**Comment by flippmoke** [comment]
@ericfischer interesting... This has been something that I have been working hard to fix, but its not always obvious what causes this each time could you reduce this to a test case for me?

**Comment by ericfischer** [comment]
Sure @flippmoke, I'll try to find a more reasonable way to make it happen.

**Comment by ericfischer** [comment]
@flippmoke It is pretty easy to make this happen if you just generate 50 or so random vertices within a grid size of 20 or so. I just made a [quick test branch](https://github.com/mapbox/tippecanoe/tree/self-intersecting) with some code that will quickly generate bad test cases for you:

```
$ git checkout self-intersecting
Switched to branch 'self-intersecting'
$ make abuse
c++  -I/usr/local/include -I. -g -Wall -O3 -DNDEBUG  -std=c++11 -c -o geometry.o geometry.cpp
geometry.cpp:375:13: warning: unused function 'dump' [-Wunused-function]
static void dump(drawvec &geom) {
            ^
1 warning generated.
c++  -I/usr/local/include -I. -g -Wall -O3 -DNDEBUG  -std=c++11 -c -o abuse.o abuse.cpp
c++  -L/usr/local/lib -g -Wall -O3 -DNDEBUG  -std=c++11 -o abuse geojson.o jsonpull/jsonpull.o tile.o pool.o mbtiles.o geometry.o projection.o memfile.o clipper/clipper.o mvt.o serial.o abuse.o  -lm -lz -lsqlite3 -lpthread
$ ./abuse > foo.ps
srand(1461748222)
Found ring with child area but no parent 0
Internal error: self-intersecting polygon. 12,9 to 11,10 intersects 13,10 to 10,9
$ ps2pdf -dDEVICEHEIGHTPOINTS=20 -dDEVICEWIDTHPOINTS=20 foo.ps
$ open foo.pdf
```

![screen shot 2016-04-28 at 5 07 46 pm](https://cloud.githubusercontent.com/assets/1951835/14905260/dc7eca04-0d63-11e6-81aa-352b7de446cd.png)

I *think* what's probably going on here is that a pass through the geometry cleanup is probably moving an intersection from a fractional coordinate to an integer one, which then creates a new intersection that never gets checked for. When I was trying to write some polygon cleaning code of my own, I got it to work by retrying the cleanup if anything had changed in the first pass. That may be what Clipper needs too.

**Comment by ericfischer** [comment]
Just looping if there is any change turns out not to be sufficient, though, because it quickly hits cases where the order of vertices is unstable (possibly from my ring reordering code) and gets stuck vibrating between the two versions.

**Comment by mkv123** [comment]
Hi, I'm seeing a situation where the output (at a certain zoom) contains a polygon with a small exterior/contour area and a large hole area. In addition the hole is completely and clearly outside of the exterior and aligns mostly with the tile borders. Seems clearly the result of some tile border related clipping, the neighbouring tiles don't contain this fake interior hole.

The problem is that most GeoJSON tools will consider a hole which is not inside the exterior, as another exterior, leading to visual bugs. This is true for at least qgis, mapbox.js, and mapbox-gl-js. 

I'm not sure if this is a the same bug as described here, or if I should open a new one. It would seem fairly easy for tippecanoe to check that any polygon holes it adds reside within the polygon exterior, but fixing this in our post processing, i.e. before using them is in practice very inconvenient.

Also any workarounds would be appreciated.

**Comment by ericfischer** [comment]
@mkv123 Thanks for the report. Is the GeoJSON that is producing these artifacts available? It is surprising that you are seeing this particular problem, because Tippecanoe does check ring nesting so that it can make sure holes are associated with their parents. I would have expected the errors to be rings crossing other rings, not holes entirely outside of outer rings.

That said, we have been doing a lot of work on trying to make polygons correct. @flippmoke has been working on a general solution to the problem in [wagyu](https://github.com/mapbox/wagyu), and I've done some work on Tippecanoe-specific polygon cleaning in the [partition](https://github.com/mapbox/tippecanoe/tree/partition) branch.

At the moment the best workaround I can suggest is to check out and build Tippecanoe from the [partition](https://github.com/mapbox/tippecanoe/tree/partition) branch, which I hope will be able to produce correct polygons from your data.

**Comment by mkv123** [comment]
Built the partition branch but ./tippecanoe -f -z20 dest.mbtiles source.json doesn't generate any tiles at higher zoom levels than 13. The issue we're seeing is around zoom level 18.

**Comment by mkv123** [comment]
@ericfischer I've shared a reduced test case privately (sorry, can't publish) with you.

**Comment by ericfischer** [comment]
Thanks @mkv123. I'll try it and see what I can figure out.

**Comment by ericfischer** [comment]
@mkv123 I responded to your mail. Can you clarify what you think is wrong with the tiles?

**Comment by mkv123** [comment]
Yes, sorry for the radio silence. Apparently in making a minimal test case, the data was accidentally swapped so that the output was a valid polygon and I hadn't double checked it before sending it to you. I'll update during this week. My apologies for the confusion.

**Comment by ericfischer** [comment]
Should be fixed with the switch to Wagyu in https://github.com/mapbox/tippecanoe/pull/333
