### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by musicformellons** [mapbox/tippecanoe#129]
after running this:
usr@xps:~/TEST$ tippecanoe -o file.mbtiles importfile0.json 

I get:
tippecanoe: symbol lookup error: tippecanoe: undefined symbol: _ZN6google8protobuf8internal13empty_string_E

**Comment by musicformellons** [comment]
Did:
make clean
make install

and now it works...!

**Comment by ericfischer** [comment]
Glad you got it working!
