### ISSUE TITLE
how to uninstall

### ISSUE THREAD

**Issue by musicformellons** [mapbox/tippecanoe#130]
I am on ubuntu and probably should have used 'checkinstall' instead of 'make install'..., but now when I try to uninstall using 'make uninstall' it does not work.

I actually would like to reinstall, so would simply do another 'make install' (or 'checkinstall')  work?

**Comment by ericfischer** [comment]
Another `make install` ought to overwrite the previous install. I could add an `uninstall` target if it would be useful but I haven't seen that in many makefiles.
