### ISSUE TITLE
Internal error: 160 shards not a power of 2

### ISSUE THREAD

**Issue by dpl10** [mapbox/tippecanoe#133]
Using yesterday's version (and previous versions back to 1.4.2) on Ubuntu 14.4, I get the error 'Internal error: 160 shards not a power of 2' when I say 'tippecanoe -z 16 -Z 2 -ac -ar -ao -al -pk -q -o stream-b.mbtiles stream-b.json' (the attached input file is an OpenStreetMap extract). I am getting it with multiple input files, so I assume it is something that I am doing wrong, but I know not what.
[stream-b.json.zip](https://github.com/mapbox/tippecanoe/files/69863/stream-b.json.zip)

**Comment by ericfischer** [comment]
Thanks @dpl10. You're not doing anything wrong: I made a mistake somewhere in the calculation of how many threads to use. How many CPUs does your computer have? 160 is way more than any that I have.

**Comment by dpl10** [comment]
The computer has 20 cores, hyperthreading is on, so nproc reports 40.

Damon


> On 2015 Dec 22, at 1:17 PM, Eric Fischer <notifications@github.com> wrote:
> 
> Thanks @dpl10. You're not doing anything wrong: I made a mistake somewhere in the calculation of how many threads to use. How many CPUs does your computer have? 160 is way more than any that I have.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--------------------------
Damon Little
Associate Curator of Bioinformatics
Cullman Program for Molecular Systematics
The New York Botanical Garden
Bronx, New York 10458-5126
U.S.A.
Tel: 718.817.8521

**Comment by ericfischer** [comment]
Thanks. I think I may have only tested on machines where the number of CPUs is a power of 2. Can you also tell me what `ulimit -n` reports for the maximum number of open files?

**Comment by dpl10** [comment]
> ulimit -n
1024

On 2015 Dec 22, at 1:26 PM, Eric Fischer <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks. I think I may have only tested on machines where the number of CPUs is a power of 2. Can you also tell me what ulimit -n reports for the maximum number of open files?

—
Reply to this email directly or view it on GitHub<https://github.com/mapbox/tippecanoe/issues/133#issuecomment-166696822>.

--------------------------
Damon Little
Associate Curator of Bioinformatics
Cullman Program for Molecular Systematics
The New York Botanical Garden
Bronx, New York 10458-5126
U.S.A.
Tel: 718.817.8521

**Comment by ericfischer** [comment]
Thanks for reporting this. https://github.com/mapbox/tippecanoe/pull/134 will round the number of threads that it uses down to a power of 2 until I figure out how to fix the other calculations so that it will take advantage of all 40 CPUs and not just 32 of them.
