### ISSUE TITLE
Multithreaded parsing of streaming input

### ISSUE THREAD

**Issue by aaronlidman** [mapbox/tippecanoe#139]
Continuing from https://github.com/mapbox/tippecanoe/issues/102#issuecomment-167266545

>Doing some chunking on streamed input should definitely be possible. I need to figure out some strategy for figuring out how much to buffer before handing it off to the parser threads, but even pulling a number out of the air should be better than nothing.

@ericfischer - Could we start with a buffer of 10,000 features and see how that works? Is that too high?

**Comment by ericfischer** [comment]
Working on this in https://github.com/mapbox/tippecanoe/tree/stream-parallel

**Comment by ericfischer** [comment]
OK @aaronlidman, this should work after https://github.com/mapbox/tippecanoe/pull/150. Please let me know how it works for you.
