### ISSUE TITLE
Inconsistent feature count

### ISSUE THREAD

**Issue by aaronlidman** [mapbox/tippecanoe#146]
I ran tippecanoe against the same file twice in a row and the count differed. While not a big deal, it gave me a scare because I knew what the previous feature count was.

- 3866000 features, 332343092 bytes of geometry, 39627752 bytes of metadata, 35350636 bytes of string pool
- 3863061 features, 332343092 bytes of geometry, 39627752 bytes of metadata, 35350636 bytes of string pool

**Comment by ericfischer** [comment]
Hmm, that is alarming. The progress indicator has some slop because of multithreading, but this one really ought to know.

**Comment by ericfischer** [comment]
Oh, this message does use the jittery count from the progress indicator. I'll change it to use the actual number of features in the final product.

**Comment by ericfischer** [comment]
Should be fixed in https://github.com/mapbox/tippecanoe/pull/149
