### ISSUE TITLE
Exit with error when unrecognized argument supplied

### ISSUE THREAD

**Issue by danpat** [mapbox/tippecanoe#147]
Tippecanoe should exit with an error when an unrecognized argument is supplied.  As new features are added, if we forget to upgrade tippecanoe, we'll silently succeed without the new argument actually working.

This recently led to some subtle problems after `-pS` was introduced, but the tippecanoe version wasn't updated.

**Comment by ericfischer** [comment]
Good point. I've been sloppy about this with the sub-argument options.

**Comment by ericfischer** [comment]
https://github.com/mapbox/tippecanoe/pull/148
