### ISSUE TITLE
Allow NULL properties on GeoJSON features

### ISSUE THREAD

**Issue by martinburch** [mapbox/tippecanoe#15]
Tippecanoe allows `"properties": { }` but not `"properties": null`

The error given is

```
 json_file_name.json:1: feature without properties hash
```

The [GeoJSON spec](http://geojson.org/geojson-spec.html#feature-objects) says NULL is valid.

**Comment by shongololo** [comment]
I had an error which where tippecanoe said it encountered an invalid character, and listed a line with a `NULL` value, however, checking the raw text I only found `null`. Is `null` supported?

**Comment by ericfischer** [comment]
If the `NULL` was in capital letters, this will generally mean that the key for a feature property could be parsed but the value couldn't, leaving the JSON object with a `NULL` reference to the undefined value. Null property values and geometries (lower case `null`) can be parsed but will be left out of the vector tiles.

**Comment by shongololo** [comment]
Yes, this makes sense, looks like it is trying to parse `NaN`

**Comment by shongololo** [comment]
@ericfischer when you say that `null` values will be left out, does this mean that features with a `null` property will be discarded? In my case I might have one property, e.g. `color` which has a value, but another property, e.g. `height` that might have a `null`

**Comment by ericfischer** [comment]
Yes, features with a `null` property will be left out, since there is currently no way to represent them in vector tiles. In your example, the feature in the tile will have a `color` attribute but not a `height`.

[JSON doesn't support `NaN` values](https://tools.ietf.org/html/rfc4627), so that's why Tippecanoe doesn't. I should add a better error message for this case to clear up the confusion.

**Comment by ericfischer** [comment]
https://github.com/mapbox/tippecanoe/pull/458 will add better error messages for `NaN` and `Infinity` (and replace the `NULL` in partial objects with `...`)
