### ISSUE TITLE
Inconsistent polygons between Mac and Linux

### ISSUE THREAD

**Issue by ericfischer** [mapbox/tippecanoe#159]
Three Natural Earth polygons (Antarctica, Canada, and Indonesia) from `ne_110m_admin_0_countries` get encoded differently on Mac vs Linux, making the tests flaky.

Removed from test as a workaround in https://github.com/mapbox/tippecanoe/commit/886b2c3350eb4754e10c1fdf64fcefc0bcb4e411.

Must be floating point calculations somewhere in Clipper, but I'm not sure where.

**Comment by ericfischer** [comment]
The specific polygons that come out different: https://gist.github.com/ericfischer/1446a3d1621a910c927a

It's noteworthy that both versions appear to have the same vertices, just in a different order, so maybe there is some additional canonicalization that would make them identical.

**Comment by ericfischer** [comment]
@springmeyer points out that this is because of https://github.com/mapnik/node-mapnik/issues/442 and will be fixed by incorporating the https://github.com/mapnik/clipper/ clipper fork.

**Comment by springmeyer** [comment]
@ericfischer fyi: here is the branch/hash we are currently using of clipper: https://github.com/mapbox/mapnik-vector-tile/blob/master/Makefile#L17

**Comment by ericfischer** [comment]
Thanks @springmeyer. I'll try that branch. After swapping in the version from `master` I'm seeing some crashes in tippecanoe (`close_poly`, apparently with a bogus reference in `geom`) so there's a bug in the glue code that I need to track down.

**Comment by ericfischer** [comment]
The crash goes away with the newer branch, and may have been from some of my object files still having been built with the old headers.

Code coverage check is unfortunately failing again in https://github.com/mapbox/tippecanoe/pull/173, but manual tests are looking encouraging, including the ones that weren't matching across platforms before.
