### ISSUE TITLE
Glowing map style

### ISSUE THREAD

**Issue by ericfischer** [mapbox/tippecanoe#162]
@morganherlocker, [recording the interpoint gap](https://github.com/mapbox/tippecanoe/tree/glow-map) as an attribute in the tiles does work pretty reasonably for glowing point styling. This is with <0.01 and <0.1 as the thresholds for full and half glowing. [The test map](https://api.mapbox.com/styles/v1/enf/cik4i4g14003p96kpt5tc3h8k.html?title=true&access_token=pk.eyJ1IjoiZW5mIiwiYSI6IkNJek92bnMifQ.xn2_Uj9RkYTGRuCGg4DXZQ#11.53/37.7742/-122.4139) is Muni bus locations from March 6, 2014.

![screen shot 2016-02-01 at 1 48 39 pm](https://cloud.githubusercontent.com/assets/1951835/12732540/da940aaa-c8ea-11e5-8709-86680f8c6d28.png)

The low zooms probably glow too much and the high zooms too little, but that shouldn't be too hard to adjust.

**Comment by morganherlocker** [comment]
Interesting! Any ideas for LineStrings?

**Comment by ericfischer** [comment]
It might work to chop them up and apply the same treatment to subsegments of them.

**Comment by ericfischer** [comment]
Reopening this since there has also been an external request for a similar feature.

**Comment by ericfischer** [comment]
Revived in https://github.com/mapbox/tippecanoe/pull/252

**Comment by ericfischer** [comment]
Merged.
