### ISSUE TITLE
Request for a basic tutorial

### ISSUE THREAD

**Issue by umaar** [mapbox/tippecanoe#174]
Your detailed tweet map is stunning. Really nice work!

It could be useful (for me and others) to add to the readme a basic guide on how to create something which resembles those maps. Personally, I'm interested in the "dot"-style maps, and also the Runkeeper style maps. The ericfischer/datamaps did this well.

For example:

---

To create something like this: _link to one of your mapbox posts_ you can do the following:

Step 1 - Have a dataset like the following:

```
lat, lng, someValue
38.6855097, -96.50390625, 1
38.6855097, -96.50390625, 2
38.6855097, -96.50390625, 3
```

Step 2 - Run command `$ ...` to generate tiles.

I have a feeling your readme may already have all that's needed, if that's the case, please close this issue and ignore me!

**Comment by lyzidiamond** [comment]
Hi @umaar! There is a guide for how to use Tippecanoe on the Mapbox website: https://www.mapbox.com/help/large-data-tippecanoe/. Does this help?

**Comment by umaar** [comment]
It does! Thanks
