### ISSUE TITLE
Release cycle

### ISSUE THREAD

**Issue by timiyay** [mapbox/tippecanoe#177]
I was curious as to the general release cycle for `tippecanoe`.

Over the past few weeks, I've updated the Homebrew formula for `tippecanoe` to match the latest Github release. Currently, the latest GH release is `v1.8.1`, while `master` is at `v1.9.2`.

Do you plan to make regular GH releases? Or should I modify the Homebrew formula to build from specific repo commits (basically, setting my own version tags, based on the version in `CHANGELOG.md`?

I'm happy to maintain the Homebrew formula, now I'm used to the process. Having an up-to-date `brew install tippecanoe` at my disposal really helps me when getting other team members onboarded.

**Comment by ericfischer** [comment]
Sorry @timiyay, there's no cycle, just me forgetting to tag things properly. I'll tag 1.9.2 now and try to remember to do it whenever I bump the version in the future. Thank you for taking on the homebrew formula.

**Comment by ericfischer** [comment]
[1.9.2 is tagged now](https://github.com/mapbox/tippecanoe/releases/tag/1.9.2). Thanks again for the nudge.

**Comment by timiyay** [comment]
Thanks for `tippecanoe`!

It has been my gateway drug into building vector tiles. Would still be image tiles all the way, without it
