### ISSUE TITLE
Indexing while converting to mbtiles

### ISSUE THREAD

**Issue by divya1c** [mapbox/tippecanoe#183]
Hi!

Is there a way to create custom indexes on the data while converting to mbtiles? 

Thanks!

**Comment by ericfischer** [comment]
Not currently. Do you have an example of the kind of thing you have in mind?

**Comment by divya1c** [comment]
I have a database of some geoids and geoms in Postgres. Since I am using mapbox gl and a tile server, I currently convert my psql database to geojson and then to mbtiles (for which I use tippecanoe). 

However, for my functionality in mapbox gl rendering, since I have a lot of features, I thought it would help having indexes on my geoid. I am not sure if that's possible or if that would make a difference in mbtiles data access. Or is there any other way to speed up data access in mbtiles format?

**Comment by ericfischer** [comment]
When it creates the mbtiles database, it does

    create unique index tile_index on tiles (zoom_level, tile_column, tile_row);

to index the access to each tile. Within each tile, though, Mapbox GL needs to draw all the features from the tile, so there is not any real advantage to indexing the features within the tile, and the vector tile file format does not provide any way to index them.

**Comment by divya1c** [comment]
I am trying a hover highlight functionality, so, I use a filter on geoids in mapbox gl on a layer. So, this filter filters out features (polygons) based on the geoid so as to pick the polygon i need to highlight.

In this case, I thought indexing on the geoid would help?

**Comment by ericfischer** [comment]
That would probably help. Tippecanoe has no way to encode this index because there is no support for it in the vector tile format itself, but on the client side, you could use [rbush](https://github.com/mourner/rbush) to index the currently visible features so that they can be selected quickly.

**Comment by divya1c** [comment]
Thanks, I'll try it :)
