### ISSUE TITLE
Optimize line simplification

### ISSUE THREAD

**Issue by ericfischer** [mapbox/tippecanoe#19]
As @mourner points out, the line simplification can be done once (to the max needed level of detail) and then reused at lower zooms if it retains the knowledge of what zooms each point is needed for, rather than having to redo it from scratch at each zoom level.

**Comment by ericfischer** [comment]
Not going to happen.

**Comment by mourner** [comment]
Any technical limitations preventing this?

**Comment by ericfischer** [comment]
I still think it could be done, with the possible exception of `--detect-share-borders`, which has to figure out which portions of a feature are exact matches to portions of another feature before simplifying. Other than that, it's just another piece of information that would have to be carried around with the geometry structure everywhere.
