### ISSUE TITLE
More Control Over Polygon Dropping

### ISSUE THREAD

**Issue by jaylev1** [mapbox/tippecanoe#204]
Hi -

First off thanks for a wonderful tool. I'm using Tippecanoe to visualize a dataset of several million polygons, and it's been very helpful so far.

My main challenge has been achieving aesthetic consistency throughout the map while remaining under the 500k tile limit for every tile. I first tried Tippecanoe using no special arguments - in other words, I let it handle the excessively large tiles by using lower detail. Unfortunately, in my case this is necessary even at low zooms, but it's usually not needed for _all_ tiles at a given zoom level. So at zoom level 3, for example, I have some tiles using detail 12, others using detail 11, and still others using detail 10. Because all of these tiles are visible at the same time, this makes for a very odd looking map!

Obviously I could handle this by forcing all tiles to detail 10 with a -d10 argument, but this degrades the appearance of the map considerably. So my next attempt was to use the -pd argument to tell Tippecanoe to drop features rather than using lower detail. And in the case of the tiles that were >500k, I love the way this turned out! The relative sparsity of features actually looks better to me than it did before, and as a bonus I still have detail level 12.

The problem now is the tiles that are NOT >500k. Because they're not dropping features, they look dramatically more dense than the tiles that are, which ultimately leads to the same very gridded aesthetic that I was struggling with before. And even among the tiles that are dropping features, they're often doing so at different rates, thereby making the tile borders more obvious (as you allude to in the README).

So I guess what I'm looking for is a way to drop polygons such that, for a given zoom level, the map looks equally dense at all tiles. I've thought of a few possible implementations but don't love any of them, so I'll leave that part to the expert:)

Thanks for any help.

-Jay

**Comment by ericfischer** [comment]
I wish I had an implementation of this that I loved either. The closest I ever came was in the ["consistent" branch](https://github.com/mapbox/tippecanoe/commits/consistent) that made `-pd` drop the closest-together features first, and drop the same features from each tile. But it's slow and I haven't figured out yet how to reconcile it with multithreaded tile generation because it needs to inspect the whole zoom level before generating any of the tiles.

In this case extending the `-al`/`--drop-lines` option to polygons might get you the effect you want, thinning out the low zooms by a fraction of features, even though it isn't a general solution.

**Comment by jaylev1** [comment]
Agree that extending `-al` to polygons would likely help a lot, so if that's an easy change, I'd love to give it a try.

The other solution sounds interesting as well - would be excited to try it if you're able to sort out the speed issues at some point in the future.

**Comment by ericfischer** [comment]
Option added in https://github.com/mapbox/tippecanoe/pull/206. Will merge once tests pass.

**Comment by jaylev1** [comment]
Perfect! I'm still messing with the different gamma / drop rate / base zoom combos, but already the map is MUCH improved. And I think with a little more tinkering it'll look exactly as I had hoped.

Thanks a ton!

**Comment by ericfischer** [comment]
Glad to hear it is working for you!

**Comment by ericfischer** [comment]
This is merged now.
