### ISSUE TITLE
Using mbtiles in map box

### ISSUE THREAD

**Issue by maggieGit** [mapbox/tippecanoe#21]
Hi, 
I have created using tippecanoe a file with 43 features with no output error
43 features, 1005 bytes of geometry, 1548 bytes of metadata
  99.9%  13/2319/6199 
(this is just a test, eventually would like to have 5 Million features)
I uploaded it to map box, and then opened it in Map Box Studio, and only one feature appears. 
(the first one)
Any idea why?
Here is the source id: maggiemaps.1cib2xec
Thank you for your precious time.
Maggie

**Comment by ericfischer** [comment]
I'm sorry I missed this issue before @maggieGit! It got resolved through Help Scout, right?

**Comment by maggieGit** [comment]
Sure, not problem, yes it got resolved with the -g option even better!
Thank you!
M

On Mon, Apr 6, 2015 at 11:45 AM, Eric Fischer <notifications@github.com>
wrote:

> I'm sorry I missed this issue before @maggieGit
> <https://github.com/maggieGit>! It got resolved through Help Scout, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mapbox/tippecanoe/issues/21#issuecomment-90169679>.
>



-- 

Maggie Sleziak-Sallee
Software Engineer
COSMIC - UCAR
Phone: 303-497-8020
Email: maggie@ucar.eduhttp://www.cosmic.ucar.edu/
