### ISSUE TITLE
Option to not clip polygons?

### ISSUE THREAD

**Issue by jasonbeverage** [mapbox/tippecanoe#214]
Is there an option to not clip polygons to the bounding box of the tile, but instead allow them to extend a bit into their neighbors.  I'm using tippecanoe to generate tiles for rendering 3d extruded buildings in osgEarth and the buildings need to be kept whole so they extrude correctly.

If there is no option can you point me to the where I could modify the code to optionally disable the clipping?

**Comment by ericfischer** [comment]
I was just thinking about this. There's no way to turn clipping completely off now but it should be a straightforward option for me to add. (You could work around it now by specifying a large enough buffer with `-b` if you don't mind having features duplicated between adjacent tiles, but it would be better to have a way to just keep features intact.)

**Comment by ericfischer** [comment]
Please try https://github.com/mapbox/tippecanoe/pull/215 when you have a chance and let me know if it does what you are looking for.

**Comment by ericfischer** [comment]
Hmm, actually that can't be right: the test shape didn't come out the same in all the tiles.

**Comment by ericfischer** [comment]
OK, now they should be consistent between tiles.

**Comment by jasonbeverage** [comment]
Thanks @ericfischer.  It isn't clipping the polygons, but it looks like it's sticking the polygons in multiple tiles instead of just one so you end up with duplicate features.  So now I get multiple buildings in the same location instead of just one.  Can we tweak it to only include the polygon in the tile where it's centroid lies so it only gets output to one tile?

**Comment by ericfischer** [comment]
That seems like a violation of the principle that each tile should contain all the information necessary to render that tile. If you need uniqueness, can you include a feature ID and filter duplicates on the client side by it?

**Comment by jasonbeverage** [comment]
It probably wouldn't be trivial to add that kind of filtering to osgEarth, although I'd consider it.  The issue is that we're creating 3D buildings like [this](https://lh3.googleusercontent.com/BTk9TaPPq18wY3zy3a5empKAe7Etn_sjMMmt_V8EgRjTILrh383gOXOm1XrGyBY7iAJ0=w1920-h1080-rw-no) and if you have duplicate buildings then you end up with z fighting.  

If I wanted to add a crop to centroid function to tippecanoe would I just need to add a check in that write_tile method and simply not write out the geometry if the centroid wasn't in the tile?

**Comment by ericfischer** [comment]
Sure, you can add your own filter in `write_tile` to leave out features by centroid. You'll probably want to do it in the series of feature-dropping `continue`s after the `rewrite` call.

**Comment by ericfischer** [comment]
Merged!
