### ISSUE TITLE
Drop libprotobuf dependency

### ISSUE THREAD

**Issue by springmeyer** [mapbox/tippecanoe#218]
We should move to https://github.com/mapbox/protozero and drop the libprotobuf dependency. This will:

  - reduce external dependencies and ease builds (protozero can easily by bundled as it is header-only)
  - improve performance and reduce memory needs in `decode.cc` as `tile.ParseFromCodedStream`/`tile.ParseFromString` allocates many objects all at once
  - improve performance and reduce memory needs in tile creation (tile.cc and tile-join.cc) as the pbf can be created in a streaming fashion rather than in-memory and then dumped all at once `outtile.SerializeToString`
  - Would also avoid the hack used in #176

Protozero usage is documented at https://github.com/mapbox/protozero/blob/master/tutorial.md

**Comment by ericfischer** [comment]
I think this is ready to go in Tippecanoe if I can figure out how to fix the Travis configuration on Linux. mapbox/tippecanoe#219

**Comment by ericfischer** [comment]
Merged!
