### ISSUE TITLE
Convert all files to C++

### ISSUE THREAD

**Issue by springmeyer** [mapbox/tippecanoe#231]
This will unlock:

  - Being able to consistently set `-std=c++11`
  - Being able to use protozero headers in more code, like what is currently `geojson.c`: refs #228
  - Dodge breakages when fixing `-Wshadow` warnings: https://github.com/mapbox/tippecanoe/pull/229#issuecomment-215180505
  - Might surface other bugs / invalid casting.

I propose also moving to `.cpp` and `.hpp` instead of `cc` and `hh` as the former is more consistent with major Mapbox maintained codebases in C++.

**Comment by ericfischer** [comment]
It is in C++ now. https://github.com/mapbox/tippecanoe/pull/232
