### ISSUE TITLE
Question about scheme

### ISSUE THREAD

**Issue by jingsam** [mapbox/tippecanoe#237]
I want to know the output mbtiles follows which sheme, tms or zxy? And it will be better to have a `sheme` field in metadata

**Comment by ericfischer** [comment]
The output mbtiles is in TMS, [as the mbtiles spec requires](https://github.com/mapbox/mbtiles-spec/blob/master/1.2/spec.md). As far as I'm aware this is never declared explicitly in mbtiles files from other creators like Mapbox Studio Classic either, although it makes sense to clarify it.

**Comment by jingsam** [comment]
Thanks, I get it. I think the default TMS scheme is a historical debut because xyz is more convenient and  efficient. However, the spec has defined it, I will follow this rule.

**Comment by ericfischer** [comment]
I agree. As far as I know, everything at Mapbox uses XYZ except mbtiles. Tippecanoe is all XYZ internally except for the translation when reading and writing the mbtiles file.

**Comment by ericfischer** [comment]
Closing because I don't think there's any action I can take here.
