### ISSUE TITLE
Add multiple layer capability 

### ISSUE THREAD

**Issue by amyleew** [mapbox/tippecanoe#24]
Please add functionality to pass multiple data files that produce one .MBTile with each added data file as it's own separate layer.

@ericfischer

**Comment by ericfischer** [comment]
I'm working on this now @amyleew

**Comment by amyleew** [comment]
:+1: @ericfischer

**Comment by ericfischer** [comment]
I finally went ahead and merged this.

**Comment by amyleew** [comment]
awesome! great addition @ericfischer
