### ISSUE TITLE
Something is wrong with polygon dropping

### ISSUE THREAD

**Issue by ericfischer** [mapbox/tippecanoe#240]
San Francisco buildings built >= 1918, <= 1934 just above and just below the z13 transition:

![screen shot 2016-05-05 at 10 24 16 am](https://cloud.githubusercontent.com/assets/1951835/15051067/ba7282dc-12ab-11e6-817d-bfe6cd7873aa.png)

![screen shot 2016-05-05 at 10 24 08 am](https://cloud.githubusercontent.com/assets/1951835/15051075/bed8d2f4-12ab-11e6-956b-9741bc08db74.png)

There are a *lot* of small parcels getting dropped at z12 in unrepresentative ways. It looks like the north-south-oriented ones are surviving, to the exclusion of the east-west-oriented ones.

**Comment by mourner** [comment]
@ericfischer how do you calculate the area? Are you using lat/lon values with the area formula?

**Comment by ericfischer** [comment]
@mourner The area is with surveyor's formula in tile-extent coordinates.

Z11 and Z13 look OK, so it is hitting the tile grain wrong just at Z12. Probably small rectangles degenerating to effectively be lines at tile resolution and therefore getting excluded.

**Comment by ericfischer** [comment]
Correction: they are still in world (32-bit plane) coordinates at the time of tiny-polygon dropping and are downsampled to tile coordinates afterward. So the area calculation knows how big they are, but not whether the downsampling will lose them.

**Comment by ericfischer** [comment]
In the interest of reproducibility, this was with

    zcat LandUse2016.json.gz | ./tippecanoe -f -o LandUse2016.mbtiles -y LANDUSE -y PDR -y RESUNITS -y RETAIL -y TOTAL_USES -y VISITOR -y YRBUILT

**Comment by ericfischer** [comment]
Working on this in https://github.com/mapbox/tippecanoe/pull/241

**Comment by ericfischer** [comment]
It keeps a placeholder now if the polygon vanishes during cleaning.
