### ISSUE TITLE
Points offset more as you zoom out?

### ISSUE THREAD

**Issue by apollolm** [mapbox/tippecanoe#25]
Hello - I'm quite certain I'm doing something wrong.
I'm starting with a 50K feature .geojson file.  Coords are srid of 4326 and were sucked out of PostGIS -> GeoJSON.

I run tippecanoe with all of the defaults

    tippecanoe -o health_2014.mbtiles health_2014.geojson

It successfully creates an .mbtiles file.

I'm hosting the tiles myself using [PGRestAPI] (https://github.com/spatialdev/PGRestAPI).

Lastly, I'm previewing the data in MapboxGL.

I'm noticing that when I'm zoomed far out (maybe 3 or 4), I see some points waaayyy off from where they should be (northern India):

![screen shot 2015-03-22 at 1 20 07 pm](https://cloud.githubusercontent.com/assets/144543/6771242/30825d4c-d097-11e4-960a-0c6b74e93741.png)

As I zoom in, the points move closer and closer to being in the right place in northern India.

![screen shot 2015-03-22 at 1 28 43 pm](https://cloud.githubusercontent.com/assets/144543/6771248/651abf9a-d097-11e4-971e-1498104181b4.png)

Closer...

![screen shot 2015-03-22 at 1 29 18 pm](https://cloud.githubusercontent.com/assets/144543/6771254/825ebaca-d097-11e4-8c8c-cd177112e11e.png)

In even more: 

![screen shot 2015-03-22 at 1 30 15 pm](https://cloud.githubusercontent.com/assets/144543/6771255/a8cbcd06-d097-11e4-815c-a6aaa7ee32fd.png)

When zoomed in to 12 or 13 or so, it starts to show groups of points in each quadrant of the screen:
![screen shot 2015-03-22 at 1 36 29 pm](https://cloud.githubusercontent.com/assets/144543/6771288/89e3d23e-d098-11e4-8bb1-9ab9517b7668.png)

Here's the original .geojson file in QGIS:

![screen shot 2015-03-22 at 1 31 04 pm](https://cloud.githubusercontent.com/assets/144543/6771257/bc565774-d097-11e4-96d1-7239f404c4f6.png)

Any thoughts?  Is there a setting in Tippecanoe somewhere I'm missing?
Why might the points be appearing offset by so much?

I haven't had problems using PGRestAPI to host other .mbtiles data exported from Mapbox Studio and presented in MapboxGL, so I'm wondering what it could be?

Thanks!

**Comment by springmeyer** [comment]
Did you try using Studio with the same exact geojson file? I wonder if you could reduce the testcase smaller and post the data for @ericfischer to try to replicate with?

**Comment by apollolm** [comment]
Good call.  I just loaded the same .geojson file in Mabpox Studio Source View (v 0.2.5), and exported as .mbtiles. Restarted PGRestAPI to serve them and then loaded into MapboxGL just fine.

Studio View:
![screen shot 2015-04-05 at 5 01 46 pm](https://cloud.githubusercontent.com/assets/144543/6999245/1c24eb6e-dbb7-11e4-83c2-e98e733e527d.png)

MapboxGL View:
![screen shot 2015-04-05 at 5 10 32 pm](https://cloud.githubusercontent.com/assets/144543/6999248/3841d438-dbb7-11e4-9505-1451dd03e4c2.png)

I'm going to try the entire thing again now with some different settings (more closely following the settings from the 350 million-point blog post, and see what happens.

If that doesn't work, I'll post the test data somewhere.

Thanks!

**Comment by ericfischer** [comment]
I think this is probably the bug where GL doesn't work properly with tiles that have a resolution other than 4096. Tippecanoe tries to use lower resolutions at lower zooms to save space. Could you try encoding with -d 10 -D 10 to force a tile resolution of 4096 and see if that fixes it?

**Comment by ericfischer** [comment]
(And sorry I missed this bug report for so long @apollolm! I'll set a mail filter now so I am sure to see tippecanoe issues.)

**Comment by apollolm** [comment]
No worries.  I tried -d10 and -D10:

    tippecanoe -o health_4096.mbtiles -d10 -D10 -f health_2014.geojson

And loaded in GL.  Still doing a similar thing.  Features appear Northwest of where they should be, and steadily get closer to northern India as I zoom in.

Source GeoJSON data:
https://gist.github.com/apollolm/eb5814c48b1e74c673ea#file-health_2014-geojson

**Comment by ericfischer** [comment]
I really think this is a GL bug, since the points do display in the correct and consistent location in Studio when I encode your data with tippecanoe:

![screen shot 2015-04-06 at 1 56 10 pm](https://cloud.githubusercontent.com/assets/1951835/7012279/cae5459c-dc64-11e4-8c3a-880a4b61e1f5.png)

I should have said -d12 -D12, not -d10 -D10, since 10 is 1024-pixel tiles. 12 should make the 4096 that GL expects. Can you try that and see if it works for you?

**Comment by apollolm** [comment]
Thanks.  Changed to -d12 -D12 and still see the same issues.
Here is a zoomed in view that shows the 'blotchy' effect.  When zoomed out, features still appear to the northwest.

![screen shot 2015-04-06 at 2 01 53 pm](https://cloud.githubusercontent.com/assets/144543/7012369/9646620c-dc65-11e4-8171-14f49492da3a.png)

**Comment by ericfischer** [comment]
Since you closed it @apollolm, does that mean it works now?

**Comment by apollolm** [comment]
No - but if this is a GL problem, I didn't want this open issue lingering in your issues list! :-)

**Comment by aaronpdennis** [comment]
I've run into this issue when generating vector tiles with Tippecanoe and then trying to use them with GL. I'll have to try encoding with -d12 -D12.

My understanding is that GL vector tiles are rendered larger than tiles in Leaflet/Mapbox Studio, which seems related to the tile resolution of 4096 issue...

I wrote about the issues I had trying to use Tippecanoe generated tiles with GL here: https://github.com/mapbox/mapbox-gl-js/issues/1091.

**Comment by ericfischer** [comment]
I hope that works for you @aaronpdennis. I do think this is a GL problem, not a tippecanoe problem.

**Comment by wheredoesyourmindgo** [comment]
I had the same issue using mapbox-gl-js with tippecanoe, which a data source that looked fine in Mabox Studio.  Using -d12 -D12 with tippecanoe solved this issue for me! Thanks.

**Comment by aaronpdennis** [comment]
Thank you @ericfischer! Encoding with -d12 -D12 definitely solved my issue.

**Comment by ericfischer** [comment]
I changed the default in 541d3518c to use -d12 at -z14 and above, and -d13 at -z13 and lower, which, as far as I know, works correctly with GL.
