### ISSUE TITLE
Empty tile

### ISSUE THREAD

**Issue by stackTom** [mapbox/tippecanoe#250]
I have some geojson feature collections (all points) which I convert to mbtiles using tippecanoe. When I try to preview the mbtiles in MapTiller, I can't see anything, just an empty, gray map. I also try this tile server - https://github.com/klokantech/tileserver-php, and I get a black, empty map. What am I doing wrong. I would like the points to show up as dots, something similar to this: https://www.mapbox.com/blog/twitter-map-every-tweet/

**Comment by stackTom** [comment]
Changing the type to circle instead of line in the layer json objects fixed my issue. It appears the default example code the tile server generates automatically sets the type to line even for geojson Points.

**Comment by ericfischer** [comment]
I'm closing this because it doesn't sound like there is a Tippecanoe bug. Please reopen with more details if you disagree.
