### ISSUE TITLE
Meaning of overlapping rings

### ISSUE THREAD

**Issue by ericfischer** [mapbox/tippecanoe#256]
Trying to come up with a reasonable interpretation of what overlapping rings should mean. I think probably the areas that should be included in the final polygon are the ones where the net coverage >= 1. So if you have two outer rings like the blue ones here and two holes like the yellow ones:

![screen shot 2016-06-07 at 3 47 44 pm](https://cloud.githubusercontent.com/assets/1951835/15877255/c25a561a-2cc7-11e6-8913-e5330b13eabd.png)

the final polygon should look like the solid black shape here:

![screen shot 2016-06-07 at 3 49 20 pm](https://cloud.githubusercontent.com/assets/1951835/15877259/ca37f0e0-2cc7-11e6-8b1d-0393d35d399e.png)

One hole can cancel out one outer ring, but where there are two overlapping outer rings, it takes two overlapping holes to cancel them both out. A hole outside of any outer ring has negative coverage and has no effect.

cc @flippmoke

**Comment by ericfischer** [comment]
At least I finally realized how to think about clipping in these terms: the clip region is just a regular polygon, but the area outside of it has a depth of -1, so it takes being inside the clip *and* inside the polygon being clipped to get to a depth of 1.

**Comment by flippmoke** [comment]
http://www.angusj.com/delphi/clipper/documentation/Docs/Units/ClipperLib/Types/PolyFillType.htm

In my general opinion we should generally be using EvenOdd or Positive Filling. I think that NonZero isn't really ideal in most situations. EvenOdd in the situations where we are not confident that winding order is correct and Positive in the situation where we assume that winding order is generally correct.

**Comment by ericfischer** [comment]
@flippmoke I thought you said you didn't want EvenOdd, since it doesn't respect winding order?

Positive is what I was trying to talk about above, I think. NonZero would mean that there are no holes.

**Comment by flippmoke** [comment]
@ericfischer we currently use positive when creating vector tiles, the reason is that for most formats we expect there to be some sort of reasonable winding order that is used by mapnik prior to being sent to mapnik-vector-tile encoder. However, when we updating v1 tiles to v2 tiles we are using EvenOdd because we are not certain that previous versions of vector tiles were using any sort of winding order. In this case we have no idea if it is a ring or hole as winding order may not be correct for any of the rings.

**Comment by ericfischer** [comment]
Makes sense @flippmoke. Thanks for the clarification.
