### ISSUE TITLE
Large geojson gets stuck subdividing polygons

### ISSUE THREAD

**Issue by gonesurfing** [mapbox/tippecanoe#257]
I'm running into an issue and could use some ideas.  Tippecanoe was working well for me until I increased the number of points in my geojson files. Now, I get the following errors most of the time when when processing the files and the process never finishes. I have validated my output files and cannot find any issues with them, so I'm thinking the problem is in the clipper part of tippecanoe. The geojson is a feature collection of multi polygons, and none of them have any negative space or what I consider "child area". 

tippecanoe -o test.mbtiles swell.json
For layer 0, using name "swell"
182 features, 7355051 bytes of geometry, 104 bytes of separate metadata, 332 bytes of string pool
Warning: splitting up polygon with more than 700 sides
Warning: splitting up polygon with more than 700 sides
Warning: splitting up polygon with more than 700 sides
Subdividing complex polygon failed
Subdividing complex polygon failed
Subdividing complex polygon failed
Subdividing complex polygon failed
Subdividing complex polygon failed
Subdividing complex polygon failed
Subdividing complex polygon failed
Found ring with child area but no parent 0
Found ring with child area but no parent 0

... on and on for hours until ctl-C

**Comment by ingalls** [comment]
cc/ @ericfischer

**Comment by gonesurfing** [comment]
OK. Figures as soon as I post an issue I find the cause.  My json generating routine was using some old geo points that didn't match the data and the result was probably a lot of garbage polygons.

If you want the problem file to look at for some reason, let me know. Otherwise I'll close this.
Thanks,

Eric

**Comment by ericfischer** [comment]
@gonesurfing It would be great to at least know what version of tippecanoe you are using that is running into the problem. 7896c3c2c94afba7 was meant to fix a problem similar to this, so if it's still not fixed, I would like to see your file.

That said, all the polygon cleaning will be getting a complete rewrite in the next couple of weeks, so the problem may also get fixed in the course of that.

**Comment by ericfischer** [comment]
Although you must have that change, since it was the one that added that message. So it would be useful to see your file to understand what is still going wrong.

**Comment by gonesurfing** [comment]
Using 1.11.7

https://drive.google.com/file/d/0B9hi7NIHJF4HZDdxRjUyOEZENE0/view?usp=sharing

Let me know if you have trouble accessing the file. I'll leave the link up for a couple days. It's ~45M.

**Comment by ericfischer** [comment]
Thanks! I downloaded it and will take a look.

**Comment by ericfischer** [comment]
OK, it looks like what is going wrong here is that the polygon is massively self-intersecting, with points jumping back and forth across vast distances. Trying to split it into smaller pieces doesn't work because the pieces are just as self-intersecting.
