### ISSUE TITLE
Clarification re -B (when bigger than -z)

### ISSUE THREAD

**Issue by jmcazaux** [mapbox/tippecanoe#260]
Hi there,
I am trying the build a MBTile map with different layer per zoom level (adding layers as the level increase) and I am a bit unsure re the -B parameter.

First, tippecanoe do apply feature simplification for lines and polygons as well, right?
So if I have a land layer that is present from levels 0 to 10, the features in the level 0 will be far less complex?
Am I correct here?

Then: how does the B parameter impact things when it is bigger then max zoom?
Due to the way tile-join works, I am building my map layer by layer.
So say I have 
- "land" for levels 0 to 6 => mbtile_0_6
- "land" + "rivers" for levels 7 and 8 => mbtile_7_8
- "land" + "rivers" + "railways" for levels 9 and 10 => mbtile_9_10

And I then join mbtile_0_6 + mbtile_7_8 + mbtile_9_10 using tile-join

Obviously I would like the "land" layer to be simplified consistently between the 3 initial tile sets
So the idea would be to build the fiirst file with: -Z 0 -z 6 -B 10
The second file with: -Z 7 -z 8 -B 10
And the third with: -Z 9 -z 10

Would that have the desired effect and will the simplification happen in the 2 first sets so that features are only fully defined at level 10 ?

Many thanks for the clarification.

**Comment by ericfischer** [comment]
The `-B` parameter only applies to Point features unless you also use `--drop-lines` or `--drop-polygons` to drop a fraction of those at low zooms.

Simplification, however, does apply to line and polygons, so yes, those will come out simpler at low zooms than at high zooms.

For these layers you should be able to use `-Z0 -z6` for land, `-Z7 -z8` for land and rivers, and `-Z9 -z10` for land, rivers, and railways, without ever using `-B`. If you want less simplification at z10 so you can overzoom further, you can use `-pS` not to do any simplification at the highest zoom level.

**Comment by jmcazaux** [comment]
Thanks for that Eric, this is clarifying things for me.
