### ISSUE TITLE
Error "Vector tile Layer has an unsupported version" when uploading file to Mapbox 

### ISSUE THREAD

**Issue by jmcazaux** [mapbox/tippecanoe#261]
Hi there,
I am building vector MBtiles file with tippecanoe, but when uploading to Mapbox, I jave the following error message `Vector tile Layer has an unsupported version`

Neither tile-enumerate nor tile-decode complain when opening this file.
I do not have any error message while building it.

Any idea where this could come from ?

Many thanks,
JM

**Comment by ericfischer** [comment]
I haven't seen that problem. What version of tippecanoe are you using? (From `tippecanoe --version`)

**Comment by jmcazaux** [comment]
Hi Eric,
it is 1.11.9.

**Comment by jmcazaux** [comment]
I have just investigated more.

The tileset is a joint of individual levels.

The individual levels all load on their own, but they do not load when joint.

**Comment by jmcazaux** [comment]
Same after upgrading to 1.12.0.

**Comment by ericfischer** [comment]
Thanks. So this must be a tile-join bug, not in tippecanoe proper. I'll try to reproduce it.

**Comment by jmcazaux** [comment]
Does it help if I give you access to my data ?

**Comment by jmcazaux** [comment]
Eric, just sent you an email with a link to the data.

**Comment by ericfischer** [comment]
Thanks. It looks like this is just an uninitialized variable in mbtiles parsing and I should have a fix checked in later today.

**Comment by ericfischer** [comment]
Should be fixed in https://github.com/mapbox/tippecanoe/pull/262. I'll merge it once the tests all complete.

**Comment by ericfischer** [comment]
Thanks for finding this bug!
