### ISSUE TITLE
Build progress greater than 100%

### ISSUE THREAD

**Issue by bkowshik** [mapbox/tippecanoe#268]
Running following tippecanoe command:
```
$ tippecanoe -f -z14 -Z14 -o data.mbtiles data.json
```

Logs the following from build:
```
telemetry-clipped-default.mbtiles:1: ignoring dimensions beyond two
For layer 0, using name "telemetryclippeddefault"
Sorting 530141 features
530141 features, 109957661 bytes of geometry, 530141 bytes of metadata, 0 bytes of string pool
  100.4%  14/2832/6560
```

Question: Why does the progress say `100.4%`?

**Comment by ericfischer** [comment]
There is a race condition between multiple tiling threads updating the progress indicator at the same time. I should give each of them its own independent counter so that the total can only lag behind reality instead of getting ahead of it.

**Comment by ericfischer** [comment]
Actually not a race condition, just a math error. Should be fixed in https://github.com/mapbox/tippecanoe/pull/269

**Comment by bkowshik** [comment]
Cool. Thank you @ericfischer!
