### ISSUE TITLE
support boolean values in properties

### ISSUE THREAD

**Issue by tchannel** [mapbox/tippecanoe#27]
I get a segmentation fault running tippecanoe against features which include boolean properties

**Comment by ericfischer** [comment]
Oops! Thanks. I'll investigate and fix, @tchannel.

**Comment by blkqi** [comment]
Here's a stack trace of the issue

    (lldb) target create "tippecanoe"
    Current executable set to 'tippecanoe' (x86_64).
    (lldb) settings set -- target.run-args  "-o" "test.mbtiles" "test.json"
    (lldb) r
    Process 655 launched: '/usr/local/bin/tippecanoe' (x86_64)
    Process 655 stopped
    * thread #1: tid = 0x6042, 0x00007fff8a1ac152 libsystem_c.dylib`strlen + 18, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
        frame #0: 0x00007fff8a1ac152 libsystem_c.dylib`strlen + 18
    libsystem_c.dylib`strlen + 18:
    -> 0x7fff8a1ac152:  pcmpeqb (%rdi), %xmm0
       0x7fff8a1ac156:  pmovmskb %xmm0, %esi
       0x7fff8a1ac15a:  andq   $0xf, %rcx
       0x7fff8a1ac15e:  orq    $-0x1, %rax
    (lldb) bt
    * thread #1: tid = 0x6042, 0x00007fff8a1ac152 libsystem_c.dylib`strlen + 18, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
      * frame #0: 0x00007fff8a1ac152 libsystem_c.dylib`strlen + 18
        frame #1: 0x0000000100002850 tippecanoe`serialize_string + 41
        frame #2: 0x0000000100003551 tippecanoe`read_json + 1461
        frame #3: 0x0000000100004356 tippecanoe`main + 978
        frame #4: 0x00007fff8d5235c9 libdyld.dylib`start + 1
        frame #5: 0x00007fff8d5235c9 libdyld.dylib`start + 1

**Comment by ericfischer** [comment]
Thanks for the report. Fixed in d64328ac3575ff657a610e3dc2a44a8b0dfec1d4

**Comment by tchannel** [comment]
thanks!
