### ISSUE TITLE
"pthread_join: Invalid argument" when reading multiple files, but not for each one individually

### ISSUE THREAD

**Issue by anandthakker** [mapbox/tippecanoe#272]
When I do:
```
tippecanoe --projection EPSG:3857 -z4 --read-parallel -fo /tmp/out.mbtiles file1.geojson file2.geojson file3.geojson file4.geojson
```

I get `pthread_join: Invalid argument`.

However, if I either (a) remove `--read-parallel` or (b) only use any single one of the files as input, it works fine.  Happy to share the particular files if that's helpful.

**Comment by anandthakker** [comment]
Sorry, forgot to say: the `Invalid argument` error happens after a couple seconds of "Read 0.00 million features"

**Comment by ericfischer** [comment]
Thanks for the report @anandthakker! I can't immediately reproduce this, so I'd appreciate a copy of your files. Also what OS you are using and how many CPUs your computer has.

**Comment by anandthakker** [comment]
Oh, I feel sheepish: I just realized that one of the input files is `0B` due to a bug in my data prep scripts.  I'm okay to close this @ericfischer unless you want to leave this issue open for gracefully handling a 0B file in a case like this

**Comment by ericfischer** [comment]
Thanks! That explains the problem but I should detect the empty file and make it provide a sensible error message.

**Comment by ericfischer** [comment]
Interesting: I can reproduce a problem with a special file like `/dev/null`, but not with a regular 0-byte empty file. Is it consistently reproducible for you?

**Comment by ericfischer** [comment]
Should be fixed in https://github.com/mapbox/tippecanoe/pull/273.
