### ISSUE TITLE
Support the GeoJSON / MVT 2.0 "id" field?

### ISSUE THREAD

**Issue by anandthakker** [mapbox/tippecanoe#274]
While I'm sure that the full v2.0 of the vector tile spec would be a big project, I wonder if it would be possible for tippecanoe to support the optional ["id" property for vector tile features](https://github.com/mapbox/vector-tile-spec/tree/master/2.0#42-features), based upon the [equivalent property for geojson feature objects](http://geojson.org/geojson-spec.html#feature-objects)?

Raising this in anticipation of https://github.com/mapbox/mapbox-gl-style-spec/issues/391 and https://github.com/mapbox/mapbox-gl-js/issues/2874

**Comment by ericfischer** [comment]
Oh sure, I can add that. Thanks for pointing out the omission.

**Comment by anandthakker** [comment]
👍 thanks!

**Comment by ericfischer** [comment]
I think https://github.com/mapbox/tippecanoe/pull/275 should take care of this. Please give it a try and see if it works for you.

**Comment by ericfischer** [comment]
Please also sync https://github.com/mapbox/tippecanoe/pull/276 which fixes a typo that would make it do the wrong thing if you had both an ID and a per-feature minzoom.

**Comment by anandthakker** [comment]
Ah -- thanks for the heads up!
