### ISSUE TITLE
Change Marker and Layer Value in Mapbox

### ISSUE THREAD

**Issue by achalnexus** [mapbox/tippecanoe#278]
I have set marker on map load. Now i m change same marker icon in zoom change event.
How to change layer value or in zoom change value. 
===============JS===============
var map;
var mapbounds;
var south = 0.0;
var west = 0.0;
var north = 0.0;
var east = 0.0;
var center = [-94.6858998, 46.729553];
mapboxgl.accessToken = 'pk.eyJ1IjoiYWNoYWxwcmFqYXBhdGkiLCJhIjoiY2lyNGkwZGsxMDFpenUybHd5bjRtMjVjeiJ9.2teTa5MmVqOW-MDpryv56w';
function Init() {
    if (!mapboxgl.supported()) {
        console.log('Mapbox GL not supported! Using standard map');
    } else {
        // Set Center Point Values

        // Inia map
        map = new mapboxgl.Map({
            container: 'map', // container id or map id
            //style: 'mapbox://styles/achalprajapati/cir4j4zcq000gcgnbu8t4k8wf', //stylesheet location
            style: 'mapbox://styles/achalprajapati/cir4j4zcq000gcgnbu8t4k8wf',
            center: center, // starting position
            zoom: 8, // starting zoom
            //position: 'top-left',
            minZoom: 7,
            maxZoom: 15,
            keyboard: true,
            doubleClickZoom: false,
        });
        map.scrollZoom.disable(); // Drage n drop 
        map.addControl(new mapboxgl.Navigation({ position: 'top-left' })); // Zoom in-out navigation control//

        map.on('style.load', function () {
            map.addSource("markers", {
                "type": "geojson",
                "data": {
                    "type": "FeatureCollection",
                    "features": [{
                        "type": "Feature",
                        "geometry": {
                            "type": "Point",
                            "coordinates": [-94.3303952, 46.2714266]
                        },
                        "properties": {
                            "title": "Crow Wing State Park",
                            "description": "<strong>Make it Mount Pleasant</strong><p><a href=\"javascript:void(0);\"  onclick=\'alert();\' title=\"Opens in a new window\">Make it Mount Pleasant</a></p>",
                            "marker-symbol": "ap"
                        }
                    }, {
                        "type": "Feature",
                        "geometry": {
                            "type": "Point",
                            "coordinates": [-93.9762852, 46.4785914]
                        },
                        "properties": {
                            "title": "Cuyuna Country State Recreation Area",
                            "marker-symbol": "monument"
                        }
                    }]
                }
            });

            map.addLayer({
                "id": "markers",
                "type": "symbol",
                "source": "markers",
                "layout": {
                    "icon-image": "{marker-symbol}-15",
                    "text-field": "{title}",
                    "text-font": ["Open Sans Semibold", "Arial Unicode MS Bold"],
                    "text-offset": [0, 0.3],
                    "text-anchor": "top"

                }
            });
        });
       
        map.on('zoomstart', function (e) {
            //alert(map.getZoom());
            // Every time fill color.
            RadiusDraw();
        });

    }
}
function RadiusDraw() {
    map.addLayer({
        "id": "circle500",
        "type": "circle",
        "source": "source_circle_500",
        "paint": {
            "circle-radius": {
                "stops": [
                    // zoom is 5 -> circle radius will be 1px
                    [7, 100],
                    // zoom is 10 -> circle radius will be 2px
                    [8, 200],
                    [9, 50],
                    [10, 500],
                ]
            },
            "circle-color": "#fff",
            "circle-opacity": 0.2
        }
    });
}

**Comment by ericfischer** [comment]
Tippecanoe is a tile encoder and has no control over the rendering. [Mapbox Help](https://www.mapbox.com/help/) is probably the right place to find an answer to your question or to ask for support.
