### ISSUE TITLE
Question: does tippecanoe 'split' polygons within one zoom level?

### ISSUE THREAD

**Issue by liebrand** [mapbox/tippecanoe#282]
Hi there,

Just a quick question (are github issues the best place to raise these?):

I've noticed individual geojson polygons appear to get split as multiple 'touching' polygons within one zoom level and not just at the borders of tiles. I thought tippecanoe would only simplify polygons, but not split one in to two (except at tile borders)?

This means if I style the polygon with a fill colour and stroke, I end up with a line cutting through the original shape, if that makes sense?

Still trying to work out if it's actually tippecanoe that split the polygon, but I've only noticed it on very large data sets so debugging is tricky; hence I figured I'd just ask ;-)

/Cheers,
Jelte

**Comment by ericfischer** [comment]
@liebrand Tippecanoe will split polygons with more than 700 sides into multiple features, because the geometry cleaning can get very slow with complicated polygons. You can use `--no-polygon-splitting` to keep it from doing this. I hope a future version with a better polygon cleaning algorithm will eliminate the need to ever split polygons up.

**Comment by liebrand** [comment]
@ericfischer excellent, thanks! Out of interest, what's the reasoning for it doing this? 
a- is it done for performance reasons for tippecanoe? or
b- does it help keep the size of the tileset down (I assume not, because feature A becomes two A1 and A2 features so if anything the tileset would be slightly bigger - although it's probably negligible?)
c- does it ensure the rendering of the tileset is faster?

**Comment by ericfischer** [comment]
It's for performance reasons inside tippecanoe, and as far as I know doesn't make any difference in rendering speed. It does make the tiles slightly larger.

We've been working on some new algorithms for polygon cleaning that don't bog down so badly with complex polygons, but there are still some bugs. Once everything works correctly and efficiently, I'll remove the polygon splitting.
