### ISSUE TITLE
Retain feature id in tile-join

### ISSUE THREAD

**Issue by anandthakker** [mapbox/tippecanoe#283]
I am seeing `feature.id` being successfully set by `tippecanoe`, but then dropped when i use `tile-join` to join two (zoom-disjoint) tilesets.  Example is too big to attach here, but I can send it to you if it's helpful

**Comment by ericfischer** [comment]
Oops! Thanks. I'll make sure tile-join does it right too.

**Comment by anandthakker** [comment]
👍 Thanks!

**Comment by ericfischer** [comment]
Should be fixed in https://github.com/mapbox/tippecanoe/pull/284

**Comment by anandthakker** [comment]
Confirmed!
