### ISSUE TITLE
MVT 2.1 Polygons

### ISSUE THREAD

**Issue by ShibaBandit** [mapbox/tippecanoe#285]
**Does tippecanoe currently enforce MVT 2.1 polygon winding/signed areas for interior and exterior rings? If not, are there plans to?**

For example, in the 2.1 spec (https://github.com/mapbox/vector-tile-spec/tree/master/2.1):

> 4.3.4.4. Polygon Geometry Type
...
> An exterior ring is DEFINED as a linear ring having a positive area as calculated by applying the surveyor's formula to the vertices of the polygon in tile coordinates. In the tile coordinate system (with the Y axis positive down and X axis positive to the right) this makes the exterior ring's winding order appear clockwise.

> An interior ring is DEFINED as a linear ring having a negative area as calculated by applying the surveyor's formula to the vertices of the polygon in tile coordinates. In the tile coordinate system (with the Y axis positive down and X axis positive to the right) this makes the interior ring's winding order appear counterclockwise.

Here's an example in another Mapbox project that has been changed as of ~June 9th for encoding 2.0 MVT winding order - https://github.com/mapbox/geojson-vt/blob/master/src/tile.js

https://github.com/mapbox/geojson-vt/commit/a3aa2fa80b59ff993f864b94c4d23f3bda0318ad

```js
function rewind(ring, clockwise) {
     var area = signedArea(ring);
     if (area < 0 === clockwise) ring.reverse();
 }
 
function signedArea(ring) {
     var sum = 0;
     for (var i = 0, len = ring.length, j = len - 1, p1, p2; i < len; j = i++) {
         p1 = ring[i];
         p2 = ring[j];
         sum += (p2[0] - p1[0]) * (p1[1] + p2[1]);
     }
     return sum;
}
```

For further reference on where the is coming from, see this issue: wdtinc/mapbox-vector-tile-java#1

**Comment by mourner** [comment]
It should produce valid v2.1 vector tiles. Are you seeing issues?

**Comment by ShibaBandit** [comment]
Thank you for the fast response @mourner . I mainly wanted to ask whether support for 2.1 encoding was in, I looked through the commits for some time but didn't find an answer. I'll re-open the issue if I confirm anything.
