### ISSUE TITLE
Points not showing up in mapbox studio

### ISSUE THREAD

**Issue by ianbruton** [mapbox/tippecanoe#287]
Preface, Apologies if this is the wrong place to put this, but I am running out of places to look for a solution to the issue that I am having, which I am sure is human error on my part.

I will be brief, 

What I am trying to do:
1. I am trying to convert a data set from geojson to mbtiles. 
2. Geojson file is ~125MB in size. 
3. I can get the data to show up by reading the file if hosted in s3 bucket but it is very slow, so I tried to use tippecanoe to make a tileset after being recommended by Tom from Mapbox.
4. when I upload the resulting mbtiles file to mapbox studio I can see the data in the data view but not in the style view.

I tried it with the stations.geojson example from Mapbox's site and I am still getting the same issue. If I take the stations.geojson and upload it as a data set I can see the data on the map, but if create a mbtiles file of the same data (stations), I cannot see any points in the style view either. 

I am assuming that ther is some other things that I need to do but I don't know where.

Do I need to host the tiles on my mapbox account and then apply the style to the points in my html? I tried to follow this guide but I am still a bit confused. https://www.mapbox.com/help/large-data-tippecanoe/

This data that I am working with is only a sample dataset, the end goal will be to read in data periodically from a geojson/json file that is pushed to my tippecanoe server (currently hosted in ec2 instance in AWS)

I have included some screenshots and some sample of the geojson data that I am using

Start of geojson file: (sensitive info removed)

`{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "ASSET": "ASSETNAME",
        "IP": "IPADDRESS"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -0.1043,
          43.9943
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "ASSET": "ASSETNAME",
        "IP": "IPADDRESS"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -83.1499,
          42.6056
        ]
      }
    },
    .
    .
    .
    }
  ]
}`

![image](https://cloud.githubusercontent.com/assets/4050482/17930869/aaffc7b0-6a08-11e6-8cb6-8501a1194c3a.png)
![image](https://cloud.githubusercontent.com/assets/4050482/17930881/b7ecb0f0-6a08-11e6-86d3-492605c237b9.png)
![image](https://cloud.githubusercontent.com/assets/4050482/17931270/e98657b8-6a0a-11e6-8c51-7d8e1f65004d.png)

**Comment by ericfischer** [comment]
Looking at your screenshot, the problem with the style is that the "Type" is set to Fill instead of to Circle. Fill is for polygons.

**Comment by ianbruton** [comment]
I should really have noticed this myself, points are showing up now. Thank you very much.
