### ISSUE TITLE
Romanian projection oddities

### ISSUE THREAD

**Issue by migurski** [mapbox/tippecanoe#289]
Steps to reproduce:

0. Use latest Tippecanoe from Homebrew.
    
        $ brew install tippecanoe
        $ tippecanoe --version 
        tippecanoe v1.12.9
1. Download [IMPOSM GeoJSON data for Cluj](https://mapzen.com/data/metro-extracts/metro/cluj_romania/). I’m looking at the Biserica Sfântul Mihail in the central square, [OSM way ID=202294653](http://www.openstreetmap.org/way/202294653#map=19/46.76992/23.58993&layers=D). Its [rightmost point should be at (46.76997, 23.58999)](http://www.openstreetmap.org/node/2122673947). First thing I notice is that Mapzen’s Metro Extract has it at (46.76682, 23.59325), which is a few city blocks to the south east of its OSM location. So that’s bad, but I’m going to push ahead anyway.
    
    I’ve pasted a GeoJSON file for just this Church at bottom.
2. Convert `cluj_romania_buildings.geojson` to MBTiles with Tippecanoe; no special arguments:
    
        $ tippecanoe -o cluj_romania.mbtiles cluj_romania_buildings.geojson
3. Extract [tile 16/9265/5778](http://teczno.com/squares/#16/46.76997/23.58999) where I expect to see the church:
    
        $ tippecanoe-decode cluj_romania.mbtiles 14 9265 5778 > cluj_romania-14-9265-5778.geojson
4. Open everything up in QGIS 2.14 and bask in the weirdness. I have a screenshot below, showing the correct geographic location of the church at the black star, the incorrect Mapzen Extract location of the church at the blue star, and the even-more-incorrect Tippecanoe location of the church at the orange star. They seem to be marching south and east. Is this a compounding Mercator projection error, because I’m pretty sure out IMPOSM extraction process includes this step?

<img width="683" alt="Cluj QGIS" src="https://cloud.githubusercontent.com/assets/58730/17978239/dbc8bc5c-6aa9-11e6-9f75-b521d8c11b39.png">

Just the church in `202294653.geojson`:

```JSON
{
  "type": "FeatureCollection",
  "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::4236" } },
  "features": [
    { "type": "Feature", "properties": { "id": 1797, "osm_id": 202294653, "name": "Biserica Sfântul Mihail", "type": "yes" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 23.592322605866972, 46.766812239208434 ], [ 23.592352607824118, 46.766816428844237 ], [ 23.592350513685417, 46.76683226894658 ], [ 23.592374314071968, 46.766834782563421 ], [ 23.592377665315755, 46.766819780522908 ], [ 23.592463899791248, 46.766828494288859 ], [ 23.592459961921943, 46.76684349634607 ], [ 23.592483091904548, 46.766846429030707 ], [ 23.592486945960136, 46.766831259356373 ], [ 23.592592539455733, 46.766846258304099 ], [ 23.592588769128174, 46.766860170829759 ], [ 23.592610223037866, 46.766863103561981 ], [ 23.592614160977725, 46.766849274841313 ], [ 23.592689082137397, 46.766860922269736 ], [ 23.59268673611405, 46.766868884262671 ], [ 23.592664946999886, 46.766866119159467 ], [ 23.592660757719642, 46.766881121223783 ], [ 23.592686066617155, 46.766884389085561 ], [ 23.592666879734683, 46.766953448864882 ], [ 23.592660091563797, 46.766952191911322 ], [ 23.592654645223835, 46.766967110201605 ], [ 23.59267626679117, 46.76697088102658 ], [ 23.59267073663748, 46.766985631699697 ], [ 23.592697973109541, 46.766990408082286 ], [ 23.592703335645869, 46.766975489794419 ], [ 23.592787726798896, 46.766990154105052 ], [ 23.592783704803427, 46.766999792340556 ], [ 23.592811527931232, 46.767005071565002 ], [ 23.592817812267345, 46.766989482772956 ], [ 23.59282602512036, 46.766991074925073 ], [ 23.592828790217368, 46.766984034827509 ], [ 23.592834740341743, 46.766985124185354 ], [ 23.59285392666488, 46.7669067615237 ], [ 23.592869514238714, 46.766908353466455 ], [ 23.59287202749141, 46.766894105737471 ], [ 23.592915437986445, 46.766897540704903 ], [ 23.592941583842016, 46.766882873256293 ], [ 23.592950131960006, 46.766885303496409 ], [ 23.592961026343257, 46.766883794611601 ], [ 23.592967562191109, 46.766869882007448 ], [ 23.593029996536988, 46.766880356453882 ], [ 23.593059410961505, 46.766869460351266 ], [ 23.593065109911763, 46.766874488774533 ], [ 23.59307801523984, 46.766867280769603 ], [ 23.593069215322874, 46.766858397185842 ], [ 23.593072064530919, 46.766856469480686 ], [ 23.59306217515147, 46.766847334498607 ], [ 23.593099299083089, 46.766829314348279 ], [ 23.593128630580775, 46.766833001144661 ], [ 23.59312527936719, 46.766848506043708 ], [ 23.593142459250597, 46.766850768419275 ], [ 23.593145978142022, 46.766836436851975 ], [ 23.593184276770884, 46.766842470066834 ], [ 23.593189222420563, 46.766863003315365 ], [ 23.593207156274772, 46.766860907562489 ], [ 23.593202043007725, 46.7668402066992 ], [ 23.593234641915345, 46.766828388598917 ], [ 23.59325534193988, 46.766837104225367 ], [ 23.593266822263306, 46.766824197197856 ], [ 23.593246122243812, 46.766815565381165 ], [ 23.593251903077807, 46.766788662287063 ], [ 23.593285843146113, 46.766781872733787 ], [ 23.593279557000933, 46.766767373825346 ], [ 23.593242600036657, 46.766774750132541 ], [ 23.593230949707326, 46.766747763723544 ], [ 23.593247709317772, 46.766729157483098 ], [ 23.593224746695583, 46.766722118115894 ], [ 23.593209662880898, 46.766736114772478 ], [ 23.593174381268909, 46.766731506237754 ], [ 23.593178989441437, 46.766714408917757 ], [ 23.593158289779709, 46.766711727593339 ], [ 23.593153513999887, 46.766728824918097 ], [ 23.593118986630813, 46.766724383981476 ], [ 23.593123092082251, 46.766708962870773 ], [ 23.59310943198723, 46.766707287063539 ], [ 23.593110269499615, 46.766698570825689 ], [ 23.593133985563483, 46.766692452040637 ], [ 23.5931296273355, 46.766685160716037 ], [ 23.593108592927827, 46.766690273707958 ], [ 23.593092669474252, 46.766677618887627 ], [ 23.593097529334869, 46.766665131096815 ], [ 23.593074399065067, 46.766657421256369 ], [ 23.593066270781613, 46.766668568183952 ], [ 23.593027804409374, 46.766660272110627 ], [ 23.593035680924086, 46.766643174697883 ], [ 23.593013388836869, 46.766637895316407 ], [ 23.593005763632313, 46.766653316526998 ], [ 23.592989756677429, 46.766645690294098 ], [ 23.592995957003328, 46.766626665304663 ], [ 23.592976011559287, 46.766623732529602 ], [ 23.592972157322261, 46.766635885052885 ], [ 23.592910477294776, 46.766626835350785 ], [ 23.592915253175381, 46.766611414221067 ], [ 23.592896732398344, 46.766608565215314 ], [ 23.592891788905415, 46.766623902540054 ], [ 23.592798682374728, 46.766612590866835 ], [ 23.592803542053932, 46.76659708592495 ], [ 23.592784853679678, 46.766594404543468 ], [ 23.59278007779405, 46.766609741863455 ], [ 23.592696105825453, 46.766597843262666 ], [ 23.59270029515611, 46.766583679295863 ], [ 23.592680349722137, 46.76658091414032 ], [ 23.592675992774105, 46.76659491049238 ], [ 23.592608614078557, 46.76658552571309 ], [ 23.592613138593553, 46.766570858878254 ], [ 23.592588081086767, 46.766567255770319 ], [ 23.592591348748684, 46.766555941361204 ], [ 23.592570146244871, 46.766552924812089 ], [ 23.59256369467435, 46.766574715530432 ], [ 23.592444776283084, 46.766557789336758 ], [ 23.592446451857111, 46.766549492123865 ], [ 23.592422651495735, 46.766547397555762 ], [ 23.592418881485671, 46.766566590095721 ], [ 23.592389466249795, 46.766563992828502 ], [ 23.592387288070583, 46.766575893874943 ], [ 23.592416703316534, 46.766578658761652 ], [ 23.592400365702559, 46.766646796552855 ], [ 23.592366173583294, 46.766642942274991 ], [ 23.592362319477321, 46.766657273851798 ], [ 23.592395673570202, 46.766661295772948 ], [ 23.59237506195521, 46.766729182256228 ], [ 23.592345981858308, 46.766725327833271 ], [ 23.592340116389245, 46.766738402320897 ], [ 23.592370118351443, 46.766742675766451 ], [ 23.592351098658025, 46.766804779331721 ], [ 23.592326292567225, 46.766801260026412 ], [ 23.592322605866972, 46.766812239208434 ] ] ] } }
  ]
}
```

**Comment by ericfischer** [comment]
I am pretty sure the GeoJSON metro extract is just in the wrong projection, and this is leading to a cascade of errors.

As, you say, OSM thinks [node 2122673947](http://www.openstreetmap.org/node/2122673947) in [way 202294653](http://www.openstreetmap.org/way/202294653) is at 46.7699694,23.5899938. Google, Bing, Mapbox Satellite, etc., all seem to agree that this is correct.

A round trip through Tippecanoe for this point:

```
$ echo '{ "type": "Feature", "properties": {}, "geometry": { "type": "Point", "coordinates": [ 23.5899938, 46.7699694 ] } }' | ./tippecanoe -f -o point.mbtiles -Z14
…
$ ./tippecanoe-decode point.mbtiles
…
{ "type": "Feature", "properties": {  }, "geometry": { "type": "Point", "coordinates": [ 23.589991, 46.769972 ] } }
```

puts it at 46.769972, 23.589991 which is about a foot of rounding error away. It is in both tiles 14/9265/5778 and 14/9265/5777 because of buffering at the tile edges. Viewing `point.mbtiles` with [mbview](https://github.com/mapbox/mbview) shows the point where it should be.

If I use [minjur](https://github.com/mapbox/minjur) to extract the church from the .osm version of the metro extract:

```
$ ./minjur ../../Downloads/cluj_romania.osm.bz2 | grep 202294653 | ../../tippecanoe/tippecanoe -f -o biserica.mbtiles
```

then `mbview` shows the whole church in the correct location, and `tippecanoe-decode` shows `[ 23.589991, 46.769972 ]` as one of the coordinate pairs in its outline.

Meanwhile, if I take the (wrongly projected) `cluj_romania_buildings.geojson` and run it through tippecanoe and tippecanoe-decode:

```
$ cat cluj_romania_buildings.geojson | grep 202294653 | ../../tippecanoe/tippecanoe -o biserica.mbtiles
…
$ ../../tippecanoe/tippecanoe-decode biserica.mbtiles 14 9265 5778 > out.json
```

I get [two essentially identical polygons](https://gist.github.com/ericfischer/49f12feab95125cb90fc6c5dac6bb6de) from the input and output, even though they are both in the wrong place.

As far as I can tell, Tippecanoe is doing the correct thing when it has correct input and is behaving predictably even when the input is wrong.

**Comment by migurski** [comment]
Thank you for investigating! We do have a CRS defined for the GeoJSON output, but it’s EPSG:4326 which should be a no-op. I’ll take this up with folks here and see if we can come up with something.

**Comment by migurski** [comment]
(I have just confirmed that removing the CRS line from the GeoJSON input prevents Tippecanoe from  translating the church to the south and east, so clearly the value there is wrong)

**Comment by migurski** [comment]
Ha, we had an errant "4236" in our process, which is [similar-enough to pass a smell test](http://spatialreference.org/ref/epsg/4236/) but uses the wrong ellipse. Thank you for being responsive.

**Comment by ericfischer** [comment]
Tippecanoe even gives the warning:

```
luj_romania_buildings.geojson: Warning: GeoJSON specified projection "urn:ogc:def:crs:EPSG::4236", not "urn:ogc:def:crs:OGC:1.3:CRS84".
```

but I completely missed it.
