### ISSUE TITLE
option name collision?

### ISSUE THREAD

**Issue by haoliangyu** [mapbox/tippecanoe#291]
I try to use the following command to generate tile

```  bash
cat /regions.geojson | tippecanoe --output=regions.mbtiles --layer=ckan --simplify=10 --force --drop-polygons --no-polygon-splitting --reverse
```

but it returns the error

```
tippecanoe: option \'--simplify-only-low-zooms\' doesn\'t allow an argument.
```

I suspect there is a name collision between `--simplify` and `--simplify-only-low-zooms`.

**Comment by ericfischer** [comment]
Oops, the documentation is wrong. The name of the option is `--simplification=10`, not `--simplify=10`. I'll fix it.

**Comment by ericfischer** [comment]
https://github.com/mapbox/tippecanoe/pull/293
