### ISSUE TITLE
Strange visual effects after running tippecanoe

### ISSUE THREAD

**Issue by sabman** [mapbox/tippecanoe#292]
I am using mapbox vector tileservice. To set my zoom range I use something like the following

```bash
tippecanoe -o atlas-sa1-services.mbtiles -Z 7 -z 15 atlas-sa1-services.geojson -l atlas-sa1-services
```
I am now seeing strange effects when rendering my vector tiles
![strangeness-mapbox](https://cloud.githubusercontent.com/assets/1907/18037249/b56de7ac-6d7f-11e6-9bb4-505b862c23e3.gif)

**Comment by ericfischer** [comment]
The blocky polygons you see at low zooms are Tippecanoe's best attempt to fit as good a representation of the data as it can into the 500K limit on tile sizes. You may be able to get it to work better by using `-x` or `-y` to exclude unneeded feature attributes, leaving more room for better geometry.

**Comment by sabman** [comment]
thanks @ericfischer
