### ISSUE TITLE
Make polygon simplification aware of shared edges

### ISSUE THREAD

**Issue by ericfischer** [mapbox/tippecanoe#301]
And simplify them the same in both polygons

**Comment by mtirwin** [comment]
:heart_eyes:

cc/ @ryanbaumann

**Comment by ericfischer** [comment]
The topology information that comes out this should also enable parcel merging (https://github.com/mapbox/tippecanoe/issues/169).

**Comment by ericfischer** [comment]
Working on this in https://github.com/mapbox/tippecanoe/pull/302

**Comment by ericfischer** [comment]
There is a missing edge at z1 with

```
tippecanoe -ps --simplify-polygons-together --no-polygon-splitting -f -z5 -o proper3.mbtiles ne_10m_admin_0_countries.json
```

![screen shot 2016-09-26 at 10 53 50 pm](https://cloud.githubusercontent.com/assets/1951835/18861711/3bb6c4dc-843c-11e6-8f69-3868bae8cbac.png)

**Comment by ericfischer** [comment]
The missing edge also happens without this new code even running.

```
grep Russia ne_10m_admin_0_countries.json | time ./tippecanoe -ps --no-polygon-splitting -f -Z1 -z1 -o separate.mbtiles
```

**Comment by ericfischer** [comment]
And the missing edge ends up in a different place in the `partition` branch, even though the output polygon ultimately contains the same points.

One suspicious thing is that Russia here is a polygon ring with 17393 points, which is quite large, and there are strange rendering artifacts as you zoom in. I wonder if GL has an internal limit of 16384 points per polygon ring and this is running into it.

**Comment by ericfischer** [comment]
Merged. The Russian polygon displays fine in Studio even though mbview has a hard time with it.

**Comment by ryanbaumann** [comment]
@ericfischer great work!  Will test this with some large workflows asap.

**Comment by ericfischer** [comment]
Hope it works for you @ryanbaumann! Please note you have to specify `--detect-shared-borders` to turn the feature on.

**Comment by ericfischer** [comment]
Same problem apparently came up recently in the QGIS world: http://philmikejones.me/2016/09/29/simplify-polygons-without-creating-slithers/
