### ISSUE TITLE
Alert if features are not URIEncode-able

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/tippecanoe#305]
# Issue 
Creating vector tiles from geojson with properties that are not Unicode works.  However, the property data causes a URIEncode error when serving the vector tiles from Mapbox API's.

# Replicate
Create a geojson feature with a non-Unicode value in properties.
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "name": "è\"//\\"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [[[20.214843749999996,
              54.87660665410869],
            [4.74609375,
              46.800059446787316],[16.34765625,
              36.87962060502676],[35.33203125,
              48.69096039092549],[20.214843749999996,
              54.87660665410869]]]}}]}
```

Create a Vector Tile from Tippecanoe with the feature

Upload the feature to Mapbox.

Add the vector tile to a Map Style in Studio.  Get the following error:

![](https://cl.ly/000S1E371t1T/download/Image%202016-09-23%20at%208.15.47%20AM.png)

# Expected Behavior

Tippecanoe warns or encodes non-Unicode characters.

**Comment by ericfischer** [comment]
Thanks @ryanbaumann. https://github.com/mapbox/tippecanoe/pull/304 will make it an error to have string feature attributes that are not correctly UTF-8-encoded.

**Comment by ericfischer** [comment]
Merged!
