### ISSUE TITLE
how to update the geojson features geometry in mbtiles?

### ISSUE THREAD

**Issue by lzxue** [mapbox/tippecanoe#306]
if the geojson features geometry  edited,how upateed the mbtiles?

**Comment by ericfischer** [comment]
@lzxue In most cases, if you change the GeoJSON, you will need to run `tippecanoe` again to make new mbtiles.

If you just added some new features, and you have those new features in a separate GeoJSON file, you can use `tile-join` to merge a new mbtiles file of them with an existing mbtiles, like this:

```
tippecanoe -o newfeatures.mbtiles newfeatures.json
tile-join -o combined.mbtiles newfeatures.mbtiles oldfeatures.mbtiles
```
