### ISSUE TITLE
make: protoc: Command not found

### ISSUE THREAD

**Issue by devTristan** [mapbox/tippecanoe#31]
Ubuntu 14.04

Solved w/ `sudo apt-get install protobuf-compiler`

Looks like libprotobuf-dev does not provide it. Documentation needed?

**Comment by ericfischer** [comment]
Oops, thanks @devTristan, I'll add that. My Linux machines all have a zillion packages already installed and I didn't realize that one needed to be installed separately.

**Comment by ericfischer** [comment]
Thanks. Fixed in fa9474ff74abfcacc10deb219.

**Comment by ShifaSZ** [comment]
Solved w/ ```sudo apt-get install libprotobuf-dev protobuf-compiler```
as suggested by https://github.com/tensorflow/models/issues/1116 which also solves the 'google/protobuf/stubs/common.h' file not found issue.

**Comment by ericfischer** [comment]
Tippecanoe should not actually need `protoc` any more. Are you still seeing a dependency?
