### ISSUE TITLE
Can't generate tile with very dense polygon layer

### ISSUE THREAD

**Issue by palmerj** [mapbox/tippecanoe#311]
I have a dense polygon layer of parcel boundaries containing 2.5 million records and over 75 million points. I've tried all sorts of options to generate tiles for the data, but it keeps failing on zoom level 8. Here's the data:

https://dl.dropboxusercontent.com/u/30623980/nz_primary_parcels.json.zip

<img width="906" alt="screen shot 2016-10-21 at 9 00 00 pm" src="https://cloud.githubusercontent.com/assets/580022/19591027/7e385dfe-97d1-11e6-9306-efb87edf4f45.png">

The last set of options I tried was:

```
tippecanoe -X -r4.0 -d 8 -B 18 -S 10 -pd -ar -o primary_parcels.mbtiles nz_primary_parcels.json
```

output https://gist.github.com/palmerj/d99ce2d3a3de2d083767ff14d8703520

I also tried the `-pk` option but that also failed (And also ended up with large vtiles).

I'm running on MacOSX using latest master build. 

```
tippecanoe --version
tippecanoe v1.14.4
```

Any suggestions?

**Comment by ericfischer** [comment]
Thanks @palmerj, I'll download this and give it a try. Parcels are [something I've been struggling with for a while](https://github.com/mapbox/tippecanoe/issues/169) but I'm hoping the [recent work on shared polygon edges](https://github.com/mapbox/tippecanoe/issues/301) will also enable some more useful ways of manipulating parcels.

**Comment by palmerj** [comment]
Thanks @ericfischer. I can get process to complete now using `-g2', but that option doesn't work at low zoom level (e.g 0-8) as too many features are dropped out and weird artifacts appear. For example large polygons on the edge of the parcel network disappearing:

<img width="823" alt="gamma_0 5_z4" src="https://cloud.githubusercontent.com/assets/580022/19622811/e50e3bcc-990f-11e6-953f-e0e3b08b85e1.png">

Compare that against a process run without any gamma applied (`tippecanoe -X -P -f -o primary_parcels_2.mbtiles ../nz_primary_parcels.json`):

<img width="998" alt="no_gamma" src="https://cloud.githubusercontent.com/assets/580022/19622818/0448bf62-9910-11e6-9690-3014f699b5ec.png">

Also at mid level zooms (i.e z7-8) very large polygon get reduced too much which causes vertical and horizontal straight line artifacts:

Zoom 7:
<img width="1222" alt="vertical_line_2_z7" src="https://cloud.githubusercontent.com/assets/580022/19622859/b6bfa5ca-9910-11e6-863d-7e55a0648f28.png">


Zoom 8:
<img width="737" alt="horizontal_line_1_z8" src="https://cloud.githubusercontent.com/assets/580022/19622842/6b1abc22-9910-11e6-9378-9bd74c2f4858.png">

Zoom 7:
<img width="1133" alt="vertical_line_1_z7" src="https://cloud.githubusercontent.com/assets/580022/19622843/70d13538-9910-11e6-9ce6-9d9fe3629e70.png">

The vtiles generated from z0-8 when not using the gamma option are good, and the vtiles generated from z9-14 when not using the gamma option are also good. Able to get the best of both worlds?

Thanks.

**Comment by ericfischer** [comment]
Hmm, maybe I can add an option to keep bumping up the gamma value if a tile is too big until it fits. I'll give that a try.

**Comment by palmerj** [comment]
Thanks!

**Comment by ericfischer** [comment]
Working on this in https://github.com/mapbox/tippecanoe/pull/312 if you want to try it.

The big trouble with adjusting the gamma dynamically is that, because it gets adjusted in each tile, the tile boundaries become visible when one tile has much more data to represent than its neighbors.

![screen shot 2016-10-24 at 12 24 15 pm](https://cloud.githubusercontent.com/assets/1951835/19660511/febee00a-99e4-11e6-8edd-a6be41bb6bfa.png)

So this is another case where it really needs to preflight the entire zoom level to choose parameters, and then go back and do the whole zoom level again with whatever options work for the worst tile.

**Comment by palmerj** [comment]
> So this is another case where it really needs to preflight the entire zoom level to choose parameters, and then go back and do the whole zoom level again with whatever options work for the worst tile.

That makes sense. Thanks again.

**Comment by ericfischer** [comment]
I've started working on a `--merge-polygons-as-needed` option to combine, rather than, dropping, polygons, but it is too slow currently to be effective with this much data.

**Comment by palmerj** [comment]
Thanks. Yes it's a large dataset!

**Comment by ericfischer** [comment]
The `--increase-spacing-as-needed` option in this pull request doesn't know anything about polygon topology, but gives the most satisfying results I've been able to come up with for the general case of thinning tiles. It has a rural bias, though, tending to keep big rural features and losing small urban ones.

The alternative is `--drop-fraction-as-needed`, which preserves the original spatial distribution of features rather than tending to space the remaining features evenly across the tile. It then has an urban bias, keeping more closely spaced features than can really be distinguished while leaving big gaps in rural areas.

Both of these now apply to entire zoom levels, not just tiles, so there is no longer a big problem with visible jumps in density at tile boundaries.

I really need some sort of compromise that comes out somewhere between the rural bias of the former and the urban bias of the latter.

**Comment by palmerj** [comment]
Thanks @ericfischer! Any chance to somehow resolve the weird horizontal artifacts I report above and some of the large coastal polygons getting removed from the solution?

**Comment by ericfischer** [comment]
The horizontal and vertical artifacts you can probably get rid of with `--no-polygon-splitting`, at the cost of some slower processing. I still don't have a good answer for how to determine which polygons are the most significant and must be preserved.

**Comment by ericfischer** [comment]
I just added a `--drop-smallest-as-needed` feature that I think will do what you are looking for. To make the tiles small enough, it will lose all the small urban parcels at low zoom levels, but will keep all the large water parcels.

**Comment by palmerj** [comment]
Thank again @ericfischer. I used the following command to generate a vectortile set with didn't split ploygons and maintained the outer extents of the coverage:

```
tippecanoe -X -P -f --drop-smallest-as-needed --no-polygon-splitting --drop-fraction-as-needed -o primary_parcels_2.mbtiles ../nz_primary_parcels.json
```

However `--drop-smallest-as-needed` does seems to aggressively remove all urban parcel (as you documented) from zoom level 6 - 10 and created holes in the coverage. 

Is there some way to keep some of the polygons in the urban areas to show density rather than just completely removing them? Maybe at the cost of further simplifying the rural parcels? I tried both the `--increase-spacing-as-needed` and the `--drop-fraction-as-needed` options and didn't manage to achieve this. But maybe they are in conflict with `--drop-smallest-as-needed`?

**Comment by ericfischer** [comment]
As it stands right now, it will try only one size-reduction strategy at a time, so it doesn't help to specify several of them. There might be some useful compromise it could make, though, between dropping just the smallest features and dropping a uniform fraction of them.

You make a good point that bumping up simplification may help, but I don't think it's enough. For instance,

    ./tippecanoe -X -P -f --drop-smallest-as-needed --no-polygon-splitting --simplification=100 -o primary_parcels_2.mbtiles ../Downloads/nz_primary_parcels.json

is enough simplification to make a lot of the larger polygons look terrible, but not enough to keep any reasonable number of urban parcels.

I still think the best hope is to merge adjacent small polygons into larger, combined features, but I still haven't figured out an efficient way to do it.

**Comment by palmerj** [comment]
> I still think the best hope is to merge adjacent small polygons into larger, combined features, but I still haven't figured out an efficient way to do it.

Oh yes that would be good :) Would it not be possible to determine candidates for merging with some sort of snapped grid index based on the resolution of the zoom level?

**Comment by ericfischer** [comment]
That's sort of what `--merge-polygons-as-needed` is already doing, since it is using the quadkey indexes of features to determine which pairs of features are the best candidates for merging, but finding the shared edges is still expensive. It may work to just concatenate the geometries and let Clipper sort it out, though.

**Comment by palmerj** [comment]
Oh great thanks.

**Comment by ericfischer** [comment]
I've started another branch, [wagyu-dynamic-gamma](https://github.com/mapbox/tippecanoe/tree/wagyu-dynamic-gamma), where `--merge-polygons-as-needed` concatenates the geometries and uses Wagyu to find the common edges. It seems to work on more modest data, but I still have not managed to get through a successful run with these parcels.

**Comment by palmerj** [comment]
Thanks I'll take a look.

**Comment by ericfischer** [comment]
I am running this now with a few additional changes. As currently checked in, it crashes at zoom level 5. With some additional changes, it makes it through zoom level 5 but is extremely slow (more than an hour) at trying to generate zoom level 6, in particular tile 6/63/39.

**Comment by palmerj** [comment]
Thanks. Once you check the new code in I will give it a go.

**Comment by ericfischer** [comment]
With the latest changes and

    tippecanoe -P -X -f -o nz.mbtiles --merge-polygons-as-needed --no-polygon-splitting ../Downloads/nz_primary_parcels.json

I've been able to make it through zooms 6 and 7, but tile 8/252/156 is still quite slow to reduce to a small enough form. I think it still needs

* better guessing about what fraction of features to drop, since the combined geometry of 2 polygon rings comes out larger than 1/2 the size of the unmerged geometry, and
* line simplification after merging, since it is probably leaving unneeded nodes in the merged geometries

**Comment by palmerj** [comment]
> I've been able to make it through zooms 6 and 7, but tile 8/252/156 is still quite slow to reduce to a small enough form

I see what you mean, it's been 3 hours of processing and still no result lower than 500k for that tile:

```
Going to try merging the densest 91.62% of the features to make it fit
tile 8/252/156 size is 675945 with detail 12, >500000
Going to try merging the densest 99.82% of the features to make it fit
tile 8/252/156 size is 640988 with detail 12, >500000
Going to try merging the densest 99.88% of the features to make it fit
tile 8/252/156 size is 621797 with detail 12, >500000
Going to try merging the densest 99.91% of the features to make it fit
tile 8/252/156 size is 600963 with detail 12, >500000
Going to try merging the densest 99.93% of the features to make it fit
tile 8/252/156 size is 586172 with detail 12, >500000
Going to try merging the densest 99.95% of the features to make it fit
tile 8/252/156 size is 576709 with detail 12, >500000
Going to try merging the densest 99.96% of the features to make it fit
tile 8/252/156 size is 568527 with detail 12, >500000
Going to try merging the densest 99.97% of the features to make it fit
tile 8/252/156 size is 561583 with detail 12, >500000
Going to try merging the densest 99.97% of the features to make it fit
tile 8/252/156 size is 555062 with detail 12, >500000
Going to try merging the densest 99.98% of the features to make it fit
tile 8/252/156 size is 548841 with detail 12, >500000
Going to try merging the densest 99.98% of the features to make it fit
tile 8/252/156 size is 542840 with detail 12, >500000
Going to try merging the densest 99.99% of the features to make it fit
tile 8/252/156 size is 541170 with detail 12, >500000
Going to try merging the densest 99.99% of the features to make it fit
tile 8/252/156 size is 535214 with detail 12, >500000
Going to try merging the densest 99.99% of the features to make it fit
tile 8/252/156 size is 535033 with detail 12, >500000
Going to try merging the densest 99.99% of the features to make it fit
tile 8/252/156 size is 533309 with detail 12, >500000
Going to try merging the densest 99.99% of the features to make it fit
tile 8/252/156 size is 531487 with detail 12, >500000
Going to try merging the densest 99.99% of the features to make it fit
tile 8/252/156 size is 524628 with detail 12, >500000
Going to try merging the densest 99.99% of the features to make it fit
tile 8/252/156 size is 522536 with detail 12, >500000
Going to try merging the densest 100.00% of the features to make it fit
tile 8/252/156 size is 519715 with detail 12, >500000
Going to try merging the densest 100.00% of the features to make it fit
tile 8/252/156 size is 518614 with detail 12, >500000
Going to try merging the densest 100.00% of the features to make it fit
tile 8/252/156 size is 519320 with detail 12, >500000
Going to try merging the densest 100.00% of the features to make it fit
tile 8/252/156 size is 517487 with detail 12, >500000
Going to try merging the densest 100.00% of the features to make it fit
tile 8/252/156 size is 515267 with detail 12, >500000
Going to try merging the densest 100.00% of the features to make it fit
tile 8/252/156 size is 512816 with detail 12, >500000
Going to try merging the densest 100.00% of the features to make it fit
tile 8/252/156 size is 509992 with detail 12, >500000
Going to try merging the densest 100.00% of the features to make it fit
tile 8/252/156 size is 512536 with detail 12, >500000
Going to try merging the densest 100.00% of the features to make it fit
```

**Comment by palmerj** [comment]
@ericfischer I finally got the vector tile set to generation! Took about 7.5 hours. Unfortunately the results have visual density inconsistencies between tiles. See examples:

<img width="1070" alt="screen shot 2016-11-20 at 3 36 36 pm" src="https://cloud.githubusercontent.com/assets/580022/20459919/c19b025e-af37-11e6-8f1c-0dd23180bc59.png">

![Uploading Screen Shot 2016-11-20 at 3.36.56 PM.png…]()

![Uploading Screen Shot 2016-11-20 at 3.37.07 PM.png…]()

I've attached the mbtiles file result if you would like to look at the final result: https://dl.dropboxusercontent.com/u/30623980/primary_parcels_2.mbtiles.zip

**Comment by ericfischer** [comment]
Thanks for following through on the 7.5 hour process! I'm not sure what I did wrong that allowed the adjacent tiles to be merged differently, but I'll investigate and try to fix it.

**Comment by timiyay** [comment]
FWIW I have a similar use case for Victorian parcels - 2.4GB of GeoJSON.

I used the new `--drop-densest-as-needed` flag in `1.15.0`, and it gave good results down to zoom 0, which I'd never been able to achieve before. No inconsistencies along tile boundaries.

![vic_parcels](https://cloud.githubusercontent.com/assets/1470250/20504779/67fae68a-b09d-11e6-95ea-a360f9be06bd.png)

There's visible gaps in the densest areas at low zooms, like the centre of Melbourne, which I find perfectly acceptable. This new flag allows larger rural parcels to be viewed at lower zooms, and progressively-higher levels of details for urban areas when zooming in.

![melb_parcels](https://cloud.githubusercontent.com/assets/1470250/20504825/a1bd88d2-b09d-11e6-9f8f-701984fd1917.png)

Thanks @ericfischer!

**Comment by ericfischer** [comment]
Glad to hear it's working for your data, @timiyay!

**Comment by ericfischer** [comment]
Empirically, from testing with

    ./tippecanoe -f -o foo.mbtiles -X --no-polygon-splitting --merge-polygons-as-needed -M15000 tl_2010_06001_tabblock10.json

merging fraction x of the polygons results in a tile size of about x ** .3, so that's the curve that it needs to follow when deciding how many polygons to try to merge.

**Comment by ericfischer** [comment]
For an entirely different approach, try https://github.com/mapbox/tippecanoe/pull/325 with

    tippecanoe -P -X -f -o nz.mbtiles -D8 --grid-low-zooms --no-polygon-splitting ../Downloads/nz_primary_parcels.json

to coarsely preserve a sample of features by snapping their edges to the tile grid.

![screen shot 2016-11-28 at 3 59 30 pm](https://cloud.githubusercontent.com/assets/1951835/20691130/b6578960-b583-11e6-9797-9a198f85aad3.png)

**Comment by palmerj** [comment]
ok thanks. I will download and try now

**Comment by palmerj** [comment]
Thanks heaps again @ericfischer. The -D8 option was a little too rasterised (as you pictured). I tried -D11 but it failed on zoom 9  due to the level of detail being too high to fit the data into one one - but it looked nice up to zoom 8. -D10 seemed almost about right but there are a few areas that a still a little too rasterised.

**Comment by wheredoesyourmindgo** [comment]
this is a great thread. thanks to @palmerj and @ericfischer for clearing up some things relating to parcel-like tilesets.

**Comment by ericfischer** [comment]
Closing because I think I've gone as far on this as I can.

**Comment by palmerj** [comment]
Are the results of any of this work getting merged into master?

**Comment by palmerj** [comment]
Ok sorry i see both PRs have been merged!

**Comment by ericfischer** [comment]
Sorry for the confusion! It's all included in recent releases.

**Comment by palmerj** [comment]
@palmerj:
>> Oh yes that would be good :) Would it not be possible to determine candidates for merging with some sort of snapped grid index based on the resolution of the zoom level?

@ericfischer:
> That's sort of what --merge-polygons-as-needed is already doing, since it is using the quadkey indexes of features to determine which pairs of features are the best candidates for merging, but finding the shared edges is still expensive. It may work to just concatenate the geometries and let Clipper sort it out, though.

Sorry to dig this old issue up, but any chance to look at the `--merge-polygons-as-needed` reduction method again? I see it's been [removed](https://github.com/mapbox/tippecanoe/commit/bedace67e7a67672994aa8c1c23d051df144a38c) from master due to problems. I've now been looking at this again and trying to include a minimum set of attributes needed for stying but the tile sizes are too large for the visual results that are acceptable. I've found the `--grid-low-zooms` options is best e.g:

```
tippecanoe -P -f -o parcels.mbtiles --maximum-tile-bytes=5800000 --detect-shared-borders -D11 --no-polygon-splitting --grid-low-zooms --include=id --include=parcel_intent --include=appellation nz_primary_parcels.geojson
```

But tiles like 9/504/312 are over 5MBs with over 300k features.

I really like the idea of --merge-polygons-as-needed if it can be improved.

I can raise a new issue if it's an option. Happy to help as much as I can

**Comment by ericfischer** [comment]
@palmerj The `--coalesce-smallest-as-needed` option is the best I can currently suggest for polygons, and mostly does what I had intended `--merge-polygons-as-needed` to do. (It does in fact do the "just concatenate the geometries and let Clipper sort it out" process that I speculated about above.)

Could you try it and see if it works for your data? If a `--coalesce-densest…` or `--coalesce-fraction…` would work better, I could add either or both of those.

**Comment by palmerj** [comment]
Thanks @ericfischer.

I tried running: 

```
tippecanoe -P -f -o parcels-coalesce.mbtiles --detect-shared-borders -D11 --no-polygon-splitting --coalesce-smallest-as-needed --include=id --include=parcel_intent --include=appellation nz_primary_parcels.geojson
```

However the result is the dense effect within urban areas is lost:

![parcels-coalesce](https://user-images.githubusercontent.com/580022/35846924-6b3e9968-0b7d-11e8-97a7-482987bfc320.png)

Compare that against grid-low-zooms test I did above:

![parcels-grid](https://user-images.githubusercontent.com/580022/35846947-803b34ac-0b7d-11e8-8ae3-e940705cda01.png)

Thank you.
Jeremy

**Comment by ericfischer** [comment]
Hmm, yes, that doesn't look great. A `--coalesce-fraction-as-needed` would at least keep the rate of feature coalescing constant across the area, so maybe that would preserve a better sense of the original density. I'll give that a try when I get a chance.

**Comment by palmerj** [comment]
Thanks @ericfischer, you are awesome!

**Comment by ericfischer** [comment]
OK, https://github.com/mapbox/tippecanoe/pull/529 will add `--coalesce-fraction-as-needed` and `--coalesce-densest-as-needed`.

It still has to merge quite a lot of features in the medium zooms (and some of the merges are of large, prominent features), but is more consistent with the original texture than before. I used:

```
zcat /Users/enf/Downloads/nz_primary_parcels.json.gz | ./tippecanoe -zg -P -f -o parcels-coalesce.mbtiles -D11 --no-polygon-splitting --coalesce-fraction-as-needed --include=id --include=parcel_intent --include=appellation
```

**Comment by ericfischer** [comment]
As you would probably expect `--coalesce-densest-as-needed` does a better job on the large features at the cost of losing texture in the dense areas.

**Comment by palmerj** [comment]
Thank you. Just wonder do I need to provide both the -D11 and -zg options? Or is -zg enough

**Comment by ericfischer** [comment]
They are independent. If you don't specify the `-D11` you get the default detail of 12. If you don't specify `-zg` you get the default maxzoom of 14.

**Comment by palmerj** [comment]
> They are independent. If you don't specify the -D11 you get the default detail of 12. If you don't specify -zg you get the default maxzoom of 14.

Thank you.

The result of `--coalesce-fraction-as-needed` and `--coalesce-densest-as-needed`. Still don't seem to product the result I'm after. 

`--coalesce-fraction-as-needed` does well in the dense urban areas, but rural areas are really sparse:

![parcels-coalesce-fraction](https://user-images.githubusercontent.com/580022/36067751-a4286552-0f28-11e8-855c-bf9a2041b49c.png)

`--coalesce-densest-as-needed` is the opposite:

![parcels-coalesce-densest](https://user-images.githubusercontent.com/580022/36067753-ad6621c2-0f28-11e8-9e88-c68e18485acc.png)

Possible to combine the two methods somehow?

**Comment by ericfischer** [comment]
The best thing I can think of is https://github.com/mapbox/tippecanoe/pull/530, which allows specifying both `--coalesce-densest-as-needed` and `--coalesce-fraction-as-needed` together, to back off in both directions at the same time. I don't think the results are better than doing just one or the other though.

**Comment by ericfischer** [comment]
Maybe I should try K-means clustering instead of the quadkey clustering. It'll be slow, but it should choose better-looking clusters than these ones, which tend to start looking gridded.

**Comment by palmerj** [comment]
> Maybe I should try K-means clustering instead of the quadkey clustering

That would be interesting to see. Any idea how much slower?

**Comment by elgelbo** [comment]
Disclaimer: I'm new to JS and CLI. But, FWIW - struggling with this as well.

I was able to render a decent tiles on a parcel set with ~20,000k records using `-P -f -ac --no-polygon-splitting` flags. A few parcels got dropped at high zoom, which won't work for my application (lookup data by parcel). 

I also had a challenge converting from shp to geojson to even be able to run (did I mention I'm new). I tried to have tippecanoe read individual .geojson files for each record and concat those as part of creating tileset. This approach did not work, as I was generating a lot of metadata that exceeded limit. 

All this to say: **my best results for creating a tileset from a shp file full of parcels was using the online mapbox dashboard.** It was much easier and looks great at all zoom levels.

**Comment by ericfischer** [comment]
Thanks for adding your experience @elgelbo.

For converting `shp` to `geojson` I generally use `ogr2ogr`, like

```
ogr2ogr -f GeoJSON file.json file.shp
```

If you are using lots of GeoJSON files as input and specifying them all on the command line, you probably want to specify a layer name with `-l` so they all get merged into the same layer.

I'm glad to hear the Mapbox uploader worked for you. I think it allows larger tiles than are allowed when you upload an `mbtiles` file, so that is probably why you were able to get away with having lots of metadata.

**Comment by palmerj** [comment]
@ericfischer: Any chance to look at the K-means clustering options?

**Comment by ericfischer** [comment]
Sorry, no, I haven't had a chance to try the K-means clustering.
