### ISSUE TITLE
How to build it on iOS?

### ISSUE THREAD

**Issue by nhatlee** [mapbox/tippecanoe#316]
Dear, 
I have a large geojson file. So I need use tippecanoe to load it on map into iOS app(on iPad). How to use it?
Thanks
Nhat

**Comment by ericfischer** [comment]
You can run Tippecanoe on a desktop or server computer to create an `mbtiles` file from your `geojson` file. You can then upload the `mbtiles` file to http://mapbox.com/studio and refer to it from your iOS application from there.
