### ISSUE TITLE
POSIX only commands

### ISSUE THREAD

**Issue by james2432** [mapbox/tippecanoe#317]
This code is compilable outside Linux. You are currently using POSIX only commands for which there are equivalent ANSI methods of doing it.
for example: tile.cpp uses `fdopen` and `mkstemp`
Cygwin cannot compile the code because of the use of these functions.

**Comment by ericfischer** [comment]
I'm basically targeting the two current mainstream Unix implementations, Linux and Mac OS X.

Are `mkstemp` and `fdopen` the only pain points for you? I could probably switch to a different way of creating temporary files and to using more memory-mapped I/O and less stdio streaming if that alone would be sufficient to make it more portable, but Tippecanoe already makes extensive use of memory-mapped I/O so it will not be possible to restrict it to pure ANSI C.

**Comment by james2432** [comment]
I mean I can change `CXXFLAGS := $(CXXFLAGS) -std=c++11` to `CXXFLAGS := $(CXXFLAGS) -std=gnu++11` but then I get undefined references to _realloc _free and other things in geojson.cpp (jsonpull) which is probably a linking issue....

**Comment by jingsam** [comment]
Try `CXXFLAGS := $(CXXFLAGS) -std=c++11 -U__STRICT_ANSI__`

**Comment by ericfischer** [comment]
Closing since it will not be realistic to avoid using `fdopen`. I hope the suggestion above will solve the linkage problem.
