### ISSUE TITLE
Question about the use case of tippecanoe 

### ISSUE THREAD

**Issue by jingsam** [mapbox/tippecanoe#318]
I know `tilelive-bridge` can also generate vector tiles from GeoJSON files. But tippecanoe have more configuration parameters. So my question are:
1. What is the difference between `tilelive-bridge` and `tippecanoe`?
2. Does `tippecanoe` is in production usage in Mapbox internal? More specific, when I upload a geojson file on mapbox studio, does the backend uses `tippecanoe` to generate tilesets?

**Comment by aaronlidman** [comment]
1. tilelive-bridge is a library meant for including in a larger project that you would write for generating vector tiles. It is dependent on [Mapnik](https://github.com/mapnik/mapnik) for datasource that you would configure through code. Tippecanoe on the other hand is a command line tool, meant for running with GeoJSON files as a datasource that you can run in your terminal.

2. Yes, in production. No, not part of the Mapbox Studio upload process.

**Comment by jingsam** [comment]
tks
