### ISSUE TITLE
External filters/plugins

### ISSUE THREAD

**Issue by ericfischer** [mapbox/tippecanoe#329]
I am thinking that Tippecanoe ought to have a `--filter` flag that optionally runs a shell command (or node function?) on the features of each tile as it is being processed, so that things like binning can be implemented as plugins rather than having to be implemented internally.

It should probably pipe out a GeoJSON FeatureCollection and read back in an altered FeatureCollection, and invoke the command with zoom, x, and y arguments, much like tile-reduce does.

The parsing and projection overhead of GeoJSON might be expensive, but is probably more practical than writing filters that accept vector tile PBF as the input/output format.

**Comment by ericfischer** [comment]
* The filter probably needs to run on layers, not tiles. Should it be able to create new layers?
* Should the filter be informed (and how?) if it is being re-run after a tile turned to be too big?
* Should there be another run of polygon cleaning after filtering?
* If the filter introduces new feature attributes, they need to propagate up into the metadata table

**Comment by ericfischer** [comment]
* Are the coordinates within each feature still at full resolution at the time of filtering, or already reduced to tile units?

**Comment by bkowshik** [comment]
❤️ this idea @ericfischer

**Comment by ryanbaumann** [comment]
@ericfischer huge 👍

**Comment by ericfischer** [comment]
I think I figured out what is causing the occasional hangs: when two threads are starting filters at the same time, one may `fork` while the file descriptor to write to another filter's pipe is open, so that second filter doesn't get an end-of-file until the first filter exits. If they both have a file descriptor from the other, there is a deadlock. The cure should be to close any unneeded file descriptors before forking, and perhaps to add a lock so only one thread at a time can be setting up a filter.

**Comment by ericfischer** [comment]
(Working on this in https://github.com/mapbox/tippecanoe/pull/332 by the way)

**Comment by ericfischer** [comment]
Current big blocker: something goes wrong with certain multipolygons in certain tiles in the prefilter, even with a filter as simple as `cat`. (Postfilter seems fine.) For example, Argentina and Angola in `ne_10m_admin_0_countries.json`

**Comment by ericfischer** [comment]
Finally merged!

**Comment by ryanbaumann** [comment]
🎉 @ericdeveloper ❤️
