### ISSUE TITLE
tile-join does not update attribute values

### ISSUE THREAD

**Issue by x9xjdzz9** [mapbox/tippecanoe#335]
If I try to use tile-join to update an existing attribute, the attribute values do not change.

tile-join -c csv-filename -o new-filename old-filename

**Comment by ericfischer** [comment]
Good point. It is including both versions of the attribute, with the same name, rather than replacing the existing value. I'll fix it.

**Comment by ericfischer** [comment]
This will be fixed in https://github.com/mapbox/tippecanoe/pull/336
