### ISSUE TITLE
Build failure on Ubuntu 14.04

### ISSUE THREAD

**Issue by timiyay** [mapbox/tippecanoe#348]
I'm running a `tippecanoe`-based  vector tile pipeline on Ubuntu Server 14.04 LTS.

I'm trying to upgrade from `tippecanoe` 1.12 to 1.16.3, and I'm unable to build successfully.

```bash
$ make

g++ -MMD  -I/usr/local/include -I. -g -Wall -Wshadow -Wsign-compare -O3 -DNDEBUG  -std=c++14 -c -o geojson.o geojson.cpp
g++: error: unrecognized command line option ‘-std=c++14’
make: *** [geojson.o] Error 1
```

It seems that Ubuntu 14.04's g++ compiler (v4.8.4) is outdated. My immediate reaction is [let's update g++ and set it as default in Ubuntu](http://askubuntu.com/questions/26498/choose-gcc-and-g-version), but this is a reasonably low-level change to the default OS.

Before adding this to my provisioning scripts, I wanted to raise the issue here, and ask:

Is this breaking change is unavoidable? Is it possible to maintain support for both older and newer compilers?

For example, my internet research for the issue revealed one SO poster claiming that `-std=c++1y` was a backwards-compatible synonym for `-std=c++14`.

**Comment by timiyay** [comment]
In the meantime, I'm going to upgrade to 1.15.4 instead. This appears to be the last version before the `c++14` update.

There's a few missing Github release versions in the 1.15.x series, so I'm downloading based on the SHA rather than version number.

**Comment by springmeyer** [comment]
Upgrading your compiler is safe, normal, and recommended. g++ 4.8.4 is very old at this point. Here is how you can easily get g++-5 which supports c++14:

```
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt-get update -y
sudo apt-get install -y g++-5
```

**Comment by timiyay** [comment]
@springmeyer Thanks for clarifying.

My knowledge of compilers is shallow, so the reassurance is appreciated.

**Comment by springmeyer** [comment]
@timiyay sounds good. Also, I updated the above instructions with an environment setting needed for tippecanoe to pick up the new compiler.

**Comment by ericfischer** [comment]
@timiyay I wish I did have a way to make it work with older compilers, but using Wagyu for repairing polygon geometry works much better than the old Clipper code, and Wagyu requires C++-14 features.

**Comment by crawforc3** [comment]
@springmeyer  This worked for me from a fresh install of Ubuntu 14.04.1
```
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt-get update -y
sudo apt-get install -y g++-5
export CXX=g++-5
```

**Comment by ericfischer** [comment]
Thanks @crawforc3. I'll add those instructions to the README.

**Comment by ericfischer** [comment]
https://github.com/mapbox/tippecanoe/pull/358 should reduce the required compiler standard from 2014 to 2011.
