### ISSUE TITLE
tippecanoe source code

### ISSUE THREAD

**Issue by lihuadong1988** [mapbox/tippecanoe#349]
Tippecanoe source code is too difficult to understand, it will be great to give some code comments or documentation!

**Comment by ericfischer** [comment]
I started writing [a tour of the source code](https://gist.github.com/ericfischer/cef5ddf23b24cd3095e73fd5a7c09a65) a few months ago. It still needs some more work but I hope it will clarify what is going on somewhat.

**Comment by lihuadong1988** [comment]
Thank you for your answer,I will read it carefully!
