### ISSUE TITLE
Binning tool

### ISSUE THREAD

**Issue by ericfischer** [mapbox/tippecanoe#354]
There have been a lot of projects that want to count how many points are in each, say, z20 tile, and then make vector tiles to visualize the result. It doesn't work very well because the low zooms then end up with too many polygons in them.

I think there needs to be a specialized tool for making binned counts, that produces vector tiles with each zoom level having a bin size appropriate to that zoom, probably 1/8 of a tile. So, for instance, the bins at z10 will be z18 tiles, the bins at z7 will be z15 tiles, and so on. It might be possible to fit a 9x9 grid in each tile instead of 8x8, and you could certainly go coarser if you wanted.

It's basically exactly the same thing as [datamaps](https://github.com/ericfischer/datamaps) used to do, but creating vector tiles for the summed output instead of bitmaps.

**Comment by ryanbaumann** [comment]
@ericfischer This would be quite useful.  Key functions to make this useful are:

1. Property aggregation when adding features to a bin.
2. Specific bin size control (quadkey 21 -> zoom level 13 tiles, quadkey 20 bins -> zoom level 12 tiles ... etc)

Do you see this as being distinct from the https://github.com/mapbox/tippecanoe/issues/324 custom turf function plugin functionality with Tippecanoe?

**Comment by ericfischer** [comment]
I'm still trying to figure that out. I had been thinking that binning should happen as a plugin, but my early attempts to do that have been really slow at the low zoom levels. I haven't figured out yet whether the slowness is due to JSON encoding/decoding, polygon operations, or from working in Node instead of in C. But you're right: I should try doing an optimized plugin before putting more effort into an entirely separate program.

**Comment by ericfischer** [comment]
This turned into https://github.com/mapbox/tile-count/

**Comment by ericfischer** [comment]
Sum, mean, max, and min are now available in https://github.com/mapbox/tippecanoe/releases/tag/1.27.8
