### ISSUE TITLE
Decode Warning using tile 0/0/0

### ISSUE THREAD

**Issue by loconox** [mapbox/tippecanoe#356]
Hi,

I'm using tippecanoe on a large geojson file of points (54K). To process of generating the mbfiles seems going well : 
```
For layer 0, using name "geoJSONall"
54484 features, 1743131 bytes of geometry, 4 bytes of separate metadata, 866282 bytes of string pool
  99.9%  14/8005/5657
```
But when I want to generate a json for each one layers, I got this weird warning **Warning: using tile 0/0/0 instead of 9/250/335** : 
```
$ tippecanoe-decode all.mbtiles 9 250 335
all.mbtiles: Warning: using tile 0/0/0 instead of 9/250/335
{ "type": "FeatureCollection", "features": [
{ "type": "Feature", "properties":
 ... (rest of json)
```
Json output seems wrong and is identical for almost all tiles.
I'm sure that the tile exists because I can list it with tippecanoe-enumerate.
Any idea ?

**Comment by ericfischer** [comment]
That is strange. Tippecanoe-decode shouldn't give that message unless 9/250/335 isn't in the tileset at all, in which case it tries to look up a parent tile that might have the data. That doesn't make any sense if tippecanoe-enumerate says that the tile does exist. If you just do `tippecanoe-decode all.mbtiles` without specifying a tile, is 9/250/335 in the output somewhere?

**Comment by ericfischer** [comment]
Closing for lack of information on how to reproduce.
