### ISSUE TITLE
Using non-numeric feature ID

### ISSUE THREAD

**Issue by showjackyang** [mapbox/tippecanoe#357]
Hi,
I was trying to convert some geojson to mbtiles with zoom-level setups, noticed some of the geojson like [this](https://gist.github.com/showjackyang/9d1da0f79a62b2f8bcdb6fa3b2e4e716 ) have string as their feature ID, which tippecanoe warns: _Warning: Can't represent non-numeric feature ID "xx"_ 

Wondering is there a way for tippecanoe to use string feature ID directly? before trying to manually cast them to numeric types.

Thanks :)

**Comment by ericfischer** [comment]
This is a limitation of the [vector tile format specification](https://github.com/mapbox/vector-tile-spec): the feature ID is defined only as an optional integer. I think a future version of the spec could allow non-numeric IDs, but there is no way to represent them now.

**Comment by atsuidesu** [comment]
Is the vector tile format specification going to change soon to support non-numeric IDs? The last comment was in Jan 2017, over 2 years ago. i.e. tippecanoe will support non-numeric IDs soon? The map GL setFeatureState api seems to imply the feature id can be either number or string at the moment and it is not consistent with the current state of tippecanoe.

**Comment by ericfischer** [comment]
String IDs are supported in the https://github.com/mapbox/tippecanoe/pull/611 development branch for version 3 of the vector tile spec.

**Comment by bilics** [comment]
Hi, 

I am still getting a 

`Warning: Attribute "hex_id"="123123ABCBC" as feature ID is not a number`

when using Tippecanoe.

Has this been fixed? 

Thanks!
