### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by citizenfish** [mapbox/tippecanoe#359]
I may have misunderstood the command line parameters but this works fine

```
 tippecanoe -Z 0 -z 20 -B 7 -l roads /tmp/motorway.geojson /tmp/primary_road.geojson -f -o roads.mbtiles 
```

But this segfaults as soon as it tries to process second file

```
 tippecanoe -Z 0 -z 20 -B 7 -L roads:/tmp/motorway.geojson  -L roads:/tmp/primary_road.geojson -f -o roads.mbtiles 
```

**Comment by ericfischer** [comment]
Thanks for the report @citizenfish! Can you tell me what version of Tippecanoe is crashing (with `tippecanoe -v`)? It would be extremely helpful to have copies of the files that are causing the crash so I can figure out what is going wrong and fix it. The options you are using ought to be fine.

**Comment by citizenfish** [comment]
tippecanoe v1.16.4

The files are attached. 

[tip.tar.gz](https://github.com/mapbox/tippecanoe/files/742773/tip.tar.gz)

**Comment by ericfischer** [comment]
Thank you! I'll download them now and take a look.

**Comment by citizenfish** [comment]
Thanks let me know when downloaded as they contain open data and should really have an attribution. 

Just to be safe ;-)

Contains OS data © Crown copyright and database right 2017

**Comment by ericfischer** [comment]
I've got it downloaded now. It crashed for me too the first time:

```
$ tippecanoe -Z 0 -z 20 -B 7 -L roads:/tmp/motorway.geojson  -L roads:/tmp/primary_road.geojson -f -o roads.mbtiles
For layer 0, using name "roads"
For layer 1, using name "roads"
24842 features, 1208228 bytes of geometry, 4336 bytes of separate metadata, 30 bytes of string pool
tippecanoe(18919,0x700000187000) malloc: *** mach_vm_map(size=140549085474816) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
tippecanoe(18919,0x700000081000) malloc: *** mach_vm_map(size=140549085474816) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
Abort trap: 6
```

but then worked correctly the second time. Trying to figure out what could be going wrong.

**Comment by citizenfish** [comment]
I am seeing similar behaviour

This works:-

```
tippecanoe -Z 0 -z 20 -B 7 -L roads:/tmp/os_opendata/motorway.geojson -L roads:/tmp/os_opendata/primary_road.geojson -f -o /opt/nautoguide/gisraw/test_dir/test.mbtiles
```

This doesn't

```
 tippecanoe -Z 0 -z 20 -B 7 -L roads:/tmp/os_opendata/motorway.geojson -L roads:/tmp/os_opendata/primary_road.geojson -f -o /opt/nautoguide/gisraw/vector_tiles/os_opendate.mbtiles
```

For some reason it does not like the vector_tiles directory?

**Comment by ericfischer** [comment]
I can crash it reliably with

    MallocScribble=1 tippecanoe -Z 0 -z 20 -B 7 -L roads:/tmp/motorway.geojson  -L roads:/tmp/primary_road.geojson -f -o roads.mbtiles

so there must be an uninitialized variable somewhere.

**Comment by citizenfish** [comment]
More oddness this works:-

```
 -o /opt/nautoguide/gisraw/vector_tiles/123_5.test
```

This doesn't

```
 -o /opt/nautoguide/gisraw/vector_tiles/1232_5.test
````

Seems linked to the  output file name does that help track down the variable?

**Comment by ericfischer** [comment]
I believe https://github.com/mapbox/tippecanoe/pull/374 will fix this crash. When you get a chance, could you see if it also works for you?

**Comment by citizenfish** [comment]
Yes works fine now. Thanks!

**Comment by ericfischer** [comment]
Thanks for reporting and verifying!
