### ISSUE TITLE
Append to layer

### ISSUE THREAD

**Issue by citizenfish** [mapbox/tippecanoe#360]
I am sending a command line as follows:-

    -L roads:roads.geojson
    -L roads:roads_2.geojson
    -L roads:roads_3.geojson

When I view the tiles in Openlayers. I notice that:-

    feature.get("layer") 

Displays "roads" for the first layer and  "" for the subsequent ones. 

Is this by design? I may have misinterpreted  the  -L option. Basically I have split files as the roads relate to different zoom levels

**Comment by ericfischer** [comment]
This ought to work (to put everything into the same layer) but I must have another bug related to the `-L` option. I hope I'll have some time to look at this and https://github.com/mapbox/tippecanoe/issues/359 today.

**Comment by ericfischer** [comment]
When you get a chance, could you see if https://github.com/mapbox/tippecanoe/pull/374 fixes this for you? Tippecanoe should only emit a single layer for the three source files together.

**Comment by citizenfish** [comment]
Yep
