### ISSUE TITLE
How can I produce global maps including roads at very low zoom

### ISSUE THREAD

**Issue by rjbaker** [mapbox/tippecanoe#361]
Hi there,

I'd like to produce an mbtile file containing road & street paths, country and water boundaries in a similar style to "All Streets" (http://benfry.com/allstreets/map5.html). Basically, show an approximation of the path density at higher zoom levels, which I may then use with mapbox.

How would I go about this using tippecanoe and osm data? Which data source should I start with, and how do I discard unnecessary layers?

Many thanks.

**Comment by ericfischer** [comment]
"All Streets" uses TIGER. To duplicate it, download the [TIGER roads layer](https://www2.census.gov/geo/tiger/TIGER2016/ROADS/), converting the shapefiles to GeoJSON using `ogr2ogr`, and then using `tippecanoe -y FULLNAME --drop-densest-as-needed` to drop most of the attributes, keeping only street names, and dropping some dense features if needed to make the tiles small enough at low zooms.

If you want to do it with OSM, download a copy of [planet.osm](http://wiki.openstreetmap.org/wiki/Planet.osm) and use [minjur](https://github.com/mapbox/minjur) to convert it to GeoJSON. I'm not sure what the best way is to filter out everything but roads, but you could probably just use <code>grep '"highway" *:'</code> to exclude everything that doesn't have a `highway` tag.

**Comment by rjbaker** [comment]
Thanks for the pointers @ericfischer I'll give it a go. 👍

**Comment by ericfischer** [comment]
Closing since I don't think there is anything else to do here.
