### ISSUE TITLE
vertical and horizontal lines shown inside polygons

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/tippecanoe#366]
I've noticed this with many different sources, this file http://www.alantgeo.com.au/share/LGA_2015_AUST_SYD.geojson shows the problem.

I run `tippecanoe -o LGA_2015_AUST_SYD.mbtiles -z 10 LGA_2015_AUST_SYD.geojson`.

Then view in mbview. It has many straight lines appearing where there shouldn't be. Changing the buffer doesn't help.

![selection_454](https://cloud.githubusercontent.com/assets/117278/23052608/c0d0c7ca-f526-11e6-8f0e-fe6480c94950.png)

I'm not sure if this is a GL JS rendering issue or tippecanoe issue.

Using `--no-polygon-splitting` does fix the issue as a workaround.

**Comment by ericfischer** [comment]
`--no-polygon-splitting` is exactly the right option to remove these lines. I should probably just remove the polygon splitting now that Wagyu's polygon cleaning performance is good enough on complex polygons. The polygon splitting was a workaround for old code that got extremely slow on polygons with more than about 700 sides.

**Comment by andrewharvey** [comment]
> --no-polygon-splitting is exactly the right option to remove these lines. I should probably just remove the polygon splitting now that Wagyu's polygon cleaning performance is good enough on complex polygons. The polygon splitting was a workaround for old code that got extremely slow on polygons with more than about 700 sides.

Or make it the default...

Thanks the guidance!
