### ISSUE TITLE
code coverage reporting

### ISSUE THREAD

**Issue by springmeyer** [mapbox/tippecanoe#367]
Coverage reporting is broken - it looks like it is no longer posting to coveralls.io. Not planning on debugging why, let's instead move to codecov.io instead. This service works with latest llvm 3.9.x. The method is generally:

  - install llvm-cov 3.9.1 from mason
  - use the `codecov` bash script to post reports

Example at https://github.com/mapbox/node-cpp-skel/blob/6e8575a35885e5206262517398c274f1323706d4/.travis.yml#L63-L73

**Comment by ericfischer** [comment]
https://github.com/mapbox/tippecanoe/pull/542
