### ISSUE TITLE
Add a flag to inhibit sorting

### ISSUE THREAD

**Issue by ericfischer** [mapbox/tippecanoe#37]
Or a final re-sorting pass back to the original sequence, so that the output tiles can have the features in the same order they were in the input.

For @dnomadb

**Comment by dnomadb** [comment]
Awesome, thx @ericfischer !

**Comment by danpat** [comment]
:+1: for this feature.  I've got a use case where I'm using color to indicate the age of a feature.  Using the Painters Algorithm, Mapnik renders this when I can control the feature order (i.e. using a PostGIS datasource):

![screen shot 2015-09-13 at 22 46 14](https://cloud.githubusercontent.com/assets/1892250/9842903/6fd3858c-5a69-11e5-9ca7-7e29d14bc34d.png)

However, if I try to generate vector tiles using `tippecanoe`, the features get re-ordered, leading to this:

![screen shot 2015-09-13 at 22 50 47](https://cloud.githubusercontent.com/assets/1892250/9842939/ebd0d0ae-5a69-11e5-8f56-e676cb787296.png)

It would be great to be able to maintain ordering to support this.

**Comment by ericfischer** [comment]
OK @danpat, I'll get this feature added to the mainline build very soon then.

**Comment by ericfischer** [comment]
OK, this should be available as `-pi` after https://github.com/mapbox/tippecanoe/commit/4dd28f7aae212f1b2
