### ISSUE TITLE
-L <dirname> ? (or alternatively help with piping)

### ISSUE THREAD

**Issue by jliebrand** [mapbox/tippecanoe#372]
Hey there,

I've been using the  -L name:<(cat dir/*.json)  notation and it works fine. However, I've just finished a new data pipeline where I have layers of arbitrary names. eg:

/some/dir/one/foo.json
/some/dir/one/bar.json
/some/dir/two/baz.json

Where I do not know the sub dir names nor the number of them up front (eg one and two in my example), and each can/will have an arbitrary number of json files.

Ideally I would just do something like:

ls /some/dir | xargs tippecanoe foo.mbtiles 

and it would be smart enough to use the subdir names as layer names...

My bash piping skills are rusty to say the least, and trying something like this obviously wont work:
ls /some/dir/ | sed 's/\(.*\)/-L\1:<(cat \/some\/dir\/\1\/*)/' | xargs tippecanoe foo.mbtiles

Because it wont actually do the piping of the cat command.

I guess I need to first pipe the ls /some/dir somewhere, then turn each of those in to a pipe to cat, and then somehow (?) pipe the result of each of those as a -L argument to tippecanoe?

Could tippecanoe be made smart enough to read dir names as a pipe?

**Comment by jliebrand** [comment]
Ok, getting a little closer, but named pipes in bash do my head in... Something like this *almost* gets me there:

tippecanoe="tippecanoe -o foo.mbtiles"
for i in ${PWD}/dist/generated/geojson/* ; do
  if [ -d "$i" ]; then
    directory=$i
    name=${directory##*/}
    content=<(cat $directory/*)
    tippecanoe="$tippecanoe -L$name:$content"
  fi
done
echo $tippecanoe
`$tippecanoe`

except that each layer is linked to /dev/fd/63 (rather than different ones per layer), and ultimately that then fails with Bad file descriptor

**Comment by ericfischer** [comment]
Hmm. It's ugly, but the best thing I can come up with is

```
tippecanoe -f -o foo.mbtiles $(find . -name '*.json' -print | perl -e 'while (<>) { chomp; $l = $_; $l =~ s/.*\///; $l =~ s/\.json$//; print "-L$l:$_\n"; }')
```

**Comment by ericfischer** [comment]
Oh, you wanted the directory name, not the filename, to be the layer name. So something like this instead:

```
tippecanoe -f -o foo.mbtiles $(find . -name '*.json' -print | perl -e 'while (<>) { chomp; $l = $_; $l =~ s/\/[^\/]*$//; $l =~ s/.*\///; print "-L$l:$_\n"; }')
```

which also points out that I should make `-L` check for and not allow empty layer names.

**Comment by ericfischer** [comment]
Or actually I guess you are looking for

```
(echo -n 'tippecanoe -f -o foo.mbtiles'; find . -name '*.json' -print | sed 's/\/[^\/]*$//' | uniq | while read d; do echo -n " -L$(basename $d):<(cat $d/*.json)"; done)  | bash
```

so that each -L is getting a concatenated pipe of JSON rather than having each JSON file spelled out as a separate argument.

**Comment by jliebrand** [comment]
BINGO... I was just going to reply to your first comment, and then noticed your follow ups. That last one works a charm!

Obviously it would be nice if tippecanoe could just be passed some directory names, but this unblocks me for now; thanks!

**Comment by ericfischer** [comment]
Closing since I don't think there's anything left to do on this.
