### ISSUE TITLE
any plans to support docker (and release an up to date image)?

### ISSUE THREAD

**Issue by jliebrand** [mapbox/tippecanoe#373]
Just curiousity, but it would be nice if I didn't have to build tippecanoe on my build machines every time I want to run it.

Any chance of releasing an up to date docker image? I see some others have released some, but they are a little out of date:

https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=tippecanoe&starCount=0

**Comment by ericfischer** [comment]
I hadn't thought about this, but it might be worth doing if it is something that a lot of people use.

**Comment by ericfischer** [comment]
Fixed in https://github.com/mapbox/tippecanoe/pull/483

**Comment by ericfischer** [comment]
We don't currently have plans to maintain an official image, but please use our Dockerfile to build your own.
