### ISSUE TITLE
Consistent release notes

### ISSUE THREAD

**Issue by springmeyer** [mapbox/tippecanoe#377]
I noticed that:

 - some releases have release notes at https://github.com/mapbox/tippecanoe/releases, but not all.
 - the changelog release notes don't match the ones on the github release: https://github.com/mapbox/tippecanoe/blob/master/CHANGELOG.md

@ericfischer - Do you have ideas on keeping these in sync? Or maybe only use the changelog and link to it in the Release page?

**Comment by ericfischer** [comment]
The only one that doesn't have any notes is the one that @yhahn tagged when I didn't read my messages soon enough.

It is kind of too late to fix old release tags, but I can make sure to make them an exact clone of the changelog in the future, or with links into it, if you think that would be better.

**Comment by ericfischer** [comment]
I'm just copying and pasting from the CHANGELOG.md for release notes now.
