### ISSUE TITLE
Tippecanoe appears to go to max zoom level even if Tippeacanoe max zoom is defined in GeoJSON feature

### ISSUE THREAD

**Issue by JamesMilnerUK** [mapbox/tippecanoe#379]
Tippecanoe appears to keep processing to the default (14) zoom level even if a tippecanoe object with the max zoom property set  ("maxzoom") has been defined on the GeoJSON feature. The actual tiles don't seem to get created (in the output tiles) but the operation still goes on unnecessarily passed the specified zoom level.

For example with one file at max zoom 4, the operation goes on to 14 regardless:

![screen shot 2017-03-08 at 11 35 07](https://cloud.githubusercontent.com/assets/8822075/23702522/8be42616-03f3-11e7-8042-4987d33695e9.png)

Is there a way that Tippecanoe can look at the maximum zoom level provided in the GeoJSON files and avoid running to the default max zoom level?

**Comment by JamesMilnerUK** [comment]
One work around is to take the known maximum zoom and the known minimum zoom levels and plug them into --maximum-zoom and --minimum-zoom respectively, which skips them entirely.

**Comment by ericfischer** [comment]
Thanks for pointing this out. I haven't made many tilesets where all the features have explicit zoom ranges so I never noticed this.

**Comment by ericfischer** [comment]
Should be fixed in https://github.com/mapbox/tippecanoe/pull/380

**Comment by JamesMilnerUK** [comment]
@ericfischer thanks for your response and work to get that fixed. Greatly appreciated! 

Happy to test when that gets merged.

**Comment by ericfischer** [comment]
OK, it's merged.
