### ISSUE TITLE
Add an option for encoding the description.

### ISSUE THREAD

**Issue by reyemtm** [mapbox/tippecanoe#384]
Currently the file name is used as the description in the mbtile metadata if the geojson has no description. Would it be possible to add an option to encode the description, similar to how you can now add attribution to the metadata?

**Comment by ericfischer** [comment]
Oh sure, this should be pretty easy to add. Thanks for pointing out the omission.

**Comment by ericfischer** [comment]
This will be in https://github.com/mapbox/tippecanoe/pull/382

**Comment by ericfischer** [comment]
Merged.
