### ISSUE TITLE
Found Mispelling of Null on Large geo Json files

### ISSUE THREAD

**Issue by nodefiend** [mapbox/tippecanoe#388]
Greetings! 

Have been trying to spin up my own tile server , using TileserverGL, tippecanoe and leaflet

Downloaded a Planet.mbtiles (43g)

from 

https://openmaptiles.org/downloads/

I am using Tippecanoe to Decode the MBtiles file then, i seperate the mbtiles by layers by running `tippecanoe-decode` on the giant mbtiles 3 seperate times for each layer i want 

```ruby
tippecanoe-decode -l transportation_name ./world-decoded-transportation-name.mbtiles > ./world-decoded-transportation-name.geojson 2>&1

tippecanoe-decode -l water ./world-decoded-water-name.mbtiles > ./world-decoded-water-name.geojson 2>&1

tippecanoe-decode -l transportation ./world-decoded-transportation-name.mbtiles > ./world-decoded-transportation.geojson 2>&1
```

After i have 3 geojson files with each seperate layer , i recompile them together into mbtiles file by using tippecanoe

I am doing this to take advantage of Tippecanoes ability to provide "a scale-independent view " of the data , which is basically a view of "all streets" at lower zoom levels.

I know that this works because I have tried this on the smaller city websites that they provide available for download 

But, my problem is that when i try to recreate this same process with the GIANT planet mbtiles , I get an error and it kills the tippecanoe process, I dont see any documentation , and there is no verbosity flag, so i'm not sure why im getting this error, any suggestion or insight would be amazing .

My suspicions are that something is happening when i run tippecanoe-decode on the giant world mbtiles file, that isnt happening when i decode the smaller city files.

If you could point in any direction it would be much appreciated!

tippecanoe/jsonpull/jsonpull.c
Line : 376

<img width="615" alt="screen shot 2017-04-06 at 9 32 53 am" src="https://cloud.githubusercontent.com/assets/10778319/24765548/0ea65a7c-1aad-11e7-97d2-590fb7ed6d38.png">

```
/////////////////////////// Null

	if (c == 'n') {
		if (read_wrap(j) != 'u' || read_wrap(j) != 'l' || read_wrap(j) != 'l') {
			j->error = "Found misspelling of null";
			return NULL;
		}

		return add_object(j, JSON_NULL);
	}

```

**Comment by ericfischer** [comment]
The "misspelling of null" error happens when the JSON parser finds a token that starts with the letter `n` but isn't followed by the rest of the word.

The error message in your screenshot claims it is finding the error on the very first line of world-water.geojson. Can you provide a snippet of the file so I can see how it starts?

**Comment by nodefiend** [comment]
@ericfischer 

Thank you for the hasty response! I apoligize for my late replying but i greatly appreciate you taking time to help out the community with trouble shooting!

I also am a big fan of this project and have alot of respect for what you and your team are doing!!!

hmmm interesting ... 

```

nohup: ignoring input
{ "type": "FeatureCollection", "properties": {
"attribution": "<a href=\"http://openmaptiles.org/\" target=\"_blank\">&copy; OpenMapTiles</a> <a href=\"http://www.openstreetmap.org/about/\" target=\"_blank\">&copy; OpenStreetMap contributors</a>",
"bounds": "-180,-85.0511,180,85.0511",
"center": "-12.2168,28.6135,4",
"description": "http://openmaptiles.org",
"format": "pbf",
"id": "openmaptiles",
"json": "{ \"vector_layers\": [ { \"id\": \"water\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"class\": \"String\" } }, { \"id\": \"waterway\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"name\": \"String\", \"class\": \"String\" } }, { \"id\": \"landcover\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"class\": \"String\", \"subclass\": \"String\" } }, { \"id\": \"landuse\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"class\": \"String\" } }, { \"id\": \"park\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"class\": \"String\" } }, { \"id\": \"boundary\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"admin_level\": \"Number\" } }, { \"id\": \"aeroway\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"class\": \"String\" } }, { \"id\": \"transportation\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"class\": \"String\", \"oneway\": \"Number\", \"ramp\": \"Number\", \"brunnel\": \"String\", \"service\": \"String\" } }, { \"id\": \"building\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"render_height\": \"Number\", \"render_min_height\": \"Number\" } }, { \"id\": \"water_name\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"name\": \"String\", \"name_en\": \"String\", \"class\": \"String\" } }, { \"id\": \"transportation_name\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"name\": \"String\", \"ref\": \"String\", \"ref_length\": \"Number\", \"class\": \"String\" } }, { \"id\": \"place\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"name\": \"String\", \"name_en\": \"String\", \"class\": \"String\", \"rank\": \"Number\", \"capital\": \"Number\" } }, { \"id\": \"housenumber\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"housenumber\": \"String\" } }, { \"id\": \"poi\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": { \"name\": \"String\", \"name_en\": \"String\", \"class\": \"String\", \"subclass\": \"String\", \"rank\": \"Number\" } } ] }",
"maskLevel": "8",
"maxzoom": "14",
"minzoom": "0",
"name": "OpenMapTiles",
"version": "3.3"
}, "features": [
```

I was using the unbuntu `nuhup` command to persist my ssh connection to the ec2 Instance so i could run the tippecanoe command on auto pilot, it looks like a remnant of nohup got caught in the decompiled geojson, is it possible that tippecanoe is faling on this ?

I'm going to see if i can remove this first line with out opening this 70gig file >.<

**Comment by ericfischer** [comment]
Oh yes, it must be the `nohup` line. You could use `tail -n +2 original.geojson > new.geojson` to remove the first line of the file.

**Comment by nodefiend** [comment]
@ericfischer 
thanks so much for that tail command! works like a charm.. ran into another issue though..

I'm simply trying to get an "all streets" type map with extracting only the layers at all zoom levels

-l water
-l transportation-name
-l transportation

and then merging them all back together into a mbtiles file

i realize that an all streets map at all zoom levels will take a while to compile, but i have a large ec2

the command im using is :


```tippecanoe -o testall.mbtiles -z4 -ps -pf -pk -X -Bg ./water.geojson ./transportation-name.geojson ./transportation.geojson```

im running only -z4 to run a test to see if i can get  a map rendered , but it keeps killing my process .

<img width="626" alt="screen shot 2017-04-10 at 12 07 15 pm" src="https://cloud.githubusercontent.com/assets/10778319/24878031/4c8ffc94-1de6-11e7-9bb4-30cb83726f20.png">

i was able to get it working on a smaller city version of the data, but at large sized files its just killing my process .

ive run into a wall ! any help , or direction would be greatly appreciated , this is week 4 hehehe , im having alot of fun digging into tippecanoe , and really amazed by how powerful it is, but unfortunatly getting hung up at larger scale data..

**Comment by ericfischer** [comment]
The abrupt "Killed" message sounds like your computer is probably running out of memory. Unless you can use a larger machine or enable more swap space, the only suggestion I can give is to run `tippecanoe` separately on each layer and then use `tile-join` to combine the partial `mbtiles` files into one composite `mbtiles` file at the end.

**Comment by ericfischer** [comment]
(You might also want to make sure you don't have a lot of duplicate features. If your source GeoJSON is coming from `tippecanoe-decode`, it probably has a copy of each feature from each zoom level in the original tileset. You might want to use the `-Z` option to `tippecanoe-decode` to make sure you are only decoding a single zoom level.)

**Comment by nodefiend** [comment]
Omg ! that is great advice ! thank you so much! 

my plan of attack is to take the giant planet.mbtiles file, decompile out each layer i need for each zoom that i need :

```tippecanoe-decode -l water ./planet.mbtiles > ./zoom-1-worldwater.geojson ```

then once i have this file im going to run tippecanoe to turn it back into an mbtile :

```tippecanoe -o zoom1_world_water.mbtiles -z1 -Z1 -ps -pf -pk -X -Bg ./zoom-1-worldwater.geojson```

And then just repeat this process for all 3 layers at all the zooms i need .

then once i have all the mbtiles files , i will rejoin them with :

```tile-join zoom1_world_water zoom2_world_water zoom3_world_water etc..```

from what im reading it looks like i wont have to pass any options into tile-join, it will just string all the mbtiles files together into one giant MBtiles file?

**Comment by ericfischer** [comment]
Right, the only option you will need to give tile-join is the `-o output.mbtiles` to name the output file.

**Comment by ericfischer** [comment]
Honestly it sounds like what you really want, rather than using `tippecanoe-decode` and `tippecanoe` at all, is just an option to `tile-join` to specify which layers you want to include when you copy a tileset, leaving out the others.

I just added that in https://github.com/mapbox/tippecanoe/pull/390, if that really is what you want.

**Comment by nodefiend** [comment]
Nice ! that functionality will save me a ton of time. (i think lol)

The reason i used ```tippecanoe-decode``` in the first place was because my original data lives inside of a giant MBtiles file (so i need to turn it into geojson). Also,  Im breaking it apart because i only need 3 layers , and the rest i dont need.

The reason why I wanted to use ```tippecanoe``` on this giant MBtiles file was because i wanted to take advantage of scale-independent view of my data to get the desired ["all streets"](http://benfry.com/allstreets/map5.html) when i am zoomed out.

So i think what you are saying ... (sorry a noob at this ) 

1. extract each layer,  (and zoom level) from world.mbtiles
2. feed each layer into tippecanoe with the options to not simplify lines , and not limit tile size
3. use tile join to reconnect all mbtiles together 

(the reason i am using tilejoin is to join the different zooms together because my computer is not good enough to proccess the entire file )

... i think this means that this new feature of ```tile-join``` **i wont actually** need because my mbtiles file that  i will be feeding it will only have 3 layers inside of them anyways ?

p.s. im really excited to write a blog post tutorial on everything ive learned so far here, thanks so much for your help!!!!

**Comment by ericfischer** [comment]
The thing that I don't think is going to work in your methodology is that if you are extracting the source mbtiles one zoom level at a time and then having tippecanoe build the output one zoom level at a time, it is only going to include features at low zooms if they were already present in the same zooms in the source mbtiles. So I don't think you are gaining anything by the round trip through GeoJSON and back into mbtiles that you didn't already have to start with.

If what you want is for features that are only visible at high zooms in the original mbtiles to become visible at *all* zooms in the output, I think you need to extract *just one* zoom from the original:

    tippecanoe-decode -z14 -Z14 planet.mbtiles > planet-z14.geojson

and then retile *all* zoom levels based on what was in that one zoom:

    tippecanoe -o retiled.mbtiles --drop-densest-as-needed planet-z14.geojson

**Comment by nodefiend** [comment]
O wow! 

yah that makes sense , i think my understanding of what tippecanoe had a **giant** gap in it lol . (not the first time)

Thank you so much for taking the time to translate and figure this out with me! **(definitly the first time an author has helped me this much)**

**Comment by nodefiend** [comment]
@ericfischer 

Just got it working on my local, going to start same process on the server.. 

THANK YoU SooOOOo much eric ! you have been an amazing help!! i  will let you know how it goes :)

<img width="905" alt="screen shot 2017-04-10 at 5 02 24 pm" src="https://cloud.githubusercontent.com/assets/10778319/24887306/9d59fb42-1e0f-11e7-80c3-d4a2b77e0677.png">
