### ISSUE TITLE
Output 4096 tiles always 

### ISSUE THREAD

**Issue by tmcw** [mapbox/tippecanoe#39]
Tiles made with tippecanoe are apparently incompatible with Mapbox GL, which expects a 4096 extent always, rather than the 1024 / variable extent of tippecanoe.

**Comment by ericfischer** [comment]
I really think this a GL bug, since it is ignoring a documented aspect of the vector tile spec. I can add an option to force an extent of 4096, but it will severely impair the ability to make small tiles at low zoom levels.

**Comment by tmcw** [comment]
@ericfischer yes - this is a stopgap until we can get https://github.com/mapbox/mapbox-gl-js/issues/1093 fixed on the gl-js

**Comment by ericfischer** [comment]
Added -m option in bc2f243f0b0da66571
