### ISSUE TITLE
Tippecanoe not using beyond 20 CPUs

### ISSUE THREAD

**Issue by Burke9077** [mapbox/tippecanoe#392]
Hello,

I appear to be having an issue using tippecanoe on a machine with more than 20 CPUs. Several files I have to process regularly are very detailed maps of the entire united states with a lot of features and metadata. I regularly need to process these files to zoom layers of 19+ so getting as much performance as the machine can give is important for time and cost.

I've found that when using a machine with more than 20+ CPUs, only the first 20 are used. Also the CPUs that are in use are underutilized,usually hovering around the 20% usage mark. Example top command output with CPU detail on:

	top - 17:26:17 up 26 min,  3 users,  load average: 2.85, 2.88, 2.06
	Tasks: 336 total,   1 running, 335 sleeping,   0 stopped,   0 zombie
	%Cpu0  : 16.6 us,  1.0 sy,  0.0 ni, 82.4 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
	%Cpu1  : 15.5 us,  0.7 sy,  0.0 ni, 83.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
	%Cpu2  : 16.0 us,  0.7 sy,  0.0 ni, 83.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
	%Cpu3  : 15.7 us,  1.0 sy,  0.0 ni, 83.3 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
	%Cpu4  : 15.6 us,  1.0 sy,  0.0 ni, 83.4 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
	%Cpu5  : 16.9 us,  0.7 sy,  0.0 ni, 82.4 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
	%Cpu6  : 16.4 us,  0.7 sy,  0.0 ni, 82.9 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
	%Cpu7  : 16.7 us,  0.7 sy,  0.0 ni, 82.6 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
	%Cpu8  : 15.2 us,  0.7 sy,  0.0 ni, 84.1 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
	%Cpu9  : 16.3 us,  0.7 sy,  0.0 ni, 83.1 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
	%Cpu10 :  8.9 us,  0.3 sy,  0.0 ni, 90.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
	%Cpu11 :  9.6 us,  0.0 sy,  0.0 ni, 90.4 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
	%Cpu12 : 10.4 us,  0.3 sy,  0.0 ni, 89.2 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
	%Cpu13 : 10.2 us,  0.7 sy,  0.0 ni, 89.1 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
	%Cpu14 : 11.1 us,  0.3 sy,  0.0 ni, 88.6 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
	%Cpu15 : 10.2 us,  0.7 sy,  0.0 ni, 89.1 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
	%Cpu16 :  9.2 us,  0.7 sy,  0.0 ni, 90.2 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
	%Cpu17 :  9.8 us,  0.3 sy,  0.0 ni, 89.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
	%Cpu18 : 10.1 us,  0.3 sy,  0.0 ni, 89.5 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
	%Cpu19 : 10.8 us,  0.7 sy,  0.0 ni, 88.5 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
	%Cpu20 :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
	%Cpu21 :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
	%Cpu22 :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
	%Cpu23 :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
	%Cpu24 :  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
	%Cpu25 :  6.4 us,  0.0 sy,  0.0 ni, 93.6 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st

It looks like only one task is running with the rest sleeping. I suspect this might be because of the flags I have set. Example command:

	/usr/local/bin/tippecanoe \
	  --layer=conus \
	  --force \
	  --output=conus.mbtiles \
	  --name=conus \
	  --read-parallel \
	  --maximum-zoom=19 \
	  --minimum-zoom=6 \
	  --base-zoom=19 \
	  --no-feature-limit \
	  --no-tile-size-limit \
	  conus.geojson

I am on version `tippecanoe v1.16.13`

I have tried setting the TIPPECANOE_MAX_THREADS environment variable, but the behavior doesn't change. Is there any other options I can change or tweak to increase my performance? Is there any support currently or planned in the future for CUDA processing?

Thanks for making this library! Even if there is no answer or solution to this, tippecanoe has made my processing work much simpler.

**Comment by ericfischer** [comment]
Hmm, I'm not quite sure what is going on here. Tippecanoe is constrained by the number of files the OS is configured to allow a process to have open at one time, but even if it is low (1024), that is still enough that it should calculate that it can operate 64 threads at once.

The other thing that you may be running into is that Tippecanoe assumes that the number of CPUs is a power of 2, so if there were 48 CPUs it would only try to use 32 of them. I should check whether that assumption is actually necessary. This wouldn't explain why it was 20 CPUs that were used though.

Can you send me the output of `ulimit -a` and `cat /proc/cpuinfo` or `sysctl hw.activecpu` so I can understand what OS and CPU limits are active?

As for why it would use less than 100% of each active CPU, I'm guessing that your data is larger than will fit in memory, so it is having to do a lot of I/O rather than being able to run in memory. Check the status message like

    147171 features, 10479245 bytes of geometry, 20926 bytes of separate metadata, 2789649 bytes of string pool

and see how it compares to the amount of physical memory you have to work with. The geometry file is handled as a stream, but it could be thrashing on string pool lookups.

There is also some locking because only one thread can write to the final `mbtiles` at once, but that shouldn't cut utilization as much as you are seeing.

**Comment by ericfischer** [comment]
I should also ask: are you seeing low utilization during input parsing, during tiling, or both?

**Comment by Burke9077** [comment]
Hello @ericfischer!

It looks like you might be on to the problem with the ulimit output:

	[root@ip-10-10-10-95 data]# ulimit -a
	core file size          (blocks, -c) 0
	data seg size           (kbytes, -d) unlimited
	scheduling priority             (-e) 0
	file size               (blocks, -f) unlimited
	pending signals                 (-i) 643902
	max locked memory       (kbytes, -l) 64
	max memory size         (kbytes, -m) unlimited
	open files                      (-n) 1024
	pipe size            (512 bytes, -p) 8
	POSIX message queues     (bytes, -q) 819200
	real-time priority              (-r) 0
	stack size              (kbytes, -s) 8192
	cpu time               (seconds, -t) unlimited
	max user processes              (-u) 643902
	virtual memory          (kbytes, -v) unlimited
	file locks                      (-x) unlimited

Here is the first output of /proc/cpuinfo. If it helps, this is an AWS m4.10xlarge instance. I usually change the instance size to fit the job and how much data is being processed. 

	[root@ip-10-10-10-95 data]# cat /proc/cpuinfo
	processor       : 0
	vendor_id       : GenuineIntel
	cpu family      : 6
	model           : 63
	model name      : Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
	stepping        : 2
	microcode       : 0x25
	cpu MHz         : 1609.968
	cache size      : 30720 KB
	physical id     : 0
	siblings        : 20
	core id         : 0
	cpu cores       : 10
	apicid          : 0
	initial apicid  : 0
	fpu             : yes
	fpu_exception   : yes
	cpuid level     : 13
	wp              : yes
	flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq monitor est ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm ida fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt
	bogomips        : 4800.13
	clflush size    : 64
	cache_alignment : 64
	address sizes   : 46 bits physical, 48 bits virtual
	power management:

The sysctl command didn't work, looks like proc/hw doesn't exist. It's probably just something in vm instead. I'll try to get the equivalent output.

Input parsing is super quick, tiling is where it slows down. The memory utilization is suspiciously low, many times using less than a percent of the 160 gb available.

I'm going to pursue this as a problem with my limits within CentOS. That seems to be the most likely culprit, but I would be interested in seeing if it's possible to have the CPUs be something other than a power of 2.

**Comment by ericfischer** [comment]
I think the `sysctl` version of finding out the number of CPUs only works on Macintoshes. Sorry to be confusing.

It is really surprising that tiling would be slow if not much memory is in use, because if there is plenty of memory available, it ought to be working out of the disk cache and not having to do I/O. And I don't know what the CPUs would be waiting on other than I/O.

https://github.com/mapbox/tippecanoe/pull/396 removes the constraint that the number of active CPUs must be a power of two. I don't see any negative consequence so I think I was just being overly cautious before.

**Comment by Burke9077** [comment]
@ericfischer Thanks for the CPU change! I tried using a few other linux distros (centos/amazon/ubuntu) and changing every setting I could find but ultimately I'm not sure what the bottleneck is. I observed that the earlier tiles (zoom 0-12ish) used all CPUs. When it went from 12-15 it cut the number of cpus down into the mid 20s and utilization rates of individual cores dropped as well. Beyond 15 the behavior was as I described before, used only 20 cpus and used them only to 10-20%.

For the time being I am fine with changing to a smaller machine and letting 4 cores or so handle the work for a longer period of time. I'll look into working on this problem and seeing what the bottleneck is, but for the time being I have to assume that it's not tippecanoe, or if it is it is caused by non-standard use.

Thanks for your help!

**Comment by flippmoke** [comment]
As you go deeper into the tree of tiles there are some tiles that little data to be written but there is still the longer time of waiting for disk IO. This is often because they might be writing tiles that have only a small amount of data, but still need to write a tile to the disk. As the disk IO increases, the usage on the cpu often decreases. This would be my best guess.

**Comment by Burke9077** [comment]
@flippmoke I suspect this as well, my IOPs count was rather high. I tried both with and without a temp directory. Didn't seem to change the behavior.

**Comment by flippmoke** [comment]
@Burke9077 you might try mounting a ramdisk if you can to see if it helps with throughput, you can easily thrash your RAM this way too though.

**Comment by ericfischer** [comment]
This is really the opposite of what I would have expected. The low zooms are usually constrained to just a few CPUs because until you get to zoom level 2 or 3, there aren't enough tiles to be made to assign each CPU to a tile.

You're probably right @flippmoke that it's blocking on flushing the buffer cache to disk. I've seen processes block for a long time before when doing a `fflush` on a file to close out the stdio buffers before doing an `mmap` on the same file to read it as memory, as if the `fflush` also did an implicit `fsync`. The confusing part is that tiling should only close files as each thread finishes. It doesn't close other files along the way.

I keep going back and forth on this: I used to do a lot more memory-mapped I/O during tiling, but found that it was usually faster to stream it than to rely on the virtual memory subsystem. But it looks like in this case the opposite is true.

**Comment by ericfischer** [comment]
If it wasn't for the `--no-feature-limit --no-tile-size-limit`, I might think that it was blocking when it had to do an `fseek` to move backward in the stream to retry a tile. But it shouldn't have to retry any tiles.

**Comment by Burke9077** [comment]
@ericfischer @flippmoke 

The ramdisk seemed like a good use of resources and I thought it would really give a performance boost. Strangely no such luck. It's still slowing down around layer 14 and I'm seeing exactly the same behavior.

I created a 64gb ramdisk, moved everything to it including my temp dir and output mbtiles file location of course. The 0-10 layers **flew by**, certainly faster. Then the same behavior happened again.

Here's the command I'm using at the moment. I tried to take as much work as possible off sacrificing disk:

	tippecanoe/tippecanoe \
	  --layer=hiresconus \
	  --output=hiresconus.mbtiles \
	  --name=hiresconus \
	  --temporary-directory=/ramdisk/main/tmp \
	  --read-parallel \
	  --maximum-zoom=19 \
	  --minimum-zoom=6 \
	  --base-zoom=19 \
	  --no-feature-limit \
	  --no-tile-size-limit \
	  --no-line-simplification \
	  --no-tiny-polygon-reduction \
	  hiresconus.geojson

htop output:

	1  [|||||         17.2%]  11 [||||          17.3%] 21 [               0.0%]  31 [               0.0%]
	2  [|||||         17.3%]  12 [||||          14.5%] 22 [               0.0%]  32 [               0.0%]
	3  [||||          14.9%]  13 [||||          17.8%] 23 [               0.0%]  33 [               0.0%]
	4  [||||          13.5%]  14 [||||          15.6%] 24 [               0.0%]  34 [               0.0%]
	5  [|||           14.4%]  15 [||||          15.9%] 25 [               0.0%]  35 [               0.0%]
	6  [||||          15.6%]  16 [||||          16.0%] 26 [               0.0%]  36 [               0.0%]
	7  [|||||         16.7%]  17 [|||||         17.4%] 27 [||             5.3%]  37 [               0.0%]
	8  [||||          18.1%]  18 [||||          16.9%] 28 [               0.0%]  38 [               0.0%]
	9  [||||          14.8%]  19 [|||           15.8%] 29 [               0.0%]  39 [               0.0%]
	10 [||||          17.9%]  20 [||||          18.7%] 30 [               0.0%]  40 [               0.0%]
	Mem[||||                               3.50G/157G] Tasks: 51, 48 thr, 351 kthr; 4 running
	Swp[                                        0K/0K] Load average: 3.12 3.02 2.04
													   Uptime: 00:22:22
	   PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command                                
	  3933 root       20   0 2359M  226M 38480 S 365.  0.1 20:09.39 tippecanoe/tippecanoe --layer=hiresconu
	  4549 root       20   0 2359M  226M 38480 R 13.4  0.1  0:20.37 tippecanoe/tippecanoe --layer=hiresconu
	  4568 root       20   0 2359M  226M 38480 S 12.7  0.1  0:20.23 tippecanoe/tippecanoe --layer=hiresconu
	  4547 root       20   0 2359M  226M 38480 S 12.0  0.1  0:20.31 tippecanoe/tippecanoe --layer=hiresconu
	  4559 root       20   0 2359M  226M 38480 S 12.0  0.1  0:20.14 tippecanoe/tippecanoe --layer=hiresconu
	  4541 root       20   0 2359M  226M 38480 S 12.0  0.1  0:20.24 tippecanoe/tippecanoe --layer=hiresconu
	  4540 root       20   0 2359M  226M 38480 S 12.0  0.1  0:20.26 tippecanoe/tippecanoe --layer=hiresconu
	  4560 root       20   0 2359M  226M 38480 S 12.0  0.1  0:20.26 tippecanoe/tippecanoe --layer=hiresconu
	  4542 root       20   0 2359M  226M 38480 R 12.0  0.1  0:20.21 tippecanoe/tippecanoe --layer=hiresconu
	  4557 root       20   0 2359M  226M 38480 S 12.0  0.1  0:20.15 tippecanoe/tippecanoe --layer=hiresconu
	  4567 root       20   0 2359M  226M 38480 S 12.0  0.1  0:20.10 tippecanoe/tippecanoe --layer=hiresconu
	  4546 root       20   0 2359M  226M 38480 S 12.0  0.1  0:20.12 tippecanoe/tippecanoe --layer=hiresconu
	  4545 root       20   0 2359M  226M 38480 R 12.0  0.1  0:20.16 tippecanoe/tippecanoe --layer=hiresconu
	  4563 root       20   0 2359M  226M 38480 S 11.4  0.1  0:20.30 tippecanoe/tippecanoe --layer=hiresconu
	  4566 root       20   0 2359M  226M 38480 S 11.4  0.1  0:20.23 tippecanoe/tippecanoe --layer=hiresconu

Current progress:

	root@ip-10-10-8-216:/ramdisk/main# tippecanoe/tippecanoe \
	>   --layer=hiresconus \
	>   --output=hiresconus.mbtiles \
	>   --name=hiresconus \
	>   --temporary-directory=/ramdisk/main/tmp \
	>   --read-parallel \
	>   --maximum-zoom=19 \
	>   --minimum-zoom=6 \
	>   --base-zoom=19 \
	>   --no-feature-limit \
	>   --no-tile-size-limit \
	>   --no-line-simplification \
	>   --no-tiny-polygon-reduction \
	>   hiresconus.geojson
	hiresconus.geojson:1369: Reached EOF without all containers being closed
	In JSON object {"type":"FeatureCollection","crs":{"type":"name","properties":{"name":"urn:ogc:def:crs:EPSG::3857"}},"features":[]}
	hiresconus.geojson:1366: Found ] at top level
	43840 features, 2734347 bytes of geometry, 7230018 bytes of separate metadata, 27030636 bytes of string pool
	  73.4%  14/2882/6285

**Comment by flippmoke** [comment]
@ericfischer depending on what data is like the limiting factor could be very different. Imagine if you had a simple square that covered all of a zoom level 0 tile. Now imagine tiling this all the way down to zoom 22. There is very little processing required for each tile and you will quickly run out of IO.

If there was a super dense geometry however, it definitely could run out of CPU first.

**Comment by Burke9077** [comment]
The data (I believe) is a 1x1km hex tile grid that spans the continental US. Not a very complex geometry but size wise is very large and of course contains various metadata entries for each hex geometry.

**Comment by ericfischer** [comment]
Oh, that would make a lot more sense. If you've got a 1km grid, that's basically a z15 tile, so anything higher than z15 is just streaming through a zillion squares that cover the entire tile but still need to run through all the attributes.

**Comment by Burke9077** [comment]
Correction, they are 15km tiles, so that makes it even moreso an issue. So the obvious answer then is to have a more appropriate zoom level, right?

**Comment by ericfischer** [comment]
Right, a much lower maxzoom would be appropriate. I don't know how precisely the corners of your grid need to be located, but if, say, 3m precision is good enough, you could stop at z12.

**Comment by Burke9077** [comment]
Thank you both, I appreciate the help! I'm still getting familiar with tile services.
