### ISSUE TITLE
Input reading isn't constrained by max open file count

### ISSUE THREAD

**Issue by ericfischer** [mapbox/tippecanoe#393]
If you have something like 512 CPUs but can only have 1024 open files, you immediately get

    /tmp/geom.XXCqXw0m: Too many open files

I think this is because `read_input` opens a set of temporary files for each CPU without checking whether that will run the process out of files.

**Comment by ericfischer** [comment]
https://github.com/mapbox/tippecanoe/pull/396 should fix this.

**Comment by jingsam** [comment]
I use tippecanoe to process 771 geojson files (104G) on a 16-cores machine, it complains "/tmp/geom.XXs1HFBW: Too many open files".

**Comment by ericfischer** [comment]
Thanks for the report. I am surprised that the number of input files could make a difference, because they should be read one at a time. What options are you using? Does it work with smaller numbers of input files? What limits does `ulimit -a` show?

**Comment by ericfischer** [comment]
Thanks. It looks like Tippecanoe is leaving input files open at the end of reading when using `--read-parallel`. I'll figure out what's going wrong and fix it.

**Comment by jingsam** [comment]
@ericfisher Thanks for help. Is it normal or expected that reading a bunch of geojson files (104 GB, tens of millions small polygons) would spend a whole day?

**Comment by ericfischer** [comment]
That doesn't seem completely unreasonable to me. I don't have a lot of benchmarks for data of that size, but complete census blocks for the United States (about 11 million polygons) take about 13 hours of CPU time to read and tile.

As far as I can tell, the time it takes Tippecanoe to parse input is roughly comparable to how long it takes other tools like `ogr2ogr` to read the same files. If you see any big discrepancies, it would be useful to have examples of files that are especially slow so I can address those cases.

Reading [Geobuf](https://github.com/mapbox/geobuf) is faster than reading GeoJSON, so it might help to convert your files to Geobuf, but ultimately I think you would spend as much time on the conversion as you would save on reading the result into Tippecanoe.

**Comment by ericfischer** [comment]
The files being left open will be fixed in https://github.com/mapbox/tippecanoe/pull/529

**Comment by ericfischer** [comment]
Merged
