### ISSUE TITLE
Possible to fail when tiles aren’t written?

### ISSUE THREAD

**Issue by migurski** [mapbox/tippecanoe#406]
I just experienced this when running with properties for OpenAddresses:

```
  23.8%  3/4/2  
  24.0%  3/4/2  
  24.1%  3/4/2  
tile 3/4/2 size is 530305 with detail 7, >500000    
could not make tile 3/4/2 small enough

*** NOTE TILES ONLY COMPLETE THROUGH ZOOM 2 ***
```

So that’s fine, but I think the exit status must have been 0 because it continues to upload the tiles:

```
2017-05-01 20:56:52,961    INFO: Uploading oa-vpx0wpcf.mbtiles to Mapbox open-addresses's open-addresses.lec54np1
2017-05-01 20:56:53,051   DEBUG: GET /uploads/v1/open-addresses/credentials
2017-05-01 20:56:53,683   DEBUG: /tmp/oa-vpx0wpcf.mbtiles --> b8/_pending/gh0xxgo3kq23vf10mxbvl62jc/open-addresses
```

Could this be made an error instead? Or should I do something smarter to detect this case?

**Comment by ericfischer** [comment]
This is surprising because it intends to exit with `EXIT_FAILURE` after cleaning up in this case. I'll investigate. Thanks.

**Comment by ericfischer** [comment]
I am getting an error exit after intentionally setting a very small maximum tile size:

```
$ if ./tippecanoe -M100 -z1 -f -o foo.mbtiles ./tl_2015_06001_roads.json; then echo success; else echo failure; fi
…
could not make tile 1/0/0 small enough
*** NOTE TILES ONLY COMPLETE THROUGH ZOOM 0 ***
failure
```

Are you sure your wrapper script is checking the return value?

(I would also suggest using `--drop-densest-as-needed` or `--drop-fraction-as-needed` to drop enough features to make the tiles work instead of failing, but that's a separate issue.)

**Comment by migurski** [comment]
Looks like Python’s wrapper doesn’t raise an error when the return value is non-zero, so Tippecanoe is doing the right thing and I can fix on my end. Thanks for looking into this, sorry for the false alarm!

Is 500KB a Mapbox service limit?

**Comment by ericfischer** [comment]
Yes, the 500K limit is imposed by the Mapbox unpacker for the sake of rendering performance.

**Comment by flippmoke** [comment]
The 500KB limit is also a part of the philosophy of using vector tiles, if you are passing around too large of vector tiles there is an excessive amount of data you need to parse on any renderer. This also means larger file transfers to GL clients. In general the density of a 256x256 image on which a tile was originally based can not really show much more information after a point as you run out of visual space. The idea is to therefore to use a higher zoom level in these cases or limit the amount of data you are showing. We could revise it someday, but it would require a lot of thought.
