### ISSUE TITLE
can tippecanoe generate vector tiles for a given area?

### ISSUE THREAD

**Issue by lihuadong1988** [mapbox/tippecanoe#408]

**Comment by ericfischer** [comment]
There's no built-in global clipping currently, but I could add the feature if it would be useful. Is clipping to a bounding box good enough for what you need?

**Comment by lihuadong1988** [comment]
I'm thinking about updating tiles,i don't want to regenerate all the tiles,so if i can only regenerate tiles according to the bounding box of the updated features,that will help.

**Comment by ericfischer** [comment]
Oh, OK, so you want to generate all the tiles that the bounding box intersects, not just the features that are actually within the bounding box?

**Comment by lihuadong1988** [comment]
That's it,don't know if this is possible.

**Comment by ericfischer** [comment]
This sounds like a good application for the plugin scripts that I've been working on in https://github.com/mapbox/tippecanoe/pull/332.

I just added a sample script to filter tiles by bounding box in 263a1b9.

**Comment by clarkcorey** [comment]
This is great functionality. It works well, unless you set other pre-filters that produce output in the terminal. There seems to be some collision with the use of the standard out between tippecanoe and the perl script it calls into. I get a broken pipe and segfault error.

I like that the way it's setup now as it's really extendable, but do you think this is a common enough need that it could be built in as an additional pre-filter like the others (ex drop-smallest-as-needed)? Something like `--filter-by-bbox=[x_min, x_max, y_min, y_max]` Curious as to how many people find this useful

**Comment by ericfischer** [comment]
Can you provide an example of a script that causes the problem? If Tippecanoe is crashing with a segmentation fault I would really like to fix that.

It would be straightforward enough to clip to a bounding box that I should probably just go ahead and add that as another command line option.

**Comment by ericfischer** [comment]
Thanks! I'll try some filters in combination with `--maximum-tile-bytes=15000` and see if I can reproduce the problem.

**Comment by ericfischer** [comment]
Thanks! This is very reproducible with

```
tippecanoe -F --no-feature-limit --maximum-zoom=15 --no-tile-compression --maximum-tile-bytes=15000 --drop-smallest-as-needed --output-to-directory /tiles/ -C './/filters/limit-tiles-to-bbox -115.001970 43.534703 -114.147301 44.019667 $*' ne_10m_admin_0_countries.json
```

and is because of a typo I made in parsing the filter output (it is checking the wrong JSON field to make sure it is not `NULL`).

**Comment by ericfischer** [comment]
This will be fixed in https://github.com/mapbox/tippecanoe/pull/650.

**Comment by clarkcorey** [comment]
Awesome, thanks for the quick turn around!

**Comment by ericfischer** [comment]
#650 will also add a `--clip-bounding-box` option to clip the input geometry.

**Comment by ericfischer** [comment]
Merged and tagged: https://github.com/mapbox/tippecanoe/releases/tag/1.32.1
