### ISSUE TITLE
Use all cores?

### ISSUE THREAD

**Issue by jliebrand** [mapbox/tippecanoe#413]
I noticed there's a nice -P flag to speed up the reading phase, but once it starts to produce all the tiles, it seems to just use one of my many cores. Is there a way to actually make use of all the cores of a machine? I seem to be vastly underusing my machine at the moment and it is taking a *loooong* time to complete :-(

**Comment by ericfischer** [comment]
If you have any good ideas for higher utilization, I'm all ears. The low zooms tend to use only a few CPUs because, for instance, the single tile 0/0/0 has to include every feature in the entire world, so the multithreaded work is limited to per-feature tasks like simplification and clipping. Once you get up to z4 or so, there are usually a lot of tiles to work on so the processing can be split across CPUs.

What sort of data and what geographic scope are you seeing low utilization with?

**Comment by ericfischer** [comment]
Closing since I don't think there is anything I can do in this direction currently.

**Comment by jliebrand** [comment]
Sorry; I thought I had relied... I thought I was seeing it use just one CPU throughout the process, but I didn't realize it might be different at the earlier zoom levels.

Happy for this bug to be closed. If I notice something odd later on, I'll reopen it with more details

**Comment by ericfischer** [comment]
Thanks. Please do let me know if you don't see more CPUs in use at higher zooms.

**Comment by charandas** [comment]
<img width="1783" alt="screen shot 2017-08-02 at 11 50 50 am" src="https://user-images.githubusercontent.com/542168/28882309-dffb0ece-7778-11e7-9d38-fb0fd47ba580.png">

@ericfischer In this screenshot, I am on a higher zoom like 13, but its only using 1 core. Thoughts?

**Comment by charandas** [comment]
To provide more context, I am actually using 240ccbd2196516918017353ffd8704c858cb44f9.

I can try pulling in the latest to see if there are improvements since May that I haven't caught on with.

**Comment by charandas** [comment]
Never mind, when I `top` in the container, I see it using all cores. I wonder what's causing it to be this slow: its ~70K features of census tracts, curious to know what's the bottleneck.

<img width="1783" alt="screen shot 2017-08-02 at 12 32 02 pm" src="https://user-images.githubusercontent.com/542168/28884146-cb88f266-777e-11e7-8000-70da1327f645.png">

**Comment by charandas** [comment]
Running against the same dataset outside of docker was superfast with the brew package. Not sure, why containerization on my machine is slowing it down. I have all 8 cores and 8GB (of 16GB) of memory dedicated to Docker for mac.

**Comment by ericfischer** [comment]
Unfortunately I don't have much experience with Docker to help diagnose this. The most common situation I know of where Tippecanoe gets slowed down is when it is blocked waiting for I/O to complete. It uses a lot of anonymous temporary files during tiling and the general hope is that everything will actually happen in the buffer cache and the files will only actually reach the disk in the case of a low-memory situation. But maybe Docker does something to confound this expectation.
