### ISSUE TITLE
mbtiles metadata bounds not in WGS84 after passing through tile-join

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/tippecanoe#415]
1. `wget https://www.mapbox.com/help/data/trails.mbtiles`
2. `mapbox upload username.trails trails.mbtiles`
Upload works
3. `tile-join -f -o trails-join.mbtiles trails.mbtiles`
4. `mapbox upload username.trailsjoin trails-join.mbtiles`
Upload fails with bounds west value must be between -360 and 360

5. `sqlite3 trails.mbtiles 'select name,value from metadata'`
no bounds

6. `sqlite3 trails-join.mbtiles 'select name,value from metadata'`
bounds is "2147483647.000000,2147483647.000000,-2147483648.000000,-2147483648.000000"

7. According to the [mbtiles spec](https://github.com/mapbox/mbtiles-spec/blob/master/1.1/spec.md#content) bounds must be in WGS 84.

**Comment by ericfischer** [comment]
Thanks for the report! It looks like this is because the original mbtiles doesn't declare a bounding box, and tile-join isn't properly checking for its absence. I'll fix it.

**Comment by ericfischer** [comment]
This will be fixed in https://github.com/mapbox/tippecanoe/pull/416

**Comment by ericfischer** [comment]
Merged. Thanks again for the bug report!
