### ISSUE TITLE
How do I remove dot dropping? 

### ISSUE THREAD

**Issue by divya1c** [mapbox/tippecanoe#423]
Hi! 

I am trying to create a population map, similar to https://www.mapbox.com/blog/twitter-map-every-tweet/. I have one dot per avg population in each block. However, I see that many of my dots do not show up in a zoomed out view. I went through tippecanoe documentation and tried some options for avoiding dot dropping. 
I tried using -pf and -pk to disable tile size limits. 
```tippecanoe -f -pf -pk -o points.mbtiles -l "avg_estimated_population" points.geojson```
I also tried adding -r1 --drop-fraction-as-needed to turn off normal dot dropping.
```tippecanoe -f -pf -pk -r1 --drop-fraction-as-needed -o points.mbtiles -l "avg_estimated_population" points.geojson```
Neither of these methods worked. Am I missing something?

Here's my mapbox gl code to render the dots : 
```
map.on('load', function() {
  map.addSource('population-data', {
    'type': 'vector',
    'tiles': ['http://localhost:7778/population/{z}/{x}/{y}.pbf'],
    'maxzoom': 14,
    'interactive': false
  });

  map.addLayer({
      "id": "markers",
      "source": "population-data",
      "source-layer": "avg_estimated_population",
      "type": "symbol",
      "paint": {
          "icon-opacity": 0.8
      },
      'layout': {
        "icon-size": {
          "stops": [
            [5, 0.1], [6, 0.1], [7, 0.1], [8, 0.1], [9, 0.1], [10, 0.2], [11, 0.2], [12, 0.2], [13, 0.9], [14, 1]
          ]
        },
        "icon-image": "circle-11",
        "icon-allow-overlap": true,
        "icon-ignore-placement": true       
      }
  });
});
```
I serve my tiles on localhost:7778.

Thanks!

**Comment by ericfischer** [comment]
If you want to keep all the `Point` features at every zoom level, `-r1 -pk -pf` should do that. (`--drop-fraction-as-needed` should have no effect if `-pk` and `-pf` are set.)

Can you be more specific about the problem you are running into?

**Comment by divya1c** [comment]
Some dots appear only at higher zoom levels. But, I want all dots to show at all zoom levels. Here are two screen shots at zoom levels 9 and 10. Note that there are lesser number of dots in zoom level 9 compared to zoom level 10. Here, marker widths at both zoom levels are the same, but I intend to change the marker widths for different zoom levels. 
<img width="769" alt="screen shot 2017-05-24 at 1 39 04 pm" src="https://cloud.githubusercontent.com/assets/16343652/26424646/d0436022-4086-11e7-93f6-ca84cd377375.png">
<img width="771" alt="screen shot 2017-05-24 at 1 38 51 pm" src="https://cloud.githubusercontent.com/assets/16343652/26424648/d2d39708-4086-11e7-9097-8848b6313d99.png">

**Comment by ericfischer** [comment]
I don't understand how that could be. If I do

```
 tippecanoe -X -f -o foo.mbtiles -b0 -r1 -pk -pf
```

(with `-b0` to eliminate the tile buffer, to avoid double-counting) and then

```
$ tippecanoe-decode -z9 -Z9 foo.mbtiles | grep '"Feature"' | wc -l
  250028
$ tippecanoe-decode -z10 -Z10 foo.mbtiles | grep '"Feature"' | wc -l
  250028
```

I've got the same 250,028 features in each zoom level. Are you sure you don't have old tiles in the browser cache or something?

**Comment by divya1c** [comment]
Turned out that I had an older version of tippecanoe, I updated it and ran it again and now I have approx equal number of features at different zoom levels. :) thanks for the help, I now know how to debug with tippecanoe-decode.

**Comment by ericfischer** [comment]
Glad to hear it's working for you now!

**Comment by divya1c** [comment]
Hi @ericfischer ! I don't think this completely worked for me :( So, I am not able to see visual differences, but when i do tippecanoe-decode, I see that there are different number of features at different zooms. When i did it before, the difference was very small, but now I see large differences in my greater zoom levels. 

I first use tippecanoe to make my mbtiles file from a geojson file(having mutipoint geometries) that i have. Then, I use tippecanoe-decode to decode the number of features from the mbtiles file at various zooms. 

```
tippecanoe -X -f -o points_avg_pop_6.mbtiles -b0 -r1 -pk -pf -l "avg_estimated_population" -z22 -Z15 points_avg_pop_6.geojson

tippecanoe-decode -z16 -Z16 points_avg_pop_6.mbtiles | grep '"Feature"' | wc -l
 7578

tippecanoe-decode -z17 -Z17 points_avg_pop_6.mbtiles | grep '"Feature"' | wc -l
9582
```

Am I missing something here?

**Comment by ericfischer** [comment]
I'm not sure what is going on here. Can you post your GeoJSON file somewhere so I can try it myself and see if I get the same results?

**Comment by divya1c** [comment]
This is the geojson file i used - https://gist.githubusercontent.com/divya1c/fca4e46bd8abf5a6980c81e7946d974b/raw/763be52bae53051b57e75d79416f1dd2f1a501bb/points.geojson

I use this to make my mbtiles : 
tippecanoe -X -f -o points.mbtiles -b0 -r1 -pk -pf -l "avg" -z22 -Z15 points.geojson

Then , I decode it this way : 
tippecanoe-decode -z16 -Z16 points.mbtiles | grep '"Feature"' | wc -l
tippecanoe-decode -z17 -Z17 points.mbtiles | grep '"Feature"' | wc -l

I observe that the projection in my geojson file is EPSG::4269, will that cause a problem? Thanks a lot for the help!

**Comment by ericfischer** [comment]
EPSG:4629 should be OK, since it looks like it is effectively an alias for WGS84, even though it  is meant to be used in French Polynesia, not San Francisco.

I am getting different numbers of features in these tiles too. I don't understand why yet, but I'll investigate and figure it out. Thanks for the bug report.

**Comment by ericfischer** [comment]
Oh, it's because your features are MultiPoints, and the higher the zoom level gets, the more of them get split into two separate Points on either side of a tile boundary.

If you pull out just the coordinate pairs from the features, there are the same number of unique points in each zoom level.

```
$ tippecanoe-decode -z15 -Z15 points.mbtiles | grep '"Feature"' | sed 's/.*"coordinates"://' | sed 's/, /,/g' | tr '[]' '\012\012' | grep '[0-9]' | sort | uniq -c | wc -l
   33869

$ tippecanoe-decode -z16 -Z16 points.mbtiles | grep '"Feature"' | sed 's/.*"coordinates"://' | sed 's/, /,/g' | tr '[]' '\012\012' | grep '[0-9]' | sort | uniq -c | wc -l
   33869

$ tippecanoe-decode -z17 -Z17 points.mbtiles | grep '"Feature"' | sed 's/.*"coordinates"://' | sed 's/, /,/g' | tr '[]' '\012\012' | grep '[0-9]' | sort | uniq -c | wc -l
   33869
```

(There must be a cleaner way to write those shell commands, but I hope it gets the point across.)

**Comment by divya1c** [comment]
ohh! I couldn't see any difference while seeing on the map. I could only see the difference through tippecanoe-decode! makes sense now.
