### ISSUE TITLE
about examples.

### ISSUE THREAD

**Issue by lihuadong1988** [mapbox/tippecanoe#427]
example:https://www.mapbox.com/blog/geotaggers-world-atlas/.data is png format, not mvt?

**Comment by ericfischer** [comment]
The underlying data is vector tiles, but it is being rendered to bitmaps by the Mapbox tile servers. I should make a Mapbox GL style for the same data.

**Comment by ericfischer** [comment]
It's now a [Mapbox GL style](https://api.mapbox.com/styles/v1/enf/cj3xhu4l51k4s2rmzfr2hzcos.html?title=true&access_token=pk.eyJ1IjoiZW5mIiwiYSI6IkNJek92bnMifQ.xn2_Uj9RkYTGRuCGg4DXZQ#12.5/49.2909/-123.113), from the same vector tiles.

**Comment by lihuadong1988** [comment]
excuse me, i want to know how to convert mvts into pngs,do you konw how?

**Comment by ericfischer** [comment]
I haven't tried it myself, but https://github.com/mapnik/node-mapnik/issues/346#issuecomment-62632193 contains an example of a Mapnik script that reads a vector tile and writes it out as a JPEG.
