### ISSUE TITLE
Failed to use generated tilesets using -e command with Mapbox gl js

### ISSUE THREAD

**Issue by showjackyang** [mapbox/tippecanoe#434]
Hi, not sure this issue should go to tippecanoe or Mapbox gl js 

I was using `tippecanoe -e tmp -L test:test.geojson` and tried to get the pbf tilesets to work with Mapbox gl js. The generated tilesets worked for tilelive, but not Mapbox gl js, it was complaining not able to decode the pbf received. Is pbf from tippecanoe different from mvt?

Thank you.

**Comment by ericfischer** [comment]
The `-e` flag was an external contribution (https://github.com/mapbox/tippecanoe/pull/386) so I haven't used it myself extensively, but it has essentially the same effect as writing the tiles to `.mbtiles` and then extracting them to a directory with `mbutil`.

The only thing I can think of is that maybe tilelive is serving compressed tiles from your `tmp` directory and GL-JS is thinking for some reason that they would be uncompressed. But `pbf` and `mvt` ought to be synonyms.

**Comment by showjackyang** [comment]
Hi,

I was able to solve the problem just by adding a content-type header when responding to Mapbox gl js pbf requests from http sources (for instance S3).

Is pbf is gzipped by nature? 

Thanks.

**Comment by ericfischer** [comment]
Great, I'm glad you got it working. Tippecanoe will always compress tiles unless you use the `--no-tile-compression` option. Some software (like `tippecanoe-decode`) will look for a compression signature and work with either compressed or uncompressed tiles, but the general expectation is that tiles will always be compressed.
