### ISSUE TITLE
Zero feature case handling

### ISSUE THREAD

**Issue by divya1c** [mapbox/tippecanoe#437]
Hi! 

I see that a journal file is always created when i am generating my mbtiles file from my geojson file. I assumed that the journal file gets deleted once the mbtiles file has been created successfully. I tried to create an mbtiles file for a geojson with no features and my journal file is not deleted - which tells me that there's something wrong with my mbtiles creation. Does tippecanoe not handle empty feature case? 

This is my geojson : 
```
{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::4269" } },
                                                                                
"features": [

]
}
```
I use this command to generate my mbtiles : 
```
tippecanoe -o tipp_out.mbtiles -Z6 -l "smartlayer" ogr_out_smart_layer.geojson
```

I don't see any errors in my log. I see this in my log : 
```
geojsons/ogr_out_smart_layer.geojson: Warning: GeoJSON specified projection "urn:ogc:def:crs:EPSG::4269", not the expected "urn:ogc:def:crs:OGC:1.3:CRS84".
geojsons/ogr_out_smart_layer.geojson: If "urn:ogc:def:crs:OGC:1.3:CRS84" is not the expected projection, use -s to specify the right one.
0 features, 10 bytes of geometry, 4 bytes of separate metadata, 0 bytes of string pool
Did not read any valid geometries
```

**Comment by ericfischer** [comment]
Thanks for the report. It must not be closing the sqlite3 database properly when exiting after discovering that there are no features. I'll investigate and fix it.

**Comment by divya1c** [comment]
hi @ericfischer, was wondering if this will be fixed this week. I need to push something in my project and I will not being able to do that till this bug is fixed :(

**Comment by ericfischer** [comment]
I am surprised that anything important would rely on this behavior but here is a patch for you: https://github.com/mapbox/tippecanoe/pull/440

**Comment by ericfischer** [comment]
Merged.
