### ISSUE TITLE
tile-join warn duplicated layer name

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/tippecanoe#439]
When using tile-join to join two mbtiles with the same layer name, tippecanoe should emit a warning.

Currently these mbtiles with two layers with the same name look fine in mbview but are missing the duplicated layer when uploaded to Mapbox.

**Comment by ericfischer** [comment]
Do you have an example of where this is going wrong? The intent is that if you have layers with the same names in two source mbtiles, it will merge them into a single layer in the output mbtiles.

**Comment by ericfischer** [comment]
Please reopen if you have an example of the problem.

**Comment by andrewharvey** [comment]
I just tested this again now and it works as expected. :+1: 

```
# create two geojson files
echo '{"type": "FeatureCollection", "features": [{"type": "Feature", "properties": {"key": "bar"}, "geometry": {"type": "Point", "coordinates": [1,1]}}]}' > bar.geojson
echo '{"type": "FeatureCollection", "features": [{"type": "Feature", "properties": {"key": "foo"}, "geometry": {"type": "Point", "coordinates": [0,0]}}]}' > foo.geojson

# convert to mbtiles using the same zzz layer name
tippecanoe --force -o bar.mbtiles -L zzz:bar.geojson
tippecanoe --force -o foo.mbtiles -L zzz:foo.geojson

# check the layer name is the same in both mbtiles with mbinfo

# join tilesets
tile-join -o zzz.mbtiles foo.mbtiles bar.mbtiles 

# uploading zzz.mbtiles to Mapbox looks as expected
# mb-view zzz.mbtiles looks as expected
# tippecanoe-decode zzz.mbtiles looks as expected
```

**Comment by ericfischer** [comment]
Great, thanks for the confirmation!
