### ISSUE TITLE
-L flag (multiple layers/multiple geojsons) removes special characters from layer names

### ISSUE THREAD

**Issue by gtmtg** [mapbox/tippecanoe#442]
Hi!

We're using tippecanoe to convert FeatureCollection geojson files to vector tilesets and we recently switched from using the `-l` flag with one geojson file/layer name to using the `-L` flag with several geojson files that were to be placed on individual layers. However, we noticed an odd bug—while the `-l` flag was perfectly happy to take in layer names with special characters (like hyphens), the `-L` flag strips these characters from layer names without warning, so the flag switch broke a bunch of things on our end. Is this behavior intentional/documented?

**Comment by ericfischer** [comment]
The intent is that `-l` and `-L` should behave the same, except that `-L` has to have a special case for `:` to separate the layer name from the filename.

Can you be more specific about the options you were using, the behavior you saw, and the behavior you wanted to see?

**Comment by ericfischer** [comment]
Can you also say what operating system you were using, since there might be some difference in the `getopt_long` implementation on Mac vs. Linux?

**Comment by dylanparry** [comment]
I'm seeing this too, but in my case I've specified the layer names using the `"tippecanoe": { "layer": "my-layer-name" }` syntax within the JSON itself. It appears to strip out the dashes leaving very long, sometimes unreadable layer names.

For example, one of my layers is being created with the name `osopenmaplocalelectricitytransmissionline` when I've specified it should be called `os-openmaplocal-electricity-transmission-line`. The latter would let me see the source of the data (OS), the dataset it belongs to (OpenMap Local), and finally the name of the layer (Electricity Transmission Line). With all the dashes removed it's not very friendly.

I'm using Linux (Ubuntu), but I'm running tippecanoe under Docker, the contain for which I think is also based on an Ubuntu image.

**Comment by ericfischer** [comment]
Ah, thanks! I'll take a look and see what's going wrong with names specified that way.

**Comment by ericfischer** [comment]
I can't reproduce this either. This input:

```
{ "type": "Feature", "tippecanoe": { "layer": "os-openmaplocal-electricity-transmission-line" }, "properties": { }, "geometry": { "type": "Point", "coordinates": [ 0,0 ] } }
```

preserves the layername as `os-openmaplocal-electricity-transmission-line` in the output (with tippecanoe v1.20.1 on MacOS X).

What Tippecanoe version are you using?

**Comment by dylanparry** [comment]
Having just run this again, it seems it's only reporting the unwieldy layer names in the CLI. When it comes to the actual layer names in the tiles, they retain the dashes. However, the OP's issue still remains as I can confirm that the dashes were stripped from the names when I was using the `-L` flag to name them.

**Comment by ericfischer** [comment]
In addition, I am seeing the full original layer name after doing

```
$ ./tippecanoe -z0 -Los-openmaplocal-electricity-transmission-line:foo.json -f -o foo.mbtiles
1 features, 19 bytes of geometry, 4 bytes of separate metadata, 0 bytes of string pool
  52.6%  0/0/0

$ ./tippecanoe-decode foo.mbtiles
…
{ "type": "FeatureCollection", "properties": { "layer": "os-openmaplocal-electricity-transmission-line", "version": 2, "extent": 4096 }, "features": [
…
```

@dylanparry or @gtmtg, can you please supply a transcript of the command line you are using and a transcript of the messages you are seeing so I can try to reproduce the circumstances where things are going wrong?

**Comment by dylanparry** [comment]
I appear to be running a positively ancient version. I'll update my version with a new Docker build and check again. I suspect if you can't replicate it, then it must be down to me using an old version---for me at least.

**Comment by ericfischer** [comment]
I hope the upgrade fixes it for you!

**Comment by dylanparry** [comment]
Tested it this afternoon after updating my Docker container to the latest version. It seems to have fixed the issues I was having, and has also resulted in a noticeable speed improvement---so a winner all round. Thanks!

**Comment by ericfischer** [comment]
Great! I'm glad it's working now. Please reopen the issue if you run into any more layer name troubles.
