### ISSUE TITLE
Clip per layer

### ISSUE THREAD

**Issue by dylanparry** [mapbox/tippecanoe#446]
Hi,

I was wondering if it's possible to add some method of specifying the clipping behaviour on a per-layer basis? The reason being that I have several large datasets, some of which have very large polygons, and some of which have lots of small polygons---I'd want to turn clipping off for the datasets with small polygons so that I can label them efficiently (I don't want labels to appear on multiple tiles just because a polygon got split for example), but turn it off for the larger polygon datasets so I don't end up with huge tiles (or in my case failing, because one polygon covers over a thousand tiles!).

I think it'd be a case of adding an option to the JSON itself rather than the command line, as I'm pretty sure that would get messy. As the default behaviour is to clip, I guess it would make sense to add the option to turn off clipping on the feature itself?

I don't know how feasible this is, or whether there's any demand for it, but it's something that I know I for one would like :)

Thanks,

Dylan

**Comment by ericfischer** [comment]
A per-layer buffer setting seems more practical than a setting for not clipping at all, since unclipped geometries that are larger than a few tiles work badly in Mapbox GL anyway. Do you think that would handle your case?

The best workaround currently is to create separate tilesets for the layers that need different settings and then use `tile-join` to merge them into a single tileset at the end.

**Comment by ericfischer** [comment]
Maybe a `--no-duplication-if-possible` setting that puts a feature only in one tile or another if it fits in the tile plus its buffer?

**Comment by dylanparry** [comment]
That might work for me, yes. If I have small polygons that need labelling, the likeliness is that they would fit in a decent size buffer---they're not features that would ever cover more than one tile if they were bang in the middle of one tile (if you see what I mean?).

I think the `--no-duplication-if-possible` flag wouldn't work for my use case though. I'm using OpenLayers, and that doesn't seem to let a tile draw outside its boundary, so I'd get clipped polygons there.

A per-layer buffer, would seem to be a good idea though!

**Comment by dylanparry** [comment]
Missed the bit about the `tile-join` feature. I didn't realise that existed! That might come in very handy indeed. I'm guessing with that, I can create a tileset for each dataset I have now, buffer them accordingly, and then merge them all afterwards. I could possibly even turn off clipping for some tilesets, and see if that works too. Thanks.

**Comment by ericfischer** [comment]
Really the right way to support both clipped polygons and one label per feature is to split off the labels as separate point features. Maybe a `--split-label-from-polygon=PROPERTYNAME` flag, if it's too hard to do as a preprocessing step?

**Comment by ericfischer** [comment]
`*.mbtiles` ought to work as an argument for `tile-join`, since it will be handled by the shell and is equivalent to naming each file individually. What went wrong? I could add a way to read a list of filenames from the standard input, but that doesn't seem like it should really be necessary.

**Comment by dylanparry** [comment]
You're probably right about splitting the labels out into a point layer---I hadn't thought about that, so will give it a try.

Re. using a wildcard, this is what I'm getting:

```
dylanparry@dylan-Inspiron-7520:~$ docker run -it --rm -v $HOME/Tippecanoe:/data tippecanoe:latest tile-join --force --no-tile-size-limit --name="OS OpenData" --description="Base mapping derived from Ordnance Survey OpenData" --attribution="Contains OS data © Crown copyright and database right (2017)" --output=/data/basemap.mbtiles /data/tiles/*.mbtiles
/data/tiles/*.mbtiles: select failed: no such table: tiles
```

I then also get a file called `*.mbtiles` being created in the `/data/tiles` directory. It's also one that can cause issues if I delete it without remembering to put quotes around the name, ie. `rm "*.mbtiles"` is very different from `rm *.mbtiles`!!

**Comment by ericfischer** [comment]
This is another case where Docker interferes with normal Unix expectations. Wildcards like `*` are expanded by the shell, not by the program being run, so `/data/tiles/*.mbtiles` means all the `mbtiles` file in your own file system, not the file system inside the Docker environment.

I think the workaround will be to run a subshell inside Docker to do the wildcard expansion:

```
docker run -it --rm -v $HOME/Tippecanoe:/data tippecanoe:latest sh -c 'tile-join --force --no-tile-size-limit --name="OS OpenData" --description="Base mapping derived from Ordnance Survey OpenData" --attribution="Contains OS data © Crown copyright and database right (2017)" --output=/data/basemap.mbtiles /data/tiles/*.mbtiles'
```

**Comment by dylanparry** [comment]
Yes, that appears to do the trick. Thanks!

**Comment by mflint** [comment]
For anyone else reading this: _tippecanoe_ can show the "no such table" error when it can't find the _file_. So check the filepath that you're supplying on the command-line!
