### ISSUE TITLE
Merge millions of neighbouring squares?

### ISSUE THREAD

**Issue by jucor** [mapbox/tippecanoe#449]
Thanks for an extremely useful tool. Apologies if this is a naive question or the wrong place to ask.

Is there a way to ask tippecanoe to merge attributes-less neighbouring polygons? I have ~ 15 millions adjacent tiny squares, each of them corresponding to a Level 18 slippy tile, which do not render efficiently. I would be very happy for those of them who are consecutive to be merged into one big polygon -- doing away with individual squares and boundaries. 

This is a somewhat simpler case than for general polgons, as those shapes are non-overlapping squares, parallel to the axes, etc. Usual geometric toolboxes like Python's shapely are overkill and die on it. The annoying bit is that the union of the squares can still be non-convex, and have 'holes' in it.

Any help much welcome! Thanks :)

**Comment by dylanparry** [comment]
Have you tried doing this in a proper GIS before converting your data to tilesets? Something like QGIS should be able to handle this, I would have thought.

**Comment by ericfischer** [comment]
@jucor The `--coalesce` option will try to combine adjacent (defined by quadkey order, not necessarily by real adjacency, and currently stopping at 700 points per coalesced feature) that have the same attributes. I hope this is close enough for what you are looking for.

I also have some experimental code for more general polygon merging by true adjacency, but it is slow and complicated.

**Comment by jucor** [comment]
@ericfischer : thanks a *lot*, `--coalesce` did the trick perfectly! My .mbtiles file went from 106M to  9.9M, and the webmap is now much more reactive. Amazing! Closing this issue. Thanks again!

@dylanparry : thanks for the suggestion. I am trying to stay entirely programmatic, because this rendering is just one part of an automated pipeline post processing the output of a machine learning classifier. So jumping through QGIS, which is clunky and highly manual, would be a very last resort. However, if you do know some good programmatic GIS libraries (ideally in Python), I'd love to hear them -- I'm coming at this form the machine learning angle, not from the GIS one.
