### ISSUE TITLE
Generate a single tile?

### ISSUE THREAD

**Issue by dmfenton** [mapbox/tippecanoe#456]
Is there a way to just generate a single tile? E.g. 13,2343,3132.

**Comment by ericfischer** [comment]
There is not currently a way to do this. Is the use case for clipping, for tileset updating, or something else?

**Comment by dmfenton** [comment]
I want to use AWS Lambda to generate a single vector tile on demand from any arbitrary stream of geojson features

so user requests: 0/0/0.pbf
lambda returns the file
cloudfront caches

voila: serverless vector tile server

it's not the most efficient way to do things, but the operations overhead is very low

**Comment by jdeboer-geoplan** [comment]
@dmfenton did you find a way to do what you wanted with lambda? That sounds cool.

**Comment by dmfenton** [comment]
I got a tile cooker working on lambda that can return a single tile, but it has to cook the whole set first. So yes and no I guess.

**Comment by mapsam** [comment]
@dmfenton if your plan is to generate a single tile, an alternative could be a combination of [geojson-vt](https://github.com/mapbox/geojson-vt) (for ingesting geojson) & [vt-pbf](https://github.com/mapbox/vt-pbf) (writing JS objects into pbfs).

Could be set up with a script like:

```javascript
var geojsonvt = require('geojson-vt');
var vtpbf = require('vt-pbf');

var tileIndex = geojsonvt(YOUR_GEOJSON_OBJECT);
var tile = tileIndex.getTile(Z, X, Y);
var buffer = vtpbf.fromGeojsonVt({ 'YOUR-LAYER-NAME': tile });

return buffer;
```

**Comment by dmfenton** [comment]
The problem is that geojsonvt cooks the whole pyramid

Get Outlook for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__aka.ms_o0ukef&d=DwIGaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=sf9dCugEJAjYuTT5XU-MPDKI7bpoNNGaEmWlLGmRTGF-PPE_L-wdyUbm-GdMoVdiOWxwxuvOFd4Ksju46bcnndK_LfYIxL-V0Y49SSmvU47L0c--6O_kOPnh2Nli3ltuWGJ_xuxXpPEr-fofVttGEg&m=XthiXvQCROYlVmSO4VDRKtIpET3m6xTRKq6mQjMZX1w&s=88RToAttAmh5iz2i5VPg5IbNUVE-9ZLEEHqcxKDu4ss&e=>



On Fri, Jan 26, 2018 at 1:28 PM -0500, "Sam Matthews" <notifications@github.com<mailto:notifications@github.com>> wrote:


@dmfenton<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dmfenton&d=DwMFaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=qIU77Aq45OSMuD9yKJXm1Q&m=s_ce-8oDC_xNEF_jCj7dWho2u0cww8pr7wVoqvwhJbc&s=oPJYMmUDGYBapKLoH8ck_k5Vd57TxCvfFIPVYHp7WLE&e=> if your plan is to generate a single tile, an alternative could be a combination of geojson-vt<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mapbox_geojson-2Dvt&d=DwMFaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=qIU77Aq45OSMuD9yKJXm1Q&m=s_ce-8oDC_xNEF_jCj7dWho2u0cww8pr7wVoqvwhJbc&s=BpeRISoSpdKoYomMyQzkqjWsxTQAEX3sgN2BkFfyREo&e=> (for ingesting geojson) & vt-pbf<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mapbox_vt-2Dpbf&d=DwMFaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=qIU77Aq45OSMuD9yKJXm1Q&m=s_ce-8oDC_xNEF_jCj7dWho2u0cww8pr7wVoqvwhJbc&s=t1kvizph3H7j5RpvXn2T-DCMNcndxesU6C7lyYIXcU8&e=> (writing JS objects into pbfs).

Could be set up with a script like:

var geojsonvt = require('geojson-vt');
var vtpbf = require('vt-pbf');

var tileIndex = geojsonvt(YOUR_GEOJSON_OBJECT);
var tile = tileIndex.getTile(Z, X, Y);
var buffer = vtpbf.fromGeojsonVt({ 'YOUR-LAYER-NAME': tile });

return buffer;

**Comment by ericfischer** [comment]
Actually this is less complicated to do directly in Tippecanoe than I thought. Does https://github.com/mapbox/tippecanoe/pull/521 do what you were looking for?

**Comment by dmfenton** [comment]
Yes! I think it does! I'll dust off my cooker and give this a try.

**Comment by ericfischer** [comment]
PR replaced by https://github.com/mapbox/tippecanoe/pull/529

**Comment by ericfischer** [comment]
Merged

**Comment by jalessio** [comment]
@dmfenton Did you ever get this working?
