### ISSUE TITLE
Expand the functionality of tile-join

### ISSUE THREAD

**Issue by caneroj1** [mapbox/tippecanoe#457]
**Feature Request**

It would be nice to expand the capabilities of **tile-join**.

My use case is to extract different layers out of a single mbtiles file, but apply different filters to each layer.

For example, say I have a prebuilt mbtiles file that defines **layer1**, **layer2**, and **layer3**.

I'd like to keep all features from **layer1**, keep features from **layer2** that have a property that matches a filter (kind = 'river' or something), and keep features from **layer3** that pass another filter, like (kind = 'wood' and subclass = 'wood').

I'm not sure if there is a way to accomplish this at the moment with the current capabilities of **tile-join** without doing multiple passes over the mbtiles file. Please correct me if I'm wrong.

Also, like I mentioned in #455, I'd be willing to help with this feature.

**Comment by ericfischer** [comment]
I don't think there is any way to do this currently, but if you have a good idea for handling rules like this, I would welcome the contribution.

It seems like it would be ideal to support arbitrary JavaScript expressions as if each feature were a GeoJSON object, like

```
feature.tippecanoe.layer === "layer1" ||
(feature.tippecanoe.layer === "layer2" && feature.properties.kind === "river") ||
(feature.tippecanoe.layer === "layer3" && feature.properties.kind === "wood" && feature.properties.subclass === "wood")
```

which could also address the during-tiling filtering request in https://github.com/mapbox/tippecanoe/issues/453. Maybe this would be more practical than I was thinking it was, since there aren't *that* many types or operators that would need to be interpreted. JavaScript-compatible regular expression matching would probably be harder.

**Comment by caneroj1** [comment]
Hmm. I was thinking we could possible specify some sort of config file for how to do the filtering.

```json
{  
   "layers":[  
      {  
         "name":"layer1"
      },
      {  
         "name":"layer2",
         "filters":[  
            {  
               "kind":"river"
            }
         ]
      },
      {  
         "name":"layer3",
         "filters":[  
            {  
               "kind":"wood",
               "subclass":"wood"
            }
         ]
      }
   ]
}
```

You specify each layer, and if you provide no filters, all features are kept from that layer. Otherwise, the filters attribute expects a list of objects.

With **layer3**, our filter will say that we keep features whose kind == wood and subclass == wood. If we specify another object in the array, we could OR all of those filters together.

This is definitely not as flexible as just straight-up javascript, but perhaps it would be easier to integrate into the tippecanoe than a javascript interpreter.

**Comment by caneroj1** [comment]
Perhaps it would make the most sense to just support mapbox's [filter](https://www.mapbox.com/mapbox-gl-js/style-spec/#types-filter) syntax?

**Comment by ericfischer** [comment]
That would make a lot of sense as a Mapbox standard!

**Comment by ericfischer** [comment]
Fixed in https://github.com/mapbox/tippecanoe/pull/462
