### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by tmcw** [mapbox/tippecanoe#46]
This repo should have

* A linter step to make sure that the C is in a uniform style & valid
* Tests for tippecanoe

**Comment by ericfischer** [comment]
It's not exactly 100%, but a pretty good approximation to the style of this code is

    clang-format -style="{BasedOnStyle: Google, IndentWidth: 8, UseTab: Always, AllowShortIfStatementsOnASingleLine: false, ColumnLimit: 999999, ContinuationIndentWidth: 8, SpaceAfterCStyleCast: true, IndentCaseLabels: false, AllowShortBlocksOnASingleLine: false, AllowShortFunctionsOnASingleLine: false}"

I'll apply that once the couple of outstanding branches are merged.

**Comment by springmeyer** [comment]
I'm concerned at the lack of tests. I think that unit tests should be considered the top priority for tippecanoe development. /cc @aaronlidman. @lxbarth 

The tool has gained a high enough level of complexity that running test exports is not a safe way of preventing regression. Also the tool is mature enough that refactoring to make unit testing possible should be a very worthwhile task.

As a motivation for writing unit tests I've set up the infrastructure to start tracking code coverage: https://github.com/mapbox/tippecanoe/pull/138.

A game plan for next steps:

  - [ ] Start on the most basic unit tests possible
   - [ ] Use the https://github.com/philsquared/Catch testing harness
   - [ ] Inherit testing patterns from https://github.com/mapbox/variant and https://github.com/mapbox/protozero
  - [ ] Move [these lines](https://github.com/mapbox/tippecanoe/blob/88d02915d7812da6772b0017d35d32762c107d0d/.travis.yml#L35-L36) below the coverage reporting such that only unit test coverage is what we use to determine coverage.
  - [ ] Start planning refactoring needed to be able to unit test more completely.
   - [ ] Consider creating `libtippecanoe.so` as a by-product of refactoring (separating core logic and algorithms from the command line tool)

**Comment by ericfischer** [comment]
Thanks for pushing on this @springmeyer. I've been increasingly anxious about testing too as I've been working on parallelizing input and will add some round-trip tests for the basic functions and command-line flags right away.

**Comment by ericfischer** [comment]
Finally doing this in https://github.com/mapbox/tippecanoe/pull/157. It is testing complete output because testing stages of processing is still too daunting.

**Comment by springmeyer** [comment]
@ericfischer - great, can you take a look at merging https://github.com/mapbox/tippecanoe/pull/138? That will get coverage reporting working for anything branched off master once merged.

**Comment by ericfischer** [comment]
Sure, will do @springmeyer. I had assumed the "WIP" meant you had changes you still wanted to make to it.

**Comment by springmeyer** [comment]
@ericfischer I proposed you consider some of these ideas https://github.com/mapbox/tippecanoe/issues/46#issuecomment-167001936 inside this branch. But sounds like you've got another branch going so yeah, I just recommend merging this to get coverage then we can ticket and branch separately one what and how to add tests.

**Comment by ericfischer** [comment]
There are many tests now.

**Comment by springmeyer** [comment]
\o/
