### ISSUE TITLE
Metadata center and bounds projection

### ISSUE THREAD

**Issue by merterdemir** [mapbox/tippecanoe#465]
First of all, thank you all for creating such a great tool to generate vector tiles. It is so much easy to create them now. However, I have a question about projection of metadata.

Let's assume I run this command:
` tippecanoe -pC -pt -s EPSG:3857 -L buildings:/data/buildings.geojson -e /data/tiles/bina/`

Even if vector tiles created according to EPSG:3857 projection, auto-generated metadata.json file has coordinates for EPSG:4326 projection as:

```
{
    "name": "/data/tiles/bina/",
    "description": "/data/tiles/bina/",
    "version": "2",
    "minzoom": "0",
    "maxzoom": "14",
    "center": "32.947823,39.968700,14",
    "bounds": "32.933215,39.961533,32.947823,39.969365",
    "type": "overlay",
    "format": "pbf",
    "json": "{\"vector_layers\": [ { \"id\": \"bina\", \"description\": \"\", \"minzoom\": 0, \"maxzoom\": 14, \"fields\": {\"ADA_PARSEL\": \"String\"}}]}"
}
```

As you can see center and bounds are in EPSG:4326 projection. Do we have some solution for that problem like creating metadata according to given projection by user? I looked to the manual, but couldn't see any option for that. I know, if I reproject my data to EPSG:4326, everything will be fine. However, I want to know if there is a solution without reprojecting it from EPSG:3857 to EPSG:4326.

Thanks in advance.

**Comment by ericfischer** [comment]
The center and bounds are in WGS84 because that's what Mapbox GL, which knows nothing about projections, expects to find. (See the [mbtiles spec](https://github.com/mapbox/mbtiles-spec/blob/master/1.2/spec.md#metadata), which specifically calls for the bounds to be in WGS84.)

So there is no standard option to do what you want, but [here is the code that calculates the bounding box and center](https://github.com/mapbox/tippecanoe/blob/master/main.cpp#L2033), so if you want to make a fork of Tippecanoe that reports these in the input projection, you can change `tile2lonlat` to `projection->unproject` here.

**Comment by merterdemir** [comment]
It worked like a charm. Thank you.

I have another question. I was thinking what I should do in order to update my vector tiles when there is a change in one of the buildings for example. Just for one building generating all vector tiles from the beginning is a lot of work  if we have a large data set. Since I cannot update/create one vector tile, I thought getting bbox for that building and creating vector tiles in that bbox again with limit-tiles-to-bbox filter and merge/change with old tiles can help me. What do you think about the logic behind the idea? Or do we have a better solution for updating a part of the tiles?

**Comment by ericfischer** [comment]
The hard part about updating just one tile is that you also need to update that one tile in all the lower zoom levels, which, by the time you get to zoom level 0, means that you are updating the entire world.

The best workflow I can suggest for updates is:

* Use `tile-join` with the `--feature-filter` option to copy your tileset and remove whatever features are now out of date
* Use `tippecanoe` to tile just the new or changed features
* Use `tile-join` again to combine the filtered tileset with the new-and-changed tileset

**Comment by merterdemir** [comment]
Actually the reason why I want to use ```filter-tiles-to-bbox``` is layers' specific zoom levels. For example generally in my projects, most of the layers start from zoom level 6. In addition, building layer can be seen between 12 and 14 zoom levels. It is unnecessary to generate tiles at any zoom lever lower than 11 or 12.

Generating new tileset in that 3 zoom levels with a specific bounding box (which can be taken from the coordinates of updated building) is not hard when we limit this updating with several buildings. However, if we try to generate larger areas like cities, or even a couple of neighborhoods, it will be hard like you mentioned.

Feature filtering is a great tool for removing features from the map/tileset. I couldn't see any method for adding features to tileset. Are you planning to provide support for that in the future? It can solve many problems about updating vector tiles subject.

**Comment by ericfischer** [comment]
You can add features to a tileset by creating a new tileset of the new features with `tippecanoe` and then merging it with the existing tileset with `tile-join`.

There are no current plans for `tippecanoe` to append directly to an existing tileset. It is technically feasible, but would get complicated if there are errors during tiling, which would leave the tileset in an inconsistent, half-updated state.

**Comment by ericfischer** [comment]
If you only want to create one particular tile, you can use a shell filter to select the tiles you want. For example,

    tippecanoe -C 'case $1/$2/$3 in 11/328/791) cat; esac' -o oakland.mbtiles tl_2015_06001_roads.json

creates a tileset that contains only tile 11/328/791 (Oakland, California) even though the TIGER input data extends beyond that tile.

**Comment by merterdemir** [comment]
Thank you for quick, detailed response. It seems like, due to the lack of adding a new feature to existing tilesets option , your solution is the best one.
