### ISSUE TITLE
Overlapping features after decoding mbtiles

### ISSUE THREAD

**Issue by jaskiratr** [mapbox/tippecanoe#467]
Hi,
It seems like `tippecanoe-decode` creates overlapping features. Is that by design for a specific reason or a bug? I'm trying to avoid the overlap to avoid any duplication in the export.
Any thoughts on how to achieve it?

**Original Source**
![screenshot_2](https://user-images.githubusercontent.com/8619877/30623102-a8a3d920-9d83-11e7-8117-8e3f86a8566c.png)

**Decoded Geojson**
![screenshot_3](https://user-images.githubusercontent.com/8619877/30623111-adc5cdbe-9d83-11e7-9f60-8d3fce68a340.png)

Thanks!

**Comment by ericfischer** [comment]
The overlap you are seeing is the default 5-pixel buffer between tiles. You can use the `-b 0` option to `tippecanoe` to turn off the buffer and clip to the exact tile edges.

**Comment by jaskiratr** [comment]
I see. Thanks for pointing it out. Though, I get an error. Am I incorrectly using the command to decode mbtiles to geojson?
```sh
tippecanoe-decode -b 0 file.mbtiles
tippecanoe-decode: invalid option -- 'b'
Usage: tippecanoe-decode [-s projection] [-Z minzoom] [-z maxzoom] [-l layer ...] file.mbtiles [zoom x y]
``` 
Running this in Ubuntu terminal.

**Comment by andrewharvey** [comment]
@jaskiratr `-b` is an option to tippecanoe when creating the mbtiles from geojson, not tippecanoe-decode. See https://github.com/mapbox/tippecanoe#controlling-clipping-to-tile-boundaries

**Comment by jaskiratr** [comment]
@andrewharvey 
Makes sense. Sorry, if I wasn't clear in my first comment.
I'm trying to convert the `.mbtiles` to `.geojson` format and I think the duplication is being created by `tippecanoe-decode`. Is there any way to avoid that?

**Comment by jaskiratr** [comment]
I'll check again with decoding other tile sets to verify if the issue is
with the source .Mbtiles

Thanks

**Comment by ericfischer** [comment]
The duplication is in the tileset that you are decoding. `tippecanoe-decode` is just reporting what it finds in the tiles.

(Would it be useful for `tile-join` to have an option to reduce the buffer size in tiles as it copies them to a new tileset?)

**Comment by jaskiratr** [comment]
That'll be great if tile-join can "repair" the overlap by reducing the buffer size.
Meanwhile, I'll keep digging more to find the root cause of what exactly is causing this.
---

In case you need more info to replicate what I have -  here are the simplified steps that I'm performing

**1. Investigate initial tileset using tileserver-gl**
Attaching the .mbtiles file that I serve using tileserver-gl. **No overlap** or duplicate features are observed at this point.

[buildings.zip](https://github.com/mapbox/tippecanoe/files/1323582/buildings.zip)

**2. Decode using Tippecannoe-decode**
Next, I'm decoding the tiles so that the attributes of the features can be  stored and edited later in MongoDb
`tippecanoe-decode buildings.mbtiles >> buildings_decode.geojson`

**3. Extract features from the decoded geojson**
Then I extract the features from zoom 14 to be stored in Mongodb collection for adding/editing the attributes.
```
# Zoom 14 only for building features
 jq --arg layer "building_export_uniquegeojson" --compact-output '(.features[] | select(.properties | .zoom == 14) | .features[] | select(.properties| .layer == $layer) | .features[])' buildings_decode.geojson > ./layers/buildings.geojson

# Removing any duplicates based on properties.id
jq --compact-output ".features | unique_by (.properties | .id)" ./layers/buildings.geojson > 
./layers/buildings.geojson

```
**4. Storing the features in Mongodb**
Then import the features to mongodb
`mongoimport --db databaseName -c buildings --file "./layers/buildings.geojson"`

In Mongo shell, I found the **duplicate** overlapping features at this step.
```
> db.buildings.find({'properties.id': 'way/366581739'}).count()
2
> db.buildings.find({'properties.id': 'way/366581316'}).count()
4
```
My suspicion is that the duplication is occurring due to either `tippecanoe-decode` or `jq` query for extracting the data.

**Comment by ericfischer** [comment]
If you just want zoom level 14 from `tippecanoe-decode`, by the way, you can do

    tippecanoe-decode -z14 -Z14 buildings-2.mbtiles

The duplicated features are duplicated in your original tileset. For example, look for `way/406083421`. It appears four times, in these four tiles:

```
{ "zoom": 14, "x": 5183, "y": 7341 }
{ "zoom": 14, "x": 5183, "y": 7340 }
{ "zoom": 14, "x": 5184, "y": 7341 }
{ "zoom": 14, "x": 5184, "y": 7340 }
```

because it is in the buffered corner shared by these tiles.

**Comment by jaskiratr** [comment]
@ericfischer for the help. Much appreciated!
I'm not entirely certain why it's happening even with when I generate tiles with `tippecanoe -b 0` option. 
What's throwing me off is that I don't see that grid like duplication due to buffer, when I inspect the tiles in tileserver-gl

I must be missing something. Will continue probing. 

Closing the issue for now, assuming that something is wrong in my data pipeline. 

Btw, I love Tippecanoe. Thanks for it.
