### ISSUE TITLE
CSV Format for tile-join

### ISSUE THREAD

**Issue by asecondwill** [mapbox/tippecanoe#469]
I want to merge some points into my mbtiles file. 

I have a csv of points, all within Cornwall, and a mbtiles file of Cornwall. 

Doing this:

`tile-join -o join.mbtiles -c nodes.csv cornwall.mbtile`

Doesn't seem to merge them in

I must need the CSV file to have the right column headers? What are they? Or is there something else i'm doing wrong? (likely )

**Comment by ericfischer** [comment]
The first column header needs to match the name of the attribute that you are matching on. So for example if you have this GeoJSON, with attribute `id`:

```
{ "type": "Feature", "properties": { "id": 1 }, "geometry": { "type": "Point", "coordinates": [ 0, 0 ] } }
{ "type": "Feature", "properties": { "id": 2 }, "geometry": { "type": "Point", "coordinates": [ 0, 0 ] } }
{ "type": "Feature", "properties": { "id": 3 }, "geometry": { "type": "Point", "coordinates": [ 0, 0 ] } }
{ "type": "Feature", "properties": { "id": 4 }, "geometry": { "type": "Point", "coordinates": [ 0, 0 ] } }
{ "type": "Feature", "properties": { "id": 5 }, "geometry": { "type": "Point", "coordinates": [ 0, 0 ] } }
```

and this CSV, with first column `id`:

```
id,name,square
1,One,1
2,Two,4
3,Three,9
4,Four,16
5,Five,25
```

it will add `name` and `square` attributes to each feature based on the matching `id`. I'll add this to the documentation to clarify.

**Comment by asecondwill** [comment]
Have i missunderstood what the csv join does? I was hoping it would pull in the points in my csv as a layer in the mbtiles?

my csv is for eg
element, lat, long
57212, 50.18, -4.73

so i was hoping to merge those into my cornwall.mbtiles ?

**Comment by ericfischer** [comment]
The tile-join CSV is for joining new attributes to existing geometry, not for adding new geometry.

For creating new geometries from CSV, you may find useful the [csv2geojson script](https://github.com/ericfischer/geotools/blob/master/csv2geojson) I wrote a while back. It looks for columns named `lat` and `lng`, so you'll need to edit it to use `long` instead for your format.

**Comment by asecondwill** [comment]
I can export the data (from the rails app i'm making) as geojson.  It's just I can't get that to appear as a layer either! sorry.  super noob at this.  

````
tippecanoe -o nodes.mbtiles -zg --drop-densest-as-needed nodes.json
tile-join -o both.mbtiles file.mbtiles.mbtiles cornwall.mbtiles
````

Then opening that in maptiler - i can see a "nodes" layer in the legend but no nodes in the map.
![screen shot 2017-09-22 at 19 22 50](https://user-images.githubusercontent.com/156546/30758740-7ef85d4a-9fcb-11e7-9d39-445ff4769289.png)

 
The data I'm trying to demo with is:
[nodes copy.txt](https://github.com/mapbox/tippecanoe/files/1325458/nodes.copy.txt)

**Comment by asecondwill** [comment]
There should be a node just left of center on that map.

**Comment by asecondwill** [comment]
http://geojson.io/  uploading that geojson shows markers where i'm expecting them.

**Comment by ericfischer** [comment]
I don't know anything about `maptiler` and can't recognize the location of your screenshot by sight, but I think the `-zg` option may be being fooled into choosing a too-coarse maxzoom (z6, with a precision of only 500 feet) because there are only 5 points. It doesn't look like it makes a big difference, but if precision is the problem, you might want to try

    tippecanoe -r1 -o nodes.mbtiles nodes.copy.txt

to tile to a higher zoom level, but keeping all the points at every zoom.

**Comment by asecondwill** [comment]
Ok, thanks.  Can you suggest a good way to test a mbtiles file?  I'm trying to view it to check the nodes are added, should be able to do that in mapbox studio right?

**Comment by asecondwill** [comment]
sorry, yes ignore last.  of course i can.  thanks for your help.  hopefully tomorrow i can get this all working.  thanks.

**Comment by asecondwill** [comment]
closing as this was just a help ticket.
