### ISSUE TITLE
Edit the data that's written into the pbf files before it's actually written

### ISSUE THREAD

**Issue by ImCarrot** [mapbox/tippecanoe#478]
Hi, i am working on security of the data inside my `pbf` files. Since the `pbf` are basically `protobuff`, that means anyone can actually `decompile` the `pbf` and access the data inside it, which is a `security breach`. 

I wanted to know if tippecanoe supports some kind of `encryption` process (`RSA` or `AES`) in which it can encrypt the data (using a static key or generate a key and provide the key back for decryption) that's being put into the `pbf` files. So that even if someone get's the `pbf` files. he/she isn't able to make sense out of the `decompiled` data while my android app that's leveraging the `mapbox sdk for android` would be able to `decrypt` the data inside the `pbf` file and hence a map would be displayed.

If there isn't a way that tippecanoe provides a way for encryption, can someone please point me out the section where the data is being written into the pbf files, so that I can understand working and provide encryption of the data. 

any help would be much appreciated.

**Comment by ericfischer** [comment]
No, tiles are not encrypted. The client software has to be able to decode data in order to display it, so using encryption would move the security problem one more level upward. If you are using Mapbox to host your tiles, a client will not be able to download tiles from a private tileset unless it has the correct key.

The [`mvt::encode`](https://github.com/mapbox/tippecanoe/blob/cd47a398fa219d2b85443b07dac1681e27c5c1c7/mvt.cpp#L269) function is the one that is called to encode the tile contents, so you can add whatever other data transformations you want to the string that it returns.

**Comment by ImCarrot** [comment]
@ericfischer thank you for the information, I really appreciate it.  Great! so just to check my understanding, tippecanoe doesn't contain any way of providing encryption to the tiles. That being being said, if I want to encrypt the values inside the resulting `.pbf`, I need to look for a function [mvt::encode](https://github.com/mapbox/tippecanoe/blob/cd47a398fa219d2b85443b07dac1681e27c5c1c7/mvt.cpp#L269) any encrypt the data there. 

And when the client receives the data I need to decrypt the data in my mapbox android SDK.

Did I get anything wrong?

**Comment by ericfischer** [comment]
Yes, that's right. Tippecanoe does not do any encryption, so if you want encrypted tiles, you will have to do it there and then decrypt it in your application.

**Comment by ImCarrot** [comment]
Great thanks for all the help :)

**Comment by Sxriptor** [comment]
> No, tiles are not encrypted. The client software has to be able to decode data in order to display it, so using encryption would move the security problem one more level upward. If you are using Mapbox to host your tiles, a client will not be able to download tiles from a private tileset unless it has the correct key.
> 
> The [`mvt::encode`](https://github.com/mapbox/tippecanoe/blob/cd47a398fa219d2b85443b07dac1681e27c5c1c7/mvt.cpp#L269) function is the one that is called to encode the tile contents, so you can add whatever other data transformations you want to the string that it returns.

Id like to say, finding that key is not diffiicult
