### ISSUE TITLE
Question: How to convert tile-internal points to lat/lng?

### ISSUE THREAD

**Issue by Synesso** [mapbox/tippecanoe#484]
Given geojson for [this way][1]:

    {
      "type": "Feature",
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            153.541298,
            -28.227462
          ],
          [
            153.541032,
            -28.227157
          ]
        ]
      },
      "properties": {
        "type": "residential",
        "class": "street",
        "oneway": "false",
        "structure": "none"
      },
      "tippecanoe": {
        "layer": "road",
        "minzoom": 14
      }
    }

I create a vector tile database:

    cat geojson | tippecanoe -fo biby.mbtiles

The contents of the database:

    zoom_level|tile_column|tile_row|tile_data
            14|      15179|    6852|        �
            14|      15179|    6851|        �

Taking `14,15179,6852` as input I calculate the base point of the tile to be [-28.20761,153.52295][3] using [this method][3].

Inspecting the `tile_data` I see it contains the geometry:

    "geometry":"LINESTRING (212.5625 261, 210.625 258.4375)"

How can I use this linestring value `212.5625 261, 210.625 258.4375`, along with the tile's base point of `-28.20761,153.52295` to derive the original value of `[-28.227462,153.541298],[-28.227157,153.541032]`?

I tried considering these values to be proportional to the tile's x&y along the range 0-255. e.g. the linestring's first lng of 261 modifies `x` from `15179` to `15179 + (261 / 255.0)`. The values this method derives were close, but not correct.

    // scala
    import math._
    val (z, x, y) = (14, 15179, 9531) // y is flipped for zoomlevel 14
    val tileRelativeLat = 212.5625
    val tileRelativeLng = 261.0
    val lat = toDegrees(atan(sinh(Pi * (1.0 - 2.0 * (y.toDouble + (tileRelativeLng / 255.0)) / (1 << z)))))
    val lng = (x.toDouble + tileRelativeLat / 255.0) / (1 << z) * 360.0 - 180.0
    (lat, lng)

It equals [-28.227425560019782,153.54126515107998](https://www.openstreetmap.org/search?query=-28.227425560019782%2C153.54126515107998#map=19/-28.22742/153.54126), which is close, but not quite right.

What is the correct way to map these tile internal values back to lat/lngs?

  [1]: https://www.openstreetmap.org/way/42198912
  [2]: https://www.openstreetmap.org/search?query=-28.207608595327383%2C153.52294921875#map=19/-28.20761/153.52295
  [3]: http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Lon..2Flat._to_tile_numbers_2

**Comment by ericfischer** [comment]
The part that you are missing is that each tile also has an `extent` giving the resolution. It is usually 4096, not 255.

My own implementation of converting tile coordinates back to GeoJSON [is here](https://github.com/mapbox/tippecanoe/blob/master/write_json.cpp#L150).

Another implementation is [in vector-tile-js](https://github.com/mapbox/vector-tile-js/blob/master/lib/vectortilefeature.js#L129), used by [vt2geojson](https://github.com/mapbox/vt2geojson).

**Comment by Synesso** [comment]
Thank you for that info Eric. I've replicated the js implementation and tweaked it here and there, but still can't get accurate results. 

Is the tippecanoe `layer_to_geojson` function exposed? Perhaps via a script?

(Out of interest, my implementation) : ```
  class RichFeature(f: Feature) {
    def points(tk: TileKey, extent: Double = 4096): Seq[Point] = {
      val x0 = tk.x * extent
      val y0 = tk.y * extent
      val size = extent * math.pow(2, tk.z)
      f.getGeometry.getCoordinates.map { c =>
        val y2 = 180 - (c.y + y0) * 360 / size
        Point(
          360 / Pi * atan(exp(y2 * Pi / 180)) - 90,
          (c.x + x0) * 360 / size - 180
        )
      }
    }
  }
```

**Comment by ericfischer** [comment]
The `layer_to_geojson` function is used by `tippecanoe-decode` for decoding vector tiles back to GeoJSON.

What are you using that is producing the WKT format like

```
"geometry":"LINESTRING (212.5625 261, 210.625 258.4375)"
```

? The coordinates in the tiles themselves are integers, so there is already some other transformation being done to the coordinates before getting to this point.

**Comment by Synesso** [comment]
Thanks again!
