### ISSUE TITLE
Default --drop-rate should be 0

### ISSUE THREAD

**Issue by Kilatsat** [mapbox/tippecanoe#491]
As a new user, my first dataset was 7 points and the default drop rate of 2.5 was far too aggressive. The base problem here is that new user expectation is that tippecanoe will not remove data unless advanced options are set, rather than requiring the new user to know which of the advanced options they need to modify in order to get all of their data.

**Comment by ericfischer** [comment]
It was probably a mistake to have the base zoom level for dot-dropping default to 14, but changing it now would break the expectation of too many existing scripts.

The README encourages new users to use

    $ tippecanoe -o out.mbtiles -zg --drop-densest-as-needed in.geojson

to automatically choose a max/base zoom level, which I hope will give reasonable results for your data.

**Comment by Kilatsat** [comment]
Fair point on the existing script infrastructure.

In my specific case, 
$ tippecanoe -o out.mbtiles -zg --drop-densest-as-needed in.geojson
does not solve the issue; I had to use the following instead:
$ tippecanoe -o out.mbtiles -r 0 in.geojson

**Comment by ericfischer** [comment]
I can add a warning message for the case where the base zoom seems to be too high for the data. Can you share a copy of your data so I can see what's going wrong?

**Comment by Kilatsat** [comment]
@ericfischer I'm not sure if we're on the same page on this; what I want is documentation that says: `use these options if you want to keep all of the features of a small dataset` without having to guess and check with the default values that may be relevant to your dataset, or might not. A warning after the operation produces the same situation as verifying the output.

**Comment by ericfischer** [comment]
https://github.com/mapbox/tippecanoe/pull/492 is another attempt to make the documentation clearer. I hope that helps.
