### ISSUE TITLE
Small request: Option to have a semi-quiet mode?

### ISSUE THREAD

**Issue by jliebrand** [mapbox/tippecanoe#494]
At the moment (correct me if I'm wrong) tippecanoe either spits out % progress (and other progress), which for a log file can get extremely verbose; or nothing at all -q

Could there be an option to only spit out the metadata and no progress updates? Such that for example the number of features found etc still get logged, but the log file wouldn't be full of 1%, 2%, 3% etc...?

**Comment by ericfischer** [comment]
Sure, this sounds like a very sensible addition.

**Comment by ericfischer** [comment]
This will be fixed in https://github.com/mapbox/tippecanoe/pull/492

**Comment by jliebrand** [comment]
Thanks!

**Comment by ericfischer** [comment]
Merged
