### ISSUE TITLE
output to same directory, --allow-existing or  tile-join?

### ISSUE THREAD

**Issue by NieneB** [mapbox/tippecanoe#498]
I have different datasets which I want to combine over different zoom levels. So I export my datasets to different GeoJSON files and generate vector tiles of them per zoom range. 
I did this a few months before and every time I run the tippecanoe command I put the output in the same directory. So: 

```
tippecanoe --output-to-directory=/all_tiles --maximum-zoom=8 --minimum-zoom=0 --named-layer=water:/rough_dataset1.geojson

tippecanoe --output-to-directory=/all_tiles --maximum-zoom=10 --minimum-zoom=9 --named-layer=water:/detailed_dataset2.geojson

tippecanoe --output-to-directory=/all_tiles --maximum-zoom=12 --minimum-zoom=11 --named-layer=water:/detailed_dataset3.geojson

```
A few months back this worked and resulted in 1 directory with zoom levels 0 to 12. (And easy styling across all zoom levels.)

Since I updated my tippecanoe (and run it from Docker) it does not work anymore! 
When running the second tippecanoe command, it gives the error `metadata.json: file exists`. When removing this: `rm  all_tiles/metadata.json`  and running my second tippecanoe command, it gives an error the previous zoom levels already exists: `all_tiles/2/2/1.pbf: file exists` 

I tried things with `--allow-existing` and  `--no-tile-stats` but it all does not seem to do anything.. 
Using `--force` just throws away my previous made tiles. 

Reading about `tile-join` made me wonder if I should use that? But since my tile sets just need to be put in the same directory, copying all my tiles to the same directory, with `cp` or `tile-join` just seems to be a bit redundant?

**Comment by ericfischer** [comment]
It has always been the rule that you can't run Tippecanoe with the output going to an `.mbtiles` that already exists, but this wasn't enforced for directory output until 54cbc570f1b0.

If you run Tippecanoe into the same directory or mbtiles multiple times, the tileset metadata in `metadata.json` or the mbtiles `metadata` table will be wrong, because it will only reflect the last run, and if there are any runs that affect the same tile, the last run will overwrite that tile from previous runs.

So yes, please make multiple tilesets and use `tile-join` to merge them into a single output tileset.

**Comment by NieneB** [comment]
Alright. But my runs do not cover the same tiles. They are all in different zoom levels.  Still it throws away my previous made tiles? So maybe I got it wrong but what does the option `--allow-existing` do then?

I do not mind that my metadata.json is wrong because I do not use it for anything. I kind of liked the option of creating all my tiles in the same directory. :)

**Comment by ericfischer** [comment]
OK, you're right, if the `--allow-existing` option works for mbtiles, it should work for directories too. I'll add a test to make sure they behave the same and change the behavior if they don't.

**Comment by NieneB** [comment]
Sounds great! Thank you so much. I look forward to the results.

**Comment by ericfischer** [comment]
This will be fixed in https://github.com/mapbox/tippecanoe/pull/500

**Comment by ericfischer** [comment]
Merged
