### ISSUE TITLE
Layer name includes "geojson"

### ISSUE THREAD

**Issue by stevage** [mapbox/tippecanoe#499]
According to my reading of the documentation, when doing this:

`tippecanoe -o out.mbtiles foo.geojson bar.geojson`

We should have layers called 'foo' and 'bar'

>*name*.json or *name*.geojson: Read the named GeoJSON input file into a layer called *name*.

Instead, we get layers called foogeojson and bargeojson.

**Comment by ericfischer** [comment]
You're right: it trims `.json` but not `.geojson`. I'll fix that.

**Comment by stevage** [comment]
Thanks, that gives me a useful workaround in the meantime :)

**Comment by ericfischer** [comment]
This will be fixed in https://github.com/mapbox/tippecanoe/pull/500

**Comment by ericfischer** [comment]
Merged
