### ISSUE TITLE
Support CSV input

### ISSUE THREAD

**Issue by ericfischer** [mapbox/tippecanoe#502]
Using Mapnik's conventions for column names: https://github.com/mapnik/mapnik/blob/add410e6192b4f4cae671f0dd6bf7cc2c0561a72/plugins/input/csv/csv_utils.cpp#L154-L183

**Comment by mapsam** [comment]
Perhaps include the column names from [GeoCSV](https://giswiki.hsr.ch/GeoCSV) (which [GDAL uses](http://www.gdal.org/drv_csv.html)) as well!

> Starting with GDAL 2.1, accordingly with the GeoCSV specification, the "CoordX" or "Point(X)" type can be used to specify a column with longitude/easting values, "CoordY" or "Point(Y)" for latitude/northing values and "WKT" for geometries encoded in WKT

**Comment by ericfischer** [comment]
Thanks @mapsam. Looks like they are using those in a separate `.csvt` schema file though, not in the CSV header? Their examples use `lon`, `lat`, and `geom` for headers within the `.csv` file.

**Comment by ericfischer** [comment]
Very basic CSV support (only points, no WKT, no detection of numeric attributes): https://github.com/mapbox/tippecanoe/pull/503
