### ISSUE TITLE
Support BBox per feature

### ISSUE THREAD

**Issue by strech345** [mapbox/tippecanoe#504]
Hey, 
features could have a bbox 
see https://geojson.org/geojson-spec.html#bounding-boxes

would it be good to calculate and save it also into the mbtiles per feature?

I export now the centroid as propertie, but it will scale the filesize by 3 times. So maybe its possible to get it as small as the geometry?

**Comment by ericfischer** [comment]
This is something that would have to be addressed in the [vector tile spec](https://github.com/mapbox/vector-tile-spec), which does not have a way to represent bounding boxes currently.

**Comment by strech345** [comment]
Hallo Eric,
thanks, than i will ask there ;-)
