### ISSUE TITLE
Geojson identifier support

### ISSUE THREAD

**Issue by jingsam** [mapbox/tippecanoe#505]
[RFC 7946](https://tools.ietf.org/html/rfc7946) says:
```
If a Feature has a commonly used identifier, that identifier
SHOULD be included as a member of the Feature object with the name
 "id", and the value of this member is either a JSON string or
 number.
```

I get a geojson file converted from a FileGDB:
```
ogr2ogr -f GeoJSON LCA.geojson -preserve_fid DY.gdb LCA
```

Result in  a geojson file like this:
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "id": 1,
      "geometry": {},
     "properties": {}
    }
  ]
}
```

I want to preserve `id` in vector tiles so that I could highlight a whole feature based on the `id`. Could you consider to support this?

**Comment by ericfischer** [comment]
Tippecanoe will already carry the `id` forward into the vector tiles if it is an integer, as in your example. (Introduced in 488dff0efbf)

The [vector tile spec](https://github.com/mapbox/vector-tile-spec) doesn't currently provide a way to represent `id`s that are strings or other types.

**Comment by jingsam** [comment]
Thanks. that would be nice.
