### ISSUE TITLE
Point clustering

### ISSUE THREAD

**Issue by ericfischer** [mapbox/tippecanoe#510]
GL JS clustering uses `cluster: true`, `point_count: 23` to say that 23 points have been clustered together

Heatmaps can weight the intensity based on the `point_count` attribute. https://blog.mapbox.com/introducing-heatmaps-in-mapbox-gl-js-71355ada9e6c

**Comment by ericfischer** [comment]
Working on this in https://github.com/mapbox/tippecanoe/pull/511

cc @millzpaugh @mourner @peterqliu

**Comment by mourner** [comment]
🎉
