### ISSUE TITLE
One extra Feature added to tileset

### ISSUE THREAD

**Issue by nhoover** [mapbox/tippecanoe#513]
I have a FeatureCollection of MultiPolygons, each with some properties. I am using --exclude to exclude some properties.  Tippecanoe always seems to add one extra LineString Feature to the output. One of the excluded properties (sourceFlightPathGeoJson) is a LineString object.

OS: Centos 7.

The enclosed sample has 4 Multipolygons but the tileset shows 5 items. It's always one more. If I include 1 Multipolygon in the input I'll get 2 features in the tileset; if I include 1000, there will be 1001 in the tileset.

Using tippecanoe-decode I can see for most zoom levels, in addition to the expected 4 Polygons, an extra LineString that shouldn't be there.

Files:
[tippecanoe_issue.zip](https://github.com/mapbox/tippecanoe/files/1583401/tippecanoe_issue.zip)

- videoCoverage.json - json source
- videoCoverage.pretty.json - human readable version
- videoCoverage.mbtiles - tippecanoe output
- videoCoverage.mbtiles.json - tippecanoe-decode output
- videoCoverage.log - log file showing tippecanoe options and --version output (27.1)

tippecanoe-issue.png - tileset viewed in mapbox studio

![tippecanoe_issue](https://user-images.githubusercontent.com/5420750/34311160-cac65cb8-e710-11e7-8ba8-9eebd6d55ac8.png)

**Comment by ericfischer** [comment]
Thanks for the report. I'll take a look.

**Comment by ericfischer** [comment]
Tippecanoe is seeing the LineString objects and thinking that they are bare geometries outside of any feature rather than recognizing that they are part of a feature.

I don't think there is any 100% reliable way to avoid this problem, since the `"type": "Feature"` of the parent object might come after the `"properties"`, but I'll add a check to exclude anything that descends from the value associated with a `"properties"` key from being treated as a GeoJSON object of its own.

**Comment by dpieri** [comment]
Thanks for the quick response @ericfischer!

**Comment by ericfischer** [comment]
This should be fixed by https://github.com/mapbox/tippecanoe/pull/514.

As you may know, vector tile properties cannot currently be compound objects, so the LineString property will appear as a stringified representation of the object.

**Comment by nhoover** [comment]
Thanks for the super fast response and fix!

**Comment by ericfischer** [comment]
Fix moved to https://github.com/mapbox/tippecanoe/pull/627, which unifies the divergent GeoJSON parsing loops.
