### ISSUE TITLE
Segmentation fault when tile-join

### ISSUE THREAD

**Issue by denny111** [mapbox/tippecanoe#516]
this works fine
`tippecanoe -e area -z 22 -f -b 20 -aw -n area -l area -pC area.json `
Segmentation fault occurs when tile-join
`tile-join -pC -e out area`

tippecanoe version:tippecanoe v1.27.1
The files are attached.
[area.json.zip](https://github.com/mapbox/tippecanoe/files/1645685/area.json.zip)

**Comment by ericfischer** [comment]
Thanks for the report! I will try it and figure out what is going wrong.

**Comment by ericfischer** [comment]
I removed the code where this crashes in 1acd7717438a3. I will tag a new release now that includes the fixes.

**Comment by ericfischer** [comment]
Please upgrade to https://github.com/mapbox/tippecanoe/releases/tag/1.27.6 and this should be fixed.
