### ISSUE TITLE
Output tileset size is not the same for same input and same command

### ISSUE THREAD

**Issue by pathmapper** [mapbox/tippecanoe#517]
**tippecanoe v1.27.1**

I do have a large GeoJSON file `input.geojson` with around 1.3 million point features.

When using the same command `tippecanoe -o output.mbtiles -r1 -Z11 -z12 input.geojson` on it, the size of `output.mbtiles` is never exactly the same for repeated runs.

The resulting file sizes of `output.mbtiles` for four different runs:

- 91.795.456 Bytes
- 91.688.960 Bytes
- 91.693.056 Bytes
- 91.648.000 Bytes

I would expect that the size of `output.mbtiles` would be the same if the same command is used on the same `input.geojson`.

I'm having no issues with the resulting tilesets, but I am curious why there are these differences. Is there some randomness when converting the GeoJSON coordinates to tile coordinates?

**Comment by ericfischer** [comment]
I see this sometimes too, and I think the difference comes from which of the several tiling threads happens to finish first and write its tiles to the mbtiles first. As far as I know the actual tiles come out identically. Please let me know if you do see any actual variation in the tiles.

**Comment by pathmapper** [comment]
Thanks for the feedback! Sure, will let you know if I see some variation in the tiles.

**Comment by pathmapper** [comment]
Closing it for now, because there are no issues at the moment.
