### ISSUE TITLE
[Feature Request] Prefilter and Postfilter Functionality as Long-running Process

### ISSUE THREAD

**Issue by caneroj1** [mapbox/tippecanoe#520]
Tippecanoe supports `prefilter` and `postfilter` arguments to perform per-tile transformations. It looks like Tippecanoe starts a new process for each tile, though. Is that correct?

Would it be possible to have the ability to instead keep the `prefilter` and `postfilter` functionality running alongside Tippecanoe in their own processes, instead of per tile? Instead of starting up the filter processes with the z, x, and y arguments, I suppose it can just pass those variables on stdin whenever the tile changes. Maybe something like:

```
0 0 0
{ "type": "Feature" .... }
{ "type": "Feature" .... }
{ "type": "Feature" .... }
.
.
.
1 0 0
{ "type": "Feature" .... }
{ "type": "Feature" .... }
{ "type": "Feature" .... }
.
.
.
```

And Tippecanoe can continue to handle the output as it usually does.

**Comment by ericfischer** [comment]
This might be possible, but I think the greatest complication would be that Tippecanoe runs several tiling threads simultaneously, so it would have to multiplex the state of those threads into the single filter stream and then demultiplex the filtered data back to the tiling threads.

Are you finding the filter process startup time to be a performance problem? What is it that works better as a single stream on your end?

**Comment by caneroj1** [comment]
Yeah, when using a filter over a very large data set, the start up time causes the whole process to become prohibitively time consuming. Particularly because I’m working with a pretty complicated set of rules for filtering, so I’ve implemented it another language. I first tried Ruby, but that was too slow to be usable. I compiled a native executable with Haskell, and that was a lot better, but the whole process still takes longer. The single stream was just a suggestion on how to maybe make this work.

**Comment by caneroj1** [comment]
Would it be possible for each filing thread to have their own stream?

**Comment by ericfischer** [comment]
I appreciate the feedback! I don't think many people have made much use of the filtering features yet.

It would probably be possible to have one prefilter stream per thread per zoom level, if that would help.

**Comment by caneroj1** [comment]
Yeah, I definitely think that would help! I guess anything to help offset the start up times would be great.

**Comment by ericfischer** [comment]
OK, I'll think about where and how I could interject another layer of filtering.

**Comment by ericfischer** [comment]
Does your code actually need to know what tile it is working on, by the way? If it doesn't, you'll probably be better off preprocessing the features before Tippecanoe even sees them, interjecting `minzoom` and `maxzoom` tags to control which zooms each feature appears in.

**Comment by caneroj1** [comment]
Right now, just the zoom level. I’m not controlling whether or not a feature is removed, but what subset of that feature’s properties appear at which zoom levels.

**Comment by caneroj1** [comment]
Any updates on this? I could try and put together a PR if it would help.

**Comment by ericfischer** [comment]
If you've got a PR, that would be great. I've been on vacation for a couple of days.

**Comment by caneroj1** [comment]
Is there any way there could be some progress made on this?

The overhead of starting each filter as a separate process is really a gigantic bottleneck. It's not too noticeable at lower zooms, but once the tiling process gets to around 7 or so, it really slows to a crawl.

If it's not possible to change this, could there be another level of filtering injected somewhere else? My use case is to remove properties from features based on zoom level. It's not possible for me to make separate sets of features for each zoom level.

**Comment by ericfischer** [comment]
Sorry, no, I don't think there will be progress on this in the short term.

If you are able to express your filter in terms of an expression, I would recommend using `--feature-filter` to do that. The zoom level is available to expressions as `$zoom`.

Can you go into more detail about why tagging features with zoom levels in the input stream is not possible? Does it make the feature set too big?

**Comment by caneroj1** [comment]
I don't think I could express the filter in terms of the `--feature-filter` option. That remove entire features, correct?

The input features have already been tagged with zoom levels. I need certain properties removed from those features depending on the zoom level, but doing it in terms of different features for each zoom level will indeed make the feature set too big.

For example, there are many features that need labels at higher zoom levels, so each feature needs a name attribute in its properties. But those same features also need to be displayed at slightly lower zoom levels, but labeling isn't relevant there. I want to remove the names to reduce the tile size.

**Comment by ericfischer** [comment]
Hmm, maybe I could have the in-process expression evaluation apply to properties as well as to whole features? So you could say something like

```
{ "name": [ ">", "$zoom", 5 ] }
```

to drop the names at lower zooms?

**Comment by caneroj1** [comment]
Yeah, I think that sounds reasonable. As long as we could use other properties from the feature as part of those filter expressions, too, then that should solve the issue.

**Comment by ericfischer** [comment]
OK, could you try https://github.com/mapbox/tippecanoe/pull/591 and see if it does what you need?

**Comment by caneroj1** [comment]
Sounds good. Testing it out now!

**Comment by caneroj1** [comment]
I checked out the branch in #591 and ran it against a test dataset.

I saw the following error: `Unknown filter ["attribute-filter","name",[">=","$zoom",9]]`

I changed the attribute filter in your example from

`-j '{ "*": [ "attribute-filter", "FULLNAME", [ ">=", "$zoom", 9 ] ] }'`

to

`-j '{ "*": [ "attribute-filter", "name", [ ">=", "$zoom", 9 ] ] }'`

**Comment by caneroj1** [comment]
I was in the directory where I recompiled everything and ran `tippecanoe` instead of `./tippecanoe`, so it ran with an old version.

So it looks like the filter works well so far! I'm experimenting with multiple attribute filters now. Does this support constructs like `any`, `all`, inside the `attribute-filter`?

**Comment by ericfischer** [comment]
Yes, it calls the same evaluation function as all the other filters, so `all` and `any` and any of the other operations should work.

**Comment by caneroj1** [comment]
I think this does pretty much what I need, but I noticed one issue.

I have a density property added to my features that I use in the attribute-filters, but I also want to exclude that property from the final build.

If I run tippecanoe with `--exclude=density`, I receive the following message: `Warning: attribute not found for comparison: ["==","density",0]`.

Is it possible to strip out the excluded properties after the filter runs?

**Comment by ericfischer** [comment]
I think it is important to strip out excluded properties early in the process, instead of leaving it until tiling, because it is often a necessary part of getting the data down to the reasonable size.

Could you strip it out with `{ "*": [ "attribute-filter", "density", [ "!has", "density" ] ] }` at the end of the filter instead?

**Comment by caneroj1** [comment]
I see. That makes sense. Hmm, so I received the same warning after adding that to the filter.

I'm using the following filter JSON:

```
{  
    "roads":[  
        "all",
        [  
            "attribute-filter",
            "name",
            [  
                "any",
                [  
                    "all",
                    [  
                        "in",
                        "class",
                        "highway",
                        "primary"
                    ],
                    [  
                        ">=",
                        "$zoom",
                        12
                    ]
                ],
                [  
                    "all",
                    [  
                        "==",
                        "density",
                        0
                    ],
                    [  
                        "==",
                        "class",
                        "secondary"
                    ],
                    [  
                        ">=",
                        "$zoom",
                        13
                    ]
                ],
                [  
                    "all",
                    [  
                        "!=",
                        "density",
                        0
                    ],
                    [  
                        "==",
                        "class",
                        "secondary"
                    ],
                    [  
                        ">=",
                        "$zoom",
                        12
                    ]
                ],
                [  
                    "all",
                    [  
                        "==",
                        "density",
                        0
                    ],
                    [  
                        "==",
                        "class",
                        "tertiary"
                    ],
                    [  
                        ">=",
                        "$zoom",
                        14
                    ]
                ],
                [  
                    "all",
                    [  
                        "==",
                        "density",
                        1
                    ],
                    [  
                        "==",
                        "class",
                        "tertiary"
                    ],
                    [  
                        ">=",
                        "$zoom",
                        13
                    ]
                ],
                [  
                    "all",
                    [  
                        "==",
                        "density",
                        2
                    ],
                    [  
                        "==",
                        "class",
                        "tertiary"
                    ],
                    [  
                        ">=",
                        "$zoom",
                        12
                    ]
                ]
            ]
        ]
    ],
    "*":[  
        "attribute-filter",
        "density",
        [  
            "!has",
            "density"
        ]
    ]
}
```

I'm only testing with one layer right now called `roads`, and I'm no longer passing the `--exclude` parameter.

**Comment by ericfischer** [comment]
Hmm, interesting; the `roads`-specific filter should run before the `*` all-layers one. Does it work if you put it in the same block as your other `attribute-filter`?

(Or do any of your features *not* have a `density` attribute? That would also cause the warning.)

**Comment by caneroj1** [comment]
Some of my features don't have `density`, but I didn't receive that warning before, actually.

I still see the issue when moving the `density` filter under the `roads` filter block.

**Comment by caneroj1** [comment]
Since they're just warnings, perhaps they can be ignored?

It looks like everything is still correct.

**Comment by ericfischer** [comment]
I'm surprised you didn't get the warning before, but you could avoid the warning by moving everything that checks for `density` inside a `[ "has", "density", … ]` block so that it only runs if the attribute is present. It's just a warning, to try to tell you if your filter has a typo, so you can ignore the warning if it's not helping.

I'm going to go ahead and give this PR a version number and merge it unless there's anything that is still causing problems for you.

**Comment by caneroj1** [comment]
Okay, that sounds good. I could do that.

Sure! Nothing that I'm aware of. Thanks!

**Comment by ericfischer** [comment]
OK, the changes are merged and tagged now. Do you want to leave this open for the possibility of better external filtering in the future, or do you consider the problem to be solved?

**Comment by caneroj1** [comment]
Great!

I think it's probably solved, at least for my use case.
