### ISSUE TITLE
tippecanoe-decode 

### ISSUE THREAD

**Issue by bertrandmd** [mapbox/tippecanoe#524]
Hello, thanks for your incredible tool !

Since I've updated my tippecanoe with `brew upgrade tippecanoe` and get 1.27.6, 
if I do a `tippecanoe-decode data.mbtiles z x y > example.geojson`, I get a non JSON object, commas are missing between layers objects.

I havent this issue with tippecanoe 1.17.1.

thanks for yours replies

**Comment by ericfischer** [comment]
Thanks for the report. Can you give a more specific example? JSONLint seems to think the cases that I've tested are valid JSON.

**Comment by ericfischer** [comment]
Please reopen if you can give details of the problem.

**Comment by ericfischer** [comment]
OK, I do have a way to reproduce this after all.

```
➤ ./tippecanoe -f -o foo.mbtiles tl_2010_06001_tract10.json tl_2015_06001_roads.json
For layer 0, using name "tl_2010_06001_tract10"
For layer 1, using name "tl_2015_06001_roads"
28066 features, 2865801 bytes of geometry, 5490 bytes of separate metadata, 621779 bytes of string pool
  99.9%  14/2640/6347
➤ ./tippecanoe-decode foo.mbtiles 11 328 791 |  json_pp -f json -t json > /dev/null
, or ] expected while parsing array, at character offset 171154 (before " "type": "Feature", ...") at /usr/bin/json_pp5.18 line 45.
```

Seems OK when decoding either an entire mbtiles file or a single PBF, but not a single tile with multiple layers from an mbtiles file.

**Comment by ericfischer** [comment]
Thanks for the report. This will be fixed in https://github.com/mapbox/tippecanoe/pull/541

**Comment by ericfischer** [comment]
Fix is merged
