### ISSUE TITLE
layer id should be file basename when missing name property in geojson.

### ISSUE THREAD

**Issue by jingsam** [mapbox/tippecanoe#526]
I got a geosjon without `name` property. When I use following command:
```
tippecanoe -o 堤防.mbtiles 堤防.geojson --maximum-zoom=g --drop-densest-as-needed --read-parallel --force
```

The result mbtiles generate a layer with `"id": ""`, which should be `"id": "堤防"`

**Comment by ericfischer** [comment]
Thanks. I'll take a look and figure out what is going wrong here.

**Comment by ericfischer** [comment]
This should be fixed in https://github.com/mapbox/tippecanoe/pull/529

**Comment by ericfischer** [comment]
Merged
