### ISSUE TITLE
Meters maybe more friendly for international users

### ISSUE THREAD

**Issue by jingsam** [mapbox/tippecanoe#527]
```
Choosing a maxzoom of -z12 for resolution of about 72 feet within features
```

Maybe meters are friendly for international users. or we chould use `72 feet ( 24 meters )`

**Comment by ericfischer** [comment]
Good point. I'll add the unit conversion.

**Comment by ericfischer** [comment]
This will be fixed in https://github.com/mapbox/tippecanoe/pull/529

**Comment by ericfischer** [comment]
Merged
