### ISSUE TITLE
Map/Reduce of geojson properties for density lost

### ISSUE THREAD

**Issue by ricadete** [mapbox/tippecanoe#528]
Hi Eric, 

awesome work with all these libraries! I tried before to use tile-count, but then we figure out that tippecanoe would do the job for our case. We are already have good progress at our prototype to visualise the data from our customers big data as point density, but I am still stuck with the problem that I mentioned before: 
https://github.com/mapbox/tile-count/issues/49#issuecomment-347273165

So, for our application we will need to use properties for data-drive visualisation (color, size, ...) , therefore is it important to maintain the properties while running the command with the flag "--drop-densest-as-needed", i.e. with high points density, some of the points are lost.

Question:
- there is anyway to aggregate or map/reduce the GeoJson properties at the remaining points?

Example:
pt1 = {
   "type": "Feature",
    "geometry": {...}  
   "properties": [
         "TeamA": true,
         "TeamB":true
   ]
}

pt2 = {
   "type": "Feature",
   "geometry": {...}  
   "properties": {
         "TeamC": true
   }
}

Expected result:
pt3 = {
   "type": "Feature",
   "geometry": {...}  
   "properties": [
         "TeamA": true,
         "TeamB":true
         "TeamC": true
   ]
}

Any suggestion from you would be a huge help. I could try to make a pull request at tippecanoe, but maybe you already know that is going to be difficult or impossible to implement.
Let me know, thanks!

**Comment by ericfischer** [comment]
I have always hesitated to do anything with merged attributes because it is so hard to say how the the composite value should generated from its inputs (sum? product? mean? geometric mean? concatenation?).

If you want to try this yourself, take a look at how the `point_count` attribute is synthesized when clustering (https://github.com/mapbox/tippecanoe/blob/master/tile.cpp#L1589) because it'll need to do something similar.

**Comment by mourner** [comment]
@ericfischer here's the API I came up with for Supercluster to deal with this, could something like this be possible on the native side? https://github.com/mapbox/supercluster/pull/36 Maybe by using Tippecanoe as a library in a custom program that gets compiled?

**Comment by ericfischer** [comment]
A scriptable approach that doesn't require embedding a whole programming language might be to combine the attributes of the merged features into lists, which a `--postfilter` command could then average or concatenate or sum or whatever else it needed to do. If you don't specify a postfilter, the list would just get stringified into a regular attribute.

**Comment by ericfischer** [comment]
The problem with building an array is that at the low zooms, if you are clustering millions of elements  down to a few hundred, you can easily end up with an array of hundreds of thousands of elements to try to summarize.

**Comment by mourner** [comment]
@ericfischer I guess the only way to circumvent that is building clusters bottom-up, where we can reduce from higher zooms to lower ones. This is what Supercluster does.

**Comment by ricadete** [comment]
@mourner and @ericfischer that was my conclusion too. Funny thing is that, before you mentioned the SuperCluster at this thread I have already tried using the SuperCluster on my data per different zoom levels before calling the tippecanoe to build the tiles, I had to give up because I was not having the good results. I guess the most efficient way is to put do this logic at Tippecanoe code. Any plans for this feature at roadmap? i.e. building bottom-up with Map/Reduce on properties.

**Comment by ericfischer** [comment]
(Experimenting with doing a few select operations inline in https://github.com/mapbox/tippecanoe/tree/accumulate-attribute)

**Comment by ericfischer** [comment]
The first ugly part: currently features that are being dropped by zoom level with `-r` are removed before being seen by the prefilter script. But if their attributes matter, they need to be be given the opportunity to pass through the filter instead of vanishing earlier in the process.

**Comment by ericfischer** [comment]
(Still not done, but this is happening in https://github.com/mapbox/tippecanoe/pull/536)

**Comment by ericfischer** [comment]
This is in https://github.com/mapbox/tippecanoe/releases/tag/1.27.8
