### ISSUE TITLE
Arterial roads becoming jagged lines at zoom level 10

### ISSUE THREAD

**Issue by Synesso** [mapbox/tippecanoe#531]
In my map, arterial roads are rendered fine in zoom levels 11+, but are jagged at z=10.

![screen shot 2018-02-13 at 4 32 22 pm](https://user-images.githubusercontent.com/21859/36136399-ff4e7804-10db-11e8-844f-332ae9976a0c.png)

It happens for tiles that are especially dense, but not for others. The example above is from downtown LA - 10/175/408.

Inspecting the tiles with `tippecanoe-decode` I see the roads have been split into distinct, 2-point lines. These line segments seem to run due north/south or east/west and have a loss of precision. 

E.g. [this is three lines from the tile that is meant to represent part of Santa Monica Blvd](https://gist.github.com/anonymous/ab1888d988c6a8cb18a3941f713c3192). 

The `tippecanoe` parameters I use are: `--quiet -P -Z0 -z11`. I am also seeing jagged lines in z=9. But z=11 is fine. In a separate batch of processes I am running the same input data through with `-Z12 -z16` and getting correct results for those zoom levels.

As I suspect tile density is to blame, I am about to re-run with `--drop-densest-as-needed`. But I would appreciate any advice if this is a known problem.

**Comment by ericfischer** [comment]
What does your source data look like? Tippecanoe will not split up a feature into multiple features except when required to split it across multiple tiles. The presence of your `len` attribute also demonstrates that these must have been separate features in the source data.

I would suggest rejoining these sub-features in the original source data. If you can't do that, use `-x len --coalesce` to get rid of the `len` attribute and merge the features that have exactly the same attributes.

**Comment by ericfischer** [comment]
Closing unless you can provide more details of a bug

**Comment by Synesso** [comment]
Thanks Eric. Yes, I've been thinking on it, but haven't had time to collate
info. I may solve it in the process of collecting more info. Either way,
I'll report back.

**Comment by ericfischer** [comment]
Thanks. Please reopen the ticket with more details if you don't find a solution.

**Comment by Synesso** [comment]
The input data includes a large collection of unjoined line segments in random order. So adding `--reorder` as well as `--coalesce` has fixed the problem. Thanks again.

**Comment by ericfischer** [comment]
Great! Glad to hear that `--reorder` worked.
