### ISSUE TITLE
detailing input.mbtiles output1.geojson 

### ISSUE THREAD

**Issue by nielsvhal** [mapbox/tippecanoe#544]
Hi, I created a (little) example shapefile (and converted it in Qgis) to geojson. 
I than tested Tippecanoe in basic form: tippecanoe -o input.mbtiles output1.geojson
The file generated (input.mbtiles) (in Mapbox) is a lot less detailed (than my .shp file and .geojson file). I try to test the detailing in my input.mbtiles. But it seems a lot of detailing is lost when I try to use it in Mapbox. Can you give me some advise how to maintain the detailing of my input files?

**Comment by ericfischer** [comment]
You may be using too low a maxzoom. Try using the `-zg` option to automatically a guess a maxzoom that matches the precision of your input file. If it's still not enough, try increasing `-z` further. Each higher number doubles the precision.

**Comment by ericfischer** [comment]
Please reopen if there are other problems

**Comment by nielsvhal** [comment]
Thanks Eric. (Sorry for the late answer, we got our first daughter in the meantime :-))

**Comment by ericfischer** [comment]
Congratulations!
