### ISSUE TITLE
input geobuf with multiple Data{} messages

### ISSUE THREAD

**Issue by gertcuykens** [mapbox/tippecanoe#547]
Can one input stream (one giant geobuf) containing multiple proto `Data{}` message be supported? Currently only 1 `Data{}` message for each geobuf is supported if i am not mistaken?
Protobuf has message size limitations that can be solved by splitting it up in several `Data{}` messages

**Comment by ericfischer** [comment]
Thanks for the suggestion. Do you have a sample input file of this type that I can test with?

**Comment by ericfischer** [comment]
Can you say a little more about expected behavior vs. what you see now?

Tippecanoe thinks this file has 926539 features. geobuf2json appears to think it has 39 features. Is either of them right? Neither of them?

**Comment by gertcuykens** [comment]
926539 is correct, it contains all roads of Luxembourg split into small road segments. The segments are grouped by 100 segment

**Comment by ericfischer** [comment]
Thanks for verifying. I'm not sure what you're asking for, then, because it sounds like Tippecanoe already does what you want.

**Comment by gertcuykens** [comment]
Can you paste me the Tippecanoe command you are using please, guess I did that part wrong

**Comment by gertcuykens** [comment]
Doh! Let me double check with my colleague :D 
![image](https://user-images.githubusercontent.com/863731/38110453-02b7baae-339c-11e8-80cb-296ac68a4e69.png)

**Comment by gertcuykens** [comment]
I am double checking if the render is correct, need to ask my colleague. Maybe it was the result that wasn't correct. I will come back to you on this. Thank you already for your help and patients.
![image](https://user-images.githubusercontent.com/863731/38111095-03250b70-339e-11e8-9582-4e2eb62493d4.png)
% mbview map.mbtiles 
Listening on http://localhost:3000

**Comment by ericfischer** [comment]
(Specifically you are spending a lot of space on unique IDs for very short road segments.)

**Comment by gertcuykens** [comment]
Closing this until I figure out why I opened this ticket in the first place XD Thank you for your time
![image](https://user-images.githubusercontent.com/863731/38119500-7a5e28ec-33c2-11e8-8ca2-e9e21c860919.png)

**Comment by gertcuykens** [comment]
Maybe one request if you have time is to check if current implementation can distribute calculation for each Data{} message to all cpu cores available, like it does for multiple geobuf files? Could be that it does that already too XD

**Comment by tarikatac** [comment]
It is interesting that tippecanoe is able to read this file correct. But geobuf2json is able to only read the last Data message. Which contains the last 39 features. 

But I guess this wouldn't be considered safe to use. Since this is no where specified.

**Comment by ericfischer** [comment]
Parsing individual Geobuf features is already parallelized: it has to read through the wrapper object serially, but the features are placed in a queue that is then processed in parallel once it fills up.

Tiling is parallel once you get to the high zooms, but the low zooms are difficult to parallelize, so there are still some bottlenecks in that stage that may be improved in the future.

**Comment by gertcuykens** [comment]
Thank you, Ps How does Tippecanoe figure out all the messages? In Go when I unmarshal that file I only get the last Data{} message. The one that contains the remaining features (39)
```
func TestReadGeobuf(t *testing.T) {
	b, err := ioutil.ReadFile("map.geobuf")
	if err != nil {
		t.Fatal(err)
	}
	data := geobuf.Data{}
	err = proto.Unmarshal(b, &data)
	if err != nil {
		log.Fatal(err)
	}
	f := data.DataType
	t.Logf("%v", f)
}
```

**Comment by ericfischer** [comment]
My reader loop is here: https://github.com/mapbox/tippecanoe/blob/6b29966e4ae339881c795d5cd9a9d45d9c34fe6e/geobuf.cpp#L535

Maybe I'm doing it wrong and maybe it only works by accident. (If each `Data` section has its own pool of `keys`, I am probably decoding the attributes wrong in all but the first section, since I'm not getting anything that indicates that a new section has begun.)

**Comment by gertcuykens** [comment]
hmm note that I am a c++ noob but I don't see any code that figures out the message size of `Data{}` messages which as far as I know is required (https://developers.google.com/protocol-buffers/docs/techniques#streaming) So my guess is that it mis interprets the file as one giant single `Data{}` message? Feel free to reopen this if you think it needs investigation :)
