### ISSUE TITLE
why mbtiles tile_column and tile_row are different with pbf format?

### ISSUE THREAD

**Issue by tangjuncheng1986** [mapbox/tippecanoe#558]
tippecanoe -o out.mbtiles --no-feature-limit --no-tile-size-limit --include=name  --minimum-zoom=0  --maximum-zoom=11 -r1  `find ./geojson -type f | grep .json` 

tippecanoe --no-feature-limit --no-tile-size-limit  --minimum-zoom=0  --maximum-zoom=11 -r1  --output-to-directory "./tiles/test" `find ./geojson -type f | grep .json`

The result of the two commands are diffrent.The mbtiles tile_column and tile_row are different with pbf format.
![pbf](https://user-images.githubusercontent.com/19219876/38538513-cf28854a-3cc6-11e8-9690-3cf89e506965.png)

![mbtiles](https://user-images.githubusercontent.com/19219876/38538490-b13575e8-3cc6-11e8-8a48-c6ffa37bd548.png)

**Comment by ericfischer** [comment]
The `mbtiles` tile rows and columns are in the "TMS" scheme ([Tile Map Service Specification](http://wiki.osgeo.org/wiki/Tile_Map_Service_Specification)), which is the same as the "XYZ" web map URL scheme except that the Y axis (`tile_row`) runs the opposite direction.

See https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md#content-1 for the details in the `mbtiles` spec. It was probably a mistake to use TMS in `mbtiles` but it's too late to change now.
