### ISSUE TITLE
What are the units of buffer size option?

### ISSUE THREAD

**Issue by anandthakker** [mapbox/tippecanoe#56]
Lines like [this one](https://github.com/mapbox/tippecanoe/blob/9b34f7e6e35441b79b4f67d9c775feca33187e3d/geometry.cc#L202) make me think that buffer size is in units of 1/256th of the tile width -- @ericfischer is this the case?

**Comment by ericfischer** [comment]
@anandthakker Yes, that's the unit. "Screen pixels," not relative to the tile's internal resolution. Sorry if that's confusing.

**Comment by anandthakker** [comment]
@ericfischer Gotcha, thanks!  It does make sense--I think my confusion only arose because I was immersed rendering issues in mapbox-gl-js, where the "screen" resolution of tiles seems to be 4096 rather than 256.

Closing now.

**Comment by ericfischer** [comment]
Thanks. I'll add a note to the documentation to clarify.

**Comment by anandthakker** [comment]
@ericfischer done! #57

**Comment by jingsam** [comment]
@ericfischer @anandthakker  What does  "screen pixel" mean? As mapbox-gl render a tile to 512*512 size. Why "screen pixel" = 256?

**Comment by ericfischer** [comment]
Bitmap tiles, and vector tiles rendered to bitmaps for Mapbox Studio Classic, were 256 pixels on each side. 512-pixel GL tiles came later.
