### ISSUE TITLE
Brew formula is not up to date

### ISSUE THREAD

**Issue by manassra** [mapbox/tippecanoe#560]
Was trying to use the zoom filters feature (which is a great addition, btw!), but it seems that the brew formula was never updated with the latest changes.

**Comment by ericfischer** [comment]
https://github.com/mapbox/tippecanoe/releases/tag/1.27.13 is tagged now and I think should be available in homebrew soon.

**Comment by ericfischer** [comment]
https://github.com/Homebrew/homebrew-core/pull/26686
