### ISSUE TITLE
--extend-zooms-if-still-dropping should notice --force-feature-limit dropping tiles

### ISSUE THREAD

**Issue by jdeboer-geoplan** [mapbox/tippecanoe#563]
Hi,

I think that the --extend-zooms-if-still-dropping flag doesn't extend if a tile is reduced in size with the --force-feature-limit flag.  It does if the whole zoom level is reduced in size with the --drop-fraction-as-needed flag.
Shouldn't it?
I see that potentially you're creating a whole almost unneeded zoom level because of one very busy tile, in which case perhaps the documentation should be clear that --extend-zooms-if-still-dropping only applies to whole level dropping?

Thanks!

**Comment by ericfischer** [comment]
You're right, `--force-feature-limit` ought to also count for this purpose. I'll try to get this fixed soon.

**Comment by ericfischer** [comment]
Fixed in https://github.com/mapbox/tippecanoe/pull/566

**Comment by jdeboer-geoplan** [comment]
wow, fantastic quick work.
