### ISSUE TITLE
Description for layers pulled from separate files

### ISSUE THREAD

**Issue by stdmn** [mapbox/tippecanoe#572]
Would be great to have the option to include a description for each vector layer when aggregating layers from different files (using -L). This would help tremendously in creating dropdown menus from the metadata file.

**Comment by ericfischer** [comment]
Thanks for the request. This is referring to the `description` in the `vector layers` field of the tileset `metadata`?

**Comment by stdmn** [comment]
Exactly. When tippecanoe outputs the metadata.json, the description is empty: `"{\"vector_layers\": [ { \"id\": \"amenities\", \"description\": \"\", `

**Comment by ericfischer** [comment]
OK, it still needs tests, but this will be in https://github.com/mapbox/tippecanoe/pull/574

**Comment by ericfischer** [comment]
Is there any provision for per-attribute descriptions in TileJSON?

**Comment by ericfischer** [comment]
Oh, in place of the `String`, `Number`, or `Boolean` placeholders that are there now in the `vector_layers`? That seems reasonable, although it's unfortunate that they would have to be separate options instead of tracked as part of the input file.

**Comment by ericfischer** [comment]
OK, I also added an `--attribute-description` option to set the attribute descriptions.
