### ISSUE TITLE
csv_split on null values

### ISSUE THREAD

**Issue by mfisher35** [mapbox/tippecanoe#573]
I think I'm having an issue related to csv_split, namely if one of my rows has a last column null value it looks something like this:
id,A,B,C
1,1,2,3
2,1,2,

and tippecanoe gives me an error that the number of columns is not correct for id=2, I'm forced to put an artificial "NULL" value there (which is a problem for me later because it's supposed to be an integer value, but 0 and -1 are used)

**Comment by ericfischer** [comment]
This will be fixed in https://github.com/mapbox/tippecanoe/pull/574

**Comment by mfisher35** [comment]
Hi Eric, 
   To answer your question, the command I used was: tippecanoe -pk -pf -pt -ps --output-to-directory outfolder in.csv

but it looks like you found the bug in any case!

Thank you!

-Matt
