### ISSUE TITLE
--one-tile argument must be z/x/y

### ISSUE THREAD

**Issue by sameertwans** [mapbox/tippecanoe#578]
-R zoom/x/y or --one-tile=zoom/x/y: Set the minzoom and maxzoom to zoom and produce only the single specified tile at that zoom level.
How to use this feature?
I tried this:
tippecanoe -o mbtilename.mbtiles -f -R zoom/x/y -l layername --drop-densest-as-needed layername.geojson
but this error came up
--one-tile argument must be z/x/y

**Comment by ericfischer** [comment]
Example:

```
tippecanoe -o oakland.mbtiles --one-tile=11/328/791 tl_2015_06001_roads.json
```

produces the single tile 11/328/791.
