### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by ericfischer** [mapbox/tippecanoe#58]
Starting to work on this. Awkward things so far:

 * The global list of attribute names
 * The global bounding box and map center
 * The output files that each zoom is split into for the next stage. Currently there are exactly 4. I guess we should let them multiply until there are as many jobs running at once as we want, and then merge some of the sub-files after that zoom and each subsequent zoom?
 * Which thread owns the progress indicator?
 * What sqlite options are needed to allow simultaneous writes to the mbtiles from multiple threads?

@aaronlidman @MateoV

**Comment by ericfischer** [comment]
Maybe no merging is actually necessary. If we have a max zoom increment of 3, there are 64 temporary files. Zoom level 0, in a single thread, shards into all of those. At zoom level 1, we can have 16 threads, each of which reads 4 of those files in sequence and writes the sub-tiles out into 4 new files.

Rather than have each thread just do 4/64 of the input files, it should probably run through them at the start of the zoom and assign each one to the thread that has been tasked with the least work so far, so that they each have approximately equal work to do.

Should decouple the number of temporary files a little bit from the maximum zoom increment, so that, for instance, there could be 128 temporary files/32 threads instead of 64/16. Set the max increment from floor(temp files / 4) instead of the other way around.

**Comment by ericfischer** [comment]
Working on this in https://github.com/mapbox/tippecanoe/tree/multithread

**Comment by anandthakker** [comment]
@ericfischer Nice!  You may well already know all this stuff, but in case not, two things I learned re: concurrency & sqlite while working on [vt-grid](https://github.com/developmentseed/vt-grid):

 - [WAL mode](https://www.sqlite.org/wal.html) allows readers not to block writers and vice versa.
 - Writers still block other writers, though, so it's necessary to handle [SQLITE_BUSY](https://www.sqlite.org/rescode.html#busy).  I just set the busy timeout to something excessive because of the limitations of the node interface...

**Comment by ericfischer** [comment]
Thanks @anandthakker! I still haven't made it as far as trying any concurrent writes to sqlite3 so this is very useful to know.

**Comment by ericfischer** [comment]
This is working pretty well now and cuts the total running time by 30 to 50 percent or so. For example tiling the Natural Earth `ne_10m_admin_0_countries` to z8 goes from 56 seconds to 26.

The big limit is that with many data sets it only helps at the high zooms. Even in the best case as currently implemented, z0 can only use 1 thread and z1 4 threads, before getting up to 16 at z2. But for data that only covers a small area instead of the whole world, like a TIGER county, it doesn't get up to 16 threads until z11 or so. One possibility might be to generate z1-3 from z0 and do those all at once instead of in sequence, at the cost of more complexity.

Parallelization also doesn't help at all with parsing GeoJSON, which is still slow. It might be possible to hand projection and re-encoding off to a worker thread so that only the parsing itself has to be linear. (Or encourage multiple input files, which could theoretically be parsed in parallel.)

**Comment by ericfischer** [comment]
Multithreading is in master as of 3fbd0d654695a01ec via https://github.com/mapbox/tippecanoe/pull/100.

I'm not going to tag a new release until I'm sure the polygons are going the right direction.
