### ISSUE TITLE
Missing polygons

### ISSUE THREAD

**Issue by Plantain** [mapbox/tippecanoe#580]
Hi,
I have a GeoJSON file that renders on tools such as Mapshaper.org as follows:
<img width="786" alt="screen shot 2018-06-01 at 3 35 23 pm" src="https://user-images.githubusercontent.com/319895/40843503-740a1bba-65b1-11e8-9b3d-9774727cf9a3.png">
Run through tippecanoe, half the content seems to be lost, as shown by mbview.
<img width="860" alt="screen shot 2018-06-01 at 3 36 09 pm" src="https://user-images.githubusercontent.com/319895/40843535-9782eb30-65b1-11e8-8ff0-a2f315bf93d8.png">
Same behaviour with -zg or with manually specified levels.

Attached mbtiles file, and GeoJSON data.
[mbtiles+json.zip](https://github.com/mapbox/tippecanoe/files/2062867/mbtiles.json.zip)

**Comment by ericfischer** [comment]
Thanks. I'll download it and take a look.

**Comment by ericfischer** [comment]
What you get by directly uploading the GeoJSON to Mapbox looks a lot like the Tippecanoe output, so Tippecanoe and Mapnik must be interpreting it similarly.

![screen shot 2018-06-01 at 10 30 42 am](https://user-images.githubusercontent.com/1951835/40854679-76d864a2-65d2-11e8-83b2-356377c5d6d3.png)

Still trying to figure out what Mapshaper is doing differently.

**Comment by ericfischer** [comment]
The discrepancy is introduced by the use of Wagyu to clean the polygon geometry. With polygon cleaning turned off, the geometries are strange, but there are a lot more of them.

![screen shot 2018-06-01 at 10 47 11 am](https://user-images.githubusercontent.com/1951835/40855372-b522c9f8-65d4-11e8-85c0-5210041a3488.png)

**Comment by Plantain** [comment]
I have seen this behaviour from files generated with a number of different tools, so I think there might be some merit in adding the flags you mention. This particular file was generated by geojsoncontour, I will open an issue and investigate with them too.

**Comment by ericfischer** [comment]
https://github.com/mapbox/tippecanoe/pull/581 adds the `--use-source-polygon-winding` and `--reverse-source-polygon-winding` flags.
