### ISSUE TITLE
Error: Unimplemented Type: 3

### ISSUE THREAD

**Issue by stdmn** [mapbox/tippecanoe#582]
I'm having problems with the new build of Tippecanoe. When trying to open Mapbox tiles, I'm getting the following error: 

<img width="415" alt="screen shot 2018-06-02 at 11 57 22 am" src="https://user-images.githubusercontent.com/17128916/40878255-4d51cd50-665c-11e8-8109-93cb0fd95eeb.png">

From blob:
`        skip: function(t) {
            var e = 7 & t;
            if (e === aa.Varint)
                for (; this.buf[this.pos++] > 127; )
                    ;
            else if (e === aa.Bytes)
                this.pos = this.readVarint() + this.pos;
            else if (e === aa.Fixed32)
                this.pos += 4;
            else {
                if (e !== aa.Fixed64)
                    throw new Error("Unimplemented type: " + e);
                this.pos += 8;
            }
        },
      `

...but only at higher zoom levels (13+). On Mapbox tiles created with older versions of Tippecanoe I'm not having any problems. 

Self-contained version of JS Fiddle: [https://jsfiddle.net/jncmz6qy/](https://jsfiddle.net/jncmz6qy/1/)

I've tried with different settings on the Tippecanoe output. The current command line code is: `tippecanoe -pk -pf -pt -ps --output-to-directory /path_to_directory/test /path_to_input/transit.geojson
`

This worked as of last week without any problems.

**Comment by stdmn** [comment]
Sorry. You are correct. I have the tiles streaming from an Amazon S3 instance and for some reason S3 was only applying content-encoding metadata to some tiles. Closing issue.

**Comment by symonsoft** [comment]
@stdmn @andrewharvey 
What is the solution of this problem? Changing S3 options when creating shared S3 link to tile?

**Comment by roblabs** [comment]
The Mapbox Mobile SDK's do not report an error when `.pbf` are gzipped.  Which makes debugging _why a set of tile data doesn't render_ somewhat challenging.

On mobile, if you have `.pbf` that you are adding as`{z}/{x}/{y}.pbf` tiles be sure that the call to `tippecanoe` includes the `--no-tile-compression` format option (see [Setting or disabling tile size limits](https://github.com/mapbox/tippecanoe#setting-or-disabling-tile-size-limits))

For anyone debugging the _validity_ of `.pbf` that was already processed for you and you want to know its compression state:

* port you Mobile style to a web page and check for error code:  `Error: Unimplemented Type: 3` in the browser.   [Example](https://github.com/roblabs/openmaptiles-ios-demo/blob/master/OSM2VectorTiles/styles/geography-class-localhost-5000.json).
* As well, you can simply change the name to `0/0/0.pbf.gzip` and see if the file gets larger.  Then your tile at zoom 0 should be rendered.

![image](https://user-images.githubusercontent.com/118112/107136338-fe9d7280-68b6-11eb-8546-16dd8b8c30e3.png)

**Comment by Jesperpaulsen** [comment]
@stdmn could you elaborate on what kind of metadata that needs to be added?

**Comment by torsol** [comment]
@Jesperpaulsen Perhaps its with regards to adding something like: `headers={"Content-Encoding": "gzip"}`?
