### ISSUE TITLE
Save tippecanoe version in metadata table?

### ISSUE THREAD

**Issue by mapsam** [mapbox/tippecanoe#586]
It'd be nice to have access to the version of tippecanoe used to create an MBTiles file, which could simplify debugging. Could this be saved in the `json` row of the metadata table? Would that invalidate the MBTiles specification?

cc @ericfischer @springmeyer

**Comment by ericfischer** [comment]
Good idea. I should have done that long ago. "The `metadata` table MAY contain additional rows… for other purposes" so I don't think there is any mbtiles spec issue.

**Comment by ericfischer** [comment]
Oh, sorry, in the `json` row? The spec doesn't say that it can be there but it also doesn't say that it can't, so I think we're probably safe adding it there.

**Comment by mapsam** [comment]
@ericfischer oh nice, didn't realize we could add new rows - I think adding an additional row to `metadata` would be best (rather than using `json`), and least intrusive to other tooling!
