### ISSUE TITLE
Wrong tiles indexes

### ISSUE THREAD

**Issue by symonsoft** [mapbox/tippecanoe#589]
I executed next command line (geojson attached):

    tippecanoe -f -e /tiles_folder -z 20 NY.geojson

But, it seems that tile indexes (numerical filenames) were generated improperly:

For exemple generated for zoom level 14 is `14/4822/6161.pbf` although it should be `14/4822/10221.pbf` (or near that number).

GeoJSON file [NY.geojson.zip](https://github.com/mapbox/tippecanoe/files/2087996/NY.geojson.zip):

    {
    "type": "FeatureCollection",
    "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                                                                                    
    "features": [
    { "type": "Feature", "properties": { "FID": 0 }, "geometry": { "type": "Polygon", "coordinates": [ [ [ -74.044402241706848, 40.689648327187975 ], [ -74.044402241706848, 40.689648327187975 ], [ -74.043962359428406, 40.689148012792003 ], [ -74.043962359428406, 40.689148012792003 ], [ -74.044568538665771, 40.688863279344773 ], [ -74.044568538665771, 40.688863279344773 ], [ -74.044970870018005, 40.689326987479006 ], [ -74.044970870018005, 40.689326987479006 ], [ -74.044402241706848, 40.689648327187975 ] ] ] } }
    ]
    }

**Comment by KingElimy** [comment]
how do you confirm this is wrong index?
here in tippecanoe,the index has been transferred to tms index system, and you can refer to this [Addressing tiles: same tile bounds with different indexes](http://www.maptiler.org/google-maps-coordinates-tile-bounds-projection/)
:)

**Comment by symonsoft** [comment]
@KingElimy here the projection for google tiles http://www.maptiler.org/google-maps-coordinates-tile-bounds-projection/

**Comment by symonsoft** [comment]
@KingElimy I see now. That tippicanoe gives tiles in Google projection. But how can I switch it to TMS scheme?

**Comment by symonsoft** [comment]
Is it worth to request a feature like switching to TMS indexes?

**Comment by ericfischer** [comment]
Sorry, I don't want to add the additional complexity of supporting TMS directories within Tippecanoe. Please use a script to rename the tiles, or use https://github.com/mapbox/mbutil

```
mb-util --scheme=tms --image_format=pbf xyz.mbtiles tms.dir
```

to convert an mbtiles tileset to a directory of files in the TMS scheme.
