### ISSUE TITLE
Installing Tippecanoe with no access to hosted linux machine

### ISSUE THREAD

**Issue by adbedada** [mapbox/tippecanoe#590]
I'm attempting to clone and install Tippecanoe on shared Linux cluster with restricted access to /usr/local/bin and the only option I have is to have it installed on home directory. Do you have any suggestion on how I might be able to use a --prefix option to redirect and compile the package? 

```
g++ -L/usr/local/lib -g -Wall -Wshadow -Wsign-compare -Wextra -Wunreachable-code -Wuninitialized -Wshadow -O3 -DNDEBUG -std=c++11 -o tippecanoe geojson.o jsonpull/jsonpull.o tile.o pool.o mbtiles.o geometry.o projection.o memfile.o mvt.o serial.o main.o text.o dirtiles.o plugin.o read_json.o write_json.o geobuf.o evaluator.o geocsv.o csv.o -lm -lz -lsqlite3 -lpthread
mkdir -p /usr/local/bin
mkdir -p /usr/local/share/man/man1/
cp tippecanoe /usr/local/bin/tippecanoe
cp: cannot create regular file `/usr/local/bin/tippecanoe’: Permission denied
make: * [install] Error 1 
```

FYI, I installed Tippecanoe on Ubuntu on a pc and there was no error.

**Comment by ericfischer** [comment]
If you do `PREFIX=/home/bin make install` it should install to that prefix instead of the default `/usr/local`.

**Comment by adbedada** [comment]
awsome @ericfisher! It worked.
