### ISSUE TITLE
`Smaller` branch seg fault

### ISSUE THREAD

**Issue by aaronlidman** [mapbox/tippecanoe#61]
@ericfischer Here's the backtrace we talked about earlier:

Regular output:
```
(gdb) run -o quarter22-xad.vtiles -z15 -Z15 -ps -pc -pf -pk xadfeatures.json 
Starting program: /usr/local/bin/tippecanoe -o quarter22-xad.vtiles -z15 -Z15 -ps -pc -pf -pk xadfeatures.json
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
using layer 0 name xadfeatures
Sorting 93850449 features
Sorting part 43 of 43
93850449 features, 4814302098 bytes of geometry, 4239675573 bytes of metadata, 1728094639 bytes of string pool
  99.9%  15/32767/16383  

Program received signal SIGSEGV, Segmentation fault.
```

Backtrace:
```
#0  mbtiles_write_metadata (outdb=outdb@entry=0x6282d8, 
    fname=fname@entry=0x7fffffffe8b7 "quarter22-xad.vtiles", layername=layername@entry=0x7fffffffde78, 
    minzoom=minzoom@entry=15, maxzoom=maxzoom@entry=15, minlat=-85.05112321974741, minlon=-180, 
    maxlat=85.05112321974741, maxlon=179.99999991618097, midlat=39.567585783079423, 
    midlon=3.2135009765625, file_keys=file_keys@entry=0x7fffffffde88, nlayers=nlayers@entry=1)
    at mbtiles.c:194
#1  0x0000000000406aa9 in read_json (argc=<optimized out>, argv=<optimized out>, 
    fname=fname@entry=0x7fffffffe8b7 "quarter22-xad.vtiles", layername=<optimized out>, 
    layername@entry=0x0, maxzoom=maxzoom@entry=15, minzoom=minzoom@entry=15, 
    outdb=outdb@entry=0x6282d8, exclude=exclude@entry=0x7fffffffe3c0, 
    include=include@entry=0x7fffffffe3e0, exclude_all=exclude_all@entry=0, 
    droprate=droprate@entry=2.5, buffer=buffer@entry=5, tmpdir=tmpdir@entry=0x421ead "/tmp", 
    gamma=gamma@entry=0, prevent=prevent@entry=0x7fffffffe400 "") at geojson.c:1077
#2  0x0000000000404025 in main (argc=10, argv=0x7fffffffe628) at geojson.c:1227
```

Let me know if there's anything else I can do to help, I can rerun this easily.

**Comment by ericfischer** [comment]
Thanks @aaronlidman. It looks like maybe I let a reference from the string pool creep into the global table of field names that gets written out into the metadata table of the mbtiles, and the reference becomes invalid when I close the file. Although in that case, why doesn't it fail every time?

**Comment by ericfischer** [comment]
Hmm. Haven't found a cause yet with MALLOC_CHECK_ on Linux or MallocCheckHeapStart on MacOS.

The line number in the stack trace is surprising, because pv must be a valid pointer if pv->s was valid just above, and pv->type is scalar so there's no additional dereferencing there.

**Comment by ericfischer** [comment]
I wonder how many unique OSM property keys there are, because at the point that it's crashing, it's essentially trying to make a string that lists all of them. I was just able to make a feature with 200,000 attributes without crashing, but it took a long time.

**Comment by ericfischer** [comment]
Not sure if it's the same bug, but reproducible crasher from this fuzz input: https://gist.github.com/ericfischer/b1b4a79615e9071f0f02

**Comment by ericfischer** [comment]
Fixed my crash in https://github.com/mapbox/tippecanoe/commit/59faead7fa8d9190faea8b62f6faa12c71e35cbb. Hope it fixes yours too. (This is all in master now, so forget about the "smaller" branch.)

It was a stupid sign-extension bug with signed chars. The attempt to turn control characters into \u escapes was actually affecting any fields with non-ASCII names, and they were getting turned into huge negative numbers instead of only four digits so the buffer was overflowing.

**Comment by aaronlidman** [comment]
Just ran a test a quick test with 10M features. Worked great, thanks!
