### ISSUE TITLE
Automatically generate unique feature ID

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/tippecanoe#614]
# Feature Request

Add a Tippecanoe option to automatically generate an integer unique feature id. `--generate-id`.

# Ideal scenario

* If a geojson source contains an `id` value, use the specified `id` value in the tiles generated in Tippecanoe
* If a geojson source does not contain an `id` value, automatically generate one by default.  
* Expose a Tippecanoe option to disable automatic feature `id` generation if it doesn't exist
* Expose an option to `promote` a property value from a feature to an `id` value, just like `geojson-vt` allows https://github.com/mapbox/geojson-vt/pull/109 cc/ @asheemmamoowala 

# Use case

FeatureStates in Mapbox GL require feature `id` values to function.  Currently, Tippecanoe will not generate feature ID values for a dataset, a user must create feature `id` values in their geojson data source before passing to Tippecanoe.

cc/ @ericfischer 

Reference:   https://github.com/mapbox/mapbox-gl-js/pull/6974

**Comment by ericfischer** [comment]
Thanks for the idea. Thinking out loud, there are basically two ways that this could go:

* Assign IDs sequentially
* Assign IDs by a hash of the feature data

Sequential assignment is probably preferable (and would generate smaller tiles), but has the complication that when reading in parallel with `-P` there are discontinuities between the sequence numbers being assigned by each reader thread, so the IDs would not be stable from one run to the next if assigned at that time. It is also sensitive to the input ordering in general, so if features are inserted or deleted in the source data, the generated IDs will be completely different when the edited data set is retiled.

Hash assignment is stable both across runs and across feature insertions and deletions, but has the risk of assigning the same ID to multiple features that happen to hash the same, and the certainty of assigning the same ID to duplicated features within the input.

They both have the problem of how to avoid accidentally reusing an ID that was also assigned manually.

So I think this will have to be an additional stage in between parsing and tiling, after the complete set of manually-assigned IDs is known, and the complete feature sequence is known. I'm still not sure whether it is better to hash (with increments when duplicate hashes are detected) or to use an incrementing counter.

**Comment by ericfischer** [comment]
https://github.com/mapbox/tippecanoe/pull/615 adds the most basic `--generate-ids` option (using the input feature sequence for the ID), with the disclaimer that the IDs are not stable and that their format may change in the future.

**Comment by ericfischer** [comment]
Sorry, I only just tagged the release (https://github.com/mapbox/tippecanoe/releases/tag/1.30.3). It looks like https://github.com/Homebrew/homebrew-core/blob/master/Formula/tippecanoe.rb gets updated by a bot for new releases, but I'm not sure how long that cycle takes.

**Comment by ericfischer** [comment]
Looks like this is in the homebrew version now.
