### ISSUE TITLE
Create a /help guide for common tiling scenarios using Tippecanoe

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/tippecanoe#617]
# Background

Currently, there is a basic guide on Mapbox.com showing how to use Tippecanoe to tile large datasets https://www.mapbox.com/help/large-data-tippecanoe/.  There are no other `use case` based guides I am aware of.  Tippecanoe is a very powerful, but complex tool. It can be difficult to start using it for a specific use case without a background in how vector tiles work and how data are represented in vector tiles.

# Proposal

Create a `use case` guide for tiling data using Tippecanoe with suggested `recipes` for that use case.  The top use cases I've seen include:

1. Make a polygon or linestring geometry vector tile that's visible at zoom 0 for a data visualization
    * Explain what the options below do and why to use them
    * `tippecanoe -o  out.mbtiles -P --coalesce-smallest-as-needed --detect-shared-borders --extend-zooms-if-still-dropping -z12 in.geojson`
2. Make a dense point map for a data visualization
    * `tippecanoe -o out.mbtiles -r0 --drop-densest-as-needed --extend-zooms-if-still-dropping -z12 in.geojson`
3. Make a clustered point map with an accumulated property attribute.
    * Let's cluster points by a constant radius, but for a very large dataset
    * `tippecanoe -o out.mbtiles -r0 --cluster-distance=5 --extend-zooms-if-still-dropping --accumulate-attribute=my-attribute:sum|max|min|avg -z12 in.geojson`
4. Show different levels of detail in a tileset for automatic `drilldown` from country -> state -> county -> etc.
    * Add the `geojson parameter` to your input geojson dataset, specifing the min and max zoom for each feature as a top-level feature object `tippecanoe: {minzoom: 6, maxzoom: 7}`
    * Cut tiles from the input geojson file and Tippecanoe will automatically generate data by zoom level

cc/ @allanwalkerit @cmtoomey @ericfischer @samgehret @brsbl @HeyStenson

**Comment by kalimar** [comment]
A couple more recipes:

Generate a tileset from multiple `geojson` sources as one layer (using tippecanoe  defaults):
`cat *.geojson | tippecanoe -o single-layer.mbtiles -zg --drop-densest-as-needed`

Generate a tileset from multiple `geojson` sources with a layer for each file. Each layer will use the name of the relevant `geojson` file:
`tippecanoe -o out.mbtiles -zg --drop-densest-as-needed *.geojson`

**Comment by ericfischer** [comment]
Trying to write a good clustering example is making me realize that maxzoom guessing should know about clustering. https://github.com/mapbox/tippecanoe/issues/621

**Comment by ericfischer** [comment]
I added a cookbook section for these tasks in https://github.com/mapbox/tippecanoe/pull/623. Please comment if you think things could be clearer or if you have other examples to add.
