### ISSUE TITLE
tile-join: add option to remove all attributes

### ISSUE THREAD

**Issue by pathmapper** [mapbox/tippecanoe#625]
@ericfischer would you mind adding a tile-join option to remove all attributes?

If I got it right, currently there is a need to use `-x` key for every single key to remove them all.

**Comment by ericfischer** [comment]
Oh, sure, that should be easy to add. Thanks for the suggestion.

**Comment by ericfischer** [comment]
This will be in https://github.com/mapbox/tippecanoe/pull/626

**Comment by ericfischer** [comment]
Merged

**Comment by pathmapper** [comment]
Great, thanks a lot!
