### ISSUE TITLE
Skip zoom levels if there is a minzoom

### ISSUE THREAD

**Issue by ericfischer** [mapbox/tippecanoe#63]
One of the bottlenecks in tippecanoe is that with top-down tiling, if there is a minzoom, it will spend a bunch of time running through the zooms below the minzoom, splitting features into sub-tiles, even though those levels don't make it into the output.

One optimization would be to skip some zooms. The bottleneck is the maximum plausible number of open files (looks like normally 1024 on Linux, 4864 on MacOS). Going one zoom at a time takes 8 files (4 reading, 4 writing). Skipping a zoom would take 2 * 4 * 4 = 32. Skipping two zooms would take 2 * 8 * 8 = 128. Skipping three would be 2 * 16 * 16 = 512, so that's about as far as is probably reasonable.

It seems like it could cut a lot off the running time of single-zoom tiling. If we need just z15, it would just do 0, 4, 8, 12, and 15, instead of all of 0 through 15.  Need to figure out if it's worth the additional complexity.

cc @aaronlidman @MateoV @morganherlocker

**Comment by ericfischer** [comment]
Working on this in https://github.com/mapbox/tippecanoe/tree/skip. Superficially seems to work, but I need to figure out if it is correct and if it is worthwhile. (Los Angeles county TIGER roads take 24 seconds with or without the change.)

**Comment by ericfischer** [comment]
A maximum increment of 3 levels (skipping 2) seems to be the performance sweet spot (<17 seconds for Los Angeles TIGER at z15). Beyond that, the overhead of making all those temporary files seems to outweigh the advantages of not having to reparse geometries.

**Comment by MateoV** [comment]
@ericfischer just another data point for you. I ran this for the Netherlands which I've been using to test Tilemaker.

w/o skipping: 22:54
with skipping: 21:14

**Comment by ericfischer** [comment]
This has been fixed for quite a while
