### ISSUE TITLE
Tile-join can make a 'name' value in output file metadata table which exceeds 255 characters, a limit in the current mapbox upload api

### ISSUE THREAD

**Issue by euxneks** [mapbox/tippecanoe#632]
`tile-join` can potentially make a `name` metadata value which violates a constraint in Mapbox upload api.
In my case, I had enough mbtiles files to join together, `tile-join` made a resulting mbtiles file which, in its metadata, has a `'name'` value which exceeds 255 characters violating some constraint in the Mapbox API (I don't know where - it's not documented as far as I can tell).

my case:
```bash
$ ls good_mbtiles
ab_lake_polygon.mbtiles   ab_stream_lines.mbtiles  can_river_lines.mbtiles   fwa_lakes_islands_polygon.mbtiles  fwa_stream_lines.mbtiles            north_america_river_lines.mbtiles
ab_river_polygon.mbtiles  can_lakes.mbtiles        fwa_centroids_sp.mbtiles  fwa_river_polygon.mbtiles          north_america_lake_polygon.mbtiles
$ tile-join -o joined.mbtiles good_mbtiles/*.mbtiles
```

Resulted for me in an `mbtiles` file with the `'name'` value in the `'metadata'` table exceeding 255 characters:

```bash
sqlite3 joined.mbtiles
sqlite> select value from metadata where name='name';
mbtiles/north_america_river_lines.mbtiles + mbtiles/north_america_lake_polygon.mbtiles + mbtiles/can_river_lines.mbtiles + mbtiles/can_lakes.mbtiles + mbtiles/riversfwa.mbtiles + mbtiles/fwa_centroids.mbtiles + mbtiles/fwa_stream_lines.mbtiles + mbtiles/ab_river_polygon.mbtiles + mbtiles/ab_lake_polygon.mbtiles + mbtiles/ab_stream_lines.mbtiles + fwa_lakes_islands_poly.mbtiles
```
which violates some constraint in the mapbox upload api (don't ask me where, the error message simply stated `name must be a string of 255 characters or less`)

I suspect what is happening is tile-join is simply doing a very simple concatenation of the original mbtiles `name` value in each of the mbtiles metadata.

This can be remedied easily by giving a warning and truncate the name; or error and an option on the CLI to change the 'name' metadata.

In case someone encounters this same issue, I am able to solve this myself by changing the `name` metadata into something smaller and then uploading:

```bash
sqlite3 output.mbtiles
sqlite> update metadata set value='output.mbtiles' where name='name';
```

**Comment by ericfischer** [comment]
Thanks. I'll add a check to make sure it doesn't make the `name` too long.

**Comment by ericfischer** [comment]
Should be fixed in https://github.com/mapbox/tippecanoe/pull/633

**Comment by ericfischer** [comment]
Merged
