### ISSUE TITLE
Feature Request: Option for no value limit on tilestats metadata

### ISSUE THREAD

**Issue by stdmn** [mapbox/tippecanoe#637]
@ericfischer Currently, the metadata output for a tileset limits the number of unique values at 100. It would be great to have an option to not limit this at all, or to set a specific limit (ie, 1000). This helps tremendously with things like categorically coloring tileset values based on the metadata, etc.

I imagine it has something to do with this repo: [https://github.com/mapbox/mapbox-geostats](https://github.com/mapbox/mapbox-geostats) which seems to limit to 100 unique values.

**Comment by ericfischer** [comment]
Thanks for the suggestion. Yes, Tippecanoe limits the number of values in the tilestats because it is trying to duplicate the behavior of `mapbox-geostats`.

Can you give more details about how you are using the tilestats information for styling? Is this in Mapbox Studio or a different tool?

**Comment by stdmn** [comment]
I have a script that takes the values of a given attribute and then creates a color mapping for each value to include in the styling of a polygon algorithmically. Code here:

``` export function PolygonStyle(metadata) {

        var paint
        const attr = metadata.tilestats.layers["0"].attributes["0"]
    
        const qualColors = [LIST OF COLORS]
        var colorObject = []
        for (var g in attr.values) {
            colorObject.push(attr.values[g])
            colorObject.push(qualColors[g])
        }
        colorObject.push('#cccccc')
    
        paint = {
            "fill-color": 
                ['match',
                ['get', data.sizeParam],
                ...colorObject
            ],
        }
        return paint
    }```

**Comment by stdmn** [comment]
I also forgot to mention that I use the values to populate dropdown menus as well (for filtering items on a map).

**Comment by ericfischer** [comment]
OK, https://github.com/mapbox/tippecanoe/pull/639 should let you change this limit with `--tile-stats-values-limit`.

**Comment by stdmn** [comment]
Great! Thanks for the quick response.

**Comment by ericfischer** [comment]
OK, tagged a new release: https://github.com/mapbox/tippecanoe/releases/tag/1.31.5

**Comment by stdmn** [comment]
Thanks!
