### ISSUE TITLE
Feature Request: Minify attribute names

### ISSUE THREAD

**Issue by stdmn** [mapbox/tippecanoe#638]
@ericfischer It would be great to have a simple way of minifying attribute names and then including their full names in the metadata file. 

The general idea would be similar to the -k, --keys attribute of this repo: [https://github.com/TNOCS/minify-geojson#readme](https://github.com/TNOCS/minify-geojson#readme) which turns attribute names like "SQFOOT" to "S" and then provides a map to map them back to their original values.

**Comment by ericfischer** [comment]
I don't think this will ultimately save very much space in the tiles because each attribute name is only stored once per tile. Are you seeing significant savings from shorter names?

**Comment by stdmn** [comment]
Sorry, I didn't realize that. I guess there could be a way to do a similar thing for values where there is a lot of repetition. Not sure if that is already included in the encoding...

**Comment by ericfischer** [comment]
Yes, duplicate values are also encoded as references into a pool of constants. (See the comments in https://github.com/mapbox/vector-tile-spec/pull/121 for the current efforts to make them compress even better.)
