### ISSUE TITLE
can't store points lower then zoom 14

### ISSUE THREAD

**Issue by neverwiredhouse** [mapbox/tippecanoe#646]
This is probably a very unique case, so if you don't have the time to support it, no worries. I was thinking maybe it's a quick fix though...

I created features for POI myself using OSM, and I was trying to make sure ALL poi were in one layer, and so to handle zooms, I set features like this:

```
{"type":"Feature","properties":{"name":"Sheep Creek","maki":"slipway","zoom":16,"category":[],"subCategory":[],"tag":["Slipway"],"area": "0.000000"},"tippecanoe":{ "minzoom": 16, "maxzoom": 19, "layer": "poi"},"geometry":{"type":"Point","coordinates":[-109.6750421,40.923876]}},
```

Notice, I tell tippecanoe to handle handle the feature at this lower zoom level, but like I said it doesn't process below 14, so I have to make sure it is saved at minzoom 13 at a minimum.

is this perhaps going to be a breaking change? I realize there are ways to style in mapbox to avoid this, but the easiest way is to use multiple layers, and I don't want to do that.

Anways, thanks.

**Comment by ericfischer** [comment]
Tippecanoe's default maxzoom is 14, but you can use `-z19` to tile all the way to 19 if that's what you need.

It probably should pay attention to what the highest zoom is that is explicitly declared within any feature, but the current dot-dropping implementation assumes that it already knows the base zoom level while it is parsing the features. I'll look into how complicated that would be to change.

**Comment by neverwiredhouse** [comment]
I thought because I specified in the tippecanoe geojson a lower minzoom and maxzoom then 14 it would auto respect the zoom level.

`-z19` worked for me! Thank you so much.

perhaps for data 19 is low enough.
