### ISSUE TITLE
Some polygons are merged

### ISSUE THREAD

**Issue by jvaldezch** [mapbox/tippecanoe#649]
Hi, I'm trying to produce some MBTiles using ogr2ogr and tippecanoe and Leaflet.MapboxVectorTile but when selecting a polygon I got this situation:

![image](https://user-images.githubusercontent.com/605927/47246711-15a5b700-d3c5-11e8-82af-4cc90dd9b278.png)

Multiples polygons are seleted at once. My GeoJSON looks like this on Quantum GIS:

![image](https://user-images.githubusercontent.com/605927/47246746-3f5ede00-d3c5-11e8-9a60-e344001de734.png)

**Comment by jvaldezch** [comment]
I have tried many parameters, still same result.

`tippecanoe -o ANP_Finales.mbtiles -f -zg --no-polygon-splitting ANP_Finales.geojson`

[ANP_Finales.zip](https://github.com/mapbox/tippecanoe/files/2497634/ANP_Finales.zip)

**Comment by ericfischer** [comment]
Thanks for the command line and sample data. As far as I can tell, Tippecanoe is doing the right thing here. Looking at the output, each of these polygons is a distinct feature with a distinct `id` field. How are you selecting them in Leaflet?

**Comment by jvaldezch** [comment]
Yes, I'm using leaflet and Leaflet.MapboxVectorTile.

![image](https://user-images.githubusercontent.com/605927/47248483-5c4cde80-d3d0-11e8-9985-5f4e02c2f8e2.png)

**Comment by ericfischer** [comment]
Sorry, I think you'll have to ask about this in Leaflet.MapboxVectorTile instead. I don't know much about that library, and I think the Tippecanoe side of things is correct.

**Comment by jvaldezch** [comment]
I'm going to check there. Loading the tiles on MapTiler everaything is Ok. Thanks Erick.

**Comment by ericfischer** [comment]
Glad to hear the tiles are working correctly with MapTiler!
