### ISSUE TITLE
Can I use this for Google Map Tile Layer?

### ISSUE THREAD

**Issue by tomoyuki28jp** [mapbox/tippecanoe#659]
Sorry, this is a question rather than an issue.  Can I use this library for Google Map Tile Layer? I tried it, but no tile is shown on Google Map on iOS. Thanks in advance.

Note:
- I generated png tiles
- Google Map requested an existing tile over http

**Comment by ericfischer** [comment]
Tippecanoe generates vector tiles that have to be accompanied by a style sheet to be rendered, not raster tiles that can be used directly as an overlay with the Google Maps API. They are intended for use with Mapbox GL as the renderer.
