### ISSUE TITLE
Feature Request: Option to promote a geojson feature property to top level ID

### ISSUE THREAD

**Issue by samgehret** [mapbox/tippecanoe#660]
With the introduction of `setFeatureState` into GL-JS, it is increasingly important to have control over the top level ID of features within a vector tile.

Take the following example: I download a shape file from the census website, convert it to geojson, run through tippecanoe, and upload to mapbox as a vector tile. Now I want to use setFeatureState to style the polygons in the vector tile. But I cannot, because the top level IDs of the polygon features are generated sequentially/randomly.

It would be great, if running my geojson through tippecanoe, if I could choose which of the geojson properties would be promoted to the top level ID of each feature.

cc @ericfischer

**Comment by ericfischer** [comment]
OK, I can add a `--use-attribute-for-id` option that will treat a specified feature attribute as if it were the `id` field.

**Comment by ericfischer** [comment]
Merged
