### ISSUE TITLE
Unknown error, or, how do I debug failed runs?

### ISSUE THREAD

**Issue by AndyCJ** [mapbox/tippecanoe#670]
Unfortunately I don't have very much information to offer on this issue. I've tried to gather everything of value that I could think of, and I'll be more than happy to try and dig up more specifics if you can tell me how to provide them.

I have a geojson file that's ~14gb in size.
It's a set of high-detail features covering a US state.

The data was originally 10s of shapefiles. I've processed them using other software in to the single geojson file. I also stripped out all the unwanted attributes at the same time, leaving just the two that I'm interested in. (Gotta try to keep the data minimal!)

I've then tried to process them using tippecanoe in Docker, as I'm running on a Windows machine.
The docker container OS is: Ubuntu 16.04.5 LTS

Here's the command line I'm using to execute tippecanoe: `docker run -it --rm -v ${pwd}:/data tippecanoe:latest tippecanoe -f -o /data/Risk.mbtiles -zg --extend-zooms-if-still-dropping --drop-smallest-as-needed /data/Risk.geojson 1>stdout.txt 2>stderr.txt`

`stderr.txt` ends up with nothing in it.
`stdout.txt` does have some output in it, but nothing of apparent use:

> For layer 0, using name "Risk"
Read 0.00 million features
Read 0.01 million features
Read 0.02 million features
Read 0.03 million features
Read 0.04 million features
Read 0.05 million features
Read 0.06 million features

I've had a look around the excellent documentation on the tippecanoe github home page (it's helped me a lot as I've been working with this tech for the last few weeks, thank you!) but I've not been able to find much about getting "enhanced logging", or any other debug information which would help me track down the problem.

**Comment by ericfischer** [comment]
The debugging information ought to be in the log of the standard error. In ordinary use I don't think there will be anything on the standard output.

If you are finding the progress messages to be too noisy, you can use `--no-progress-indicator` to log only errors and warnings, not progress messages.

Maybe you are running out of disk space before anything interesting happens, and it is losing your error log as well as the actual intended output because there is no room to store either of them?

**Comment by ericfischer** [comment]
Please reopen if there are further questions.

**Comment by AndyCJ** [comment]
Thank you for your reply, it gave me some things to think about, and made me realize I'm probably not capturing standard error correctly.

I'm currently working through that but it revolves around the environment I'm using, and isn't really anything to do with tippecanoe specifically.

If I get to the point where I do have tippecanoe specific questions then I'll reopen as you suggest.

Sorry for taking so long to reply. As so often happens, other things took me away temporarily from this work, but I still could have and should have responded sooner.
