### ISSUE TITLE
tippecanoe: command not found

### ISSUE THREAD

**Issue by nklenk** [mapbox/tippecanoe#678]
I am currently on Ubuntu 18.04.1 LTS. I have followed all of the the Ubuntu instructions in the readme, including the additional apt-get commands in the development portion. The installation looked to be successful, but I receive the error "tippecanoe: command not found" whenever I try to call it. This includes commands that have worked successfully in the past.

**Comment by ericfischer** [comment]
Did you `make install`? Is `/usr/local/bin` in your `$PATH`?

**Comment by nklenk** [comment]
Hi, 

Yes, I did the make install, and i have /usr/local/bin/tippecanoe in my interpreter path in Pycharm (I followed instructions at this link: https://stackoverflow.com/questions/48947494/add-directory-to-python-path-in-pycharm) as well as my in my .bashrc file. As of now I am able to call tippecanoe from the command line, but It is failing whenever I try to call it from a program in pycharm.

**Comment by ericfischer** [comment]
Sorry, I don't know anything about `pycharm`, and don't know how to debug your issue there. If it runs from the command line, I think the `tippecanoe` side is OK.
