### ISSUE TITLE
Docker file for Ubuntu ERROR

### ISSUE THREAD

**Issue by topinvestor** [mapbox/tippecanoe#679]
make: *** No targets specified and no makefile found.  Stop.
The command '/bin/sh -c make 	&& make install' returned a non-zero code: 2
ERROR

From repository:
Dockerfile
===
# Start from ubuntu
FROM ubuntu:16.04

# Update repos and install dependencies
RUN apt-get update \
	&& apt-get -y upgrade \
	&& apt-get -y install build-essential libsqlite3-dev zlib1g-dev

# Create a directory and copy in all files
RUN mkdir -p /tmp/tippecanoe-src
WORKDIR /tmp/tippecanoe-src
COPY . /tmp/tippecanoe-src

# Build tippecanoe
RUN make \
	&& make install

# Run the tests
CMD make test
===

**Comment by ericfischer** [comment]
I think you missed the stage where you `cd` into the `tippecanoe` source directory.
