### ISSUE TITLE
Input format with faster parsing

### ISSUE THREAD

**Issue by ericfischer** [mapbox/tippecanoe#68]
@morganherlocker would like a simple CSV input format like the datamaps one that is faster to parse than GeoJSON. @aaronlidman, I think you said you'd like this too.

**Comment by aaronlidman** [comment]
Is this just for geometry or will this also include a way of passing properties?

Before investing in this, do you have an idea of how much gain we would expect by not needing to parse JSON?

**Comment by ericfischer** [comment]
@aaronlidman I was thinking just "key"="value" at the end of the line. The more serious limitation is no good precedent for a syntax for polygons.

Datamaps input parsing is about 10x the speed of tippecanoe's, and the only real difference is GeoJSON vs just blasting through comma-separated pairs.

There's got to be something that is reasonably fast, easy to generate, and reasonably standardized, but I don't know what it is. GeoJSON is standard but slow to parse and hard to generate because of all the nested objects.

**Comment by aaronlidman** [comment]
I think parallelized input mitigates this need quite a bit.

@ericfischer - Think we're good to close this?

**Comment by ericfischer** [comment]
Yeah, probably not worth worrying about this unless to support some other widely-used format like shapefile.
