### ISSUE TITLE
Incorrect contouring

### ISSUE THREAD

**Issue by Plantain** [mapbox/tippecanoe#680]
Hi,
I think I have found a fairly rare but quite bad bug producing seemingly randomly incorrect contours:
Processing the attached JSON file
[1600.json.gz](https://github.com/mapbox/tippecanoe/files/2642934/1600.json.gz)
 with tippecanoe --quiet --coalesce-smallest-as-needed --detect-shared-borders --coalesce --reorder -z5 -d 14 -D 14 -pw 1600.json
Produces rendering that looks like this:
<img width="675" alt="screen shot 2018-12-04 at 10 07 58 am" src="https://user-images.githubusercontent.com/319895/49427712-bcdf8180-f7ac-11e8-8fbf-8ed8e95f0caa.png">

When it should look (more like) this:
<img width="886" alt="screen shot 2018-12-04 at 10 07 46 am" src="https://user-images.githubusercontent.com/319895/49427732-c7018000-f7ac-11e8-8d09-9f104c4406cb.png">

Notice that in the tippecanoe'd tiles that it's as though the colours that should be a continuous progression are somehow out of order. I have added an "idx" parameter to the GeoJSON to assist with tracking the contiguity. It jumps from 8->4->21 in this example producing the discontinuity around the pentagon shaped hole.

I have confirmed on mapshaper that they are in fact continuous in the GeoJSON.
<img width="601" alt="screen shot 2018-12-04 at 10 09 17 am" src="https://user-images.githubusercontent.com/319895/49427789-f3b59780-f7ac-11e8-8e29-a14bd62ef550.png">
<img width="619" alt="screen shot 2018-12-04 at 10 09 11 am" src="https://user-images.githubusercontent.com/319895/49427790-f3b59780-f7ac-11e8-8014-1311096cc6a6.png">
<img width="651" alt="screen shot 2018-12-04 at 10 09 06 am" src="https://user-images.githubusercontent.com/319895/49427791-f3b59780-f7ac-11e8-8a24-ade90bf47091.png">

Mapbox Studio shows they are not continuous after tiling with tippecanoe:
<img width="654" alt="screen shot 2018-12-04 at 10 06 40 am" src="https://user-images.githubusercontent.com/319895/49427869-252e6300-f7ad-11e8-89e6-7642739b22ee.png">
<img width="635" alt="screen shot 2018-12-04 at 10 06 35 am" src="https://user-images.githubusercontent.com/319895/49427872-25c6f980-f7ad-11e8-9fc2-0a4eef34eb38.png">
<img width="690" alt="screen shot 2018-12-04 at 10 06 29 am" src="https://user-images.githubusercontent.com/319895/49427873-25c6f980-f7ad-11e8-9e69-522e1bd58e94.png">

To find the exact location in the example, see here - although it is present in many places.
<img width="1236" alt="screen shot 2018-12-04 at 9 57 09 am" src="https://user-images.githubusercontent.com/319895/49427965-6c1c5880-f7ad-11e8-869c-8a79700cc3c1.png">

**Comment by Plantain** [comment]
More curiously, the ordering is correct if I remove -d 14 -D 14 from the flags. But the contours becomes jagged.
<img width="700" alt="screen shot 2018-12-04 at 10 38 24 am" src="https://user-images.githubusercontent.com/319895/49429296-d71b5e80-f7b0-11e8-8976-0545375e3833.png">

**Comment by ericfischer** [comment]
Thanks for the report! I'll download your source file and try to figure out what is going on.

**Comment by ericfischer** [comment]
The hole you identify is at 38.1531/138.5892

**Comment by Plantain** [comment]
Just clarifying the hole itself is not part of the problem (as far as I can tell) - I think that's because of the reversed windings in the file, but the odd order of contours around it are the unexpected behaviour.

**Comment by ericfischer** [comment]
To be clear, are you aware that `--coalesce-smallest-as-needed` can cause features to be combined even if their attributes are not identical? I think this is what is causing the disordered contours you see, as features in tile `5/28/12` are merged together to reduce the tile size. Small inner contours are probably inheriting the attributes of the large outer contours they are being coalesced onto.

**Comment by Plantain** [comment]
I was not aware of that - I'll try it without and see if it affects it.

**Comment by Plantain** [comment]
That fixes the issue for me.
I think there is still a bug here though? Shouldn't they be coalesced into their nearest neighbor such that they never get out of order like this?

**Comment by ericfischer** [comment]
That would be ideal, but nearest neighbor is a difficult concept to define precisely, especially when features can overlap. Tippecanoe uses the quadkey sequence of the feature centroids, which is fast and generally gives reasonable results, but occasionally makes some surprising jumps. Maybe there is another sequencing that would be more appropriate for nested features.

**Comment by Plantain** [comment]
Perhaps via some interaction with --detect-shared-borders. I'm happy to close this if it's implausible. I created a pull to improve the documentation as I think this behaviour may catch other people.

**Comment by ericfischer** [comment]
Thanks for the documentation improvement!

I just realized that it is actually currently using the center of the feature bounding box rather than the centroid, and that the centroid might give better results, so I will try that. But that's the only plausible idea I have currently.

**Comment by ericfischer** [comment]
Using the centroid instead of the bounding box center doesn't seem to make much difference. The other possibility I should try: using a Hilbert curve instead of quadkey sequence, since it is continuous instead of ever jumping.

**Comment by ericfischer** [comment]
It doesn't solve the problem entirely, but the Hilbert curve does seem to have better locality in general, so I think I will make that switch (after some more testing, since it affects everything).

**Comment by ericfischer** [comment]
I'm still trying to decide how risky a change this is, since it does change the order of every output tile, but if you want to try it out and see if it improves the handling of your data, it's in https://github.com/mapbox/tippecanoe/pull/682.

**Comment by ericfischer** [comment]
Actually this breaks basezoom guessing, which relies on the feature indices within each tile being contiguous. Or maybe it is still OK, and the indices are still contiguous, but in a different tiling scheme? I need to verify, anyway.

**Comment by ericfischer** [comment]
I think the basezoom guessing is actually still OK. Tiles are still contiguous in sequence, and decoding indices to tile number always goes through the decode function, so it doesn't matter that the exact bit patterns have changed.

**Comment by ericfischer** [comment]
https://github.com/mapbox/tippecanoe/pull/683 added the `--hilbert` option, which should make Tippecanoe do a better job of choosing which features to coalesce together, and is as much as I can do currently to improve the situation here.
