### ISSUE TITLE
tippecanoe geojson extensions as regular properties

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/tippecanoe#685]
Some software which can write to GeoJSON has trouble outputting the tippecanoe GeoJSON extensions https://github.com/mapbox/tippecanoe#geojson-extension. Is it possible to optionally allow these to be read as regular properties?

**Comment by ericfischer** [comment]
I hesitate to do this, because the properties namespace belongs to the user data, not to the tool, but I have already made a special case for `id`, so maybe I should make more special cases for the others.

**Comment by andrewharvey** [comment]
I wrote a node script to transform feature properties into tippecanoe extensions for this issue.

https://github.com/andrewharvey/geojson-tippecanoe-extensions-from-attributes

**Comment by ericfischer** [comment]
Oh good, I'm glad you have a workaround.

**Comment by andrewharvey** [comment]
... and if you're working with [newline delimited geojson](http://geojson.win/newline-delimited/) I discovered you can transform it with a one-liner from [ndjson-cli](https://github.com/mbostock/ndjson-cli/blob/master/README.md).

    ndjson-map 'd.tippecanoe = { minzoom: d.properties.minzoom, maxzoom: d.properties.maxzoom, layer: d.properties.layer }, delete d.properties.minzoom, delete d.properties.maxzoom, delete d.properties.layer, d'
