### ISSUE TITLE
Error with protobuf symbols

### ISSUE THREAD

**Issue by rowanwins** [mapbox/tippecanoe#69]
Hi tippecanoe team,

Thanks for a very handy utliity. I had it up and running and upgraded to tippecanoe v1.2 yesterday and now I'm getting the following error, its obvisouly getting part way through the process but then failing.

````
tippecanoe -o blah.mbtiles point.geojson
using layer 0 name pointgeojson
Sorting 152268 features
152268 features, 3197641 bytes of geometry, 19818802 bytes of metadata
dyld: lazy symbol binding failed: Symbol not found: __ZNK6google8protobuf11MessageLite17SerializeToStringEPNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE
  Referenced from: /usr/local/bin/tippecanoe
  Expected in: /usr/local/lib/libprotobuf-lite.9.dylib

dyld: Symbol not found: __ZNK6google8protobuf11MessageLite17SerializeToStringEPNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE
  Referenced from: /usr/local/bin/tippecanoe
  Expected in: /usr/local/lib/libprotobuf-lite.9.dylib

Trace/BPT trap: 5
````

I've tried a few different geojson datasets all with the same results. Any tips?

Thanks
Rowan

**Comment by ericfischer** [comment]
Thanks for the report @rowanwins. I haven't seen this one before. Are you building it yourself from the source code or using a prepackacked build? If you are building it yourself, a "make clean" might help. It looks like the header and source files for the protocol buffer library don't match up.

**Comment by rowanwins** [comment]
Thanks @ericfischer , I was just using the homebrew install process. I had some issues updating yesterday so maybe something has gone astray in the process. I'll try removing the packages and starting from scratch and fingers crossed it works itself out.

Cheers
Rowan

**Comment by rowanwins** [comment]
Ahh indeed it appears that the protobuf and tippecanoe brews somehow got out of sync
To resolve it I ran
````
brew uninstall protobuf --force
brew install protobuf
````
All seems to be good now!

**Comment by ericfischer** [comment]
Great! Glad to hear that fixed it for you.
