### ISSUE TITLE
--help not supported

### ISSUE THREAD

**Issue by stevage** [mapbox/tippecanoe#690]
```
$ tippecanoe --help
tippecanoe: unrecognized option `--help'
Unknown option -?
Usage: tippecanoe [options] [file.json ...]
  Output tileset
...
```

Obviously it doesn't really matter, as the help is printed anyway, it's just a bit weird.

(That's with 1.32.5, which seems to be the latest version on Homebrew.)

**Comment by ericfischer** [comment]
Thanks. I'll add it.

**Comment by ericfischer** [comment]
This will be fixed in https://github.com/mapbox/tippecanoe/pull/691
