### ISSUE TITLE
Features are not hidden above maxzoom?

### ISSUE THREAD

**Issue by bravecow** [mapbox/tippecanoe#692]
In this example:

https://github.com/mapbox/tippecanoe#show-countries-at-low-zoom-levels-but-states-at-higher-zoom-levels

Countries are shown at low level **BUT** states at higher or **AND** states at higher level?

According to: https://stackoverflow.com/questions/48197271/what-do-minzoom-and-maxzoom-do-in-mapbox-gl-js-exactly/48197272

Features are never hidden above maxzoom, they are overzoomed instead.

So tippecanoe can help me when I need to show features for 14-... zoom, but can't help me when I want to show features 0-14? I am right? (Hide them, not overzoom).

**Comment by ericfischer** [comment]
Mapbox tile rendering will overzoom features from a lower zoom when a tile is not defined at all at a higher zoom. However, if your tileset defines some layers in tiles at a zoom level, rendering that tile will only render the layers defined in the tile; it will not look to the lower zoom levels for other layers to overzoom. So `tile-join` should only be used to join tilesets that are defined for the same zoom levels, or that intentionally include some layers at low zooms and others at high zooms.

**Comment by bravecow** [comment]
@ericfischer Maybe it is just me, but not very obvious behaviour for `minzoom `/ `maxzoom` 🙄 Thank you for clarifying.
