### ISSUE TITLE
Crash on 177MB file

### ISSUE THREAD

**Issue by Schwanksta** [mapbox/tippecanoe#70]
Ethics of >100MB geojson files aside, I dumped some data into said format so I could run it through tippecanoe and serve it up in vector form. I've tried some variations on running tippecanoe, but they all crash without a helpful error. -Z0 -z0 seemed to work, but somehow not sure that's what I want.

I'll try to drop the file on S3 in a bit so you can test it. Is there a known upward limit on a GeoJSON file size?

```bash
Ken-Schwencke-3836: iowa $ tippecanoe -o corn.mbtiles -f -l corn -n "Iowa has a lot of corn." corn.geojson 
Sorting 327019 featuresres
327019 features, 54277103 bytes of geometry, 6867399 bytes of metadata
  6.6%  0/0/0  
Ken-Schwencke-3836: iowa $ tippecanoe -o corn.mbtiles -Z15 -z15 -f -l corn -n "Iowa has a lot of corn." corn.geojson 
Sorting 327019 featuresres
327019 features, 54277103 bytes of geometry, 6867399 bytes of metadata
  6.2%  0/0/0  
Ken-Schwencke-3836: iowa $ tippecanoe -o corn.mbtiles -Z0 -z0 -f -l corn -n "Iowa has a lot of corn." corn.geojson 
Sorting 327019 featuresres
327019 features, 54277103 bytes of geometry, 6867399 bytes of metadata
  99.9%  0/0/0  
Ken-Schwencke-3836: iowa $ tippecanoe -o corn.mbtiles -Z0 -z1 -f -l corn -n "Iowa has a lot of corn." corn.geojson 
Sorting 327019 featuresres
327019 features, 54277103 bytes of geometry, 6867399 bytes of metadata
  49.9%  0/0/0  
Ken-Schwencke-3836: iowa $ tippecanoe -o corn.mbtiles -Z0 -z1 -f -d1 -l corn -n "Iowa has a lot of corn." corn.geojson 
Sorting 327019 featuresres
327019 features, 54277103 bytes of geometry, 6867399 bytes of metadata
  49.9%  0/0/0  
```

**Comment by ericfischer** [comment]
The whole point of tippecanoe is to let you tile gigantic GeoJSON files, so I certainly hope 100MB should work.

Without seeing your file, I bet it is in some projection other than WGS84 (EPSG:4326) so all the features are being clipped away. I added a warning for this in 263ae94e754863 but you may have an older build that doesn't include that warning.

**Comment by Schwanksta** [comment]
You are absolutely correct. Reprojected it and it seems to be working well.

**Comment by ericfischer** [comment]
Great! Glad it's working for you now.
