### ISSUE TITLE
zoom level 0 not supported in tippecanoe GeoJSON extension

### ISSUE THREAD

**Issue by boblannon** [mapbox/tippecanoe#701]
## Context:

Using `tippecanoe@1.31.0` and `tippecanoe@1.32.9`, I ran `< geo_stats.geojson tippecanoe -z10 -fo /tmp/stats.mbtiles` where `geo_stats.geojson` contains features with `tippecanoe.minzoom: 0`.  

## Expected Behavior

Should have been processed without error, as it did in `tippecanoe@1.27.9`.

## Actual behavior

Raises:

```
For layer 0, using name "stats"
standard input: Expected integer zoom level in "tippecanoe" GeoJSON extension, not 0
events.js:183
      throw er; // Unhandled 'error' event
      ^
```

## My best guess

#604 introduced [an `isnormal` check]( https://github.com/mapbox/tippecanoe/pull/604/files#diff-dce317538340b187e48dae4f2ea5ca07R130) on zoom levels specified in the `tippecanoe` GeoJSON extension.  According to the the C++ docs, however, `isnormal(0)` evaluates to` false`. Is it possible that `isfinite` is the test we're looking for, here?

**Comment by ericfischer** [comment]
Good catch! I'll replace this check with something more appropriate. I think you're right that `isfinite` is what I wanted.

**Comment by ericfischer** [comment]
This will be fixed as you suggested in https://github.com/mapbox/tippecanoe/pull/702.

**Comment by ericfischer** [comment]
Merged
