### ISSUE TITLE
what if zoom is over 32? 

### ISSUE THREAD

**Issue by damiendevienne** [mapbox/tippecanoe#706]
Hello, and congrats for the great work. 
There seems to be a limit at zoom 32, that seems to be due to a limit in the values that the tile coordinates x and y can take given their type (unsigned int). 

My question is: would it be difficult/impossible/unrealistic or not to change the zoom limit? 

The reason is that I would like [Lifemap](http://lifemap-ncbi.univ-lyon1.fr) to switch to vector tiles in the next version, and it requires up to 42 zoom levels... 
And maybe other projects might be interested as well by the possibility of ultra-zooming? ;-)

Thanks a lot

**Comment by ericfischer** [comment]
32-bit coordinates are deeply embedded throughout Tippecanoe and would not be easy to change. That gives about 0.3cm resolution on the ground, which is sufficient for most normal purposes.

Can you explain what you are doing that requires 2^42 points on a side?

**Comment by damiendevienne** [comment]
Yes, I am using geographic tools to produce the interactive tree of all living species (called Lifemap, [lifemap.univ-lyon1.fr](http://lifemap.univ-lyon1.fr). 
The deep hierarchical nature of the data makes it require a lot more zoom levels than for classical maps... 
Maybe one option is to use other vector tile generators, since only about 1% of Tippecanoe functionalities are needed, but which one??

**Comment by ericfischer** [comment]
The best thing I can currently suggest is that you could make the high zooms by making a series of scaled-and-offset copies of your data, so that, say, the data that you want to be subsidiary to each particular z10 tile is scaled and offset so that it takes up the full extent of z0. Then after making a sub-tileset for each of those z10 tiles, merge the sub-tilesets, renaming the tiles to reflect their intended zooms and locations.

**Comment by ericfischer** [comment]
There might be other people who are interested in a larger range of valid coordinates, but I haven't received any other such requests. I don't have any particular interest in limiting coordinates to 32 bits, and would be happy to accept a patch that widens the coordinate type everywhere, but can't prioritize making this change myself when the demand seems to be so limited.

**Comment by briantran37** [comment]
So ive done what @ericfischer suggested but im getting a "found unexpected character" error when trying to merge the two mbtiles

```
Running Command: ~/bin/tippecanoe -r1 -z6 -o ./data/low/snow24hr-bc_20201206_0000.mbtiles --force --detect-shared-borders --extend-zooms-if-still-dropping --drop-fraction-as-needed --drop-densest-as-needed ./geodata/geojson/snow24hr-bc_20201206_0000.geojson
converting low zoom mbtiles 
For layer 0, using name "snow24hrbc_20201206_0000"
28749 features, 1401338 bytes of geometry, 8 bytes of separate metadata, 167 bytes of string pool
  99.9%  6/19/23  
Running Command: ~/bin/tippecanoe -r1 -Z7 -o ./data/high/snow24hr-bc_20201206_0000.mbtiles --force --detect-shared-borders --extend-zooms-if-still-dropping --drop-fraction-as-needed --drop-densest-as-needed ./geodata/geojson/snow24hr-bc_20201206_0000.geojson
converting high zoom mbtiles 
For layer 0, using name "snow24hrbc_20201206_0000"
28749 features, 1682167 bytes of geometry, 13809 bytes of separate metadata, 167 bytes of string pool
  99.9%  14/4949/5999  
Running Command: ~/bin/tile-join -r1 -o ./data/snow24hr-bc_20201206_0000.mbtiles --force --layer=nanoweather24hrpast ./data/low/snow24hr-bc_20201206_0000.mbtiles ./data/high/snow24hr-bc_20201206_0000.mbtiles
joining mbtiles 
./data/low/snow24hr-bc_20201206_0000.mbtiles:1: Found unexpected character
./data/high/snow24hr-bc_20201206_0000.mbtiles:1: Found unexpected character
0 features, 10 bytes of geometry, 8 bytes of separate metadata, 0 bytes of string pool
Did not read any valid geometries
```

My vector tile at high zoom level is pixalated and wanting to merge two vector tiles to remedy that. What do you suggest to resolve the error?

![image](https://user-images.githubusercontent.com/72456221/101272006-4dfbe100-3756-11eb-88e4-c506f5e28bb0.png)

**Comment by ericfischer** [comment]
This is rather strange, since the `Found unexpected character` message would come from JSON parsing, not from opening an mbtiles file. The only reason I can think of that `tile-join` would be reading a JSON file would be if you were using `-J` to read a filter from a file, and it doesn't look like you are doing that.

**Comment by ericfischer** [comment]
Are you sure you are running `tile-join` and not `tippecanoe`? `tile-join` would also not produce the message:

```
0 features, 10 bytes of geometry, 8 bytes of separate metadata, 0 bytes of string pool
Did not read any valid geometries
```

That is a `tippecanoe` status message.

**Comment by briantran37** [comment]
I'm sure I am as per this log line :
```
Running Command: ~/bin/tile-join -r1 -o product_vector_tile.mbtiles --force --layer=product_vector_tile low_zoom.mbtiles high_zoom.mbtiles
joining mbtiles 
low_zoom.mbtiles:1: Found unexpected character
high_zoom.mbtiles:1: Found unexpected character
0 features, 10 bytes of geometry, 8 bytes of separate metadata, 0 bytes of string pool
Did not read any valid geometries
```

**Comment by ericfischer** [comment]
Something is wrong with your installation because these are messages you would get from `tippecanoe`, not `tile-join`.

**Comment by ericfischer** [comment]
If you can share your data I can probably offer some advice on what to do at high zooms.

**Comment by ericfischer** [comment]
I'm not sure how the high zooms even come into this. I did

```
tippecanoe -zg --coalesce --low-detail=10 -f -o foo.mbtiles Downloads/some_data.geojson
```

and z6 seems to be plenty for the resolution of the data. The data looks blocky because the source data is blocky.

**Comment by briantran37** [comment]
Are you familiar with grib files? My conversion looks like

Grib->Geotiff->GeoJSON->MbTiles

Using gdal_translate gdal_polyganize and tippecanoe libraries. 

Do you recommend a different conversion method between grib to Tiff and/or to gejson?

**Comment by ericfischer** [comment]
Sorry, I don't know anything about grib files. I have head that `gdal_polygonize` has an option to create smooth contours from gridded data, but I have not used it myself.

**Comment by briantran37** [comment]
@ericfischer what options (gdal or tippecanoe) can I use to remedy vector tiles that are coming out black?

**Comment by briantran37** [comment]
@ericfischer figured out the right options to get the diagonals to work so it not blocky any more...but some parts of the vector tile are still block... do you suggest any other options to get optimal vector tiles with minimum to no blockyness? 

heres what I used : 

`tippecanoe -zg -S10 -d12 -o  data.mbtiles --force --layer=layername --detect-shared-borders --coalesce-densest-as-needed --extend-zooms-if-still-dropping --drop-densest-as-needed data.geojson`
