### ISSUE TITLE
inner workings of"detail"

### ISSUE THREAD

**Issue by kdanaher** [mapbox/tippecanoe#710]
I have a super detailed set of lines which I'm feeding through tippecanoe for zooms 1 through 12 using:

`tippecanoe --minimum-zoom=1 --maximum-zoom=12 -o lines.mbtiles --drop-densest-as-needed lines.geojson`

The output is great, but I'd be completely happy with the lines being more simplified/generalized at lower zooms, while staying just the way they are at higher zooms and zoom level 12. Sorry if this is supposed to be obvious, but I just want to understand how the detail parameters work -- 

If I were to specify a -D of something like 6 (implying that the lowest zoom level 1 can have a detail level of 6 ) would the detail level for zooms 1 through the max zoom 12 be interpolated for each level between the set detail 6 through detail 12 (the default) at highest zoom? So something like

z1 - detail 6
z2- detail 6.5
z3- detail 7
z4- detail 7.5
...
etc
...
z10 detail 11
z11 detail 11.5
z12 detail 12 (default)

Many thanks. Apologies this is more of a clarification than an issue.

**Comment by ericfischer** [comment]
The detail can only be an integer. For detail *d*, the internal coordinate system within each tile has a resolution of 2^*d* tile units, so, for example, tiles with a detail of 12 have 4096 units on each side.

There is no interpolation: there is one detail for the maxzoom and another for all lower zooms. The idea is that the maxzoom tile is the only one that can ever be substantially overzoomed, so it is the only one that ever needs to be much more than the screen resolution. In the lower zooms, the tiles for zoom N will only ever be seen at most at scale N.99999 before rendering switches over to tiles from zoom level N+1.

You may actually be looking for `--simplification`, which controls line simplification/generalization more directly than by changing the tile resolution. I wouldn't be opposed to making this more controllable at different zoom levels, but I don't think changing it usually actually makes much difference in the tile sizes.

**Comment by kdanaher** [comment]
Eric, thanks for the reply. That makes sense.

After playing around a bit more, and adding in simplification, i think the issue I was experiencing was more related to my lines being cut into small segments in many places rather than contiguous.

After running a dissolve and creating contiguous stretches wherever possible, the data looks much better.this plus combining with a small simplification scale seems to have hit the sweet spot. 

Unrelated to this particular issue,  but would it be possible to add an option to tile-join that would allow all tiles joined to overzoom? You've stated this elsewhere, but currently overzooming only occurs across all the tiles joined if their max zooms are identical. (I can create this in a different issue if you'd like)

**Comment by ericfischer** [comment]
Oh good, I'm glad you got it working. `--coalesce` can also be useful for merging separate features together into a single feature so they can be represented more compactly.

It probably would be useful to give `tile-join` the ability to do internal overzooming to make the zooms of the merged layers consistent. Please file a separate ticket about that since it is not very closely related to this one.

**Comment by kdanaher** [comment]
Will do. Marking this as closed and will post an issue to specific to tile-join separately. Thanks!
