### ISSUE TITLE
How to install tippecanoe on Windows

### ISSUE THREAD

**Issue by SarthakTewari** [mapbox/tippecanoe#712]
What are the steps to install tippecanoe on Windows?

**Comment by ericfischer** [comment]
Tippecanoe is not supported on Windows but it reportedly works under the Windows Subsystem for Linux.

**Comment by plevy** [comment]
I have built it and runs fine on Cygwin also.  Followed these steps:
https://github.com/GISupportICRC/ArcGIS2Mapbox
Look for "Installing tippecanoe on Windows"
