### ISSUE TITLE
Clustering and point_count 

### ISSUE THREAD

**Issue by mikeomeara1** [mapbox/tippecanoe#713]
First, let me say how ridiculously great this lib is. I'm having my mind blown every time I use it. We've having lots of success...and that's a credit to your implementation and extensive docs. Really well done.

We have one scenario that has us scratching our heads though and I can't seem to figure out how to make what we're after work (and it's likely a case of being dumb, not understanding the correct options to pass, being dumb again or being extra dumb). 

We have a json file that has ~200,000 point features in it (some proprietary data for Wyoming households). We pass that to `tippecanoe` using `-zg --cluster-densest-as-needed --cluster-distance=10 -b0`. Then we take the resultant tileset, render it on a map, then use `querySourceFeatures` to sum the generated `point_count` properties (realizing that due to the nature of vector tiles, it's very unlikely I'll ever get a 100% accurate count of the source features...in our use-case an estimate is fine).

But in all scenarios, we're ending up with a total `point_count` of far less than ~200,000. 

For example, at zoom level 5, `querySourceFeatures` returns 33 features with a `point_count` sum of 38 . Only 3 of those features have `clustered=true` and they each carry a `point_count` <= 3 -- the fact that there are only 33 features is generally OK...but we would expect the `point_count`'s to be much higher than what it's generating. As we zoom in, we get more features, but never getting to a total `point_count` that seems to make sense for having ~200,000 features in the source file.

I've tried a number of different option combos and haven't been able to figure out where I'm going wrong:

 - `-zg --cluster-densest-as-needed --cluster-distance=10 -b0`
 - `-zg --cluster-densest-as-needed --cluster-distance=10 -b0 --no-feature-limit`
 - `-zg --cluster-distance=10 -b0 --no-feature-limit`
 - `-zg --cluster-distance=1 -b0 --no-feature-limit`
 - `-zg --cluster-distance=0 -b0 --no-feature-limit`
 - etc. changing the cluster distance value around...we've tried dozens of different options/combos

It very much feels like I'm just missing a critical option to make this work. 

Can anyone spot what we're doing wrong?

Thank you so much in advance for any suggestions you may have!

**Comment by ericfischer** [comment]
I think the thing you're missing is `-r1` to turn off the normal dot-dropping at low zoom levels. I probably should have made the clustering options automatically do that, but it's not automatic now.

**Comment by mikeomeara1** [comment]
Wow...that immediately made an enormous difference! Thanks so much for the quick response.

Now I'm getting counts that are 2 to 3 times what they should be (in fact, with the exception of z0 which is always correct, every zoom level is almost exactly 2 or 3 times larger...meaning if you divide the number of the summed `point_count` by 2 or 3...you get a number very close to the total number of features...say +/-100).

I initially thought this had to do with duplication of features near tile boundaries, so I generated an `id` field and de-duplicated...but that didn't help either. 

After decoding a zoom level, parsing out the `point_count` properties and adding them up manually...it does appear that `tippecanoe` is aggregating correctly. So, I'm guessing I'm up against a problem with `querySourceFeatures`.

Thanks again for the quick response!

Mike

**Comment by ericfischer** [comment]
Great, glad to hear it's working for you now!
