### ISSUE TITLE
Question: how to handle 3d coordinates

### ISSUE THREAD

**Issue by jliebrand** [mapbox/tippecanoe#714]
Quick question: I have GeoJSON data which is formatted slightly oddly (and I'm not even sure it's valid??). Example:

```
{
  "type": "Feature",
  "properties": {},
  "geometry": {
    "type": "MultiPoint",
    "coordinates": [
      [4.2986051, 51.1254047, -2.6],
      [4.3025707, 51.1202334, -3.4],
      [4.305517, 51.1223118, 7.6],
      [4.3011774, 51.1241362, 9.7],
      [4.3047621, 51.1253548, 3.0],
      [4.3076292, 51.126133, 3.4],
      [4.3138017, 51.1268111, 8.7],
      [4.3118194, 51.1274344, 4.1],
      [4.3171699, 51.1287236, 6.8],
      [4.3198019, 51.1290972, 12.1]
    ]
  }
}
```

Basically the third digit is the elevation. Can tippecanoe handle this, and if not, how should I reformat it (short of individual points all with elevation set in properties??)

**Comment by ericfischer** [comment]
The release branch of Tippecanoe doesn't handle 3-D because version 2 of the vector tile spec doesn't have a way to represent it.

The VT3 development branch (https://github.com/mapbox/tippecanoe/pull/611) does support 3-D, using the same syntax as you used above. But the tiles will be of limited use until rendering clients start to support the VT3 format.

**Comment by jliebrand** [comment]
Ah ok - then for now I'll reformat the geojson to individual points with properties I guess...

**Comment by ericfischer** [comment]
Yes, I think that is your best option at the moment.

**Comment by omrivolk** [comment]
Hi, revisiting this issue, if I want to display the depth at each point, should formatting it like this work:

{
  "type": "Feature",
  "properties": {"name":"-2.6"},
  "geometry": {
    "type": "Point",
    "coordinates": 
      [4.2986051, 51.1254047]
  }
}

**Comment by jliebrand** [comment]
Yep, I think so - creating one feature per point... quite a bit more verbose, but until 3 (or multi?) dimensional points are supported, that'll have to be the way it's done. (Where "name" could be "elevation" or whatever you then want to use in the style)
