### ISSUE TITLE
Using tippecanoe's mbtiles in Geoserver

### ISSUE THREAD

**Issue by harry-wilson** [mapbox/tippecanoe#717]
I've created a mbtile file from a geojson layer using tippecanoe command tool. The qustion is that is it possible to publish this mbtile in Geoserver with [mbtile extension](https://docs.geoserver.org/stable/en/user/community/mbtiles/index.html)? I've used the extension to publish mbtile but the layer preview throws the **error rendering coverage on the fast path**. Is it something wrong with publish procedure or something else?

**Comment by morganherlocker** [comment]
This issue may be better suited to the geoserver repo, since the error is not coming from tippecanoe: https://github.com/geoserver/geoserver

**Comment by harry-wilson** [comment]
Thanks, @morganherlocker. I go through it.

**Comment by ericfischer** [comment]
Please reopen if something turns out to be wrong on the Tippecanoe side.
