### ISSUE TITLE
One particular geobuf file fails

### ISSUE THREAD

**Issue by stevage** [mapbox/tippecanoe#719]
I have a GeoJSON/Geobuf pair where the GeoJSON file is processed fine by Tippecanoe, but the Geobuf fails.

https://www.dropbox.com/sh/83357s2djn66qsk/AAAGlg0Aj0mO-KtA4XPnUWpqa?dl=0

```
$ tippecanoe --output=mbtiles/subways.mbtiles --force data/subwayLines.geobuf
For layer 0, using name "subwayLines"
0 features, 10 bytes of geometry, 8 bytes of separate metadata, 0 bytes of string pool
Did not read any valid geometries

$ tippecanoe --output=mbtiles/subways.mbtiles --force data/subwayLines.json
For layer 0, using name "subwayLines"
742 features, 50281 bytes of geometry, 13 bytes of separate metadata, 180 bytes of string pool
  99.9%  14/4829/6151
```

I'm producing the geobuf file with the `geobuf` NPM library. Round-tripping the geobuf back to GeoJSON with geobuf2json still produces a file that is processed fine by Tippecanoe. I have processed a dozen or so other datasets in this same way, without any similar problems.

So I don't know if the problem is the geobuf file is somehow defective (but still roundtrips ok), or if Tippecanoe is just choking on multilinestrings or something.

**Comment by ericfischer** [comment]
Thanks. I'll download your file and take a look.

**Comment by ericfischer** [comment]
This turns out to be a very silly bug: your geometry is a MultiLineString, and the case to decode MultiLineStrings was entirely missing from the Geobuf code.

It will be fixed in https://github.com/mapbox/tippecanoe/pull/725.

**Comment by ericfischer** [comment]
Merged and tagged: https://github.com/mapbox/tippecanoe/releases/tag/1.33.0
