### ISSUE TITLE
Produce tiles with only text label

### ISSUE THREAD

**Issue by 2803media** [mapbox/tippecanoe#723]
I wonder if this is possible:

I have a large geojson with cities polygons and names of those cities. I want to display 2 tiles sets, one with the polygons and one with the name of the cities only (so that the user can choose to display them or not).

I have no idea to do that with tippecanoe (for the name/label tile set).

Thanks for your input

**Comment by ericfischer** [comment]
Tippecanoe does not have a built-in facility to choose a label point for polygons. You might want to try https://github.com/mapbox/polylabel which is designed to find the best point for a polygon label.

**Comment by 2803media** [comment]
Thanks @ericfischer for this suggestion!

**Comment by ursNiemi** [comment]
@2803media did you ever find a solution?

**Comment by e-n-f** [comment]
https://github.com/felt/tippecanoe has this now, with `--convert-polygons-to-label-points`.
