### ISSUE TITLE
"Cluster densest as needed" doesn't seem to work right

### ISSUE THREAD

**Issue by stevage** [mapbox/tippecanoe#724]
I'm trying to produce a coverage map of ATTOM's dataset of all parcels in the US. I ran it with these settings:

```
        clusterDensestAsNeeded: true,
        minimumZoom: 5,
        maximumZoom: 11,
        readParallel: true,
        filename: `parcels.nd.json`
```

There are some really weird (and showstopping) gaps in the output:

<img width="1229" alt="screenshot 2019-03-01 12 42 11" src="https://user-images.githubusercontent.com/678344/53656126-4a056b80-3c20-11e9-8f4a-56c3d05733a4.png">

Here, the black circles are the output features, rendered as `circle`, overlaid on a `heatmap` layer of the same data. It looks like there is no data at all in South Dakota right?

<img width="1227" alt="screenshot 2019-03-01 12 45 30" src="https://user-images.githubusercontent.com/678344/53656204-8a64e980-3c20-11e9-914c-982a61d63a84.png">

But actually there is continuous coverage of parcels northeast of Pierre, SD. Zooming in further to the boundary of the dots, southeast of Pierre, and displaying the actual parcels themselves:

<img width="1241" alt="screenshot 2019-03-01 12 45 49" src="https://user-images.githubusercontent.com/678344/53656242-b08a8980-3c20-11e9-8602-e997cfa374f8.png">

It's so weird. None of the parcels from that county make it into the output. (Color coding here is by the last two digits of the FIPS code of each parcel, which gives rough per-county coloring.)

I tried converting the polygons to points first, then doing the same process, but the result was very similar:

<img width="1114" alt="screenshot 2019-03-01 12 34 10" src="https://user-images.githubusercontent.com/678344/53656383-20007900-3c21-11e9-8fcd-48aeddc63bbe.png">

Any idea what's going on?  Unfortunately I don't think I can share this dataset with you, so could be hard to reproduce.

**Comment by ericfischer** [comment]
That does look bad. It would be great to be able to try with your data, but I have parcel data for some US counties and will see if anything similar happens with them.

**Comment by ericfischer** [comment]
I'm not sure how to diagnose this without seeing your data. I tried with the parcels of Indianapolis, IN with Tippecanoe v1.32.12 and

```
tippecanoe -P -z11 --cluster-densest-as-needed -f -o parcels11.mbtiles Parcels.json
```

and the coverage looks reasonable at all zoom levels, without uneven gaps.

![screen shot 2019-03-01 at 11 41 39 am](https://user-images.githubusercontent.com/1951835/53662155-1540e680-3c17-11e9-8e50-17a955ae505c.png)

If you are seeing nothing at all in South Dakota, that suggests that no data is making it into the processing. Could you try without `--read-parallel` in case the problem is that the input JSON is formatted in such a way that parallel reading fails?

**Comment by stevage** [comment]
Thanks, it's definitely possible that something just messed up with my data processing. It's easy to make mistakes when each run takes a few hours. I'll keep poking and try to find something more definitive.

Also experimenting with other forms of "coverage visualisation". There are so many to choose from :)

**Comment by stevage** [comment]
Ok I have confirmed that I messed up my upstream processing. Sorry for wasting your time!
