### ISSUE TITLE
way of disabling over zooming

### ISSUE THREAD

**Issue by las3rlars** [mapbox/tippecanoe#726]
Hi, I'm using a engine that does not handle over zooming very well. I'm curious if its possible to disable over zooming and make tippecanoe to generate _every_ tile. From what I understand is that if a tile's children does not add any new data already present in their parent, tippecanoe skips creating the children.

Is  there a way to force the creation of the children? Even if it's redundant data.

Best regards

**Comment by ericfischer** [comment]
I think you misunderstand. For every zoom level where tippecanoe is generating tiles, it generates every tile that contains data at that zoom level. Overzooming is only for entire zoom levels beyond the maxzoom, not per tile.
