### ISSUE TITLE
tippecanoe-decode - zoom restrictions ignored when decoding directories

### ISSUE THREAD

**Issue by TerenceSperringerJr** [mapbox/tippecanoe#727]
Example usage:
`tippecanoe-decode -z 14 -Z 14 "$tiles_directory"`

This seems to generate output that includes every zoom level, so I am currently using the following half-fix (though I don't pretend to understand all of the inner-workings of what is going on, this does seem to ignore non-desired zoom levels):

decode.cpp

> 346:       `for (size_t i = 0; i < tiles.size(); i++) {`
> +**347:  ___`if((tiles[i].z >= minzoom) && (tiles[i].z <= maxzoom)) {`**
> 348:        ______`if (!pipeline && !stats) {`
...
> 376:        ______`handle(s, tiles[i].z, tiles[i].x, tiles[i].y, to_decode, pipeline, stats, state);`
> +**377:  ___`}`**
> 378:        `}`

I'm probably not using the exact correct fix, but since this seems to isolate the zoom level I need I thought I'd mention it.

See also #687

**Comment by ericfischer** [comment]
Thanks! Good catch. I'll take a look and get this fixed.

**Comment by ericfischer** [comment]
This will be fixed in https://github.com/mapbox/tippecanoe/pull/735. Same idea as your patch, but excludes the unwanted zoom levels earlier in the process.

**Comment by ericfischer** [comment]
Fixed in https://github.com/mapbox/tippecanoe/pull/735
