### ISSUE TITLE
`--exclude` after `--feature-filter`

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/tippecanoe#729]
I'm trying to use an attribute in a feature filter, but then have that attribute excluded in the output.

Currently if I pass a `--feature-filter` in first and then subsequently `--exclude` an attribute used by that feature filter, the feature filter won't work, complaining the attribute is missing.

**Comment by andrewharvey** [comment]
I guess the workaround is to follow up with a `tile-join -x excluded_attribute` to subsequently drop the attribute.

**Comment by ericfischer** [comment]
Thanks. This is tricky; filters used to run earlier in the process, but I moved them to the tiling stage so they could be aware of the zoom level. It would also work to have `--exclude` run late, but that would use a lot more space in the temporary files for attributes that would not ultimately make it into the tiles. Maybe I can delay the exclusion of attributes that filters depend upon.

The other thing you should be able to do now is to use `"attribute-filter"` to remove the attribute as the last stage of filtering, although that is probably also tricky to make happen in the right sequence.

**Comment by andrewharvey** [comment]
Ah you're right, I can use `attribute-filter` to remove it after filtering in the same feature-filter file. From my testing, doing this as the last step seems to work!
