### ISSUE TITLE
Unknown format file from tippecanoe with no compression

### ISSUE THREAD

**Issue by MauroGentile** [mapbox/tippecanoe#732]
Hi,

I have a GeoJSON file with small adjacent 10x10 meters squares, each carrying roughly 40 fields of properties. The input file size is 250Mb.

If I push the file to mapbox using the rest API command, it gets correctly converted into a tileset which can be correctly displayed on a map. I conclude that the input file is bug free.

As next step, I would like to use tippecanoe to convert GeoJSON to mbtiles in order to have a better control over the several available parameters. The problem is that If I use tippecanoe with the default options, some squares get merged in larger squares. As a result in the plot I see a combination of small (10x10) squares and larger (merged) squares.

To avoid that, I tried to use the --no-tile-compression option. The corresponding mbtile output gets correctly generated but when I upload it in mapbox, I get a "unknown format" error message.

I have no idea what the problem could be.

Any hint?

Thank you

**Comment by andrewharvey** [comment]
What's the full command line you're using?

`--no-tile-compression` is not the right option, that will skip the deflate compression. It sounds like you're using the coalesce options which combines geometries together, which is something you say you don't want.

**Comment by MauroGentile** [comment]
hi Andrew,
you are right: —no-tile-compression is not the right option.
i use a plain tippecanoe -Z12 -z23 -o out.mbtiles in.json

as you see i do not use the —coalesce option

this is the reason why i am surprised in the first place

**Comment by ericfischer** [comment]
You might be seeing what Tippecanoe calls "tiny polygon reduction," where a sample of polygons smaller than a pixel get represented as larger squares. Try `--no-tiny-polygon-reduction` to see if that helps.
