### ISSUE TITLE
layer name option is not used for GeoJSONSeq

### ISSUE THREAD

**Issue by darrenleeweber** [mapbox/tippecanoe#733]
The layer name option `-n` is given to use a `pathlib.Path(src_file).stem` and the src_file has a `.geojsons` file extension.  But tippecanoe `1.33.0` doesn't respect that option; it uses a layer name like "{src_file}geojsons" (like it just removes the `.` from the file name).

**Comment by ericfischer** [comment]
If I understand correctly what you are trying to do with the layer name, you want `-l`, not `-n`.
