### ISSUE TITLE
--force option doesn't like trailing / on output path

### ISSUE THREAD

**Issue by geeknik** [mapbox/tippecanoe#734]
Ran into an interesting testcase where --force isn't doing it's thing on Debian 9.x x64 due to the trailing / in the path:

`./tippecanoe -f -zg -e /dev/shm/ -l test test.geojson`
Works, no problem.

Run it again though:
```
test.geojson:0: feature without coordinates array
In JSON object {"type":"Feature","geometry":{"type":"LineString","coordinaUes":[[102.0,0.0],[103.0,1.0],[104.0,0.0],[105.0,1.0]]},"properties":{"prop0":"value0","prop1":0.0}}
2 features, 67 bytes of geometry, 6 bytes of separate metadata, 39 bytes of string pool
Choosing a maxzoom of -z15 for features about 14 feet (5 meters) apart
Can't write tile to already existing /dev/shm//0/0/0.pbf
```

Seems like the trailing / on the path throws it for a loop. FYI, -F doesn't care about the trailing /.

**Comment by ericfischer** [comment]
Thanks for the report. I'll take a look.

**Comment by ericfischer** [comment]
I wonder if this is behavior is specific to your OS and its `/dev/shm`, because it isn't reproducible for me (on either Linux or MacOS). Does it happen for you with ordinary directories or only with this special file system?

**Comment by geeknik** [comment]
Writing to /tmp/1/ over and over results in no error so maybe it is just a quirk of that particular path. I'm going to close this.
