### ISSUE TITLE
Cannot clone repo on Ubuntu

### ISSUE THREAD

**Issue by adamczi** [mapbox/tippecanoe#736]
I'm cloning repo in a way that is described in the `README.md`:
`git clone git@github.com:mapbox/tippecanoe.git`

Expected result: cloned repo
Actual result:
```
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by ericfischer** [comment]
Oh, you're right: the instructions assume you have a GitHub account, but it would be better for them to use anonymous HTTP access. I'll fix that.

**Comment by ericfischer** [comment]
This will be fixed in https://github.com/mapbox/tippecanoe/pull/735/commits/7419d64aab039ea057b0495ee37ea556a5aa41cc

**Comment by adamczi** [comment]
Very minor issue, but thanks a lot!
