### ISSUE TITLE
GeoJSON extension prevents overzooming 

### ISSUE THREAD

**Issue by Zbychus** [mapbox/tippecanoe#737]
I use special algorythm to define which objects to include at each level and I use GeoJSON extension with "tippecanoe" : { "maxzoom" : X "minzoom" : X }. Unfortunatelly I have discovered that when it is used, the objects are not shown with zoom > maxzoom, i.e. are not included when overzooming. It happens even if all objects have same maxzoom value. Is that right ?. Probably as a workaround I could separate them in different layers, however as they are of the same nature with just different property values I wanted to keep them in the same layer. Maybe adding "allow-overzoom" property in GeoJSON extrension could help ?

**Comment by ericfischer** [comment]
Unfortunately Tippecanoe has no control over this, and only features that appear in the highest-numbered zoom level of the entire tileset will be overzoomed by the renderer. If you want this to work I think you will have to separate them into multiple tilesets, not just multiple layers.
