### ISSUE TITLE
Can't use --use-attribute-for-id with no other attributes

### ISSUE THREAD

**Issue by stevage** [mapbox/tippecanoe#738]
I have a dataset that contains a single attribute, which I want to use as a feature ID. Then, because it would be redundant, I don't want to also include it as an attribute.

Unfortunately all of these attempts resulted in no attributes, and no feature ID:

```
tippecanoe --use-attribute-for-id=bbl --convert-stringified-ids-to-numbers --exclude-all
tippecanoe --use-attribute-for-id=bbl --convert-stringified-ids-to-numbers --include=
tippecanoe --use-attribute-for-id=bbl --convert-stringified-ids-to-numbers --exclude=bbl
tippecanoe --use-attribute-for-id=bbl --convert-stringified-ids-to-numbers --include=nonexistent
```

There doesn't seem to be any way to end up with no attributes, just the feature ID?

By contrast, `--include`-ing one attribute (not the one used for feature id) does seem to work: the feature id attribute gets dropped, you get a feature id, and just the one attribute you specify.

**Comment by ericfischer** [comment]
The way it was meant to work was that `--use-attribute-for-id` should convert the named attribute to the ID and then remove it from the attribute set, without requiring any `--exclude-all` or `--exclude` or `--include`.

So giving

```
{ "type": "Feature", "properties": { "id": 27, "other": 28 }, "geometry": { "type": "LineString", "coordinates": [ [ 50, 50 ], [ 30, 30 ] ] } }
{ "type": "Feature", "properties": { "id": 29 },  "geometry": { "type": "LineString", "coordinates": [ [ 40, 40 ], [ 20, 20 ] ] } }
```

to

```
tippecanoe -z0 -f -o id.mbtiles --use-attribute-for-id=id id.json
```

yields

```
{ "type": "Feature", "id": 29, "properties": {  }, "geometry": { "type": "LineString", "coordinates": [ [ 39.990234, 40.044438 ], [ 19.951172, 20.055931 ] ] } },
{ "type": "Feature", "id": 27, "properties": { "other": 28 }, "geometry": { "type": "LineString", "coordinates": [ [ 49.921875, 50.007739 ], [ 29.970703, 30.069094 ] ] } }
```

with the `id` attribute moved to the feature ID, and any other attributes, if present, left as they were.

Can you give an example where it goes wrong?

**Comment by ericfischer** [comment]
https://github.com/mapbox/tippecanoe/pull/716 was supposed to fix the problem where `--exclude` could exclude the attribute being converted.

**Comment by stevage** [comment]
Huh, that's interesting. I seem to be really good at trying all the ways that don't work. That does seem to work. Also, surprisingly, so does `--include=bbl`. (And even weirder, the `bbl` attribute still gets dropped from the properties).

I guess it just didn't match my expectation, that fields would remain unless explicitly dropped. I don't think always dropping the field is the right choice either, hmm.

**Comment by ericfischer** [comment]
Either before or after that PR it would always move, rather than copy, the attribute to the feature ID.

With your slightly old version of Tippecanoe, `--include=bbl` works because you are saying to exclude all attributes other than `bbl`, which then gets converted to the ID. All your other option variations exclude `bbl`, either by name or as part of everything, which (before the PR) happens before the conversion, losing it.

**Comment by stevage** [comment]
Oh, sorry, I missed that you were saying that the PR has addressed issue, and I just needed to upgrade. Done now. Thanks for your help.

**Comment by ericfischer** [comment]
Great, glad it's working for you now!

**Comment by aweinmacher** [comment]
> #716 was supposed to fix the problem where `--exclude` could exclude the attribute being converted.

Hi @ericfischer I feed that my issue is somewhat connected the this one: what if I DON'T want to remove my attribute from properties but still want its copy to become feature id. I'm not using any flags like --exclude or --include. Is there any way to do so?

**Comment by ericfischer** [comment]
There is not a way to do this currently. If you want the ID to be populated from an attribute and to have another attribute with the same value, you will need to include two attributes with the same value.

**Comment by aweinmacher** [comment]
> There is not a way to do this currently. If you want the ID to be populated from an attribute and to have another attribute with the same value, you will need to include two attributes with the same value.

Thank you, did so
