### ISSUE TITLE
Generate vector tiles for dynamic data

### ISSUE THREAD

**Issue by geoyogesh** [mapbox/tippecanoe#741]
I have million features stored in PostgreSQl table (with PostGIS extension).

I can generate vector tiles by performing below steps

Generate GeoJSON from PG table using GDAL
Generate vector files in folder format using tippecanoe
Sync the features to S3
Then using Mapbox gl js layer is rendered in map

Now we are trying to add editing functionality. so that users can add, edit or delete features.

Is there a way to efficiently generate vector tiles with new created features using tippecanoe and keep the vector tiles up to date?

Is tippecanoe is right tool for this job?

**Comment by ericfischer** [comment]
Tippecanoe is perhaps not the right tool for the job, but you can use a combination of `tippecanoe` and `tile-join` to update tilesets without retiling all the features.

## Add features to a tileset

* Use `tippecanoe` to generate a tileset of just the new features
* Use `tile-join` to merge the existing tileset and the tileset of new features into a combined tileset

```
tippecanoe -o new.mbtiles new.json
tile-join -o combined.mbtiles new.mbtiles old.mbtiles
```

## Remove features from a tileset

* Use `tile-join` with a `--feature-filter` filter that removes the features with any `$id` that no longer belongs to a current feature.

```
tile-join -o filtered.mbtiles -j '{ "*": [ "!in", "$id", 3432, 2354, 8745, 8374 ] }' old.mbtiles
```

**Comment by geoyogesh** [comment]
thanks for your response...

Great..I can also perform edit operation as delete and add feature...

is there a way to generate folder output (requested for pushing the tiles in S3) from mbtile (whole dataset)?

is there a way to generate folder output from mbtile for the features which falls within specified extent?.. so that i can override those tiles in folder output..

**Comment by ericfischer** [comment]
You can use https://github.com/mapbox/mbutil or `tile-join -e` to copy mbtiles to a directory of tiles.

I do not currently have a mechanism to clip an existing tileset to new bounds.

**Comment by geoyogesh** [comment]
I am using tippecanoe to serve around 50 data layers in production and it works splendidly. 

It wound be great If you guys can support the dynamic data workflow in future..

 Thanks

**Comment by ericfischer** [comment]
Thanks. We are planning for dynamic updates in the future.
