### ISSUE TITLE
Edit a tile 

### ISSUE THREAD

**Issue by omrivolk** [mapbox/tippecanoe#742]
Hi,
My issue is this - I have 2 sets of polygons for water which I use for routing sail boats. One for coastlines and one for rivers. I need to union them so that a sail boat could cross from the open ocean to a river without crossing a polygon boundary. Doing it on a global level before data is tiled is too hard. The data size is just too big. So I want to (1) tile the data, then (2) decode the polygons in the tile, (3) run a join operation on them and then (4) return them to the sqlite database. The problem is step 4. If I used tippeacanoe-deocde for step (2), is there a way to reverse that after the join operation? Thanks

**Comment by ericfischer** [comment]
The built-in way to handle per-tile filtering is with `tippecanoe -C script`, which lets the specified script preprocess the GeoJSON for each tile before it is placed into the tileset.

Alternately, if you use a tile buffer of 0 (`-b0`), running the output of `tippecanoe-decode -c` back into Tippecanoe should produce a new tileset with the same features as the tileset that you decoded, and you could do your filtering in between the `tippecanoe-decode` and the second-stage `tippecanoe`.

**Comment by omrivolk** [comment]
Perfect! `-C` is exactly what I was looking for. Thanks.  Is there a way I can run it on a single layer other than checking the ` "tippecanoe": { "layer":....}` for each individual feature?

**Comment by ericfischer** [comment]
There is not currently a way to do that (since most of the tiling stage wants to see the features in geometric order, not layer order), so currently your script will have to check the layer name manually.

**Comment by omrivolk** [comment]
Thanks. That's good enough for me.

**Comment by omrivolk** [comment]
`-C` seems to have a pretty large overhead. The way I'm running it is:
```
-Z11 -z11  \
-C 'if [ $1 -lt 11 ]; then cat; else python ./tools/union_osm_water.pyo $*; fi' \
```
I've noticed that still makes tiles at lower zoom levels and that processing the lower zoom is much longer than it used to be before I added the script, meaning just the `if` block is taking some time.

Is there a smarter/faster way I can run some python code on zoom level 11 only with less overhead?

**Comment by ericfischer** [comment]
Oh, good catch! It ought to only run the filter for the zoom levels that are included in the output, not when it is simply breaking up tiles into the higher zooms. I'll see if I can fix that.

**Comment by ericfischer** [comment]
Please try https://github.com/mapbox/tippecanoe/pull/745, which I think should fix the problem.

**Comment by omrivolk** [comment]
That works great for speeding up levels 1-10. Thanks!
I'm gonna try my luck here - there is still a an overhead on zoom level 11 for script startup time. Do you see a way I can improve this other than writing my filter directly into tile.cpp?

**Comment by ericfischer** [comment]
I don't currently have any way to avoid the shell startup time for each tile.

**Comment by omrivolk** [comment]
Thanks anyway. Closing this

**Comment by jliebrand** [comment]
Hi @ericfischer - just a quick question on this: am I correct in thinking that this pre/post processing script isn't run in parallel on multiple cores? Without this script it took 3 hours to process our geojson in to an mbtileset. But with the script (even if the script did as good as nothing) it took days... Just wondering where the bottleneck is and if running it on a different machine (more mem? more cpu?) would help

**Comment by ericfischer** [comment]
I am not actually sure how waiting for subprocesses to run interacts with a multithreaded program, but it sounds like the interaction is not great. Maybe the answer is to embed a scripting language within Tippecanoe itself, but I had been hoping to avoid that complexity.
