### ISSUE TITLE
Wrong display mbtiles file , using mbview

### ISSUE THREAD

**Issue by xiaofsu** [mapbox/tippecanoe#747]
`{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties": {
                "hpa": 103200
            },
            "geometry": {
                "type": "MultiLineString",
                "coordinates": [
                    [
                        [254,35],
						[204,35],
						[204,30],
						[254,30],
						[254,35]
                    ]
                ]
            }
        }
    ]
}`

Hello:
The command I am using is
  Tippecanoe -o *.mbtiles -zg --drop-densest-as-needed *.json

I use [254,35],[204,35],[204,30],[254,30],[254,35] for this set of data.
Not shown on the map.

When I use the data set [-164, 35], [-174, 35], [-174, 30], [-164, 30], [-164, 35], I can display it on the map normally.

When I use the data of [114, 35], [204, 35], [204, 30], [114, 30], [114, 35], I can also display it on the map normally.

I would like to ask, what is the agreement that tippecanoe follows? Why can't a group of data be displayed on the map when it is at the same time (>180° | < -180°)?

**Comment by xiaofsu** [comment]
> { "type": "FeatureCollection", "features": [ { "type": "Feature", "properties": { "hpa": 103200 }, "geometry": { "type": "MultiLineString", "coordinates": [ [ [254,35], [204,35], [204,30], [254,30], [254,35] ] ] } } ] }

**Comment by xiaofsu** [comment]
Use mbview to display generated mbtiles files.
Thanks you.

**Comment by ericfischer** [comment]
Thanks for the report! This will be fixed in https://github.com/mapbox/tippecanoe/pull/748. It previously only allowed out-of-range longitudes if the features also overlapped the normal longitude range.

**Comment by ericfischer** [comment]
Merged
