### ISSUE TITLE
The generated mbtiless data is not what I want.

### ISSUE THREAD

**Issue by xiaofsu** [mapbox/tippecanoe#750]
`{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"wh":1,"color":"rgba(156,222,187,1)"},"geometry":{"type":"Polygon","coordinates":[[[360.1,40],[340.1,40],[340.1,10],[360.1,10],[360.1,40]]]}},{"type":"Feature","properties":{"wh":1,"color":"rgba(156,222,187,1)"},"geometry":{"type":"Polygon","coordinates":[[[0.1,40],[20.1,40],[20.1,10],[0.1,10],[0.1,40]]]}},{"type":"Feature","properties":{"wh":2,"color":"rgba(156,222,187,1)"},"geometry":{"type":"Polygon","coordinates":[[[360.1,30],[355,31],[350,28],[351,21],[353,25],[360.1,21],[360.1,30]]]}},{"type":"Feature","properties":{"wh":2,"color":"rgba(156,222,187,1)"},"geometry":{"type":"Polygon","coordinates":[[[0.1,30],[5.2,31],[8.3,27],[8,25],[7,25],[0.1,21],[0.1,30]]]}},{"type":"Feature","properties":{"wh":2,"color":"rgba(156,222,187,1)"},"geometry":{"type":"Polygon","coordinates":[[[360.1,30],[355,31],[350,28],[351,21],[353,25],[353,25],[360.1,21],[360.1,30]]]}},{"type":"Feature","properties":{"wh":2,"color":"rgba(156,222,187,1)"},"geometry":{"type":"Polygon","coordinates":[[[0.1,30],[5.2,31],[8.3,27],[8,25],[7,25],[0.1,21],[0.1,30]]]}}]}`

The command I am using is:

> tippecanoe -o *.mbtiles -zg --drop-densest-as-needed *.json

Hello, I want to use this set of data to generate mbtiles files. But the generated data is not what I want. You can see the following pictures.

![image](https://user-images.githubusercontent.com/46067472/56104835-0797b400-5f6c-11e9-9f33-ea8b57c6b319.png)

Why are there two lines or the line is not at the edge of the face?

![image](https://user-images.githubusercontent.com/46067472/56104882-344bcb80-5f6c-11e9-8f74-23222717dd7e.png)

Left x: 360.1, right x: 0.1
Why is there a gap in the middle?

![image](https://user-images.githubusercontent.com/46067472/56104912-5ba29880-5f6c-11e9-9424-f3b8f6aa9286.png)

This is the line I generated using geojson and it looks normal.

![image](https://user-images.githubusercontent.com/46067472/56104925-6e1cd200-5f6c-11e9-8107-3422bbecf711.png)

This is the combination surface I generated using geojson and it looks normal.

Thank you.

**Comment by ericfischer** [comment]
These polygon artifacts come from a bug in the way Mapbox GL displays heavily overzoomed polygons. (Sorry, I can't find the ticket right now.) The workaround is to set a higher maxzoom with `-z`.
