### ISSUE TITLE
Feature Request: Support for Oracle Database

### ISSUE THREAD

**Issue by leoberteck** [mapbox/tippecanoe#751]
Hello I am implementing a solution using the Oracle Database and I noticed that Oracle has nothing like Tippecanoe that works inside the database. Do you think it is at leas possible to compile tippecanoe in a manner that it can be used as shared library inside Oracle using PL/SQL proxy procedure?

If this is not possible, it would be great to have a way to call tippecanoe from the shell and have it output its values to oracle tables and not to a SQLite file.

Currently, in order to have my tilesets stored on my Oracle Database I had to created a nodejs program that calls tippecanoe with a geojson file as input than connects to both the mbtiles file and my Oracle Database to transfer the tile data.

I will wait eagerly for a feedback.

Respectfully,

Leonardo B Stabile.

**Comment by ericfischer** [comment]
I don't think there is any reasonable way to make Tippecanoe into a shared library.

The code to write tiles in mbtiles format is fairly tightly isolated in [mbtiles.cpp](https://github.com/mapbox/tippecanoe/blob/master/mbtiles.cpp), and there is, for example, also [dirtiles.cpp](https://github.com/mapbox/tippecanoe/blob/master/dirtiles.cpp) to write tiles to a directory instead. Supporting other tile storage backends is not a priority for development, but I would be happy to accept a PR that adds a good generic way to interface with other storage backends.

**Comment by ericfischer** [comment]
(The reason it's not practical to make it into a shared library is that there are a large number of places in the code that exit when they detect an error instead of propagating errors up to the caller. This is OK for a program to do, but not OK for a library to do.)

**Comment by leoberteck** [comment]
Hmmm I understand.... you got a good point.
