### ISSUE TITLE
About more than 360° can not be displayed on the map

### ISSUE THREAD

**Issue by xiaofsu** [mapbox/tippecanoe#752]
`{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"wh":1,"color":"rgba(156,222,187,1)"},"geometry":{"type":"Polygon","coordinates":[[[360.1,40],[360.1,10],[350,10],[350,40],[360.1,40]]]}},{"type":"Feature","properties":{"wh":2,"color":"rgba(156,222,187,1)"},"geometry":{"type":"Polygon","coordinates":[[[360.1,30],[365.2,31],[368.3,27],[368,25],[367,25],[360.1,21],[360.1,30]]]}}]}`

Sorry to bother again.
The above data is not displayed on the map.

![image](https://user-images.githubusercontent.com/46067472/56175792-4e001800-602b-11e9-806e-df19776d848b.png)

What data should I change to show up? Also avoid the #750 problem?

![image](https://user-images.githubusercontent.com/46067472/56175906-c2d35200-602b-11e9-95b8-c85ca23875c1.png)

Thank you.

**Comment by ericfischer** [comment]
Coordinates beyond 360° are not accepted. After https://github.com/mapbox/tippecanoe/pull/748 you should have a full 180° of wraparound off either side of the earth, so please constrain your longitudes to (-360…360).

I misunderstood what problem you were running into in https://github.com/mapbox/tippecanoe/issues/750 and thought it was a rendering issue, not a coordinate issue. Now that I have reread the issue, I think the answer is the same: please constrain your longitudes to (-360…360).
