### ISSUE TITLE
What's the difference between z20 with Z15 z20?

### ISSUE THREAD

**Issue by dythbj** [mapbox/tippecanoe#753]
Hi all:
 I have make a test ,the steps like these:
 case 1: 
            tippecanoe -z 20 -L admin:admin.geojson -o admin.mbtiles
 case 2:
            step 1: tippecanoe -z 14 -L admin:admin.geojson -o admin0.mbtiles
            step 2: tippecanoe -Z15 -z20 -L admin:admin.geojson -o admin1.mbtiles
            step 3: tile-join admin0.mbtiles admin1.mbtiles -o admin.mbtiles

 The question are:
 1) In case 2, the step 2 process is very very slow, why?
 2) In case 2, the file size of admin1.mbtiles is much more bigger than admin.mbtiles(case 1), 
     why?

 Is there any idea?Thanks!

**Comment by ericfischer** [comment]
I don't know any reason why `tippecanoe -Z15 -z20` should be slower than `tippecanoe -z20`. Creating the tiles for all zoom levels should be slower than creating just some of them.

If you can share your data, I can take a look and see if I can reproduce the problem.

**Comment by dythbj** [comment]
Thanks Eric:
I have send you another data(water.json), they have the same problem.


原始邮件
发件人:Eric Fischernotifications@github.com
收件人:mapbox/tippecanoetippecanoe@noreply.github.com
抄送:dythbjgaojie@dyth.tech; Authorauthor@noreply.github.com
发送时间:2019年4月20日(周六) 01:56
主题:Re: [mapbox/tippecanoe] What's the difference between z20 with Z15z20? (#753)


I don't know any reason why tippecanoe -Z15 -z20 should be slower than tippecanoe -z20. Creating the tiles for all zoom levels should be slower than creating just some of them.
If you can share your data, I can take a look and see if I can reproduce the problem.

**Comment by dythbj** [comment]
Thanks Eric:
I have send you another data(water.json), they have the same problem.
The data’s download link is:https://pan.baidu.com/s/1FlslNstX1xayLjiK0d00IQ
Thanks again!!!


原始邮件
发件人:Eric Fischernotifications@github.com
收件人:mapbox/tippecanoetippecanoe@noreply.github.com
抄送:dythbjgaojie@dyth.tech; Authorauthor@noreply.github.com
发送时间:2019年4月20日(周六) 01:56
主题:Re: [mapbox/tippecanoe] What's the difference between z20 with Z15z20? (#753)


I don't know any reason why tippecanoe -Z15 -z20 should be slower than tippecanoe -z20. Creating the tiles for all zoom levels should be slower than creating just some of them.
If you can share your data, I can take a look and see if I can reproduce the problem.

**Comment by mjj203** [comment]
I get the same issue when using an external filter called in by `-J` that start the min zoom at 4 and builds to max zoom 15. In the logs it seems Tippecanoe is trying to build at zoom level 0-3 then after trying to build it moves on, instead of just starting at zoom level 4.

**Comment by dythbj** [comment]
> I get the same issue when using an external filter called in by `-J` that start the min zoom at 4 and builds to max zoom 15. In the logs it seems Tippecanoe is trying to build at zoom level 0-3 then after trying to build it moves on, instead of just starting at zoom level 4.

Yes, the same problem

**Comment by mjj203** [comment]
pnt.filter:```{
       "*" : [
               "any",
                       ["all", [">=", "$zoom", 4],  ["==", "ZI026_CTUU", 1000000]],
                       ["all", [">=", "$zoom", 6],  ["in", "ZI026_CTUU", 500000, 250000]],
                       ["all", [">=", "$zoom", 11], ["in", "ZI026_CTUU", 200000, 0]],
                       ["all", [">=", "$zoom", 13], ["in", "ZI026_CTUU", 100000, 50000, 0]],
                       ["all", ["<=", "$zoom", 14]]
       ]
}```
`tippecanoe -t ${TEMP} -f -o ${MBTILES} -P --simplify-only-low-zooms --drop-densest-as-needed -M 2000000 -D 10 -d 12 -Z 4 -z 14 -ae -J ${FILTER_DIR}/pnt.filter -l ${FEATURE} -n ${FEATURE} ${NDJSON}`

This is an example script and the filter used to convert a point file of roughly 96 million features from ndjson created by tippecanoe-json-tool that has also been compressed to max compression with gzip. It takes roughly 35min using the filter and starting at `-Z 4`, but take 28-30min if the filter starts at zoom level 0 and `-Z 0`. This is on a i3.metal ec2 instance with 8x nvme drives in raid 0 as the data disk, 72 vCPUs and 512GB Ram.

**Comment by ericfischer** [comment]
I haven't tried to reproduce this yet, but the one thing I can think of is that I may have guessed wrong about CPU time vs. I/O performance.

If you tile starting at z0, every tile is split out into exactly four simultaneous child tiles for the next zoom level. If you tile starting at a higher zoom, it tries to do more simultaneous splitting (based on the number of CPUs you have and the number of files your OS allows to have open at once) to get right to the first zoom level that you want, on the theory that it will be faster to write multiple files than to work through the intermediate zoom levels to split up tiles incrementally.

I may have guessed wrong, and the I/O penalty of writing many files at once may actually be worse than the CPU penalty of working through the intermediate zoom levels.

**Comment by ericfischer** [comment]
As far as I can tell (not speaking the language) that download link leads to a disk image of an application, not to a data file. I can't investigate this without access to the data.

**Comment by mjj203** [comment]
> I haven't tried to reproduce this yet, but the one thing I can think of is that I may have guessed wrong about CPU time vs. I/O performance.
> 
> If you tile starting at z0, every tile is split out into exactly four simultaneous child tiles for the next zoom level. If you tile starting at a higher zoom, it tries to do more simultaneous splitting (based on the number of CPUs you have and the number of files your OS allows to have open at once) to get right to the first zoom level that you want, on the theory that it will be faster to write multiple files than to work through the intermediate zoom levels to split up tiles incrementally.
> 
> I may have guessed wrong, and the I/O penalty of writing many files at once may actually be worse than the CPU penalty of working through the intermediate zoom levels.

That might be the issue, because it takes a really long time to go from 0%-6.6% then hangs at 6.6% before jumping to 26.6% at zoom level 4.
```
96299826` features, 3670858322 bytes of geometry, 64 bytes of separate metadata, 3852053470 bytes of string pool
  0.1%  0/0/0  
  0.2%  0/0/0  
  0.4%  0/0/0  
  0.5%  0/0/0  
  0.6%  0/0/0  
  0.7%  0/0/0  
  0.8%  0/0/0  
  0.9%  0/0/0  
  1.0%  0/0/0  
  1.1%  0/0/0  
  1.3%  0/0/0  
  1.5%  0/0/0  
  1.6%  0/0/0  
  1.8%  0/0/0  
  2.0%  0/0/0  
  2.1%  0/0/0  
  2.2%  0/0/0  
  2.4%  0/0/0  
  2.5%  0/0/0  
  2.6%  0/0/0  
  2.7%  0/0/0  
  2.9%  0/0/0  
  3.0%  0/0/0  
  3.1%  0/0/0  
  3.2%  0/0/0  
  3.4%  0/0/0  
  3.5%  0/0/0  
  3.6%  0/0/0  
  3.7%  0/0/0  
  3.9%  0/0/0  
  4.0%  0/0/0  
  4.1%  0/0/0  
  4.2%  0/0/0  
  4.3%  0/0/0  
  4.4%  0/0/0  
  4.5%  0/0/0  
  4.6%  0/0/0  
  4.7%  0/0/0  
  4.8%  0/0/0  
  4.9%  0/0/0  
  5.0%  0/0/0  
  5.1%  0/0/0  
  5.2%  0/0/0  
  5.3%  0/0/0  
  5.4%  0/0/0  
  5.5%  0/0/0  
  5.6%  0/0/0  
  5.7%  0/0/0  
  5.8%  0/0/0  
  5.9%  0/0/0  
  6.0%  0/0/0  
  6.1%  0/0/0  
  6.2%  0/0/0  
  6.3%  0/0/0  
  6.4%  0/0/0  
  6.5%  0/0/0  
  6.6%  0/0/0  
  26.6%  4/10/4  
```
Attached is the full log, custom filter, and script used. I cant attach the data since its 6GB compressed and its DoD FOUO/LIMDIS.
[Documents.zip](https://github.com/mapbox/tippecanoe/files/3105112/Documents.zip)

**Comment by dythbj** [comment]
> As far as I can tell (not speaking the language) that download link leads to a disk image of an application, not to a data file. I can't investigate this without access to the data.

Sorry ericfischer, you can download the data [here](http://47.95.2.104/water.geojson.zip).
Look forward to your reply！！！

**Comment by dythbj** [comment]
> As far as I can tell (not speaking the language) that download link leads to a disk image of an application, not to a data file. I can't investigate this without access to the data.

Any ideas?

**Comment by ericfischer** [comment]
Sorry I didn't see your reply earlier. Thanks for sending the data.

I still can't reproduce the core problem: tiling all the zoom levels of `water.geojson` to z11 still takes a little longer (13m20s) for me than tiling just z10 and z11 (12m27s). I will try again with a higher maxzoom and see if I can reproduce the performance problem there.

**Comment by ericfischer** [comment]
It also seems to be much faster (30m5s) to tile just z12 than to tile all zooms up to 12 (40m58s), so I still don't have a lead on this.

**Comment by dythbj** [comment]
Thanks for you reply, I also try to tile to z16,and it already took about 36 hours, but not finish yet, and the mbtiles file is already 65GB...

**Comment by dythbj** [comment]
And my cod is :tippecanoe -an -z16 -M 30000 -L water:water.geojson -o water.mbtiles

**Comment by ericfischer** [comment]
Your water bodies cover a large fraction of the world, and z16 is a very deep zoom level to tile to, so this will create as many as 4 billion tiles (4^16) and it is not surprising that it is big and slow.

`tippecanoe -zg` suggests that z11 should be sufficient for the precision of the geometry, which is much faster and a produces much more modest file size. Please reevaluate whether you actually need oceans full of z16 tiles or whether you can get away with slightly lower precision. Each zoom level lower that you can go should cut your file size and processing time in half.

**Comment by dythbj** [comment]
Yes,I have tried the ‘-zg’, but i did need to tile to z16, so what’s your suggestion to get away with slightly lower precision?

**Comment by dythbj** [comment]
> Your water bodies cover a large fraction of the world, and z16 is a very deep zoom level to tile to, so this will create as many as 4 billion tiles (4^16) in that zoom level and it is not surprising that it is big and slow.
> 
> `tippecanoe -zg` suggests that z11 should be sufficient for the precision of the geometry, which is much faster and a produces much more modest file size. Please reevaluate whether you actually need oceans full of z16 tiles or whether you can get away with slightly lower precision. Each zoom level lower that you can go should cut your file size and processing time in half.

And my needs are : 
     1) --maximum-tile-bytes=10000, when zoom level between L0 - L5
     2) --maximum-tile-bytes=30000, when zoom level between L6 - L16
So, i have to make it by 3 steps:
     1) tippecanoe -an -M 10000 -z5 -L water:water.geojson -o water5.mbtiles
     2) tippecanoe -an -M 30000 -Z6 -z16 -L water:water.geojson -o water16.mbtiles
     3) tile-join water5.mbtiles water16.mbtiles -o water.mbtiles

**Comment by ericfischer** [comment]
Most of the tiles at z16 are just going to contain a single square, because they are entirely covered with water, so it does not matter how small you make the maximum tile size. Your tileset will be the same huge size no matter what, because there are just a lot of tiles at z16, even if each individual tile is very small. There is no way to make it smaller without lowering the maxzoom.

**Comment by dythbj** [comment]
> Most of the tiles at z16 are just going to contain a single square, because they are entirely covered with water, so it does not matter how small you make the maximum tile size. Your tileset will be the same huge size no matter what, because there are just a lot of tiles at z16, even if each individual tile is very small. There is no way to make it smaller without lowering the maxzoom.

Dear ericfischer, Thank you very much for your patience, as the result, I can only spend time waiting for it to complete...
