### ISSUE TITLE
Changing metadata

### ISSUE THREAD

**Issue by omrivolk** [mapbox/tippecanoe#758]
I want to change the `-n   -N   -A` attributes of a tile set. What's the easiest way?

Should `tile-join` work like this? 
`tile-join -n NEW_NAME -N NEW_DESCRIPTION -A NEW_ATTRIBUTION -o new.mbtiles old.mbtiles` 
Is the new tile set guaranteed to be exactly the same?

**Comment by ericfischer** [comment]
The new tileset is intended to be exactly the same, but the layers and features do get decoded and reencoded, so there is no guarantee that the new tileset will have exactly the same representation for each tile.

If you do need the tiles to be exactly the same, you could use `sqlite3` to replace rows of the `metadata` table without decoding and reencoding the tiles.

**Comment by omrivolk** [comment]
Thanks, that is a much better approach
