### ISSUE TITLE
decoder: Figure out x and y values of MVT pbf file?

### ISSUE THREAD

**Issue by baerbock** [mapbox/tippecanoe#762]
How may I figure out the x and y position of a given MVT pbf file with known zoom level, so I can decode it with
`tippecanoe-decode file.pbf zoom x y`
?

Is there any standalone pbf decoder (in C, C++ or Python) so I can peek inside my pbf file?

**Comment by ericfischer** [comment]
Unfortunately the PBF itself does not contain its X/Y/Z coordinates, so you can't decode it without knowing its geographic context.

You can use `protoc --decode_raw` to decode any PBF file on the command line, but `protoc` is a generic PBF tool that does not know the meaning of the Mapbox Vector Tile encoding within the PBF format.

**Comment by baerbock** [comment]
Thank you very much for the clarifications.

I have here a file called _12288-12543.pbf_. I'm pretty sure that the zoom level is 12. What would be the X/Y coordinates if the file follows the standard Mapbox naming scheme?

**Comment by ericfischer** [comment]
From the name I would have guessed that this would be tile 12/12288/12543, but the X and Y coordinates in zoom level 12 only go up to 4096, so that can't be. In z14 and up that X/Y pair exists but doesn't contain anything interesting.

**Comment by baerbock** [comment]
I've inherited a set of pbfs from a previous worker which now can't be contacted anymore.

I've found a similarly named file at Mapbox servers - shouldn't this have the same X/Y/Z positions?
https://api.mapbox.com/fonts/v1/webpresence/Open%20Sans%20Semibold,Arial%20Unicode%20MS%20Bold/12288-12543.pbf?access_token=pk.eyJ1Ijoid2VicHJlc2VuY2UiLCJhIjoiQ09xLTNsZyJ9.B5hlY44Kgjn2CSQ5swqWvA

**Comment by ericfischer** [comment]
This PBF is a font, not a vector tile. The numbers refer to a glyph range (U+3000 through U+30FF, https://unicode.org/charts/PDF/U3000.pdf).
