### ISSUE TITLE
Some features disappears from some tiles

### ISSUE THREAD

**Issue by maurofaccin** [mapbox/tippecanoe#767]
Hi,

I was trying to convert a geojson with several multipolygons covering big areas.
Unfortunately I find that some features are missing in some tiles:

![screenshot](https://user-images.githubusercontent.com/18699964/59495746-483e7b80-8e90-11e9-8fcb-ac944e42842a.png)

the command I use is the following:

`tippecanoe --force -l tbi -o tbi.mbtiles --minimum-zoom=8 --maximum-zoom=13 --reverse-source-polygon-winding --no-tile-compression TBIncidence.json`

The visualization is done through `tileserver-gl`.

**Comment by ericfischer** [comment]
Thanks for the report. Can you share your data file so I can diagnose what is causing the polygons not to be generated?

The problem is probably related to `--reverse-source-polygon-winding`, but the behavior of that should be consistent from one tile to the next.

**Comment by maurofaccin** [comment]
sure, this is not the same file as above but it gives the same issues (it happens at several zooms):

[data](https://maurofaccin.github.io/cartotb/datatb/skivu/TBIncidence.json)

thanks,

**Comment by ericfischer** [comment]
Thanks. I'll take a look.

**Comment by ericfischer** [comment]
The first problem I see see is that the large polygon at http://localhost:3000/#9.37/-3.1188/28.2395 is not appearing in z8 at at all after

```
tippecanoe --force -l tbi -o tbi.mbtiles --minimum-zoom=8 --maximum-zoom=13  /Users/enf/Downloads/TBIncidence.json
```

Similarly some polygons at http://localhost:3000/#12.72/-2.87632/27.17162 disappear in z11 and even more of them in z10.

**Comment by ericfischer** [comment]
I think you probably really want `--use-source-polygon-winding`, not `--reverse-source-polygon-winding`, but there is still some sort of bug when you have an isolated hole that has no parent ring to be cut out of, that sometimes causes it to be turned into an outer ring instead of being removed.

**Comment by maurofaccin** [comment]
Indded `--use-souce-polygon-winding` works much better. Maybe there is some problem with the algorithm behind `--reverse-source-polygon-winding`.

I was using the latter in particular because not using any of those options gave me some weird results with lots of polygons missing (from a hand check it seems that the algorithm only pick the first polygon in a multiplolygon feature). Maybe this is due to the fact that most of my geojsons are in fact Multipolygons.

**Comment by ericfischer** [comment]
The GeoJSON specification for multipolygons is that the first ring of each sub-polygon is the outer ring and the rings that follow are inner rings to be cut out of that first ring. If the GeoJSON that you are generating does not follow this rule, Tippecanoe will not be able to understand your intent.

**Comment by maurofaccin** [comment]
Thanks, this is my fault then. I'll check my code.
