### ISSUE TITLE
how to merge all geojson files into 1 single layer?

### ISSUE THREAD

**Issue by hoogw** [mapbox/tippecanoe#782]
I use this, it works, 

tippecanoe -zg -o counties-merged.mbtiles -l counties --coalesce-densest-as-needed --extend-zooms-if-still-dropping tl_2010_17_county10.geojson tl_2010_18_county10.geojson

However, I want to merge 50 geojson files for all 50 states into single layer, single mbtiles, 
type all 50 states name is a pain!

Is there any default setting automatically read all files within such folder and merge them all into 1 layer?

**Comment by ericfischer** [comment]
You can use a shell wildcard for multiple files:

```
tippecanoe -zg -o counties-merged.mbtiles -l counties --coalesce-densest-as-needed --extend-zooms-if-still-dropping dirname/*.geojson
```

**Comment by hoogw** [comment]
it works, thanks.

I run this:

tippecanoe -o microsoft_us_building_footprint.mbtiles -l microsoft_us_building_footprint -zg --drop-densest-as-needed --extend-zooms-if-still-dropping *.geojson

-l single layer name
-o output file
-zg auto max zoom level

**Comment by hoogw** [comment]
It works perfectly, now I be able to merge all 50 states into single geojson 28.8GB, then convert to mbtile as 3.8GB, here is result:

[https://transparentgov.net:3200/pbf/mapbox_default?&layer=microsoft_us_building_footprint&center_lat=38.907192&center_long=-77.036873&center_zoom=11&url=https://transparentgov.net/tileserver/microsoft_us_building_footprint/{z}/{x}/{y}.pbf](https://transparentgov.net:3200/pbf/mapbox_default?&layer=microsoft_us_building_footprint&center_lat=38.907192&center_long=-77.036873&center_zoom=11&url=https://transparentgov.net/tileserver/microsoft_us_building_footprint/{z}/{x}/{y}.pbf)
