### ISSUE TITLE
Map not visible for higher zoom levels. Generating tiles taking time for higher zoom levels.

### ISSUE THREAD

**Issue by nishanthdn96** [mapbox/tippecanoe#783]
I'm trying to generate vector tiles using tippecanoe. I have used --max-zoom=g option which generates tiles up to zoom level 9. Map-box loading tiles up to zoom level 18 only with over-zooming. But when I tried to generate tiles manually with --max-zoom=15 or above, it is taking so much time to generate tiles. Is there any way I can over-zoom with zoom level 10 or any other way to create tiles in less time?

**Comment by nishanthdn96** [comment]
This is the command I'm using to generate tiles
`tippecanoe --no-feature-limit --no-tile-size-limit --exclude-all --minimum-zoom=1 --maximum-zoom=g --force --output-to-directory "tiles" `states.json`
`

**Comment by ericfischer** [comment]
The Mapbox tile serving uses https://github.com/mapbox/vtcomposite to do its overzooming, so if you are running your own tile server, you could also use vtcomposite to overzoom low-zoom tiles dynamically as they are requested.
