### ISSUE TITLE
Icon collision problem

### ISSUE THREAD

**Issue by xiaofsu** [mapbox/tippecanoe#787]
About My Question:
https://github.com/mapbox/mapbox-gl-js/issues/8668
Tippecanoe v1.34.4

First of all, I recommend that you look at the question I asked above.
At first I thought it was the mapbox that would point the collision detection and auto sparse.
But after reminders from andrewharvey,
I used tileserver-gl-light to view the mbtiles file.
(https://github.com/klokantech/tileserver-gl)

This command is used for all the problems found below:

> tippecanoe -o test.mbtiles -l winds -z5 windsymbol.geojson

![image](https://user-images.githubusercontent.com/46067472/63478868-27148f80-c4be-11e9-9d82-2d6b84293f4e.png)

Found the following issues:
1: When I zoomed out to the minimum level, it automatically sparsed all point data.
(Whose question is this? Tileserver-gl problem, or is it a problem when I generate the mbtiles file?)

![image](https://user-images.githubusercontent.com/46067472/63478607-131c5e00-c4bd-11e9-901e-a0e033d9146c.png) 

![image](https://user-images.githubusercontent.com/46067472/63478639-26c7c480-c4bd-11e9-92d8-b8e41fa3d5a6.png) 

2: Only when zooming in at the maximum level, all the points will come out. What is the problem?

![image](https://user-images.githubusercontent.com/46067472/63478762-a5246680-c4bd-11e9-9c8a-b5b466b2f9bc.png)

Thank you, the best Tippecanoe.

**Comment by ericfischer** [comment]
If you want to keep all points at all zoom levels, use `-r1`. The default is to drop a fraction of points at lower zoom levels, because many data sets have too many points to keep them all at every zoom level.
