### ISSUE TITLE
Vector tiles does not match with geojson geometry.

### ISSUE THREAD

**Issue by nishanthdn96** [mapbox/tippecanoe#792]
I recently switched my application from geojson type to vector tile source. Features drawn from vector source are geometrically different than that of geojson.
I am using following command to create these tiles
`tippecanoe --no-feature-limit --no-tile-size-limit  --minimum-zoom=1 --maximum-zoom=g --output-to-directory "tiles" states.json`

<img width="359" alt="Screenshot 2019-09-12 at 1 14 53 PM" src="https://user-images.githubusercontent.com/51163080/64764759-6d5e8b00-d560-11e9-9230-daaf5edbe7c1.png">
<img width="389" alt="Screenshot 2019-09-12 at 1 17 07 PM" src="https://user-images.githubusercontent.com/51163080/64764763-718aa880-d560-11e9-8f82-bc237270c0d1.png">
Features with blue boundary are drawn from geojson source.

How do I configure the command so that I can get exact tiles to be drawn?

**Comment by ericfischer** [comment]
If you want a more precise match to the source data, you can specify a higher maximum zoom level.
