### ISSUE TITLE
pbf output results in "Error: Unimplemented type: 3" errors across clients

### ISSUE THREAD

**Issue by tvogt** [mapbox/tippecanoe#793]
using

> tippecanoe -e routes (mydata.geojson) 

to generate a directory of *.pbf files results in "Error: Unimplemented type: 3" error messages in both openlayers and leaflet.js

the same datasource turned into *.pbf using maptiler works just fine, so it's not the data.

**Comment by tvogt** [comment]
from openlayers:

Error: Unimplemented type: 3 2 index.js:191
    skip index.js:191
    readFields index.js:41
    Hg MVT.js:306
    readFields index.js:39
    readFeatures MVT.js:252
    onload featureloader.js:86
    <anonym> self-hosted:1003

**Comment by tvogt** [comment]
from leaflet:

Error: Unimplemented type: 3 7 leaflet.vectorgrid@1.2.0:1:9530
    skip https://unpkg.com/leaflet.vectorgrid@1.2.0:1
    readFields https://unpkg.com/leaflet.vectorgrid@1.2.0:1
    VectorTileLayer$2 https://unpkg.com/leaflet.vectorgrid@1.2.0:1
    readTile https://unpkg.com/leaflet.vectorgrid@1.2.0:1
    readFields https://unpkg.com/leaflet.vectorgrid@1.2.0:1
    VectorTile$1 https://unpkg.com/leaflet.vectorgrid@1.2.0:1
    _getVectorTilePromise https://unpkg.com/leaflet.vectorgrid@1.2.0:1

**Comment by tvogt** [comment]
even in Mapbox GL it errors out:

{…}
​
message: "Unimplemented type: 3"
​
stack: ""
​
<prototype>: Object { … }
evented.js:136:20
    fire evented.js:136
    fire evented.js:130
    fire evented.js:130
    _tileLoaded source_cache.js:251
    a vector_tile_source.js:148
    process actor.js:148
    onmessage throttled_invoker.js:21

**Comment by tvogt** [comment]
Figured out after much searching that this is probably indicating a zipped pbf file. That kind of should at least be mentioned somewhere.

**Comment by ericfischer** [comment]
Tippecanoe generates gzipped tiles by default because that is what Mapbox uploads and clients expect. You can use `--no-tile-compression` if you don't want compression.

**Comment by tvogt** [comment]
As mentioned: This should be described better and/or the error message adapted. It took me a **lot** of searching to figure that one out.

**Comment by ericfischer** [comment]
Thanks. I'll add a reference to that error message in the README.

**Comment by ericfischer** [comment]
https://github.com/mapbox/tippecanoe/pull/800
