### ISSUE TITLE
How can i reduce the size of the pbf?

### ISSUE THREAD

**Issue by dythbj** [mapbox/tippecanoe#796]
Dear ericfischer:
  Compare with Mapbox's tiles, i notice that it's much more small than the tiles made by tippecanoe, eg:
  [Mapbox's 9/421/193](https://api.mapbox.com/v4/mapbox.mapbox-streets-v8,mapbox.mapbox-terrain-v2/9/421/193.vector.pbf?sku=101uR5IuOm2cF&access_token=tk.eyJ1IjoiZHl0aDIwMTZiaiIsImV4cCI6MTU2OTIyMjIzNSwiaWF0IjoxNTY5MjE4NjM1LCJzY29wZXMiOlsiZXNzZW50aWFscyIsInNjb3BlczpsaXN0IiwibWFwOnJlYWQiLCJtYXA6d3JpdGUiLCJ1c2VyOnJlYWQiLCJ1c2VyOndyaXRlIiwidXBsb2FkczpyZWFkIiwidXBsb2FkczpsaXN0IiwidXBsb2Fkczp3cml0ZSIsInN0eWxlczp0aWxlcyIsInN0eWxlczpyZWFkIiwiZm9udHM6cmVhZCIsInN0eWxlczp3cml0ZSIsInN0eWxlczpsaXN0IiwidG9rZW5zOnJlYWQiLCJ0b2tlbnM6d3JpdGUiLCJkYXRhc2V0czpsaXN0IiwiZGF0YXNldHM6cmVhZCIsImRhdGFzZXRzOndyaXRlIiwidGlsZXNldHM6bGlzdCIsInRpbGVzZXRzOnJlYWQiLCJ0aWxlc2V0czp3cml0ZSIsInZpc2lvbjpyZWFkIiwidmlzaW9uOmRvd25sb2FkIiwic3R5bGVzOmRyYWZ0IiwiZm9udHM6bGlzdCIsImZvbnRzOndyaXRlIiwiZm9udHM6bWV0YWRhdGEiLCJkYXRhc2V0czpzdHVkaW8iLCJjdXN0b21lcnM6d3JpdGUiLCJjcmVkZW50aWFsczpyZWFkIiwiY3JlZGVudGlhbHM6d3JpdGUiLCJhbmFseXRpY3M6cmVhZCJdLCJjbGllbnQiOiJtYXBib3guY29tIiwibGwiOjE1NTg2MDQyNjY3NTIsIml1IjpudWxsfQ.dK0s5of3_sFJoAWD9Rjo_g) like this:
![image](https://user-images.githubusercontent.com/41282663/65404951-5c8a0100-de0d-11e9-9854-c28c13a994dc.png)
The tile has 27 road features in it, like this:
![image](https://user-images.githubusercontent.com/41282663/65405028-8f33f980-de0d-11e9-9017-65b1fd0abc43.png)
But the tile made by tippecanoe(also 9/421/193),like this:
![image](https://user-images.githubusercontent.com/41282663/65405062-b12d7c00-de0d-11e9-8950-c96b8f49acb2.png)
It has 22758 road features in it, like this:
![image](https://user-images.githubusercontent.com/41282663/65405151-d91cdf80-de0d-11e9-9a88-d949f9332ad0.png)
===========================Break================================
  I konw that somebody may say, that the "filter" is different, i have to say, i know that, i have used minzoom&maxzoom to filter features in different zoomlevel.
  i just wonder that how coud Mapbox can reduce it to such small size&count? In zoomlevel 9, there're just 27 road features in it?

**Comment by ericfischer** [comment]
There are only 27 roads because all of the roads that have the same attributes are merged into a single MultiLineString feature, so if there are only 27 road classifications, there are only 27 features. You can do something similar in Tippecanoe with `--reorder --coalesce`.

**Comment by ericfischer** [comment]
They have also filtered out many local roads at lower zoom levels, leaving only major roads. You can do this by setting the `"tippecanoe": { "minzoom": … }` for features that are too detailed to be useful at low zoom levels.

**Comment by dythbj** [comment]
Thanks  ericfischer, get it!
