### ISSUE TITLE
About the impact of R1 on page display

### ISSUE THREAD

**Issue by xiaofsu** [mapbox/tippecanoe#797]
Sorry to bother you again.

For the previous question: #787
I tried using the command:  **tippecanoe -o test2.mbtiles -l winds -z5 -r1 -f --drop-densest-as-needed windsymbol2.geojson**
But the result is not what I want, you can see that there are 26 "idx" (idx is a unix timestamp).
![image](https://user-images.githubusercontent.com/46067472/65422850-3038a980-de3a-11e9-88c7-47164e1ed760.png)

But as shown, there is only one display.
![image](https://user-images.githubusercontent.com/46067472/65422899-48102d80-de3a-11e9-87fb-d48b79be12b4.png)

I need to show all of these 26 pieces, and when the level gets bigger, it does show up.
![image](https://user-images.githubusercontent.com/46067472/65423003-90c7e680-de3a-11e9-8217-c72d5f68aa50.png)

Am I using the wrong command line? How can I display all 26 sets of data when zoom is 0? I need to use filter to control which group of data is displayed at what time.

I am trying to upload the file in question to somewhere and provide a download link, but I don't know where I should upload it.... 🤣🤣

Thank you, the best Tippecanoe.

**Comment by xiaofsu** [comment]
I tried using -pk -pf to remove the size and number of each file. The generated pbf file is now about 10M in size... These two parameters can solve my problem, but the file is too large...
![image](https://user-images.githubusercontent.com/46067472/65493518-975f6800-dee5-11e9-8feb-a64235e4a9c9.png)

**Comment by ericfischer** [comment]
From your screenshot above, it looks like your `idx` attribute is large integers, and your `value` and `direction` are floating-point numbers with high precision. Both of these take up a lot of space in the tiles. If you can eliminate the `idx` unique ID, and if you can round the `value` and `img` to integers, they should take up a lot less space. Ideally you want many features to use the same attribute values so they can take advantage of the duplication to only represent the value once.

**Comment by xiaofsu** [comment]
I tried to split this larger mbtiles file into three copies, which looks good.

**Comment by ericfischer** [comment]
Oh good, I'm glad you got it working.
