### ISSUE TITLE
What's you suggestion on big data size & high zoom level?

### ISSUE THREAD

**Issue by dythbj** [mapbox/tippecanoe#798]
I have a big geojson file (500M、100000+ polygon features) ，if i want to make the tiles to level 18, so What's you suggestion on big data size & high zoom level?

**Comment by ericfischer** [comment]
It is a bad idea to tile to z18 unless you actually need 4cm precision. If you do actually need that precision, I don't know what to suggest other than doing it on a computer with a lot of memory and disk space. That doesn't sound like an unreasonable number of features, though. Does it work or do you run into problems?

**Comment by dythbj** [comment]
Maybe i need MapBox's official tile scheme...😂

**Comment by ericfischer** [comment]
Sorry, I don't know what you mean by official tile scheme.

**Comment by dythbj** [comment]
> Sorry, I don't know what you mean by official tile scheme.

That's ok,it's just a joke😄,thanks very much,i will close it !
