### ISSUE TITLE
Java calls tippecanoe and expects to get the return value

### ISSUE THREAD

**Issue by xiaofsu** [mapbox/tippecanoe#807]
I tried to use java to call the tippecanoe service and expect to get the return value, but it didn't give me the same result as I entered the command in the terminal.

```java

  public static void main(String[] args) {

        try {
            String[] cmd = new String[]{"/bin/sh","-c", "tippecanoe -o /home/xiaofsu/file/typhoonFile/typhoon.mbtiles -l typhoon -z12 -r1 -f -pf -pk /home/xiaofsu/file/typhoonFile/typhoon.geojson"};

            Process ps = Runtime.getRuntime().exec(cmd);

            BufferedReader br = new BufferedReader(new InputStreamReader(ps.getInputStream()));
            StringBuffer sb = new StringBuffer();
            String line;
            while ((line = br.readLine()) != null) {
                sb.append(line).append("\n");
            }
            String result = sb.toString();
            System.out.println(result);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

```
Did not output anything：
![image](https://user-images.githubusercontent.com/46067472/67271460-25327100-f4ed-11e9-9e48-223cb9cc1cba.png)

Use the command to output these things
![image](https://user-images.githubusercontent.com/46067472/67271634-7a6e8280-f4ed-11e9-9379-e0f2612fa41c.png)

tippecanoe Version:
![image](https://user-images.githubusercontent.com/46067472/67271716-ad187b00-f4ed-11e9-9a45-06e51af89923.png)

**Comment by xiaofsu** [comment]
I want to get some output, so I can judge whether the generated file is successful. At present, I can only judge whether the file is 0KB after waiting for the result to return an empty string. Or is it true that the 0KB file is the correct logic?

**Comment by ericfischer** [comment]
The messages you are looking for are written to `stderr` instead of to `stdout` because they are diagnostic information, not the output of processing. If you want to redirect them to stdout so you can read them from a pipe, add `2>&1` to the end of the command line that you pass to `sh -c`.

The way to distinguish a successful run from an error is to check `Process.exitValue()` when the subprocess completes.

**Comment by xiaofsu** [comment]
I tried your method and I think he is correct and can be used normally. Thank you.
```java
import java.io.IOException;

public class Test {
    public static void main(String[] args) throws Exception {
        try {
            String[] cmd = new String[]{"/bin/sh","-c", "tippecanoe -o /home/xiaofsu/file/typhoonFile/typhoon.mbtiles -l typhoon -z12 -r1 -f -pf -pk /home/xiaofsu/file/typhoonFile/typhoon.geojson"};

            Process ps = Runtime.getRuntime().exec(cmd);
            ps.waitFor();
            int i = ps.exitValue();//true is 0 ,false is 1
            System.out.println(i);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}

```
