### ISSUE TITLE
basic_string::_M_construct null not valid

### ISSUE THREAD

**Issue by geeknik** [mapbox/tippecanoe#812]
Is there a bit of code I can drop into tippecanoe-decode to stop the following types of errors from interrupting our testing? Not exactly the Abort we're looking for. (;

```
./tippecanoe-decode -x generator test0000.mbtiles
{ "type": "FeatureCollection", "properties": {
"000000": "00000000000000000000000000000000000",
"000000": "0000000000000000000",
"00000000000": "000000000000000000000000000000000000000000",
"000000": "000",
"0000000000\u000a\u0003\u0019\u00010000": "000000000000000000000000000000000000000000",
"00000000000000000\u000b": "000000000000000000",
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted
```

[test0000.mbtiles.gz](https://github.com/mapbox/tippecanoe/files/3795517/test0000.mbtiles.gz)

**Comment by ericfischer** [comment]
Thanks. I'll take a look and figure out what is going wrong here.

**Comment by ericfischer** [comment]
The bug is here:

```
                        while (sqlite3_step(stmt2) == SQLITE_ROW) {
                                const unsigned char *name = sqlite3_column_text(stmt2, 0);
                                const unsigned char *value = sqlite3_column_text(stmt2, 1);

                                if (exclude_meta.count((char *) name) == 0) {
```

and appears to be because the `name` column in the `metadata` table is unexpectedly null. It checks for null a few lines later, but not before it has already tried to do this string construction.

It is confusing, though, because from `sqlite3`, it looks like the `metadata` table doesn't exist at all.

**Comment by ericfischer** [comment]
This will be fixed in https://github.com/mapbox/tippecanoe/pull/813

**Comment by ericfischer** [comment]
Fix merged

**Comment by geeknik** [comment]
Thank you.
