### ISSUE TITLE
Ways to decode pbf to geojson keeping the xyz file structure (either directly in 1 geojson or multiple geojson in xyz folders)

### ISSUE THREAD

**Issue by cthnguyen** [mapbox/tippecanoe#814]
Hello, 

Is there any way to decode the pbf to geojson, while keeping the Slippy map file structure ? I would like to either to have one geojson with an extra line with the xy information, or to quickly transform all the pbf files that are split in multiple folders (in slippy map format) to geojsons ? 

I tried the command `tippecanoe-decode`with option `-c`but it's not what I want. 

Thank you

**Comment by ericfischer** [comment]
If you have a directory of `.pbf` files named `tiles`, you could make a parallel directory `geojsons` of corresponding JSON with something like

```
find tiles -name '*.pbf' -print |
while read i
do
  out="$(echo "$i" | sed 's/^tiles/geojsons/').json"
  mkdir -p "$(dirname "$out")"
  tippecanoe-decode "$i" $(echo "$i" | awk -F/ '{print $2, $3, $4}') > "$out"
done
```

**Comment by cthnguyen** [comment]
Thank you, I will try it. 

Is there any way to read the pbf files in python ?

**Comment by ericfischer** [comment]
You can use https://github.com/mapbox/vector-tile-base to decode vector tiles from python.
