### ISSUE TITLE
conditions to have --generate-id working ?

### ISSUE THREAD

**Issue by pixime** [mapbox/tippecanoe#818]
I have a shape file converted to geojson. The geojson file contains id per feature (not in properties).

I use the following tippecanoe command (v. 1.34.3) :
$ tippecanoe -o Sector_Boundary_2006.mbtiles -f -zg --generate-ids Sector_Boundary_2006.json

Then the mbtile file is processed with mb-util and and served by web server (raster source with tiles array). The map is visible but no id are present when requesting features (using queryRenderedFeatures).

Here is the chrome console output:
_{type: "Feature", _vectorTileFeature: Ro, properties: {…}, layer: {…}, source: "custom", …}
layer: {id: "Sector_Boundary_2006", type: "fill", source: "custom", source-layer: "Sector_Boundary_2006", layout: {…}, …}
properties: {OBJECTID: 398, Prov_ID: 5, Province: "Eastern Province", Dist_ID: 56, District: "Ngoma", …}
source: "custom"
sourceLayer: "Sector_Boundary_2006"
state: {}
type: "Feature"
_vectorTileFeature: Ro {properties: {…}, extent: 4096, type: 3, _pbf: yu, _geometry: 79827, …}_

Is there something wrong ? Thanks

**Comment by ericfischer** [comment]
If your GeoJSON source already has an `id` you shouldn't need to use `--generate-ids` to add more `id`s, but otherwise that seems like it should work, and I don't know why you aren't seeing them in the tiles that you receive. Does `tippecanoe-decode` on the `mbtiles` file show the IDs to be present there?

**Comment by pixime** [comment]
Thanks Eric, You are right, I can see the feature IDs using mbtiles-decode:

{ "type": "Feature", "id": 250, "properties": { "OBJECTID": 251 ...

But I don't understand why it is still missing in the browser, using mb-util probably do not remove it...
I will dive into

**Comment by ericfischer** [comment]
`mb-util` does not alter the content of the tiles, so the ID must be being lost further downstream.

**Comment by pixime** [comment]
Apologies, the previous generated tiles (without `--generated-ids`) was cached in my browser. After cleaning cache and rebuild the new ones (with `--generated-ids`) work perfectly. Thanks for the `tippecanoe-decode` tip.
