### ISSUE TITLE
Is --cluster-distance working wrong?

### ISSUE THREAD

**Issue by iBinh** [mapbox/tippecanoe#820]
From example 

```
curl -L -O https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_populated_places.zip
unzip -o ne_10m_populated_places.zip
ogr2ogr -f GeoJSON ne_10m_populated_places.geojson ne_10m_populated_places.shp

tippecanoe -zg -o ne_10m_populated_places.mbtiles -r1 --cluster-distance=10 --accumulate-attribute=POP_MAX:sum ne_10m_populated_places.geojson
```

The point named `Annaba` has different lat lon at different zoom level

<img width="400" alt="Screen Shot 2019-12-12 at 15 21 12" src="https://user-images.githubusercontent.com/13776018/70694831-1305cf80-1cf3-11ea-9462-547517f3c74a.png">
<img width="365" alt="Screen Shot 2019-12-12 at 15 21 21" src="https://user-images.githubusercontent.com/13776018/70694832-1305cf80-1cf3-11ea-9393-91a98c168297.png">

**Comment by ericfischer** [comment]
When points are clustered, they are given the average latitude and longitude of the points that were clustered together, but the attributes of the first point in the cluster (except for the attributes that are specified to be accumulated). So I think this is probably working as intended.

**Comment by iBinh** [comment]
Thank @ericfischer 
Do you have any suggestion that keep exactly location of the clustered point?

**Comment by ericfischer** [comment]
You could remove the special case for `VT_POINT` here, which is what does the averaging:

https://github.com/mapbox/tippecanoe/blob/065cc1d78d662ec21620596e07749c02a941337f/tile.cpp#L1889

**Comment by iBinh** [comment]
It works. Thank you!
