### ISSUE TITLE
Insufficient zoom levels with -zg produce malformed shapes

### ISSUE THREAD

**Issue by dyakovlev** [mapbox/tippecanoe#821]
I'm working with a 100x100m binned dataset of a relatively small extent. (20km square)

<img width="736" alt="Screen Shot 2019-12-17 at 12 06 13 PM" src="https://user-images.githubusercontent.com/127997/71030105-a3625c80-20c5-11ea-903f-48f78ab86a89.png">

When generating tiles for it with `-zg`, tippecanoe goes to a max-zoom of 9 and produces malformed shapes -

<img width="399" alt="Screen Shot 2019-12-17 at 11 58 12 AM" src="https://user-images.githubusercontent.com/127997/71029917-41095c00-20c5-11ea-82a9-51f89f20f1c4.png">

After regenerating manually with a max zoom of 14, the shapes are corrected -

<img width="287" alt="Screen Shot 2019-12-17 at 12 01 19 PM" src="https://user-images.githubusercontent.com/127997/71029950-541c2c00-20c5-11ea-8c98-186dd9e69cb6.png">

Any thoughts on why this would be happening? `g` seems to be a heuristic, but I don't have insight on why it would stop so early..

**Comment by ericfischer** [comment]
The size chosen by `-zg` is just a guess, not guaranteed to be correct. The intent of it is that the location of each feature should be distinguishable from the others and the nodes around the outline of each feature should be distinct from each other. But it doesn't know in this case that the sides of each feature are meant to be parallel to or perpendicular to each other, so it is not doing anything to maintain that constraint.

**Comment by dyakovlev** [comment]
got it, thank you!

is your recommendation for work like this to use a fixed max zoom that achieves some desired precision?

**Comment by ericfischer** [comment]
Yes, if you know the precision that you want, please specify it directly.
