### ISSUE TITLE
Rendering artifacts when tiling dense parcel data

### ISSUE THREAD

**Issue by mkieselmann** [mapbox/tippecanoe#829]
Hi,
I ran into some rendering issues that occur while tiling a dense parcel dataset with `--no-clipping`. I followed along the great work and discussion in #311  and https://github.com/mapbox/mapbox-gl-js/issues/6097.

My requirements are:
- high precision rendering of parcel data at zoom levels >10
- parcel selection on the map, so polygons should not be splitted

Right now I am using the following command
```
tippecanoe -l parcel -o parcels.mbtiles -z 16 -Z 10 --drop-smallest-as-needed --extend-zooms-if-still-dropping --no-clipping --detect-shared-borders file1.json file2.json ...
```
which leads to the following issue while rendering in mbview (artifacts als appear on Mapbox JS & iOS):

Straight line and polygon artifacts when overzoomed (top: zoom level 15.x; bottom: zoom level 16.x):
<img width="1337" alt="Bildschirmfoto 2020-01-11 um 17 19 47" src="https://user-images.githubusercontent.com/2893220/72207183-b97df580-3496-11ea-97be-4af7a5353142.png"><img width="1380" alt="Bildschirmfoto 2020-01-11 um 17 20 04" src="https://user-images.githubusercontent.com/2893220/72207185-bdaa1300-3496-11ea-8907-c9e99935797f.png">

The problems are caused be the `--no-clipping` option. If I leave it out everything is fine besides the fact that large polygons are splitted on tile boundaries. This behaviour is problematic if a want to select and show the selection of one complete polygon on the map. That's why I sticked with `no-clipping` during testing.

I've used the `-zg` option with before without artifacts. But it uses a max zoom of 13. This leads to low precision at high zoom levels (left: max zoom level 13; right: max zoom level 16):
<img width="413" alt="max_zoom_level_13" src="https://user-images.githubusercontent.com/2893220/72207229-445ef000-3497-11ea-8912-ceec8beec0b9.png"><img width="404" alt="max_zoom_level_16" src="https://user-images.githubusercontent.com/2893220/72207234-5476cf80-3497-11ea-96fa-58121c813a83.png">

`--no-polygon-splitting` as mentioned in #311 doesn't seems to have any effects anymore.

Using `--no-duplication` instead of `--no-clipping` screws up rendering completely as it generates a lot of artifacts and missing polygons.

Do you have any idea how to get rid of the artifacts and how to improve tiling for parcel data, while preventing polygons from splitting?

Thanks in advance.

**Comment by ericfischer** [comment]
Parcels are very difficult to tile well, but `--no-clipping` (and `--no-duplication`) is fundamentally incompatible with good rendering with Mapbox GL, because the coordinates quickly become too large for GL's 32-bit internal coordinate representation.

The best thing I can suggest is to give your features unique IDs so you can find the pieces of them across multiple tiles and reassemble them.

**Comment by mkieselmann** [comment]
Thanks Eric.
Closing as I use the approach with unique feature IDs now.
