### ISSUE TITLE
Having problems with --accumulate-attribute

### ISSUE THREAD

**Issue by lmmaynard** [mapbox/tippecanoe#830]
We recently noticed a problem with the mean accumulated attributes on our point and polygon tilesets. It was first noticeable when we applied styles to display a property with the accumulated mean values.

I created a small set of points to illustrate the problem using public earthquake data from California:
[earthquakes_points.zip](https://github.com/mapbox/tippecanoe/files/4054907/earthquakes_points.zip)

````
-Z0 -z17 -r0 --cluster-distance=5 --use-attribute-for-id=event_id --accumulate-attribute=depth:mean --accumulate-attribute=magnitude:mean
````

Since this is such a small set of data it's easy to predict what the mean values should be, and the resulting tileset appears to incorrectly generate those values.

Although this is a point feature sample, we noticed the same problem when coalescing polygons.

I have tried the sum, product, max and min functions and they all seam to work. The problem appears limited to the calculated mean values.

Please have a look and confirm what I'm seeing. If this is a bug it'd be nice to get a fix. We have large datasets where the calculated mean value are important properties.

**Comment by lmmaynard** [comment]
I should add that I've noticed another odd behavior with the mean calculation. This happens with a particular set of parameters - for example: `-r1 -aC -K2`.

If those three parameters are used the calculated mean is inconsistent at different zoom levels. For example, if I have two points that remain clustered at different zoom levels the calculated mean values are different at the different zoom levels. Obviously those values should be consistent.

In subsequent tests I removed the `-aC` parameter and this particular inconsistency went away, but the incorrect calculations (noted above) remained a problem.

**Comment by ericfischer** [comment]
Thanks for the report. I'll take a look and see if I can figure out what is going wrong with the mean calculation. If you can point to specific features that are wrong with this data set that would be helpful.

**Comment by lmmaynard** [comment]
@ericfischer I created a spreadsheet with the points and their values that get accumulated: 
[observations.xlsx](https://github.com/mapbox/tippecanoe/files/4086986/observations.xlsx)

It lists the expected and actual results. That should give you an idea of which points in the sample get clustered and what the expected mean values are.

**Comment by AnthonyMacKinnon** [comment]
@ericfischer Did you get a chance to check if there is a way around the issue? Accumulation would be very useful to us in a number of scenarios (e.g. parcel aggregation) and `sum` is often not an option due to the large numbers we're dealing with causing overflows.

**Comment by ericfischer** [comment]
Yes, you are right, something is systematically wrong with the math compared to accumulating the same attributes with `comma` and taking the mean of the result. I'll figure out what is going on.

For my future reference to verify the fix:

```
tippecanoe -Z0 -z17 -r0 --cluster-distance=5 --use-attribute-for-id=event_id --accumulate-attribute=depth:comma --accumulate-attribute=magnitude:comma -f -o comma.mbtiles <(unzip -p /Users/enf/Downloads/earthquakes_points.zip)
tippecanoe -Z0 -z17 -r0 --cluster-distance=5 --use-attribute-for-id=event_id --accumulate-attribute=depth:mean --accumulate-attribute=magnitude:mean -f -o mean.mbtiles <(unzip -p /Users/enf/Downloads/earthquakes_points.zip)
paste <(tippecanoe-decode comma.mbtiles | grep '"clustered": true') <(tippecanoe-decode mean.mbtiles | grep '"clustered": true') | perl -e 'while (<>) { if (/"depth": "([^"]+)".*"depth": ([^,]+)/) { $list = $1; $mean = $2; @list = split(/,/, $list); $sum = 0; $count = 0; for $c (@list) { $sum += $c; $count++ } printf("%f %f %s\n", $mean, $sum / $count, $list) } }'
```

**Comment by ericfischer** [comment]
Good catch! This will be fixed in https://github.com/mapbox/tippecanoe/pull/841.

I was accumulating the sum and count for the mean into tile-wide counters instead of making them local to the feature that was being accumulated onto.

**Comment by AnthonyMacKinnon** [comment]
Great, thanks @ericfischer!

**Comment by ericfischer** [comment]
Merged and tagged for release
