### ISSUE TITLE
Don't abort when minimum-zoom greater than maximum-zoom=g

### ISSUE THREAD

**Issue by stevage** [mapbox/tippecanoe#834]
I had an annoying situation with a huge file where after a lot of thinking, tippecanoe guessed a maximum zoom that was less than the minimum zoom that I had set, then aborted.

It would be nice in that case if it would just use the provided minimum for both values.

**Comment by stevage** [comment]
Wait, I think I'm misremembering. It warned, not aborted.

**Comment by ericfischer** [comment]
The intent, at least, is that it should be a warning, not an error, and that it will use the minzoom for the maxzoom, with a message like `Can't use 5 for maxzoom because minzoom is 7`.
