### ISSUE TITLE
Tile buffer overlay with -b 0

### ISSUE THREAD

**Issue by daddy88** [mapbox/tippecanoe#843]
Firstly thanks for making this wonderful tool, really love it!

I'm having some issues configuring Tippecanoe correctly. I'm experiencing buffer overlays in the tiles when exporting, even though I've set ```-b 0```

Please see attached screenhot.

I use the following command:
```sudo nohup tippecanoe -o transport-z12.mbtiles -t /mnt/volume_ams3_02/tmp/ -Z7 -z12 -f -F -ps -pf -pk -pt -Bg -d12 -b 0 transportation-layer-z12.geojson &```

Can any one spot what I'm doing wrong?

![tile_overlays](https://user-images.githubusercontent.com/20934819/74507825-d1192580-4efd-11ea-851f-a28a83fc1fa2.jpg)

**Comment by ericfischer** [comment]
The only thing that stands out as weird is the use of `-F`, which would allow you to write new data into an existing tileset, but I don't see how that would affect the buffer size.
