### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [mapbox/tippecanoe#85]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [json_begin](https://github.com/mapbox/tippecanoe/blob/b2fdcba6b04eb4356eab855c1d2cb55d68cf4f93/jsonpull.c#L10)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [read_json](https://github.com/mapbox/tippecanoe/blob/5ab2673b8c9f1bfef02e1cd1b7b606fb2d4c0479/geojson.c#L776)

**Comment by ericfischer** [comment]
Yes, I should do that, although on the C++ side there are many places that are still going to crash instead of returning cleanly when memory runs out because of implicit allocation.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by ericfischer** [comment]
These checks are in place now

**Comment by elfring** [comment]
Thanks for [your small](https://github.com/mapbox/tippecanoe/commit/bc5a7b251f97dd6c76a514500521394f7e051989#diff-43e3f99a1afe311087adee97b2dfce24R28 "Check return values after allocating memory") [source code improvement](https://github.com/mapbox/tippecanoe/commit/eee596d5f505662b3a3d3daae50f4b1a2b5e63f6 "Check return values from memory allocation").
