### ISSUE TITLE
A UI project for tippecanoe

### ISSUE THREAD

**Issue by rowanwins** [mapbox/tippecanoe#858]
Hi tippecanoe team

Just letting you know that I've started dabbling on a little UI wrapper for tippecanoe using [electron](https://www.electronjs.org/).

It's not quite in github yet but I plan on making it open source and free. I'm currently just working which parameters to support as it won't be the full range. And also working out the logic for how to make which parameters override which.

![Tippecanoe](https://user-images.githubusercontent.com/6735870/81752514-f0bbec00-94f4-11ea-8fe0-cbf8e83991c4.gif)

I'll post an update here once it's alive in Github. In the meantime if anyone is interested in supporting this or helping the efforts to make it let me know.

Cheers

**Comment by adilyoltay** [comment]
hi Rowan 
thanks for your great idea it woluld be help for non technical users. We can use ,test  and support you..

**Comment by rowanwins** [comment]
Repo up at
https://github.com/rowanwins/tippecanoe-ui

Includes the link to a mac package so testing welcome :)
