### ISSUE TITLE
How to create a mbtitles with layer based on different features properties

### ISSUE THREAD

**Issue by 2803media** [mapbox/tippecanoe#863]
I try to manage this for some time but can't get a way to make it working. The idea is to build a Mbtitles with multiple layers based a the properties inside the geojson.

For example if in my json i have the property name STATE with different state names I want to create an mbtitles with different layers based on the name of STATE.

Any idea easier than split the json into multi json files (one for each STATE) and then use tippecanoe?

**Comment by ericfischer** [comment]
There is no way to do it just from an attribute, but you can use `"tippecanoe": { "layer": "whatever" }` in the Feature to specify the layer name.

**Comment by 2803media** [comment]
Thanks Eric, I dig this way ;)
