### ISSUE TITLE
Generating Tiles from Gridded Data - Diagonal Artifacts

### ISSUE THREAD

**Issue by bransonf** [mapbox/tippecanoe#864]
I'm attempting to generate tiles from a vector grid. This data starts as a shapefile projected in NAD83 Stateplane Feet. I convert it with GDAL like so:
```
ogr2ogr -f GEOJSON -t_srs EPSG:4326 source.geojson source.shp
```
At this point, loading the geojson into QGIS, I still have grid squares with perfect vertical/diagonal alignment.

I attempt to generate tiles:
```
tippecanoe -zg -o outputTiles.mbtiles --coalesce-densest-as-needed --extend-zooms-if-still-dropping source.geojson
```
but the result is this (specifically the diagonal artifacts):

![](https://bransonf.com/img/Grid_Alignment.png)

I've tried with and without `--drop-densest-as-needed` as well as `--buffer=0`, `--detect-shared-borders`, `--no-clipping` and `--no-line-simplification` to no avail.

I've run out of ideas. Thank you in advance for any assistance you may be willing to offer.

**Comment by springmeyer** [comment]
The `-zg` option auto-chooses a descent `maxzoom` for the tileset. It may be that you need to pass `zN` where `N` is a number higher than tippecanoe is choosing automatically.

**Comment by bransonf** [comment]
Thanks @springmeyer  for such a quick response. This did fix the issue, you're a life saver.
