### ISSUE TITLE
Points shift when converting using default command

### ISSUE THREAD

**Issue by nipuna777** [mapbox/tippecanoe#872]
I've attempted to export some data from the overpass API(as geojson) and then converted to mbtiles using the following command.

`tippecanoe -zg -o out.mbtiles --drop-densest-as-needed in.geojson`

When importing the mbtiles into Mapbox Studio, the points have all shifted. 
Is there a way of debugging this? What settings should I use to fix this?

The red and blue circles are geojson and mbtile layers.

![Screenshot 2020-07-21 at 6 47 44 PM](https://user-images.githubusercontent.com/5859290/88046568-d9e3e680-cb82-11ea-87dd-4f7e47e195ac.png)

This is a subset of the data:
```
{
  "type": "FeatureCollection",
  "generator": "overpass-ide",
  "copyright": "The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.",
  "timestamp": "2020-07-21T10:38:07Z",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "@id": "node/1918317450",
        "description:en": "Yangjae Station gate 2",
        "name": "양재역 2번출구",
        "name:ja": "良才駅 2番出口",
        "railway": "subway_entrance",
        "ref": "2"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          127.0334789,
          37.48495
        ]
      },
      "id": "node/1918317450"
    },
    {
      "type": "Feature",
      "properties": {
        "@id": "node/1925380667",
        "description:en": "Yangjae Station gate 11",
        "name": "양재역 11번출구",
        "name:ja": "良才駅 11番出口",
        "railway": "subway_entrance",
        "ref": "11"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          127.0339735,
          37.484163
        ]
      },
      "id": "node/1925380667"
    }
  ]
}
```

**Comment by luqinghui** [comment]
may [this](https://github.com/mapbox/tippecanoe/issues/664) can help you

**Comment by ericfischer** [comment]
`-zg` tries to choose a zoom level where all the points are distinguishable, but it doesn't actually know how much precision you need.  Your screenshot looks like it is around zoom level 18, so you probably want -z18 to have enough display precision.

**Comment by nipuna777** [comment]
That helps @lubademskaya & @ericfischer. Thanks for the clarification.
I will use a better zoom level for the use case and close the issue.

Out of curiosity, why does this shift happen in points?  Are decimal places removed to for better compression?
(This maybe a stupid question as I don't fully understand how the compression works apart from reducing the details on polygons/lines when at higher zoom levels.)
