### ISSUE TITLE
Feature: easier on RAM for large datasets.

### ISSUE THREAD

**Issue by viktor76525** [mapbox/tippecanoe#877]
I have a geojson file ~64 GB that I am trying to generate tiles for.
The machine has 64GB RAM and 32 threads.
I have noticed that when processing, tippecanoe uses as many threads as possible and that it doesn't seem to save any output until a later stage.

An option that would be useful is limiting the number of threads, even if not helpful for the overall memory requirement, it would be better for sharing resources on shared machines.
Maybe each zoom level could be stored to the output as it is produced?

**Comment by geeknik** [comment]
From the documentation:

```
Tippecanoe ordinarily uses as many parallel threads as the operating system claims that CPUs are available. You can override this number by setting the TIPPECANOE_MAX_THREADS environmental variable.
```

For example: `TIPPECANOE_MAX_THREADS=2 ./tippecanoe -zg -f -o file.out --drop-densest-as-needed file.json`

**Comment by viktor76525** [comment]
Thanks @geeknik , I was only looking in the command line parameters.

**Comment by ericfischer** [comment]
Glad you got this figured out!
