### ISSUE TITLE
Specific options by layer

### ISSUE THREAD

**Issue by flp-gpc** [mapbox/tippecanoe#88]
I would like to suggest an improvement: would it be possible to set specific options for each layer ?

For instance when importing 2 layers:
  tippecanoe -o result.mbtiles A.json B.json

I would like to be able to specify options "-Z 2 -z10 -r 2.0" for the layer A and "-Z 8 -z14 -r 1.5" for the layer B.

**Comment by ericfischer** [comment]
This would be useful, and the main challenge is coming up with a good syntax for it. Maybe the right thing to do is to make the input file a dash-option instead of an argument, so it could parse options from left to right, and ones you specified after one input file would only affect the following input files.

**Comment by flemmens** [comment]
A simple json config file could be OK, something like this:

tippecanoe -c config.json

config.json:
{
  "file": {
	"output":  "result.mbtiles",
	"options": "-f -t /tmp"
  },
  "sources": {
    "country_layer": {
      "source":  "countries.json",
      "options": "-Z 2 -z 10 -r 1.5 -ar -ao"
    },
    "region_layer": {
      "source": "regions.json",
      "options": "-Z 4 -z 14 -ar -ao -al"
    }
  }
}

This way the layer name is directly defined in the config file (no need of -l option) and it is easy to read and understand.

**Comment by ericfischer** [comment]
As of https://github.com/mapbox/tippecanoe/commit/7154c2945990f5c1571969db51a591c33d0a19ae you can now specify minzoom and maxzoom for individual features, although still not for whole layers.

**Comment by ericfischer** [comment]
I don't think it is going to be practical to do this. If you need it, you can make the layers as separate mbtiles and use tile-join to combine them.
