### ISSUE TITLE
gdal contours to mbtiles polygons with holes

### ISSUE THREAD

**Issue by denissanga** [mapbox/tippecanoe#886]
Goodmorning, I'm working with GDAL launched by python code. I used the gdal.countour function to transform a raster file in vector. I obtain many polygons and from them I need to create holes inside them and then export in mbtiles (also using tippecanoe tool) the polygons obtained with outer and inner rings. It is possible do this? This because with the contour function I obtain many concentrics polygons.
Thank you

**Comment by ericfischer** [comment]
Sorry, I don't know how to make gdal generate polygons with holes instead of overlapping "pancake" polygons.
