### ISSUE TITLE
Support bare geometries

### ISSUE THREAD

**Issue by ericfischer** [mapbox/tippecanoe#89]
After discussion in https://github.com/openaddresses/machine/issues/210, supporting bare geometries seems more practical than I previously thought, since they can usually be distinguished from geometries that are part of a Feature or a GeometryCollection.

**Comment by ericfischer** [comment]
Working on this in https://github.com/mapbox/tippecanoe/tree/bare-geometry.

It basically seems ok, but I worry that if there are other wrapper objects around the GeoJSON geometries (like if you give it a bare stream of tweets), they'll never get cleaned up and the parse tree will eat up all the memory. It would be better with some way to detect objects that will never matter so they can be freed.

cc @migurski

**Comment by migurski** [comment]
Yuck, yeah. I dunno.

**Comment by ericfischer** [comment]
I guess I could just add an allocation counter and have it bail out if it gets bad.

**Comment by ericfischer** [comment]
I went ahead and merged this.
