### ISSUE TITLE
missing large chunks of data at certain zoom levels

### ISSUE THREAD

**Issue by briantran37** [mapbox/tippecanoe#890]
i am missing large chunks of data at certain zoom - it wont display data at zoom levels less than 6 - levels when trying to project mbtile layers.... i dont suspect it being data issue....could it be a maputnik/maptiler loading issue? 
have you any idea how to diagnose/ resolve this issue? 

![image](https://user-images.githubusercontent.com/72456221/99316306-24742780-2832-11eb-8f3c-d47a357bd88c.png)

zoom level less than 6 with large chunks of data missing

**Comment by kochis** [comment]
I'm also seeing a similar issue. The issue is only affecting some of the layers, but essentially most of the data between zoom levels 4 - 7 are missing. I'm using the following command

```bash
tippecanoe -z 9 -Z 0 -r1 -P -pf -pk -f -o "./tiles/us-constituencies.mbtiles" "data/constituencies-with-layers.geojson"
```

https://www.loom.com/share/7b766304231243cbbd27f5f315ed4218

**Comment by kochis** [comment]
This issues actually seems to have resolved itself. Wonder if it was somehow related to mapbox-gl-js.

**Comment by ericfischer** [comment]
Glad you got it working! Please reopen with more details if you still have problems.
