### ISSUE TITLE
Installation on Linux 

### ISSUE THREAD

**Issue by musicformellons** [mapbox/tippecanoe#90]
I'm on ubuntu. How do I install?

**Comment by ericfischer** [comment]
Does `make install` (after the `apt-get` steps from `README.md`) work for you? It does for me.

**Comment by musicformellons** [comment]
Yes works, thanks.

**Comment by tkayne23** [comment]
I'm also on ubuntu. I ran the apt-get steps, but the make and make install steps aren't working for me. I receive "no target specified and no makefile found". I can't seem to find the right directory to run the commands. Protobuf-compiler, libprotobuf-dev and libsqlite3-dev were copied to my /usr/share/doc directroy.

**Comment by ericfischer** [comment]
@tkayne23 Did you `cd` into the tippecanoe directory after you `git clone`d the project before running `make`?

**Comment by tkayne23** [comment]
I followed these instructions for Linux:
sudo apt-get install libprotobuf-dev protobuf-compiler libsqlite3-dev
make
make install

I did not do "git clone". I need to clone the entire repository? Or just certain files.

**Comment by ericfischer** [comment]
You need to download a copy of the tippecanoe repositoryt, and then compile it, with

```
git clone https://github.com/mapbox/tippecanoe.git
cd tippecanoe
make
```

(You could also use a release tarball from https://github.com/mapbox/tippecanoe/releases if you really don't want to clone the repository.)

**Comment by tkayne23** [comment]
Thanks. I'll try that.

**Comment by tkayne23** [comment]
I'm pretty sure it worked. I didn't get any errors. Thanks!

**Comment by ericfischer** [comment]
Glad to hear it!
