### ISSUE TITLE
Allow a per-feature minzoom and maxzoom to be specified

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/tippecanoe#91]
It would be useful if individual features could be shown / hidden at specified zoom levels. For example, this could be used to show highways at low zoom levels and hiking trails at high zoom levels. 

Syntactically, it could look like
```
tippecanoe --feature-maxzoom-field=maxzoom --feature-minzoom-field=minzoom layer.json 
```

Is this feasible with the tippecanoe algorithm?

**Comment by lucaswoj** [comment]
A naive reading of the code and docs would suggest that it might be possible to implement a per-feature maxzoom but not a minzoom. This would still be pretty useful.

**Comment by ericfischer** [comment]
It should be possible to do either, within the constraint that there is still an outer loop that goes through the global range of zooms; the question is mostly just what makes a decent syntax for it.

It could either be a layer attribute as proposed in https://github.com/mapbox/tippecanoe/issues/88 or it could be a per-feature tag or it could be a full-fledged filter query syntax of some sort.

A per-feature tag would be the easiest and possibly the most flexible, but pushes the problem of how to add the tag to each feature out to whatever is generating the GeoJSON.

**Comment by lucaswoj** [comment]
Glad to hear it is possible! Do you think it is something that *should* be included in tippecanoe? 

> The goal of Tippecanoe is to enable making a **scale-independent** view of your data, so that at any level from the entire world to a single building, you can see the density and texture of the data rather than a simplification from dropping supposedly unimportant features or clustering or aggregating them.

If you're on board with the idea, I'm interested in discussing syntax and implementing this feature.

**Comment by ericfischer** [comment]
I do think it would be useful and appropriate. The attempt at scale-independence is pragmatic, not religious. I'm just genuinely unsure about the best way to specify it.

**Comment by lucaswoj** [comment]
What about extending the `-z` and `-Z` parameters to accept string field names in addition to numeric values. They could, in the future, be extend to accept a more sophisticated query syntax.

**Comment by lucaswoj** [comment]
Is this roughly the place where the filtering would be added? https://github.com/mapbox/tippecanoe/blob/master/tile.cc#L586

**Comment by ericfischer** [comment]
Yes, that would be where to do it @lucaswoj. Sorry I've been letting this sit instead of fixing it for you!

**Comment by lucaswoj** [comment]
No worries @ericfischer! This is just something I'm curious about for a side project (though it might also be relevant to better data processing in the new Mapbox Studio).

**Comment by ericfischer** [comment]
OK, you can specify maxzoom and minzoom for individual features as of https://github.com/mapbox/tippecanoe/commit/7154c2945990f5c1571969db51a591c33d0a19ae.

cc @mick

**Comment by lucaswoj** [comment]
Fantastic! Thanks @ericfischer!

**Comment by mick** [comment]
\o/ :tada:
