### ISSUE TITLE
Higher resolution

### ISSUE THREAD

**Issue by stackTom** [mapbox/tippecanoe#942]
I need to display an extremely dense dataset consisting of geoJSON point geometries which are very tightly spaced next to each other. It appears at zoom levels of 16 and higher, I can't get all the points to display. Tippecanoe seems to drop some of the points no matter what options I select.

I have tried `-pf -pk` to no avail. I have also played around with the -d flag. But it seems that using higher -d values limits the max zoom... Is this a hard limit due to Tippecanoe's use of a 32-bit tile coordinate system? I see there is a tradeoff between choosing a larger max zoom and choosing a larger detail. I would ideally like to use a max zoom of 17 or higher and a level of detail of 32 (I just want all my features to be visible). Is this possible?

Is there any other way to accomplish my goal?

**Comment by e-n-f** [comment]
Hmm, it's not at all obvious to me why you should be losing data at that precision. All the points should be present in the maxzoom tiles, even with no command-line options. If you can provide a sample of the data I can take a look.

**Comment by stackTom** [comment]
I really appreciate all your help. After more digging, I think the issue was with a bug on my own end (with the software I wrote to visualize the mbtiles). I have since fixed it and I don't see any points being dropped anymore.

Thanks again for the help. I'll close the issue and reopen if I see the issue occurs again with other mbtiles.

**Comment by e-n-f** [comment]
Glad you figured it out!
