### ISSUE TITLE
broken rings on tile boundaries

### ISSUE THREAD

**Issue by anandthakker** [mapbox/tippecanoe#95]
When some polygons are split across tile boundaries, the result is a polygon with rings whose first and last coordinates aren't the same.  This doesn't usually affect rendering, but when rehydrating to geojson, this sometimes makes geoprocessing stuff like Turf choke.

Example here: https://gist.github.com/anandthakker/a498dbf5bb0733f6a267

**Comment by ericfischer** [comment]
Thanks @anandthakker! I knew there were some issues with rehydrating tippecanoe polygons but didn't have a good test case. This should be very helpful for fixing the polygon encoding.

**Comment by ericfischer** [comment]
Working on this and polygon winding order in https://github.com/mapbox/tippecanoe/tree/polygon-ring

**Comment by ericfischer** [comment]
The GeoJSON that the code is now producing for this tile looks like https://gist.github.com/ericfischer/4db384eb65e799af5c8d.

@anandthakker, does this look like what you are expecting now? Or were you hoping that the southern hole would be clipped entirely out of the outer shape instead of them sharing an edge along the left side?

**Comment by ericfischer** [comment]
Sounds like I do need to handle that case specially: https://github.com/mapbox/tippecanoe/issues/97

**Comment by anandthakker** [comment]
@ericfischer Nice.  I'm actually not sure about the case of a hole sharing an edge with the outer ring, but I guess I'd pessimistically guess that it would probably blow up some algorithm or another, heh :-/

**Comment by anandthakker** [comment]
Oh weird, I didn't see your last comment till after I sent mine.

**Comment by ericfischer** [comment]
Using the Clipper library for clipping clips that hole out cleanly. Merged in https://github.com/mapbox/tippecanoe/commit/37ffacdeb9be1ec484ce0e7a1de7d4fdd7b91deb
