### ISSUE TITLE
Gaps in LineStrings

### ISSUE THREAD

**Issue by larsschwarz** [mapbox/tippecanoe#950]
Using the following parameters

`tippecanoe --minimum-zoom=3 --maximum-zoom=22 -l "file" -r1 -P -pf -pk -f --extend-zooms-if-still-dropping -o "out.mbtiles" "in.geojson"`

it generates a lot of weird gaps in the actual LineStrings depending on the actual zoom level. See green styled lines in this two examples to mark the most obvious ones:

![gaps1](https://user-images.githubusercontent.com/902940/194703370-3fed45a4-e005-42d7-bc90-0787a0771a32.JPG)
![gaps2](https://user-images.githubusercontent.com/902940/194703373-c4eadd69-f6ad-4652-a360-1f75c573c187.JPG)

I tried playing around with various parameters, but there was no actual change in the output/display. 

Any suggestions on how to debug this?

**Comment by larsschwarz** [comment]
Quick note: adding --no-simplification-of-shared-nodes at least keeps the same display at various zoom levels, but still with gaps in lines.

**Comment by larsschwarz** [comment]
Closing this issue myself. Running this with no additional parameters generates the expected result.

**Comment by e-n-f** [comment]
Glad you figured it out!
