### ISSUE TITLE
tippecanoe gets stuck while generating certain types of files

### ISSUE THREAD

**Issue by divysts** [mapbox/tippecanoe#971]
While the tile generation part is smooth in most cases while generating tiles tippecanoe get stuck in tile generation state while generating tile in some cases. It does not throw an error in that case even after hours. File size is very low 1.5MB <br><br>``tippecanoe --minimum-zoom=1 --read-parallel --buffer=127 --simplification=1 --layer=layer_id_name --no-feature-limit --no-tiny-polygon-reduction --preserve-input-order --no-line-simplification --extend-zooms-if-still-dropping --force --drop-rate=0 --maximum-tile-bytes=500000 --coalesce-densest-as-needed --output-to-directory=/outputfolder /usr/src/app/local/AfghanistanRoads_UTM42N.geojson
1409 features, 157464 bytes of geometry, 18455 bytes of separate metadata, 555 bytes of string pool``<br>
If there is an error while processing certain files tippecanoe should ideally throw an error . I am attaching my geojson file in zip format since github doesnot allow geojson format file
[AfghanistanRoads_UTM42N.zip](https://github.com/mapbox/tippecanoe/files/11497620/AfghanistanRoads_UTM42N.zip)

**Comment by e-n-f** [comment]
Perhaps this is a bug that has since been fixed in https://github.com/felt/tippecanoe? For me it completes in less than 6 seconds:

```
➤ ./tippecanoe --version
tippecanoe v2.26.1
➤ time ./tippecanoe --minimum-zoom=1 --read-parallel --buffer=127 --simplification=1 --layer=layer_id_name --no-feature-limit --no-tiny-polygon-reduction --preserve-input-order --no-line-simplification --extend-zooms-if-still-dropping --force --drop-rate=0 --maximum-tile-bytes=500000 --coalesce-densest-as-needed --output-to-directory=outputfolder ../Downloads/AfghanistanRoads_UTM42N.geojson
../Downloads/AfghanistanRoads_UTM42N.geojson:188: Reached EOF without all containers being closed: in JSON object {"type":"FeatureCollection","name":"AfghanistanRoads_UTM42N","crs":{"type":"name","properties":{"name":"urn:ogc:def:crs:EPSG::32642"}},"features":[]}
../Downloads/AfghanistanRoads_UTM42N.geojson:250: Found ] at top level: 
1409 features, 176394 bytes of geometry, 1095 bytes of string pool
  99.9%  14/11305/6659  

real	0m5.723s
user	0m7.258s
sys	0m4.605s
```

**Comment by divysts** [comment]
This tile generation can take time due to less I/O PS of the file system
