### ISSUE TITLE
How can I improve my conversion from GeoJSON to MBTiles?

### ISSUE THREAD

**Issue by mcleantom** [mapbox/tippecanoe#981]
I am trying to write a script to convert a GeoTIFF tile into mapbox vector tiles. I have uploaded the geojson data [here](https://github.com/mcleantom/file_dump/blob/main/sfctmp.geojson)

Rendering the GeoJSON with d3 looks fine:

![image](https://github.com/mapbox/tippecanoe/assets/64887735/89fed880-bdd7-4c52-8ad0-0d6e5f002ac7)

And uploading it to geojson.io looks okay (other than some anti-meridian artifacts):

![image](https://github.com/mapbox/tippecanoe/assets/64887735/e0a0f472-77c5-41f9-a657-0ba6824fe30e)

However when I convert the file to MBTiles and upload it to mapbox, only a few polygons are added:

![image](https://github.com/mapbox/tippecanoe/assets/64887735/b766631c-cc5c-4640-8dc3-8a2f13c0f52c)
(and the same thing, styled)
![image](https://github.com/mapbox/tippecanoe/assets/64887735/1dfcc994-09bf-4b1e-835e-ccceb8ccea48)

I convert the geojson to MBTiles using the line:

```
tippecanoe -o output.mbtiles -zg --drop-densest-as-needed contours.geojson -f
```

I am not sure why this geojson file cant be converted correctly.

I have also tried adding a bunch of different flags and some of them increase the number of polygons shown, but I cant get any of them to look similar to the render by d3.

Any help with this would be appreciated! :)

**Comment by mcleantom** [comment]
For reference, I have added the code that created the d3 visualization [here](https://github.com/mcleantom/GribToMBTiles)

**Comment by e-n-f** [comment]
Your GeoJSON generation is messed up, such that many of the rings that you intend to be outer rings are specified to be inner rings, and if they are not actually inner rings they just get lost because they are being cut out of nothing. You are probably generating Polygons where you mean to be generating MultiPolygons.

Until you fix that, I think you can get what you intended with

```
tippecanoe --reverse-source-polygon-winding -zg -f -o out.mbtiles /Users/enf/Downloads/sfctmp.geojson 
```

**Comment by mcleantom** [comment]
@e-n-f Thanks for your help. I ended up generating my geojson files using gdal_contour instead of my own script which removed the bugs due to winding errors and crossing the anti-meridian :)
