### ISSUE TITLE
Couldn't set zoom extent to 22

### ISSUE THREAD

**Issue by MelihCelik00** [mapbox/tippecanoe#983]
Hi everybody,

I know this might be a duplicate question but I wasn't able to find any solution. I'm working on a tool with the help of this package which is actually a platform to convert a geojson file to mbtiles with the help of tippecanoe. The problem is actually not about conversion because it works successfully but the problem is with zoom levels in the Mapbox studio.

I need 22 zoom level which is stated with -z22 parameter. But even though I did state, it automatically defines 15 zoom level.
![image](https://github.com/mapbox/tippecanoe/assets/45492251/23cdd8a8-e944-43f5-a07c-04d8df21edac)

I'm developing this with JavaScript and my converter currently works with these parameters:
```
        tippecanoe(
            [inputGeojsonPath],
            {
              "maximum-zoom": 22,
              "full-detail": 10,
              "low-detail": 10,
              simplification: 10,
              layer: "buildings",
              output: outputMbtilesPath,
              description: "Building footprints in the municipality of Hobbiton.",
              force: true,
              "drop-densest-as-needed": true,
              "extend-zooms-if-still-dropping": true,
              pk: true,
              pf: true,
            },
            { echo: true }
          );
```

Also, command version of it goes like this:
`tippecanoe --maximum-zoom=22 --full-detail=10 --low-detail=11 --simplification=10 --layer=buildings --output=/tmp/sample.mbtiles --description='Building footprints in the municipality of Hobbiton.' --force --drop-densest-as-needed --extend-zooms-if-still-dropping -pk -pf /tmp/sample.geojson`

Are there any workarounds or suggestions that you can give? Is there anybody that had the same issue and solved it? I really need exact zoom extent level 22.

Thanks in advance.

**Comment by e-n-f** [comment]
I don't think Mapbox will let you upload an mbtiles with a maxzoom beyond 16.
